### ISSUE TITLE
의문점 - 바뀌어버린 런던

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1000]
![screenshot_2016-07-13-11-49-36](https://cloud.githubusercontent.com/assets/19295794/16831622/fd951de2-49e0-11e6-8854-496cec319fda.png)

**Comment by STRIKE-F** [comment]
확실하진 않지만 공간이 살짝 부족할 거예요. 
시간으로부터를 시간보다 또는 시대에서로 바꾼다면 어떨까요?

**Comment by jungin019** [comment]
공간 모자랍니다.

**Comment by Porowl** [comment]
그대로 두어도 문제없어 보입니다

**Comment by STRIKE-F** [comment]
현재 좀 수정해서

이 이상한, 낯선 거리는
레이튼과 루크가 원래 살던 시대에서 
10년이 지난 미래였던 것이다.

로 수정했습니다.
