### ISSUE TITLE
이 가게에는 더이상 건질 게 없는 것 같구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1001]
![screenshot_2016-07-13-11-50-42](https://cloud.githubusercontent.com/assets/19295794/16834761/53bcaf5a-49f0-11e6-848e-19f2fa6a0717.png)

**Comment by STRIKE-F** [comment]
저 장면에서 상황이 정확히 어떻게 되나요? 정황상 힌트코인 얻은 뒤에 다시 터치하면 나오는 대사 같긴 한데...

**Comment by jungin019** [comment]
저는 '구경할' 괜찮아보이네요

**Comment by STRIKE-F** [comment]
구경할로 고치겠습니다.
