### ISSUE TITLE
맥스가 말한 큰길이 여기 같아요. 맞네요, 플랫스톤 가.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1002]
![screenshot_2016-07-13-11-51-35](https://cloud.githubusercontent.com/assets/19295794/16834804/7e3c44ac-49f0-11e6-9fdd-659b532716be.png)

**Comment by STRIKE-F** [comment]
저는 여기라고만 해도 충분해 보입니다 ㅇㅅㅇ
다른 분들은 어떻게 생각하시나요?

**Comment by jungin019** [comment]
저도 그냥 여기라고 써도 괜찮은 것 같네요

**Comment by Porowl** [comment]
지금도 괜찮아 보입니다
