### ISSUE TITLE
음? 선생님, 저 모퉁이에 서 있는 분이 제가 보기에만 덜덜 떨고 있는 건가요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1004]
![screenshot_2016-07-13-11-52-52](https://cloud.githubusercontent.com/assets/19295794/16834867/bc88d036-49f0-11e6-9742-853305b22b79.png)

**Comment by STRIKE-F** [comment]
그냥 핵심 의미만 뽑으면 모퉁이에 서 있는 사람이 떨고 있단 거니까
"음? 선생님, 저 모퉁이에 서 계신 분이 왠지 엄청 덜덜 떨고 있어요." 이러면 어떨까요?

**Comment by jungin019** [comment]
'음? 저 모퉁이에 서 있는 사람, 덜덜 떨고 있는데요. 제 눈에만 그런가요?'는 어떨까요

**Comment by STRIKE-F** [comment]
음? 선생님, 저 모퉁이에 서 계신 분이 왠지 엄청 덜덜 떨고 있어요.
그냥 이거로 수정하겠습니다.
