### ISSUE TITLE
어! 저기 우리가 봤던 모자파가 있어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1006]
![screenshot_2016-07-13-13-00-00](https://cloud.githubusercontent.com/assets/19295794/16834922/fd8f8c64-49f0-11e6-84b0-887a82fb1a33.png)

**Comment by STRIKE-F** [comment]
"어! 저기 저번에 봤던 모자파 단원이에요." 나 "~모자파예요." 로 고치는 건 어떨까요?

**Comment by STRIKE-F** [comment]
모자파예요로 수정하겠습니다.
