### ISSUE TITLE
비슷하게 입은 건 맞지만, 아무래도 저 분은 우리가 전에 봤던 모자파는 아닌 것 같구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1007]
![screenshot_2016-07-13-13-01-38](https://cloud.githubusercontent.com/assets/19295794/16834940/1b326e26-49f1-11e6-8006-03fcca9994e2.png)

**Comment by STRIKE-F** [comment]
모자파 단원 이건 빼고 나머지는 올리신 대로 수정했습니다.
