### ISSUE TITLE
이 유리 반대쪽에는 병원에 관련된 포스터가 붙어 있는 것 같아요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1008]
![screenshot_2016-07-13-13-03-09](https://cloud.githubusercontent.com/assets/19295794/16834978/447a0564-49f1-11e6-920d-dd81f56423bf.png)

그리고 3행의 '같아요.'는 2행 끝부분에 붙여 쓰는 건 어떤가요?

**Comment by STRIKE-F** [comment]
줄 길이 한계상 이렇게 고쳤습니다.

이 유리 반대쪽에는 
병원에 관련된 포스터가 
붙어 있는 것 같아요.
