### ISSUE TITLE
PL-UF-Nazo 659 (수수께끼 125) 로봇의 단위

### ISSUE THREAD

**Issue by jungin019** [elfinlazz/lt3translation#101]
로봇의 단위는 '기'로 하는 게 좋을까 '대'로 하는 게 좋을까

**Comment by Latteria** [comment]
단위 중에서 기 를 쓰는 용례는 없는 걸로 압니다만
적어도 비행기라도 한 기체 등의 표현을 쓰지
일본에서 넘어온 표현으로 추측(?)

**Comment by jungin019** [comment]
음... 그럼 바꾸는 게 좋겠네요

**Comment by STRIKE-F** [comment]
대로 수정했습니다
