### ISSUE TITLE
목소리를 좀 낮춰주십시오. 선생님, 여긴 지금 병원입니다. ...그래서, 슈레이더 박사님의 친척분이신가요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1011]
![screenshot_2016-07-13-13-08-05](https://cloud.githubusercontent.com/assets/19295794/16835060/c0c6ed26-49f1-11e6-9b4e-0b9469d75b78.png)

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
