### ISSUE TITLE
감사합니다. 이제 슈레이더 박사님을 뵈러 가셔도 됩니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1013]
![screenshot_2016-07-13-13-11-10](https://cloud.githubusercontent.com/assets/19295794/16857676/63e3c924-4a5c-11e6-9510-6637ca1a9ca6.png)

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
