### ISSUE TITLE
PL-UF-40 304 자동차 게임 글씨 잘림

### ISSUE THREAD

**Issue by jungin019** [elfinlazz/lt3translation#102]
저는 지금 큰 곤경에 빠졌습니다!
어젯밤에 카지노에서 시간을
좀 보내다가 돈 전부를 잃었습니다.
모자파가 절 뒤따라오기 전에 돈을 얻어야 합니다.

-> 전 지금 큰 곤경에 빠졌습니다! 
어젯밤 카지노에서 가지고 있던 돈 
전부를 잃었습니다. 모자파가 절 
뒤따라오기 전에 돈을 얻어야 합니다.

로 수정 

원문) I'm in big trouble! I spent a little
too long in the casino last night
and lost all my money. I need to
get some money before the Family
comes after me!

**Comment by elfinlazz** [comment]
5줄까지 가능해졌으니 이전으로 돌리고 개행하시면 될겁니다.

**Comment by jungin019** [comment]
넹~
