### ISSUE TITLE
어떤 종류냐고 물었지? 왜 있잖나. 머시기. 그게. 거시기. 아, 이런

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1020]
![screenshot_2016-07-13-13-23-04](https://cloud.githubusercontent.com/assets/19295794/16857832/7b208cf2-4a5d-11e6-91db-8322c0df6447.png)

**Comment by jungin019** [comment]
현재 녹음을 한 상태인데, 녹음본에서 '머시기... 그게... 거시기...'이런식으로 성우분이 약간 늘여서 얘기하십니다. 이렇게 말줄임표를 넣는 게 좀 더 자연스럽지 않을까요?

**Comment by vbn2523** [comment]
아, 그렇다면 가만 둬도 좋겠습니다.
다만 개행을 조금 바꿔서
어떤 종류냐고 물었지? 왜 있잖나.
머시기. 그게. 거시기. 아, 이런.
으로 수정하는 게 좋겠습니다.
말줄임표는 보기 좋으신대로 수정할지 말지를 결정하시면 좋겠다는 의견입니다.

**Comment by Porowl** [comment]
우선 말씀하신대로 개행은 했습니다.

말줄임표는 얘기를 나눠봐야 겠군요.

**Comment by Latteria** [comment]
외주 작업팀의 녹음은 더 이상 수저이 불가합니다.
