### ISSUE TITLE
자네가 개인 사무실이 있었나? 아, 내가 무슨 소릴 하는 건지. 자네가 사무실을 가진 지 꽤 오래 됐지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1024]
![screenshot_2016-07-13-13-27-40](https://cloud.githubusercontent.com/assets/19295794/16857924/21bf93a0-4a5e-11e6-9454-6c30795530fb.png)

**Comment by Porowl** [comment]
현재

자네 개인 사무실이 있었나? 아, 내가
무슨 소릴... 자네가 사무실을 꾸린 지 
꽤 오래 됐지.

으로 수정되어 있습니다.

**Comment by Y00N** [comment]
"지"에 관해서는 http://krdic.naver.com/detail.nhn?docid=35508800 와 http://krdic.naver.com/detail.nhn?docid=35506500를 보시는 게 어떠실지...

**Comment by STRIKE-F** [comment]
새로운 의견이 안 올라와 이슈 닫습니다
