### ISSUE TITLE
박사님, 다시 뵈어서 정말 반가웠습니다만, 시간이 많이 늦었군요. 저희는 이만 가 봐야 할 것 같습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1028]
![screenshot_2016-07-13-13-38-34](https://cloud.githubusercontent.com/assets/19295794/16858037/fb1c80a4-4a5e-11e6-929d-46554479db64.png)

**Comment by jungin019** [comment]
칸이 애매하게 남아 개행은 보류하겠습니다.

**Comment by STRIKE-F** [comment]
박사님, 다시 뵈어서 정말 반가웠지만 
시간이 많이 늦어서요. 
저희는 이만 가 봐야겠습니다.

이건 어떨까요
