### ISSUE TITLE
꼬맹아, 내 앞에서 사라지는데 정확히 5초 준다. 하나... 둘...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1042]
![screenshot_2016-07-13-14-07-24](https://cloud.githubusercontent.com/assets/19295794/16892152/cb3ab0a4-4b44-11e6-927b-88a8f9160ce2.png)

그리고 '사라지는데'를 '사라지는 데'로 띄워야 할지 말아야 할지 헷갈립니다 ㅠ

**Comment by jungin019** [comment]
띄어쓰는 게 맞을 겁니다.
