### ISSUE TITLE
지금까지 난 네가 동물하고 대화하는 능력이 있는 줄 알았는데 말이다 루크. 하하!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1043]
![screenshot_2016-07-13-14-08-16](https://cloud.githubusercontent.com/assets/19295794/16892161/459ecdb2-4b45-11e6-809b-f1fbb0637059.png)

**Comment by Porowl** [comment]
원문에 루크가 없습니다. 루크 뺄게요
