### ISSUE TITLE
차 안에는 미래의 루크가 남겨 두었던 또 다른 편지가 있었고, 편지에는 미래의 루크를 만날 수 있는 장소가 적혀 있었다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1045]
![screenshot_2016-07-13-14-09-51](https://cloud.githubusercontent.com/assets/19295794/16892173/a640a29e-4b45-11e6-936e-50dae934c7f6.png)

그리고 '또 다른'은 '또다른'으로 붙여 쓰는 것이 좋겠습니다.

**Comment by jungin019** [comment]
'또 다른'은 띄어쓰는 게 맞습니다.
