### ISSUE TITLE
아, 한때는 남편이 산책을 자주 다녔었는데. 그땐 남편이 저녁쯤이면 돌아왔거든.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1051]
![screenshot_2016-07-14-15-32-20](https://cloud.githubusercontent.com/assets/19295794/16892210/be36dd22-4b46-11e6-9a48-593c74377cde.png)

**Comment by jungin019** [comment]
칸이 안 돼서 이슈 닫겠습니다.
