### ISSUE TITLE
음... 그래, 내 도플갱어는 꽤 무시무시한 평판을 가지고 있는 것 같구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1057]
![screenshot_2016-07-14-15-38-21](https://cloud.githubusercontent.com/assets/19295794/16892254/1585c6be-4b48-11e6-8717-010a5cde2114.png)

**Comment by STRIKE-F** [comment]
음... 그랬지. 여기엔 나랑 똑같이 생긴 무시무시한 사람이 있나 보구나. 는 어떨까요.

**Comment by Y00N** [comment]
내 도플갱어는 꽤나 무시무시하다고 소문이 난 모양이구나.
어떨까요?

**Comment by STRIKE-F** [comment]
좋아 보이네요. 올리신 대로 수정하겠습니다.
