### ISSUE TITLE
허...걱정해 주셔서 정말 감사하네요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1059]
![screenshot_2016-07-14-16-38-55](https://cloud.githubusercontent.com/assets/19295794/16892261/600f4f8e-4b48-11e6-9aad-f969bb84e7e9.png)

**Comment by Y00N** [comment]
기왕이면 "걱정해 주셔서"도 붙여 쓰면 좋겠습니다
