### ISSUE TITLE
경감님께 말씀 좀 전해주실 수 있나요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1064]
![screenshot_2016-07-12-07-22-14](https://cloud.githubusercontent.com/assets/19270364/17130298/c8adf1dc-5352-11e6-8186-25a3e61e9b39.png)

'좀' 이라는 부사가 불필요하게 많이 들어간다는 생각이 듭니다.
<경감님께 말씀을 전해주실 수 있나요?> 로도 충분하지 않을까요?

**Comment by jungin019** [comment]
근데 말씀을 전해주실 수 있나요 가 왜 저는 어색할까요... 
일단 열어놓겠습니다

**Comment by STRIKE-F** [comment]
경감님께 알려주실 수 있을까요? 
어떨까요

**Comment by Porowl** [comment]
^ 찬성

**Comment by STRIKE-F** [comment]
경감님께 알려주실 수 있을까요? 
로 수정했습니다.
