### ISSUE TITLE
아, 서로 알고 계신 사이였어요? / 물론이지! 내 말은 난 교수님을 알고 있어.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1066]
![screenshot_2016-07-12-07-28-17](https://cloud.githubusercontent.com/assets/19270364/17130429/65ab11cc-5353-11e6-9932-a9d02c5d347d.png)
![screenshot_2016-07-12-07-28-28](https://cloud.githubusercontent.com/assets/19270364/17130433/6986d420-5353-11e6-925a-78c68255793c.png)

다소 매끄럽지 않다는 생각이 드는데...

아, 교수님을 알고 계셨어요?
물론이지! 다만 교수님은 날 모르시겠지만 말야.

정도로 어레인지 해보는 건 어떨까요...?

**Comment by jungin019** [comment]
괜찮네요

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
