### ISSUE TITLE
금방 가서 경감님께 두 분이 오셨다고 말을 전하겠습니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1068]
![screenshot_2016-07-12-07-33-10](https://cloud.githubusercontent.com/assets/19270364/17130695/d7283860-5354-11e6-9258-9a7e90b85e52.png)

음.. 이건 문장이나 맞춤법에 오류가 있는 건 아닌데요
이 친구가 이 말을 하고서 안 가더라고요.
게임하다가 "응? 니 간다며 왜 안감???" 라는 생각이 들었었는데 저만 그랬을까요...?

**Comment by jungin019** [comment]
원문이 'I'll call ahead to let the inspector know you're coming.'이네요. 정확히 말하면 미리 전화를 걸어두겠다는 것인데 고칠까요?

**Comment by STRIKE-F** [comment]
지금 바로 경감님께 두 분이 오셨다고 전해드리겠습니다

이러면 어떨까요

**Comment by Porowl** [comment]
^ 찬성

**Comment by STRIKE-F** [comment]
지금 바로 경감님께 두 분이 오셨다고 전해드리겠습니다
로 수정하겠습니다.
