### ISSUE TITLE
제가 보기에도 여기 안 계시는 것 같네요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1072]
![screenshot_2016-07-12-07-43-00](https://cloud.githubusercontent.com/assets/19270364/17130948/0b5c90ee-5356-11e6-9f49-5c21f869dda6.png)

제가 보기에도 그렇네요.
제가 보기에도 안 계시네요.
정도로 바꾸어보는 건 어떨까요?

**Comment by jungin019** [comment]
제가 보기에도 그렇네요 로 수정
