### ISSUE TITLE
듣는 법을 배우지 못하면 네 자리도 영원히 제자리걸음일 거라고.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1075]
![screenshot_2016-07-12-07-48-11](https://cloud.githubusercontent.com/assets/19270364/17131356/0b840b40-5358-11e6-80ca-629c8d18e889.png)

<듣는 법을 배우지 못하면...> 이라는 말이 다소 낯선 말이라는 생각이 들어서요.
<자꾸 남의 말을 한 귀로 흘리면...> 이라고 바꾸어보는 건 어떨까요?

**Comment by jungin019** [comment]
괜찮네요. '사람 말에 귀 기울이지 않으면~'도 괜찮을 것 같습니다.

**Comment by Porowl** [comment]
귀 기울이지 가 더 나아보입니다

**Comment by STRIKE-F** [comment]
사람 말에 귀 기울이지 않으면~
로 수정하겠습니다.
