### ISSUE TITLE
알겠어요. 아, 휴, 할머니는 또 잠드셨네.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1082]
![screenshot_2016-07-14-17-14-56](https://cloud.githubusercontent.com/assets/19295794/17138099/a839f00a-5379-11e6-9f43-d5421b67a2ec.png)

**Comment by jungin019** [comment]
원문이 'I understand. Oh, whew, Granny's asleep again.'긴 한데 이건 좀 어색하긴 하네요

**Comment by STRIKE-F** [comment]
알겠어... 흡! 이거 할머니가 들으셨으면 
큰일 났겠네.

일단 이렇게 고쳤습니다. 할머니가 못 들어서 다행이란 말만 살려서...
