### ISSUE TITLE
저는 뭔가 수상하다고 생각했지만, 그 너머에 뭐가 있는지 보려고 바로 옆을 지나갈 수는 없었어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1084]
![screenshot_2016-07-15-10-37-04](https://cloud.githubusercontent.com/assets/19295794/17138228/340a578c-537a-11e6-9479-385c7fde79b1.png)

**Comment by STRIKE-F** [comment]
저는 뭔가 수상하다고 생각했지만,
그 너머에 뭐가 있는지 보려고 
바로 옆을 지나가긴 싫었거든요.

현재 이렇게 내용을 수정했습니다.
