### ISSUE TITLE
아마 아무것도 아닐거란다. 내가 오래 전에 알던 사람이랑 조금 닮아서 말이다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1091]
![screenshot_2016-07-15-10-46-02](https://cloud.githubusercontent.com/assets/19295794/17138456/58ff71e8-537b-11e6-8ed4-70bdb7f3d809.png)

**Comment by jungin019** [comment]
현재는 '아마 별 거 아닐거야.'로 수정되어 있습니다.
