### ISSUE TITLE
쉿. 선생님. 우리를 위협하려고 하는 것 같아요

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1092]
![screenshot_2016-07-15-10-48-08](https://cloud.githubusercontent.com/assets/19295794/17138504/87adc26a-537b-11e6-9260-70f0518a255f.png)
이미 한 번 올라온 이슈이지만 다시 한 번 올립니다.

**Comment by jungin019** [comment]
쉿은 원문에도 있는 표현입니다. 나머지는 수정했습니다.
