### ISSUE TITLE
잘 했어. 네가 실력이 있단 건 증명했으니, 나도 네게 중요하지만 이해하기 힘든 경고를 해 주지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1093]
![screenshot_2016-07-15-10-52-02](https://cloud.githubusercontent.com/assets/19295794/17138545/cefe4842-537b-11e6-8dc4-a2891dc2c82c.png)

**Comment by jungin019** [comment]
'잘 했어. 네가 실력이 있단 걸 증명했으니, 나도 귀중한 경고를 해주지. 하지만 꽤 난해할 거야.' 는 어떨까요

**Comment by Porowl** [comment]
저는 찬성

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
