### ISSUE TITLE
'이 시간표는 버스의 배차 시간을 보여주네요.'

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#110]
![kakaotalk_20160510_013306001](https://cloud.githubusercontent.com/assets/19270364/15120276/ee038bf8-164f-11e6-9a23-ad2bdd8a80b8.jpg)

기존 문장이 다소 영어 투가 묻어나오는 것 같아서요
'버스의 배차 시간을 알려주는 시간표에요.' 등으로 자연스러운 문장으로 바꿔보는 게 어떨까 합니다.

**Comment by jungin019** [comment]
That schedule shows that the buses run quite frequently.
원문이 이거군요. 
'배차 시간표를 보면 배차 간격이 꽤 짧네요' 정도가 더 맞는 해석일 것 같네요

**Comment by Porowl** [comment]
배차 시간표를 보면 배차 관격이 꽤 짧네요 에 찬성

**Comment by Y00N** [comment]
아하 원문이 그랬군요. 
버스 시간표를 보'니'는 어떤가요?

**Comment by jungin019** [comment]
'보니'가 나을 것 같기도 하네요. 배차가 중복되니 앞은 버스 시간표로 바꾸는 것도 좋을 것 같습니다

**Comment by bombomS2** [comment]
버스 시간표를 보니 배차 간격이 꽤 짧네요.
이렇게 되는군요. 좋은 것 같습니다.
