### ISSUE TITLE
그러기 전에, 제가 지금 진짜 레이튼 선생님이랑 만나고 있는지 확실히 해 두고 싶어요

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1104]
![screenshot_2016-07-15-12-57-38](https://cloud.githubusercontent.com/assets/19295794/17139026/cb0be2c4-537d-11e6-8e8d-3133f1b282e4.png)

**Comment by jungin019** [comment]
현재 대사가 바뀌어 
'그전에, 제 앞에 있는 사람이 
진짜 레이튼 선생님인지 확실히 
해 두고 싶군요.'로 되어 있습니다.
