### ISSUE TITLE
제 앞에 있는 사람이 또다시 분장한 돈 파올로일지 혹시 아나요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1106]
![screenshot_2016-07-15-12-59-59](https://cloud.githubusercontent.com/assets/19295794/17139131/25faf4b8-537e-11e6-9989-acbf91481994.png)

분장은 변장으로 수정된 것으로 알고 있습니다.

**Comment by jungin019** [comment]
분장은 모두 변장으로 바뀐 것이 맞습니다.

**Comment by Porowl** [comment]
또 돈 파울로가 변장한 모습일지 혹시 아나요?

는 어떨까요

**Comment by STRIKE-F** [comment]
찬님 의견이 더 괜찮아 보입니다. 그대로 수정하겠습니다.

**Comment by STRIKE-F** [comment]
는 더빙이라 보류하겠습니다

**Comment by Latteria** [comment]
채택합니다. 대본이랑 같이 수정하고 닫아주세요.

**Comment by STRIKE-F** [comment]
수정 완료
