### ISSUE TITLE
그치만 그건 저 옛날 일이잖아요, 말도 안 돼요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1107]
![screenshot_2016-07-15-13-00-40](https://cloud.githubusercontent.com/assets/19295794/17139175/4b084f76-537e-11e6-8ba6-da74922e7ff8.png)

**Comment by Porowl** [comment]
문제없다 생각됩니다.

어색하면 이정도는 어떨까요?

언제적 얘기를 하시는 거에요?
그럴 리가 없잖아요!
