### ISSUE TITLE
여기 있는 카드 네 장은 다음 조건에 따라 배열되어 있단다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1109]
![screenshot_2016-07-15-13-30-53](https://cloud.githubusercontent.com/assets/19295794/17139372/1d98a846-537f-11e6-85b4-75cf82fd50a3.png)

**Comment by jungin019** [comment]
차라리 다음을 2행으로 개행하는 게 나아보입니다.

**Comment by STRIKE-F** [comment]
다음을 한 줄 내리겠습니다.
