### ISSUE TITLE
넘어갈 뻔 했군요, 선생님. 하지만, 이 수수께끼에는 오류가 있어요. 이건 풀 수 없어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1112]
![screenshot_2016-07-15-13-43-48](https://cloud.githubusercontent.com/assets/19295794/17139467/8d7da350-537f-11e6-8554-10d104f57e3b.png)

**Comment by jungin019** [comment]
쉼표도 뺐습니다.
