### ISSUE TITLE
하지만 선생님이랑 재치를 겨뤄볼 기회를 놓치고 싶지 않았어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1113]
![screenshot_2016-07-15-13-50-00](https://cloud.githubusercontent.com/assets/19295794/17139878/1e6e5228-5381-11e6-8c02-24b1223eb425.png)

**Comment by jungin019** [comment]
칸이 애매하게 남아 기회를은 붙여쓰지 않았습니다. 마침표는 수정
