### ISSUE TITLE
그 분의 얼굴만 봐도 많은 세월이 흘렀단 걸 알 수 있었을텐데요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1114]
![screenshot_2016-07-15-13-51-38](https://cloud.githubusercontent.com/assets/19295794/17140007/c5e9cd7a-5381-11e6-9407-ba5ce3fa8cd2.png)

**Comment by jungin019** [comment]
현재 대사가 바뀌어 
'박사님의 얼굴만 봐도 세월이 많이 
흘렀단 걸 아셨을 텐데요.'로 되어 있습니다.
