### ISSUE TITLE
한 천재가 나타났어. 아주 사악한 천재가 도시를 자기 지배 하에 놓았지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1117]
![screenshot_2016-07-15-13-56-28](https://cloud.githubusercontent.com/assets/19295794/17140166/6995037c-5382-11e6-8d74-15aa7822c427.png)

**Comment by jungin019** [comment]
이건 애매하게 남아 보류하겠습니다.
