### ISSUE TITLE
No.002 '시각들'과 '시각'의 혼용

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#112]
![kakaotalk_20160510_013320678](https://cloud.githubusercontent.com/assets/19270364/15120450/b9dc2122-1650-11e6-9004-3127c2560e7e.jpg)
![kakaotalk_20160510_013326344](https://cloud.githubusercontent.com/assets/19270364/15120459/c53e6944-1650-11e6-8884-61d246a1bfd5.jpg)

문제의 시작에선 '시각들을' 이라고 언급되어 있으나 문제를 해결하면 '시각은' 이라고 언급하네요.
통일해주시는 게 좋겠습니다.

그리고 '각 시각마다 아날로그 시계의 시침이 가리키는 곳을 매 교차로마다 따라가면 된다.' 라는 문장을
'매 교차로에서 각 시각마다 아날로그 시침이 가리키는 곳을 따라가면 된다.' 라고 하는 게 더 이해하기 쉽지 않을까요?

**Comment by jungin019** [comment]
시각으로 통일했습니다.
