### ISSUE TITLE
그의 이름은 허셜 레이튼이에요.. 그 사악한 천재는 선생님을 말하는 거예요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1120]
![screenshot_2016-07-15-13-59-00](https://cloud.githubusercontent.com/assets/19295794/17140318/02b977ae-5383-11e6-95c6-b32b9ef20d39.png)

**Comment by jungin019** [comment]
말줄임표가 아니라 마침표라서 하나 지웠습니다. 
거예요는 공간이 넘어갑니다.
