### ISSUE TITLE
런던에 있는 사람들은 누구나 아는 사실이야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1122]
![screenshot_2016-07-15-14-01-15](https://cloud.githubusercontent.com/assets/19295794/17140831/de017d92-5384-11e6-812f-fdce880c640e.png)

아니면 1행의 '누구나'를 2행으로 넘겨도 좋겠습니다.

**Comment by jungin019** [comment]
누구나를 2행으로 넘김.
