### ISSUE TITLE
의문점 - 겁먹은 구경꾼들

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1123]
![screenshot_2016-07-15-14-02-33](https://cloud.githubusercontent.com/assets/19295794/17140868/18e67192-5385-11e6-9549-6fe0f763c32b.png)

**Comment by jungin019** [comment]
원문이 'The sight of the professor, who looks the same as his future self, is enough to
spark fear in the townspeople.' 인데 
'미래의 레이튼과 닮은 레이튼의 모습은 마을 사람들을 겁주기에 충분했다.' 정도면 될 것 같아요. 
왜 문장이 저렇게 된 거지...

**Comment by STRIKE-F** [comment]
미래의 레이튼과 닮은 레이튼의 모습은 마을 사람들이 겁에 질리게 하고도 남았을 것이다.
로 수정했습니다.
