### ISSUE TITLE
더요? 저도 선생님이 아는만큼밖에 몰라요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1124]
![screenshot_2016-07-15-14-03-29](https://cloud.githubusercontent.com/assets/19295794/17140926/4398e65e-5385-11e6-8289-cbe1baf376e0.png)

**Comment by Y00N** [comment]
저도 그것 밖엔 몰라요. 는 어떨까요

**Comment by jungin019** [comment]
저도 더 아는 게 없어요 도 괜찮을 것 같네요

**Comment by Porowl** [comment]
저도 더 아는 게 없어요. 

에 찬성합니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
