### ISSUE TITLE
아니, 다른 루크에게 말하는 거였단다. ...이거 참, 꽤나 헷갈리는걸. 그렇지?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1125]
![screenshot_2016-07-15-14-04-14](https://cloud.githubusercontent.com/assets/19295794/17140949/6183b090-5385-11e6-9948-7de8b069abcf.png)

**Comment by Y00N** [comment]
그러고보니 말줄임표 다음은 띄어 써야 합니다
