### ISSUE TITLE
그 기간은 런던의 암흑기였어요..

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1127]
![screenshot_2016-07-15-14-06-38](https://cloud.githubusercontent.com/assets/19295794/17141069/bfdd7324-5385-11e6-840f-a8b386402b14.png)

**Comment by Y00N** [comment]
사실 정확히 하자면 말 줄임표와 마침표
즉 마침표 네개로 끝내야 맞습니다

**Comment by jungin019** [comment]
원문이 마침표 하나라 그걸로 수정했습니다.
