### ISSUE TITLE
그래, 그 두 사람을 포함한 몇몇 사람들도 폭발과 함께 사라져 버렸지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1129]
![screenshot_2016-07-15-14-09-23](https://cloud.githubusercontent.com/assets/19295794/17141914/0b5c9494-5389-11e6-8122-9e76ec0ffc32.png)

**Comment by jungin019** [comment]
칸이 넘어가서 닫겠습니다.
