### ISSUE TITLE
그래, 그 실종 사건들이 이 모든 것들과 연관되어 있는 것 같구나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#113]
![kakaotalk_20160510_013328716](https://cloud.githubusercontent.com/assets/19270364/15120584/637dc384-1651-11e6-990a-abc545a578fa.jpg)

이 모든 것들
'모든'이라는 복수를 의미하는 말을 이미 붙였으니 '들'을 붙이는 건 어색합니다.
'이 모든 것'이 더 자연스럽다고 생각합니다.

**Comment by Porowl** [comment]
'이 모든것과' 로 수정
