### ISSUE TITLE
하지만, 한 가지 걸리는 게 있구나. 이 웜홀은 분명 미래의 나에게는 아주 중요한 것일텐데 말이야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1137]
![screenshot_2016-07-15-14-19-31](https://cloud.githubusercontent.com/assets/19295794/17160610/1eaaa916-53e1-11e6-8ac2-a2af9bc97825.png)

**Comment by jungin019** [comment]
띄어쓰는 게 맞습니다. 수정.
