### ISSUE TITLE
항상 한 발짝 앞서시네요. 선생님은 역시 감을 잃지 않으셨군요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1140]
![screenshot_2016-07-15-14-24-15](https://cloud.githubusercontent.com/assets/19295794/17160667/8fad8ffc-53e1-11e6-92fd-7d6cfaaf6fae.png)

**Comment by jungin019** [comment]
원문은 'Always one step ahead of me. You haven't lost your touch, Professor.'로 맞는 번역입니다. 
어색하시다면 바꾸는 게 좋긴 하겠죠?

**Comment by Porowl** [comment]
원문의 허점이 드러나는 부분인가요?

여전하시네요. 는 어떨까요?

**Comment by STRIKE-F** [comment]
역시 예리하시네요. 로 바꿀게요. 이 정도면 얼추 맞아떨어질 듯해서...
