### ISSUE TITLE
일단 우리에게 가장 걸림돌이 되는 문제는 레이튼이 매우 비밀스럽게 움직인다는 거예요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1147]
![screenshot_2016-07-15-14-29-50](https://cloud.githubusercontent.com/assets/19295794/17160777/a2845a38-53e2-11e6-94c1-368194b5c06e.png)

**Comment by jungin019** [comment]
칸이 넘어가서 닫습니다.
