### ISSUE TITLE
이 카지노가 미래의 선생님의 본거지가 아니란 말이에요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1148]
![screenshot_2016-07-15-14-30-54](https://cloud.githubusercontent.com/assets/19295794/17160800/c7b78794-53e2-11e6-8fb1-000f74a5afb1.png)

'~의' 라는 표현도 반복됩니다.

**Comment by STRIKE-F** [comment]
카지노가->카지노는으로 수정했습니다
-의가 반복되는 건 일단 놔뒀습니다.

**Comment by Porowl** [comment]
<T>이 카지노는 10년 후 선생님의 
본거지가 아니란 말이에요?
