### ISSUE TITLE
[문장 다듬기 제언] 수 년 동안의 시간여행 분야에서의 연구 끝에

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#115]
![kakaotalk_20160510_013335520](https://cloud.githubusercontent.com/assets/19270364/15120666/c19d5542-1651-11e6-9343-066a8cfa0f19.jpg)

'수 년 동안의 시간여행 분야에서의 연구 끝에' 라는 말이 다소 어색하게 느껴집니다.
'수 년 동안 시간여행 분야를 연구한 끝에', '시간 여행 분야를 수 년 동안 연구한 끝에'와 같은 문장은 어떨까요?

**Comment by jungin019** [comment]
'수 년 동안 시간여행 분야를 연구한 끝에'로 고쳐놓겠습니다.

**Comment by jungin019** [comment]
*대사 변경 @Latteria

**Comment by kaleidoscope531** [comment]
시간여행 분야에서 분야를 빼고 
'수 년 동안 시간여행을 연구한 끝에' 로 하는 편이 낫지 않을까요?

**Comment by bombomS2** [comment]
수 년 동안 시간여행에 대해 연구한 끝에, 도 괜찮을 것 같습니다.

**Comment by Porowl** [comment]
"수 년 동안 시간여행을 연구한 끝에"
