### ISSUE TITLE
스턴건 박사라는 이름이나 외형 묘사에 맞는 사람은 찾을 수가 없었어요. 그건 가짜 명의였어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1151]
![screenshot_2016-07-15-14-35-20](https://cloud.githubusercontent.com/assets/19295794/17160861/7bc63c76-53e3-11e6-941e-186d775669b6.png)

그리고 '명의'보다는 '신분'이라는 표현을 사용하는 것이 어떤가요?

명의는 물건의 소유를 나타내는 느낌인데... 다른 분들은 어떻게 생각하시나요?

**Comment by jungin019** [comment]
외형 묘사는 인상착의로 바꾸는 게 어떨까요. 
원문이 'The name's a fake' 라서 그렇게 번역된 것 같네요. 신분도 괜찮을 것 같습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
