### ISSUE TITLE
정체가 누군지는 모르겠지만, 그는 발표회에서 진짜 신분을 숨기기 위해 손을 써 뒀어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1152]
![screenshot_2016-07-15-14-36-30](https://cloud.githubusercontent.com/assets/19295794/17160880/a4f11a9e-53e3-11e6-96c8-89cb5912c075.png)

**Comment by jungin019** [comment]
'그 사람이 실제로 누군지는 모르겠지만, 
발표회에서 진짜 신분을 숨기기 위해 
손을 써뒀어요.' 정도는 어떨까요

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
