### ISSUE TITLE
그 뿐만 아니라, 사람들의 삶의 질도 더 나아질 거고요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1155]
![screenshot_2016-07-15-14-39-29](https://cloud.githubusercontent.com/assets/19295794/17160959/2b7511b0-53e4-11e6-8692-7065c5ee9f93.png)

**Comment by jungin019** [comment]
그뿐만이 맞습니다.

**Comment by STRIKE-F** [comment]
수정되었으므로 닫습니다.
