### ISSUE TITLE
이제 자기랑 나랑 뽀뽀할 시간! 크~고 진~하게 해 줄게! (물결)

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1162]
![screenshot_2016-07-15-14-49-13](https://cloud.githubusercontent.com/assets/19295794/17161084/47862e92-53e5-11e6-86e4-b562fade1a2a.png)

**Comment by Porowl** [comment]
물결은 해결햇습니다.
크다 문제 없지 않나요
