### ISSUE TITLE
수수께끼를 생각나게 한다고요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1164]
![screenshot_2016-07-18-08-44-49](https://cloud.githubusercontent.com/assets/19295794/17161106/8e76d5e0-53e5-11e6-92d3-587ca1418582.png)

**Comment by jungin019** [comment]
수수께끼가 생각나신다고요? 는 어떨까요

**Comment by STRIKE-F** [comment]
수수께끼가 떠오른다고요? 로 수정했습니다.
