### ISSUE TITLE
난 커서 수수께끼학개론 교수가 될꺼야! 그때는 날 존경할 수밖에 없을 걸?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1167]
![screenshot_2016-07-18-08-51-52](https://cloud.githubusercontent.com/assets/19295794/17161150/fe1adcac-53e5-11e6-8566-152a9e94c4a6.png)

**Comment by Y00N** [comment]
동의합니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
