### ISSUE TITLE
이게 정말 차이나타운으로 가는 길인가요? 길이 정말 더럽고.... 어두침침한걸요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1168]
![screenshot_2016-07-18-08-54-40](https://cloud.githubusercontent.com/assets/19295794/17161162/1b3a26ee-53e6-11e6-8f69-312d2158b8dc.png)

**Comment by jungin019** [comment]
길인가요는 칸이 안 됩니다.
