### ISSUE TITLE
어어! 으아! 엑 윽 악 윽!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1169]
![screenshot_2016-07-18-08-55-14](https://cloud.githubusercontent.com/assets/19295794/17161170/33f91136-53e6-11e6-9c27-2088bee8a1fc.png)

**Comment by jungin019** [comment]
좀 그런 것 같기도 하네요...

**Comment by STRIKE-F** [comment]
역시 디씨에서 쓰는 표현은 좀 그런가...
순화(?)해서 아이고야! 로 바꿨습니다.
