### ISSUE TITLE
무...무슨 말씀이세요 선...선생님! 어...어차피 선생님은 비...비과학적인 것 안 믿으시잖아요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1179]
![screenshot_2016-07-18-09-58-30](https://cloud.githubusercontent.com/assets/19295794/17162542/dcb88f08-53f1-11e6-899b-a3f070adb92e.png)

**Comment by jungin019** [comment]
띄어쓰기를 하면 것이 들어가지 않습니다.
