### ISSUE TITLE
[오타] 게임의 매인 화면의 비밀 파일에서 ....

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#118]
![kakaotalk_20160510_013338157](https://cloud.githubusercontent.com/assets/19270364/15120892/dc611b38-1652-11e6-8b76-774d39a74dcf.jpg)

'매인 화면' 은 '메인 화면'이죠?

**Comment by jungin019** [comment]
아... 네...

**Comment by jungin019** [comment]
@itstake

**Comment by kaleidoscope531** [comment]
즐길거리 -> 즐길 거리
이 부분도 부탁드립니다.
