### ISSUE TITLE
쉬플리의 도움으로, 레이튼과 루크는 미래의 레이튼의 정확한 위치를 알아내었다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1200]
![screenshot_2016-07-19-07-24-10](https://cloud.githubusercontent.com/assets/19295794/17162849/8e3dbf12-53f4-11e6-9406-6acb9cca8a12.png)

**Comment by Porowl** [comment]
미래 레이튼으로 수정
