### ISSUE TITLE
미래의 루크는 차이나타운으로 들어가는 길을 확보하기 위해 먼저 떠나기로 했다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1201]
![screenshot_2016-07-19-07-25-44](https://cloud.githubusercontent.com/assets/19295794/17162866/b2c1bf32-53f4-11e6-9cd6-5b42855937b7.png)

**Comment by STRIKE-F** [comment]
저희도 가급적이면 의미 단위로 끊어서 개행을 하고 싶은데, 제가 보기엔 이건 너무 뻥 비어 보여서 좀 그렇네요...
