### ISSUE TITLE
음, 루크야. 혹시 저 둘을 보니 떠오르는 사람 없니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1204]
![screenshot_2016-07-19-07-30-51](https://cloud.githubusercontent.com/assets/19295794/17163413/070c28a2-53fa-11e6-8c36-856c7cf11bc9.png)`

**Comment by STRIKE-F** [comment]
이것도 아까 제가 올렸듯이, 첫 줄이 너무 뻥 비는 문제가 생겨서 좀 그렇네요
