### ISSUE TITLE
완전히 같지는 않지만, 우리가 잘 아는 두 사람과 꽤나 닮은 것 같단 말이지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1205]
![screenshot_2016-07-19-07-31-47](https://cloud.githubusercontent.com/assets/19295794/17163428/30792b36-53fa-11e6-857a-81e1f3b0cdb4.png)

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
