### ISSUE TITLE
덩치 큰 상관에. 땅딸막한 부하까지!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1207]
![screenshot_2016-07-19-07-34-01](https://cloud.githubusercontent.com/assets/19295794/17163445/6401df5c-53fa-11e6-97ba-0092e9bcb15d.png)

**Comment by STRIKE-F** [comment]
코드 상으로 중간에 뜸을 들이고 텍스트가 출력돼서 쉼표 정도는 있는 게 자연스러워 보였기에 쉼표로 수정했습니다.
