### ISSUE TITLE
경감님 하니까 말이다, 혹시 경감님이 그 행사에 계셨다는 점이 이상하게 느껴지지는 않았니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1208]
![screenshot_2016-07-19-07-34-51](https://cloud.githubusercontent.com/assets/19295794/17163455/8849729e-53fa-11e6-9d63-970d1786e746.png)

**Comment by STRIKE-F** [comment]
혹시를 다음 행으로 넘기면 공간이 부족해집니다. 경감님이도 경감님께서로 고쳐져서요.
