### ISSUE TITLE
그 행사요? 타임머신 시연회 말인가요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1209]
![screenshot_2016-07-19-07-35-28](https://cloud.githubusercontent.com/assets/19295794/17163465/a0931cf6-53fa-11e6-9abc-0b5655ebe270.png)

**Comment by Y00N** [comment]
그 행사요? 타임머신 시연회요?
라고 하는 것도 괜찮지 않을까요

**Comment by STRIKE-F** [comment]
현재 말인가요?를 1행으로 붙였습니다.

**Comment by STRIKE-F** [comment]
현재
그 행사라면... 타임머신 시연회요?
로 고쳤습니다.
