### ISSUE TITLE
내가 본 바로는, 그 곳에 초대된 거의 모든 사람들은 런던의 상류층이거나 언론에 종사하는 사람이었거든.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1210]
![screenshot_2016-07-19-07-37-59](https://cloud.githubusercontent.com/assets/19295794/17163527/5f79956e-53fb-11e6-9892-23d628d267ef.png)

**Comment by Y00N** [comment]
넘기면 "상류층이거나가" 잘리지 않나요?

**Comment by STRIKE-F** [comment]
"그 곳에"는 고쳤습니다.
그리고 현로님 말대로 개행 수정은 공간이 부족해서 힘듭니다.
