### ISSUE TITLE
네, 원래의 시간대로 돌아가서 물어볼 수밖에 없다는 게 좀 아쉽네요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1212]
![screenshot_2016-07-19-07-39-50](https://cloud.githubusercontent.com/assets/19295794/17163562/a79d8260-53fb-11e6-8252-daff88a197fe.png)

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
