### ISSUE TITLE
잠깐! 체르미 경감님이 미래에도 아직 일하고 계시다면요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1213]
![screenshot_2016-07-19-07-42-17](https://cloud.githubusercontent.com/assets/19295794/17163579/c3b35d62-53fb-11e6-9534-52d1ba9e3f80.png)

**Comment by STRIKE-F** [comment]
잠깐! 미래에서도 체르미 경감님이 일하고 계신다면요? 는 어떠려나요

**Comment by STRIKE-F** [comment]
이대로 수정하겠습니다.
