### ISSUE TITLE
보는 눈이 있으니 다른 곳에서 계속 얘기하도록 하죠.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1214]
![screenshot_2016-07-19-07-43-22](https://cloud.githubusercontent.com/assets/19295794/17163605/ed14e4e6-53fb-11e6-9e14-921f21b4237f.png)

**Comment by STRIKE-F** [comment]
현재는

여긴 누가 볼 수도 있으니
다른 곳에서 계속 얘기하도록 하죠.

이렇게 수정했습니다.
