### ISSUE TITLE
저 끔찍한 생물체가 날 덮치곤 내 소매에서 최고급 커프스 단추를 잡아 뜯었어!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1217]
![screenshot_2016-07-19-07-48-32](https://cloud.githubusercontent.com/assets/19295794/17163676/abaa5558-53fc-11e6-8745-3ecf9a0856e2.png)

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
