### ISSUE TITLE
[문장 다듬기 제언] 레이튼 교수는 미래라는 이상한 발신일이 적힌 편지를 받았다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#122]
![kakaotalk_20160510_013355204](https://cloud.githubusercontent.com/assets/19270364/15121015/5caa5296-1653-11e6-8b36-a341025a775f.jpg)

'레이튼 교수는 발신일이 미래라고 적힌 이상한 편지를 받았다.' 는 어떨까요?

**Comment by Y00N** [comment]
이렇게 보고있자니 '10년 후의 미래에서 보내온 편지의 발송인은 미래의 루크이다.'라는 문장도
[10년 후의 미래에서 보내온]이  [편지]를 수식하는지 [편지의 '발송인']을 수식하는지가 매끄럽지 않다고 생각이 드네요.
'10년 후의 미래에서 편지를 보낸 사람은 미래의 루크이다.' 는 어떨까요?

**Comment by Glacie** [comment]
굳이 적힌이라는 표현을 쓸 필요가 있을까요?
개인적으로는 [발신일이 미래인] 정도로만 써도 충분하지 않을까 생각됩니다

**Comment by Porowl** [comment]
레이튼 교수는 발신일이 미래로
되어있는 이상한 편지를 받았다.
10년 후의 미래에서 편지를 
보낸 사람은 미래의 루크이다.
이게 가능한 일일까?

로 고쳤습니다. 혹시라도 고칠 부분이 있을까 열어둡니다.

**Comment by Porowl** [comment]
레이튼 교수는 10년 후의 미래에서
보냈다는 이상한 편지를 받았다. 
심지어 편지를 보낸 사람은 
미래의 루크였다.
이게 가능한 일일까?
