### ISSUE TITLE
이렇게나 반짝이는 보석이라면, 충분히 저 깃털 달린 친구의 관심을 끌 수 있겠네요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1222]
![screenshot_2016-07-19-08-17-50](https://cloud.githubusercontent.com/assets/19295794/17163794/8ae94788-53fd-11e6-87cd-625b1d8d63d5.png)

**Comment by STRIKE-F** [comment]
이렇게나 반짝이는 보석이라면, 
저 깃털 달린 친구의 관심을 끌기에는 
충분하겠네요.

현재 이렇게 바꿔 봤는데, 이건 어떨까요?

**Comment by jungin019** [comment]
스프님 문장 괜찮은 것 같네요

**Comment by STRIKE-F** [comment]
이대로 수정하겠습니다.
