### ISSUE TITLE
아, 내가 자네들의 고생에 대한 보상을 해야 할 것 같군.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1229]
![screenshot_2016-07-19-08-25-12](https://cloud.githubusercontent.com/assets/19295794/17163983/efd1fcc0-53fe-11e6-9b49-8c9c1d626344.png)

**Comment by STRIKE-F** [comment]
이건 의미상 보상을은 밑 줄에 있는 편이 더 낫지 않을까 싶어서 일단은 놔두겠습니다.
그리고 해야->줘야로 바뀌었습니다. 보상을 하다라고 쓸 거면 보상하다로 적는 게 더 적절하다는 맞춤법 검사기느님의 말에 따라..
