### ISSUE TITLE
아, 내가 자네들의 고생에 대한 보상을 해야 할 것 같군.(2)

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1230]
![screenshot_2016-07-19-08-26-34](https://cloud.githubusercontent.com/assets/19295794/17163990/186bb054-53ff-11e6-928a-16acb950f51c.png)

**Comment by STRIKE-F** [comment]
현재 앞 대사에서는 -군이 모두 사라진 상태이므로 해결된 듯합니다.
