### ISSUE TITLE
맞습니다. 신사에게 보상이란 사람을 돕는 것만으로도 충분한 법이죠.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1231]
![screenshot_2016-07-19-08-27-24](https://cloud.githubusercontent.com/assets/19295794/17164009/48ee8e7c-53ff-11e6-9a89-23a57438c07e.png)

**Comment by STRIKE-F** [comment]
번역하다가 말하는 사람을 착각했나 보네요...

**Comment by STRIKE-F** [comment]
맞습니다-> 맞아요로 고쳤습니다.
