### ISSUE TITLE
조사 메모 - 차이나타운의 경비

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1235]
![screenshot_2016-07-19-08-35-09](https://cloud.githubusercontent.com/assets/19295794/17164124/253aa94c-5400-11e6-89d0-18ac76e95583.png)

**Comment by STRIKE-F** [comment]
차이나타운으로 들어가는 길목에 있는 
큰 문 앞에 서 있는 두 남자의 모습이 
체르미 경감님과 조수 바튼의 모습과 
꽤 닮아 보였다. 
나는 두 사람도  타임머신 발표회 때
그 장소에 같이 있었다는 것을 
떠올렸다. 난 우리 시간대의
런던으로 돌아가 체르미 경감님께
몇 가지를 물어보기로 했다.

약간 바꿔 이렇게 수정했습니다.
