### ISSUE TITLE
만약 앵무새가 평평한 땅에 닿게 되면, 일반적인 방법으로 날게 됩니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1237]
![screenshot_2016-07-19-08-40-42](https://cloud.githubusercontent.com/assets/19295794/17164176/91b04ea6-5400-11e6-834a-9c6dd5545e84.png)

**Comment by jungin019** [comment]
문장을 '만약 앵무새가 평평한 땅에 닿게 되면, 
다시 기본적인 궤도로 날아 오릅니다.'로 수정
