### ISSUE TITLE
내 감시는 철통같아서 내가 보초를 서고 있을 때는 아무도 감히 지나가려고 하지 않지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1239]
![screenshot_2016-07-19-08-45-15](https://cloud.githubusercontent.com/assets/19295794/17164203/e6e9e800-5400-11e6-81d1-878789685978.png)

**Comment by jungin019** [comment]
철통같은 은 합성어라 붙여씁니다.
