### ISSUE TITLE
동화책 설명 부분의 그림 부분의 오타

### ISSUE THREAD

**Issue by rabbitdoggy** [elfinlazz/lt3translation#124]
![screenshot_2016-05-09-04-52-12](https://cloud.githubusercontent.com/assets/19265174/15121198/627382c8-1654-11e6-9ed4-9444bc758078.png)

위의 예시로 쓰인 그림에서 [노란색 물건]으로 적혀있어야 하는 부분이

[노랜삭 물건]으로 적혀있습니다. 오타 수정되기 전에 찍은 스크린샷이 들어간 듯합니다.

**Comment by Porowl** [comment]
@itstake

**Comment by jungin019** [comment]
이거 그래픽인가?

**Comment by itstake** [comment]
동화책 재번역이 이루어 진 후 확정 동화책 번역이 나오면 그때 작업하도록 하겠습니다.
