### ISSUE TITLE
히야 하 하! 나에게 다가오다니 배짱이 두둑하구나. 정말 우습군! 히야 하

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1241]
![screenshot_2016-07-19-08-47-43](https://cloud.githubusercontent.com/assets/19295794/17164224/1c953626-5401-11e6-8c39-38a91ea74f9b.png)

**Comment by STRIKE-F** [comment]
원문의 웃음소리를 그대로 음역했더만 좀 어색해졌네요 ㅋㅋ;;;
웃음소리는 으허하하하로 고쳤습니다. 나머지도 수정했습니다.
