### ISSUE TITLE
너무 무식한 방법일지 모르겠지만, 거기 두 분, 이 문을 부수는 걸 도와 주시겠어요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1249]
![screenshot_2016-07-19-09-04-48](https://cloud.githubusercontent.com/assets/19295794/17164338/3a780d3e-5402-11e6-96e4-7539af8f55c3.png)

**Comment by STRIKE-F** [comment]
두 분을 빼는 건 어떠려나요

**Comment by jungin019** [comment]
거기 두 분을 다 빼는 건 몰라도 두 분만 빼는 건 글쎄요...

**Comment by STRIKE-F** [comment]
그냥 처음의 쉼표를 ....로 바꾸었습니다.
