### ISSUE TITLE
대사의 띄어쓰기(못하다 관련)

### ISSUE THREAD

**Issue by rabbitdoggy** [elfinlazz/lt3translation#125]
![screenshot_2016-05-09-04-54-33](https://cloud.githubusercontent.com/assets/19265174/15121286/d48e6918-1654-11e6-93a6-694db4ededaa.png)

# 1. 놀래라 -> 놀라라.

# 2. 보지도 못 했어요 -> 보지도 못했어요.

로 붙여 씁니다.

※ 못하다는 어미 '지' 뒤에 올 때는 '못'과 '하다'를 붙여 씁니다.
    관련 띄어쓰기 오류가 종종 발견되는 것 같습니다.

**Comment by Porowl** [comment]
놀래라/놀라라 둘 다 알맞지 않은 표현이라는데
'놀랐네'로 바꾸는 것은 어떨까요?

사실상 말투를 고려하여 쓴거긴 하지만.

**Comment by jungin019** [comment]
차라리 깜짝이야 라거나...

**Comment by bombomS2** [comment]
어머, 깜짝이야. 가 제일 좋을 것 같아요.

**Comment by kaleidoscope531** [comment]
보지도 못해서요를 그냥 못 봐서요로 바꾸는 것은 어떨까요?

**Comment by jungin019** [comment]
그럼 '어머, 깜짝이야. 안녕하세요. 이거 참 실례했네요. 두 분이 오시는 걸 못 보았어요.'는 어떤가요?

**Comment by bombomS2** [comment]
어머, 깜짝이야. 안녕하세요. 이거 참 실례했네요. 두 분이 오시는 걸 못 봤어요.
좋은 것 같아요.
