### ISSUE TITLE
모든 수수께끼에는 해답이 있다는 말이 다시 한 번 성립하는구나. 그게 무식한 힘이라도 말이다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1250]
![screenshot_2016-07-19-09-08-12](https://cloud.githubusercontent.com/assets/19295794/17164374/79f64926-5402-11e6-82ca-48b5687a989f.png)

**Comment by STRIKE-F** [comment]
모든 수수께끼에는 반드시 해답이 있지.
그게 무식한 힘이라도 말이다.

원문에 있던 미사어구? 를 굳이 넣지 않는 편이 더 나아 보여서 다 빼버렸습니다.
