### ISSUE TITLE
어.. 괜찮아요. 근데 제가 지금 좀 몸이 안 좋아서요. 집에 가렵니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1251]
![screenshot_2016-07-19-09-09-27](https://cloud.githubusercontent.com/assets/19295794/17164402/c3ceae76-5402-11e6-8765-a4ae6addce81.png)

문장 순서도 약간 수정했습니다.

**Comment by jungin019** [comment]
그냥 '좀'은 뺐습니다
