### ISSUE TITLE
어쩐지 앞쪽에서 이야기가 들리는 것 같더라니.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1263]
![screenshot_2016-07-19-09-48-52](https://cloud.githubusercontent.com/assets/19295794/17171902/985a882a-542d-11e6-85b7-c035f713c2bb.png)

**Comment by Porowl** [comment]
<T>어쩐지 앞쪽 방에서 이야기 하는 소리가 
들리더라니.

**Comment by STRIKE-F** [comment]
'이야기 소리' 가 더 낫겠네요. 이대로 수정하겠습니다.
