### ISSUE TITLE
물론이지. 이봐 루크! 음... 그러니까 좀 더 작은 루크 말야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1264]
![screenshot_2016-07-19-09-49-37](https://cloud.githubusercontent.com/assets/19295794/17171920/b19d7a18-542d-11e6-8707-a7f6df6cabf0.png)

**Comment by STRIKE-F** [comment]
굳이 넘겨야 할까요? 그러니까는 그냥 다른 행에 써도 크게 안 어색해 보이는데

**Comment by Porowl** [comment]
음만 따로 냅두기도 뭣하니 넘기지 않는 쪽으로
