### ISSUE TITLE
확실하군. 어이, 형님! 말씀하신 대로 여기 아주 큰 시계가 있네요. 정말 멋진데요? 한 번 와서 보세요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1265]
![screenshot_2016-07-19-09-51-48](https://cloud.githubusercontent.com/assets/19295794/17171991/0991ecb8-542e-11e6-9ea8-56facd1ddf07.png)

그리고, 존댓말을 사용하는 '형님'을 '어이'로 부르는 것에 대해서는 어떻게 생각하시는지...

**Comment by STRIKE-F** [comment]
어이, 형님! 이라고 조폭물에서 자주 본 듯한데 말이죠. 제가 보기엔 크게 안 어색해 보여요

**Comment by jungin019** [comment]
저도 이건 별로...
