### ISSUE TITLE
도대체 무슨 생각으로 내 가게에 멋대로 들어오는 거야? 지금 당장 내 시계에서 손 떼!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1266]
![screenshot_2016-07-19-09-52-31](https://cloud.githubusercontent.com/assets/19295794/17172039/42f66bc8-542e-11e6-857a-909190b1eecd.png)

**Comment by STRIKE-F** [comment]
2번째 행이 너무 비어 보이지 않을까요

**Comment by Porowl** [comment]
<T><A1/1>도대체 무슨 생각으로 
내 가게에 멋대로 들어오는 거야? 
지금 당장 내 시계에서 손 떼!
