### ISSUE TITLE
죄송합니다, 보스트로 형님. 우리는 최선을 다하고 있습니다만, 이 할배가 일을 성가시게 만들어서요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1267]
![screenshot_2016-07-19-09-53-13](https://cloud.githubusercontent.com/assets/19295794/17172070/69aa0928-542e-11e6-85b2-a960d3b7c9a4.png)

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
