### ISSUE TITLE
그렇지만 큰 형님이 말씀하신 정확한 시각까지는 기다려야 해. 몇 번이나 거듭 말씀하셨으니까 말이야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1268]
![screenshot_2016-07-19-09-54-18](https://cloud.githubusercontent.com/assets/19295794/17172112/918c2e80-542e-11e6-973f-f9760c9eab60.png)

**Comment by STRIKE-F** [comment]
현재는 큰형님으로 통일된 상태입니다. 올리신 대로 수정했습니다.
