### ISSUE TITLE
그 간극이 웜홀의 한쪽 끝을 이 시계가 있는 현재로 끌어당긴 것이 아닌가 싶어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1269]
![screenshot_2016-07-19-09-58-48](https://cloud.githubusercontent.com/assets/19295794/17172186/dcf4f56e-542e-11e6-8270-7be1d6c477b3.png)

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
