### ISSUE TITLE
그러부터 좀 지난 뒤, 전 코그씨의 상황을 듣게 되었죠.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1270]
![screenshot_2016-07-19-10-01-53](https://cloud.githubusercontent.com/assets/19295794/17172299/5a908c54-542f-11e6-9bf2-c1b6ff15bc8c.png)

**Comment by STRIKE-F** [comment]
현재 

얼마 뒤에, 전 코그 씨의 상황을 
알게 되었죠.

이렇게 수정했습니다.
