### ISSUE TITLE
루크, 그 질문에 대한 답은 모두가 알고 있을 것 같구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1271]
![screenshot_2016-07-19-10-02-59](https://cloud.githubusercontent.com/assets/19295794/17172326/85d160be-542f-11e6-9f09-52c0c95f6fae.png)

**Comment by STRIKE-F** [comment]
현재

루크, 그 질문의 대답은 모두가 알잖니.

이래서 한 줄 안에 모두 들어가게 됐습니다.
