### ISSUE TITLE
감사합니다, 선생님. 바로 그 대답을 원했습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1272]
![screenshot_2016-07-19-10-03-27](https://cloud.githubusercontent.com/assets/19295794/17172364/bb3e76f6-542f-11e6-9740-e680ac6ed923.png)

**Comment by STRIKE-F** [comment]
이것도 첫 줄이 너무 뻥 비어 보입니다 ㅇㅅㅇ;;
