### ISSUE TITLE
글쎄, 이 상태로 내버려 두는건 상상도 하기 싫구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1273]
![screenshot_2016-07-19-10-04-14](https://cloud.githubusercontent.com/assets/19295794/17172392/e22febc8-542f-11e6-8f74-054336c2788f.png)

띄워쓰기는 이미 수정되었으니 개행을 수행하면 좋겠습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
