### ISSUE TITLE
코그씨가 분명 가게의 모든 시계를 직접 만드셨을 거예요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1274]
![screenshot_2016-07-19-10-06-00](https://cloud.githubusercontent.com/assets/19295794/17172438/1199d004-5430-11e6-961d-f78160d23ab9.png)

**Comment by STRIKE-F** [comment]
현재 텍스트가

분명 가게 안의 시계는 
모두 코그 씨가
직접 만드셨을 거예요!

이렇게 바뀌었습니다.
