### ISSUE TITLE
저희 시간대의 문제를 해결하는 데 도움이 되는 정보를 찾으셨으면 좋겠습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1275]
![screenshot_2016-07-19-10-06-44](https://cloud.githubusercontent.com/assets/19295794/17172462/37cfcb48-5430-11e6-8613-1c0257920d05.png)

**Comment by STRIKE-F** [comment]
저희 시간대의 문제를 해결하는 데 
도움이 되는 정보를 찾을 수 있길
바랍니다.

일단 이렇게 바꾸어 봤습니다. 찾으시길 바랍니다는 명령체 같이 보여서요.

**Comment by STRIKE-F** [comment]
추가적인 의견이 없는고로...
