### ISSUE TITLE
네. 저도 그랬으면 좋겠군요. 코그씨, 시계를 부탁드리겠습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1276]
![screenshot_2016-07-19-10-07-54](https://cloud.githubusercontent.com/assets/19295794/17172494/591f5462-5430-11e6-8b3e-11aa86ab23ea.png)

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
