### ISSUE TITLE
그것보다, 내가 두 명의 루크와 함께 체르미 경감님을 찾아간다면 그가 얼마나 놀랄 지 상상이 안 가는걸.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1277]
![screenshot_2016-07-19-10-08-33](https://cloud.githubusercontent.com/assets/19295794/17172567/a738ff2c-5430-11e6-962a-aacd6f4fa7a6.png)

**Comment by STRIKE-F** [comment]
현재는 
"~체르미 경감님을 찾아간다면
그분이 얼마나 놀랄지 상상이 안 가는걸."

로 수정했습니다.
