### ISSUE TITLE
그래도 정말로 그렇게 된다면, 경감님 반응이 얼마나 재밌을지 상상해 보세요! 같이 오지 못한다니... 아쉬워요, 큰 루크

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1278]
![screenshot_2016-07-19-10-09-11](https://cloud.githubusercontent.com/assets/19295794/17172614/e0f39308-5430-11e6-9013-ee0acc5be24d.png)

**Comment by STRIKE-F** [comment]
같이 오지 못한다니... 아쉽네요. 로 수정했습니다.
큰 루크라는 말도 뭔가 루크가 쓰기엔 너무 어색해 보여서요.
