### ISSUE TITLE
이제 우리 시간대로 돌아왔으니, 버스로 대학교에 가는 건 시간문제겠구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1283]
![screenshot_2016-07-19-11-55-16](https://cloud.githubusercontent.com/assets/19295794/17172726/888b69f6-5431-11e6-85f5-1129e7ce8091.png)

**Comment by jungin019** [comment]
애매해서 그냥 놔두겠습니다

**Comment by jungin019** [comment]
아 그냥 시간 문제겠구나를 다음 행으로 넘길게요
