### ISSUE TITLE
어.. 음..우린 분명 안전할 거예요, 그렇죠? 절대로 제가 겁먹었거나 그런 게 아니라요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1292]
![screenshot_2016-07-15-10-02-26](https://cloud.githubusercontent.com/assets/19295794/17172930/bcebcde8-5432-11e6-8124-ff2edca8ab61.png)

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
