### ISSUE TITLE
어떻게 다른 사람이 내 배역을 가져가도록 내버려둔 거냐!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1294]
![screenshot_2016-05-10-17-52-19](https://cloud.githubusercontent.com/assets/19295794/17172994/2686bb3c-5433-11e6-94a3-cd4f8ed93d40.png)

다른 사람이 수염머플러의 배역을 어떠한 방법으로 가져가도록 했냐고 묻는 듯한 느낌입니다.

수정할 수 없을까요?

**Comment by Porowl** [comment]
어떻게 -> 어째서

**Comment by STRIKE-F** [comment]
어째서로 수정하겠습니다.
