### ISSUE TITLE
코그 씨. 저희가 왔을 때 조금 당황하시던 것 같던데요. 저희가 폐를 끼친 것이 아니기를 바랍니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1296]
![screenshot_2016-05-10-18-39-33](https://cloud.githubusercontent.com/assets/19295794/17173084/9e1628cc-5433-11e6-9a5f-0d93903391ff.png)

'당황하시던 것'을 '당황하신 것' 으로 바꿔서 1행에 넣을 수는 없을까요?

**Comment by STRIKE-F** [comment]
현재 

코그 씨. 저희가 왔을 때 조금 
당황하신 것 같던데요. 혹시 저희가
폐를 끼쳤나요?

이렇게 수정했습니다.
