### ISSUE TITLE
네. 그래서 교수님께서 이 시계의 아주 아름다운 모습을 보실 수 있도록 오시기 전에 조금 손보려고 했습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1297]
![screenshot_2016-05-10-18-41-48](https://cloud.githubusercontent.com/assets/19295794/17173114/d1a0413c-5433-11e6-971b-2f08e1ffa931.png)

1행의 '아주'를 생략하거나 다음 행으로 넘기는 건 어떨까요?

**Comment by STRIKE-F** [comment]
아주를 뺐습니다.
