### ISSUE TITLE
세상에, 정말 일을 빨리도 하시는군요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1298]
![screenshot_2016-05-10-21-20-38](https://cloud.githubusercontent.com/assets/19295794/17173156/10558c70-5434-11e6-9681-1a40b1f5805e.png)

'빨리도' 라는 표현은 반어법처럼 느껴지기도 하는데요,

레이튼은 그냥 진짜 빨리 했다는 느낌을 표현하고 싶은 것이니 

'빨리' 또는 '빠르게' 라는 표현을 사용하는 것은 어떨까요?

**Comment by Porowl** [comment]
실제로 반어법으로 받아들입니다.
남기는게 좋을듯 하네요
