### ISSUE TITLE
나로 말하자면 아름답고 미래를 내다보는 수수께끼 마담이란다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1299]
![screenshot_2016-05-19-13-23-05](https://cloud.githubusercontent.com/assets/19295794/17181421/0bc20356-545b-11e6-839c-4706e2e7d5fa.png)

'아름답고 미래를 내다보는' 이라는 표현이 조금 어색하지 않나요?

아니면 이미 수정되어 있나요?

**Comment by STRIKE-F** [comment]
아름다운 예언가 정도가 괜찮지 않을까 싶습니다.

**Comment by Porowl** [comment]
아름다운 미모의 예언가

로 바꾸면 어떨까요

**Comment by STRIKE-F** [comment]
찬님 의견을 반영해 현재

나로 말하자면 날카로운 통찰력을 가진 
아름다운 미모의 예언가, 
수수께끼 마담이란다.

로 수정했습니다.
