### ISSUE TITLE
시계를 작동시키자 땅이 흔들렸고, 레이튼과 루크는 가게 밖으로 나갔을때, 바뀌어버린 런던의 풍경에 충격을 받았다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1300]
![screenshot_2016-05-19-22-26-13](https://cloud.githubusercontent.com/assets/19295794/17201395/ec506490-54c8-11e6-9e11-54cddb4fc3b3.png)

'루크는' 보다 '루크가' 는 어떤가요?

그리고 '나갔을때,'는 '나갔을 때,' 로 띄우고,

글씨가 연필 표시에 가려지는 부분은 수정 가능한지 궁금합니다.

**Comment by STRIKE-F** [comment]
1,2는 올리신 대로 수정했습니다.
3은 눈 앞의 광경을 도무지 믿을 수 없었다. 정도가 어떠련지요

**Comment by Porowl** [comment]
그거에 찬성

**Comment by jungin019** [comment]
저도 스프님 의견 괜찮네요
