### ISSUE TITLE
한두 군데 정도 고장나 있어도 전혀 놀랄게 없어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1301]
![screenshot_2016-05-20-01-11-31](https://cloud.githubusercontent.com/assets/19295794/17201474/b5e29cb0-54c9-11e6-825a-d29d6a0423d9.png)

'놀랄게'는 '놀랄 게'로 띄우는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
