### ISSUE TITLE
플로라, 체르미, 그리고 바튼은 레이튼과 루크를 따라 미래로 오게된다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1302]
![screenshot_2016-07-21-11-12-42](https://cloud.githubusercontent.com/assets/19295794/17202145/642d08f2-54d2-11e6-9535-5492a63672c7.png)
'플로라, 체르미, 그리고 바튼은' 이라는 표현은

그냥 '그리고'를 빼고 '플로라, 체르미, 바튼은' 으로 바꾸는 것이 어떨까요?

그리고 '오게된다.'는 '오게 된다.' 로 띄워도 좋을 것 같습니다.

**Comment by STRIKE-F** [comment]
현재 쉼표 대신 '와'를 붙이는 거로 수정했습니다.
