### ISSUE TITLE
그분들은 항상 그랬고, 솔직히 그것 때문에 정말 마음이 아팠는데, 그래서..

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1303]
![screenshot_2016-07-21-11-19-22](https://cloud.githubusercontent.com/assets/19295794/17202250/27af8bd8-54d3-11e6-95dc-8a0fe4617f95.png)

1행의 '솔직히'는 다음 행으로 넘기고, 가능하다면 3행의 '아팠는데'를 2행 끝부분에 붙여 쓸 수 있을까요?

**Comment by STRIKE-F** [comment]
아팠는데와 솔직히 중 하나만 2행에 들어가는지라 아팠는데를 올리고 솔직히는 그대로 1행에 두었습니다. 솔직히를 내리면 첫째 줄이 뻥 비어 보이기도 해서요...
