### ISSUE TITLE
아, 죄송해요. 잡담해서 당신 시간을 뺏으려는 건 아니었는데...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1304]
![screenshot_2016-07-21-11-19-25](https://cloud.githubusercontent.com/assets/19295794/17211493/c70b5a5a-5504-11e6-96ee-cbaec79be0b2.png)

'잡담해서'를 '잡담을 해서' 로 수정하고,

3행 전체를 2행 끝부분에 붙여 쓰는 것은 어떨까요?

**Comment by STRIKE-F** [comment]
현재는

아, 죄송해요. 잡담으로
그쪽 시간을 뺏으려던 건 아니었는데...

로 수정했습니다.
