### ISSUE TITLE
그녀는 신경쓰지 마세요, 베키.플로라는 처음 보는 사람들이니까 좀 어색할지 모르겠군요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1305]
![screenshot_2016-07-21-11-19-32](https://cloud.githubusercontent.com/assets/19295794/17211536/00dc34e8-5505-11e6-8523-e18b70ed9b45.png)

그녀는 신경쓰지 마세요, 베키.
플로라는 처음 보는 사람들이니까
좀 어색할지 모르겠군요.

로 개행 수정하는 것은 어떨까요?

**Comment by STRIKE-F** [comment]
오역도 좀 낑긴 게 있고 해서 현재는

베키, 혹시 걱정하셨다면 괜찮습니다.
처음 뵙는 분이라 플로라가 좀
당황했나 보네요. 

로 고쳤습니다.
