### ISSUE TITLE
아, 그러실 필요 없어요. 이렇게 방을 함께 쓰는 게 좋은 걸요. 칸막이 정도만 달아두면 돼죠.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1306]
![screenshot_2016-07-21-11-20-05](https://cloud.githubusercontent.com/assets/19295794/17211585/3e4ab566-5505-11e6-977e-63c6c92ec4a8.png)

아, 그러실 필요 없어요.
이렇게 방을 함께 쓰는 게 좋은걸요.
칸막이 정도만 달아두면 되죠.

로 개행과 내용 수정하는 것은 어떨까요?

**Comment by Y00N** [comment]
쓰는 게 좋은 걸요. 보다는 **쓰는 게 좋아요** 쪽이 더 좋다고 생각합니다.

**Comment by STRIKE-F** [comment]
아, 그러실 필요 없어요. 
이렇게 방을 함께 쓰는 게 좋아요. 
칸막이 정도만 달아 두면 되죠.

종합해서 이렇게 수정했습니다
