### ISSUE TITLE
그럼 내가 침대를 하나 쓰고, 나머지 하나는 선생님께서 쓰시면 되겠네.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1307]
![screenshot_2016-07-21-11-20-12](https://cloud.githubusercontent.com/assets/19295794/17211613/732d3ef2-5505-11e6-920b-86389209333b.png)

문장을 조금 수정해서,

'그럼 내가 침대 하나, 다른 하나는 선생님께서 쓰시면 되겠네.' 로 수정하는 것은 어떤가요?

**Comment by STRIKE-F** [comment]
의미 차이가 좀 있어서 재번역을 했는데

그럼 내가 침대 하나를 쓰고, 나머지 
하나는 선생님께서 쓰시면 되지.

일단은 이렇게 수정해 봤습니다.

**Comment by Porowl** [comment]
다른 의견 없으면 낼 닫을게요
