### ISSUE TITLE
말도 안돼요! 저 작은 의자에 구겨 넣기엔 제 몸은 너무 크다고요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1308]
![screenshot_2016-07-21-11-20-17](https://cloud.githubusercontent.com/assets/19295794/17211647/ad05360c-5505-11e6-8939-bb144595e356.png)

번역체스러운 느낌이 조금 있다고 생각합니다. 어떻게 수정할 수는 없을까요?

ex) 말도 안돼요! 저도 커서 저렇게 작은 의자에는 안 들어간다구요.

**Comment by Y00N** [comment]
말도 안 돼요! 저렇게 작은 의자에 들어갈 만큼 작진 않다구요!

**Comment by STRIKE-F** [comment]
말도 안 돼요! 저도 그만큼 작진 않다구요!
로 수정하겠습니다.
