### ISSUE TITLE
선생님 말씀은 우리가 시간을 여행했다는 거예요! 여긴 10년 후 미래의 런던이라고요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1309]
![screenshot_2016-07-21-11-20-42](https://cloud.githubusercontent.com/assets/19295794/17211679/e207fc4a-5505-11e6-971d-7ca8b442770b.png)

선생님 말씀은
우리가 시간을 여행했다는 거예요!
여긴 10년 후 미래의 런던이라고요!

로 개행 수정하는 것은 어떨까요?

**Comment by STRIKE-F** [comment]
좀 자연스럽게 고쳐서

그러니까, 우린 시간여행을 했다고요!
여긴 10년 후의 런던이에요!

이렇게 고쳐 봤는데, 어떤가요?

**Comment by Porowl** [comment]
^ 찬성
