### ISSUE TITLE
우리는 지금 자신을 루크라고 밝힌 청년과 손을 잡고 있어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1310]
![screenshot_2016-07-21-11-20-47](https://cloud.githubusercontent.com/assets/19295794/17211747/32a59cc0-5506-11e6-84cd-2f952fdc38d0.png)

1행의 '루크라고 밝힌' 은 다음 행으로 넘기는 것이 어떤가요?

**Comment by STRIKE-F** [comment]
이게 좀 문장이 어색해 보여서

우린 지금 자기가 루크라고 하는 청년과
함께 다니고 있어.

이렇게 고쳐 봤는데 어떤가요?

**Comment by Porowl** [comment]
우린 지금 자기가 루크라고 주장하는
청년과 함께 다니고 있어

**Comment by jungin019** [comment]
전 스프님 의견이 더 괜찮은 것 같네요
