### ISSUE TITLE
그에 따르면 10년 동안 내가 굉장히 악한 사람이 되었다고 하는구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1311]
![screenshot_2016-07-21-11-20-52](https://cloud.githubusercontent.com/assets/19295794/17211823/85d6731a-5506-11e6-8067-c8950d4b03a2.png)

1행의 '굉장히'는 다음 행으로 넘기는 것이 어떤가요?

**Comment by STRIKE-F** [comment]
올리신 내용과 더불어 문장을 좀 자연스럽게 하고자

그가 말하길 10년 동안 내가 
굉장히 악한 사람이 되었다고 하는구나.

이렇게 수정했습니다.
