### ISSUE TITLE
이 청년은 우리와 손을 잡고 미래의 악한 레이튼을 멈추려고 한단다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1312]
![screenshot_2016-07-21-11-21-01](https://cloud.githubusercontent.com/assets/19295794/17211862/b40e7a02-5506-11e6-9ce6-eeb693878bea.png)

1행의 '미래의' 는 다음 행으로 넘기는 것이 어떤가요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
