### ISSUE TITLE
그런데...나는 못 봤다는 것에 이상함을 느끼지 않은 거야?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1313]
![screenshot_2016-07-21-11-21-46](https://cloud.githubusercontent.com/assets/19295794/17211892/dc355424-5506-11e6-9bef-a832646e8cd2.png)

말줄임표와 '나를' 사이에 한 칸을 띄우는 것이 좋겠습니다.

그리고 1행의 '이상함을' 은 다음 행으로 넘기는 것이 어떨까요?

**Comment by Y00N** [comment]
플로라의 말이요... **그런데... 내가 안 보여서 이상하진 않았어?** 라고 고쳐보는 건 어떨까요?

**Comment by jungin019** [comment]
전 현로님께서 말씀하신 게 좋은 것 같네요

**Comment by STRIKE-F** [comment]
현로님 번역이 괜찮아 보이네요. 이대로 수정하겠습니다.
