### ISSUE TITLE
이 도시에서 가장 잘 나가는 레스토랑에 가서 기분 전환 좀 하는게 어떠니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1314]
![screenshot_2016-07-21-11-22-02](https://cloud.githubusercontent.com/assets/19295794/17211927/0ad10e2c-5507-11e6-9890-e0d6ea548c27.png)

'하는게'는 '하는 게' 로 띄우는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
띄어쓰기도 고치고, 현재는

이 도시에서 가장 잘나가는 레스토랑에서 
기분 전환 좀 하는 게 어떠니?

로 고쳤습니다.
