### ISSUE TITLE
네, 잘 지내고 있습니다. 학장님도 잘 지내고 계신가 보군요. 젊어보이시기까지 한데요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1315]
![screenshot_2016-07-21-11-22-50](https://cloud.githubusercontent.com/assets/19295794/17211959/41ddc9a0-5507-11e6-8926-7f395a38415a.png)

네, 잘 지내고 있습니다.
학장님도 잘 지내고 계신가 보군요.
젊어보이시기까지 한데요!

로 개행 수정하는 것은 어떤가요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
