### ISSUE TITLE
맙소사! 하루가 다르게 늙어가는 이 노인네한테 무슨 소리를 하는 겐가.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1316]
![screenshot_2016-07-21-11-22-53](https://cloud.githubusercontent.com/assets/19295794/17212016/86d48292-5507-11e6-8f2a-0b941a6b028d.png)

1행의 '이'는 다음 행으로 넘기는 것이 어떤가요?

**Comment by Y00N** [comment]
"이"는 뺐으면 좋겠습니다.

**Comment by STRIKE-F** [comment]
이를 빼는 쪽으로 수정했습니다.
