### ISSUE TITLE
수두룩한 흰머리만 봐도 알 수 있지 않은가.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1317]
![screenshot_2016-07-21-11-22-59](https://cloud.githubusercontent.com/assets/19295794/17212053/b89816a4-5507-11e6-9a3e-e62355bd8d34.png)

1행의 '알 수 있지' 는 다음 행으로 넘기는 것이 어떤가요?

그리고 제 생각으로는 흰머리에 '수두룩한' 이라는 표현은 조금 어색해 보이기도 하는데

대체할 만한 다른 표현은 없을까요?

**Comment by STRIKE-F** [comment]
개행은 수정했습니다.

**Comment by Porowl** [comment]
덥수룩한...을 쓸수도 없고

**Comment by jungin019** [comment]
전 수두룩한 이 별로 어색해보이지 않는데...

**Comment by Porowl** [comment]
머리에 눈이 내렸다던가

**Comment by STRIKE-F** [comment]
저도 수두룩한이 그렇게 어색하진 않다고 생각합니다. 고로....
