### ISSUE TITLE
...아, 그렇군요. 뭔가 달라지신 것 같았습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1318]
![screenshot_2016-07-21-11-23-05](https://cloud.githubusercontent.com/assets/19295794/17212136/80566f88-5508-11e6-99b3-8c3c68ae2906.png)

말줄임표와 '아,' 사이에 한 칸을 띄우는 것이 좋겠습니다.

그리고 1행의 '뭔가 달라지신 것' 은 다음 행으로 넘기는 것이 어떨까요?

**Comment by Porowl** [comment]
<T>... 아, 그렇군요. 어쩐지 어딘가 
달라지셨다는 느낌이 들더군요.
