### ISSUE TITLE
대사의 오타(예요/에요)

### ISSUE THREAD

**Issue by rabbitdoggy** [elfinlazz/lt3translation#132]
![screenshot_2016-05-09-18-43-33](https://cloud.githubusercontent.com/assets/19265174/15121650/7afc25f0-1656-11e6-8c1e-54ad0315e51b.png)

말이예요? -> 혹은 말이에요?

※ '말'이 받침 있는 단어이므로 '이에요'가 와야 합니다.

**Comment by Porowl** [comment]
말인가요? 로 고쳤습니다.
