### ISSUE TITLE
그래...세월이 학장님께 선명한 흔적을 남긴 것 같구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1320]
![screenshot_2016-07-21-11-23-29](https://cloud.githubusercontent.com/assets/19295794/17212249/0a762fa0-5509-11e6-9772-7e6b11ef92ca.png)

말줄임표와 '세월이' 사이에 한 칸을 띄는 것이 좋겠습니다.

그리고 1행의 '선명한' 은 다음 행으로 넘기는 것이 어떨까요?

**Comment by Y00N** [comment]
저는 문장을 좀 바꿨으면 좋겠어요.
**그래... 학장님도 세월을 비껴가진 못했구나.** 라는 식으로요

**Comment by Porowl** [comment]
^ 멋있네요. 찬성

**Comment by jungin019** [comment]
그래... 학장님도 세월을 비껴가시진 못했구나. 
괜찮은 것 같아요
