### ISSUE TITLE
런던 최고의 맛집에 오신 것을 환영합니다! 식욕은 충만하신가요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1321]
![screenshot_2016-07-21-11-24-40](https://cloud.githubusercontent.com/assets/19295794/17212296/46a95d1c-5509-11e6-9675-ec1397e8088c.png)

'식욕은 충만하신가요?' 라고 묻는 것이 약간은 무례해 보이기도 합니다.

대체할 만한 다른 표현은 없을까요?

**Comment by jungin019** [comment]
저는 딱히 무례하게 보이지는 않는데... 
뭐 '배가 많이 고프신가요?' 정도도 괜찮을 것 같네요

**Comment by Porowl** [comment]
식욕은 가져오셨겠죠?

원문이 이렇다보니

**Comment by STRIKE-F** [comment]
약간의 패러디? 로
저장된 식욕은 충분하신가요? 로 고칩니다 ㅇㅅㅇ

UBW 읍읍
