### ISSUE TITLE
그럴지도 모르겠군요. 그 얘기는 왜 꺼내신겁니까?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1322]
![screenshot_2016-07-21-11-24-46](https://cloud.githubusercontent.com/assets/19295794/17212331/82d26b62-5509-11e6-86c5-af82867bdb6a.png)

'왜 꺼내신겁니까?' 는 약간 따지는 듯한 느낌이기도 한데

수정할 수는 없을까요?

**Comment by jungin019** [comment]
원문이 'Why do you bring it up, sir?'입니다. 
맥락에 맞춰 좀 순화해보면 '뭔가 부탁하실 게 있나요?' 정도면 되려나요... 
딱히 뭐라고 고쳐야할지...

**Comment by Porowl** [comment]
^ 저거면 될듯 하네요
