### ISSUE TITLE
조사 메모 - 뒤죽박죽이 된 미래

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1327]
![screenshot_2016-07-21-11-28-47](https://cloud.githubusercontent.com/assets/19295794/17212567/0223859e-550b-11e6-94e5-a734007b3311.png)

계획이 꼬여버렸다.
우리 뒤를 밟은 사람이 몇 있다.
체르미 경감님과 바튼뿐만이 아니라
플로라까지 따라왔다.
체르미 경감님과 바튼은
열정적으로 수사를 하러 떠났지만
플로라가 우리와 함께 다니는 건
너무 위험한 것 같다.
어떻게 설득해야 하지?

로 개행 수정하는 것은 어떤가요? 

그리고 '바튼뿐만이'는 '바튼 뿐만이' 로 띄워야 하는지 말아야 하는지 헷갈리네요 ;_;

**Comment by jungin019** [comment]
바튼뿐만이는 붙이는 게 맞는 것 같습니다.
