### ISSUE TITLE
조사 메모 - 미래의 딘 델모나 

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1328]
![screenshot_2016-07-21-11-28-52](https://cloud.githubusercontent.com/assets/19295794/17212613/4210e69c-550b-11e6-86f9-960d9ee2e696.png)

플로라에게 상황을 설명하려고 했지만,
플로라는 우리가 얼마나 위험한 상황에
처해 있는지 모르는 것 같다.
아마도 플로라를 데리고 다니는 위험을
감수해야 할 것 같다.
호텔에선 머리가 백발이 된
딘 델모나 학장님을 만났다.
우리는 식당에 있을 쉬플리에게
미래의 루크의 행방을 물으러 가기로 했다.

로 개행과 내용 수정을 하면 어떨까 하는데, 공간이 될지 모르겠네요.

그리고 '~의' 라는 표현이 반복되는 것을 수정할 수는 없을까요?

**Comment by jungin019** [comment]
마지막 줄이 다 안 들어가서 했다는 다음 줄에 넣었습니다. 
미래의 루크의 행방을 미래 루크의 행방으로 고쳐놨습니다.
