### ISSUE TITLE
퀴즈 15번의 띄어쓰기

### ISSUE THREAD

**Issue by rabbitdoggy** [elfinlazz/lt3translation#133]
![screenshot_2016-05-09-18-44-54](https://cloud.githubusercontent.com/assets/19265174/15121741/e78b8882-1656-11e6-8e5d-0a2b9eae81ed.png)

몇개 -> 몇 개

**Comment by kaleidoscope531** [comment]
몇개를 -> 몇 개를
아랬쪽의 사람 B -> 아래쪽의 사람 B
이 부분도 바꿔야 하네요

그리고 이건 개인적인 생각인데요

위쪽의 사람 A는 위에서 본 모습을, 아래쪽의 사람 B는 옆에서 본 모습을 설명하고 있다.
이 쪽이 자연스럽지 않을까요?

**Comment by Porowl** [comment]
위 내용을 다 적용했습니다.
