### ISSUE TITLE
네, 맞습니다. 루크가 거기서 기다리고 있겠답니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1331]
![screenshot_2016-07-21-11-31-29](https://cloud.githubusercontent.com/assets/19295794/17212781/28a93d52-550c-11e6-9ff7-b286b800c416.png)

1행의 '루크가 거기서' 는 다음 행으로 넘기는 것이 어떨까요?

**Comment by jungin019** [comment]
팀내 회의를 통해 문장이 한 줄의 반을 넘어가지 않으면 개행을 하지 않기로 했습니다.
