### ISSUE TITLE
아무 걱정 말거라, 루크. 눈 깜짝하기도 전에 이 수수께끼를 풀고 문을 열 테니.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1333]
![screenshot_2016-07-21-11-33-07](https://cloud.githubusercontent.com/assets/19295794/17212860/74e4bc46-550c-11e6-82ab-85bd9006f8c1.png)

아무 걱정 말거라, 루크.
눈 깜짝하기도 전에
이 수수께끼를 풀고 문을 열 테니.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
아무 걱정 말거라, 루크. 
눈 깜짝하기도 전에 이 수수께끼를 풀고 
문을 열 테니. 로 개행했습니다.
