### ISSUE TITLE
그래도, 다시 만나서 반가워. 잘 지내나 보네.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1335]
![screenshot_2016-07-21-11-34-36](https://cloud.githubusercontent.com/assets/19295794/17212945/e609e644-550c-11e6-93fc-44d0d91107b8.png)

1행의 '잘 지내나' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by Y00N** [comment]
이 부분의 그래도는 **여하튼**이나 **아무튼**으로 바꾸어 쓰는 게 어떨까요?

**Comment by jungin019** [comment]
아무튼으로 수정했습니다.
