### ISSUE TITLE
경감님이 우리를 따라올 거란 걸 이미 예상했다는 거니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1336]
![screenshot_2016-07-21-11-34-47](https://cloud.githubusercontent.com/assets/19295794/17212969/0d47e6de-550d-11e6-8473-ab23314e45cc.png)

'거란 걸' 을 풀어서 쓰면 '것이란 것을' 이 되는데

'~것' 이라는 표현이 반복되어 이상하다고 생각합니다.

다른 표현으로 수정할 수는 없을까요?

**Comment by jungin019** [comment]
그냥 '따라올 걸'로 고치는 게 어떨까요
