### ISSUE TITLE
예상까지는 아니지만, 그럴 지도 모른다고 생각했어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1337]
![screenshot_2016-07-21-11-34-50](https://cloud.githubusercontent.com/assets/19295794/17212996/3f543e8e-550d-11e6-9131-632a0a7afbf5.png)

'그럴 지도'는 '그럴지도' 로 붙여 쓰는 것이 좋겠습니다.

그리고 1행의 '그럴지도' 는 다음 행으로 넘기는 것이 어떨까요?

**Comment by Y00N** [comment]
예상했다기보다도 그럴지도 모른다고 생각했어요.
라고 쓰는 게 어떨까요?

**Comment by jungin019** [comment]
현로님 의견도 괜찮을 것 같네요. 
문장 수정 뒤 개행하는 게 좋겠습니다.

**Comment by Porowl** [comment]
다른 의견 없으면 닫아주세요
