### ISSUE TITLE
잡담은 이정도로 하고, 차이나타운으로 들어갈 궁리를 해보죠.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1338]
![screenshot_2016-07-21-11-34-53](https://cloud.githubusercontent.com/assets/19295794/17213032/6c8d0958-550d-11e6-97af-9a56cf45cd85.png)

'이정도로'는 '이 정도로' 로 띄우고,

1행의 '차이나타운으로'는 다음 행으로 넘기는 것이 어떨까요?

**Comment by Y00N** [comment]
잡담은 이정도로 하자는 게 예의바른 청년루크 친구에 맞지 않게 조금 되바라져 보이는데 

중요한 이야기는 아니니 이만하고, 
차이나타운으로 들어갈 궁리를 하죠.

라고 바꾸어보면 어떨까요? 그래도 별 소용이 없나...?

**Comment by jungin019** [comment]
현로님 말씀이 더 괜찮을 것 같기도 하네요

**Comment by Porowl** [comment]
다른 의견 없으면 닫아주세요

**Comment by STRIKE-F** [comment]
현로님이 올리신 대로 수정했습니다.
