### ISSUE TITLE
그 보초들을 어떻게 하지 않으면 거기엔 들어가지도 못할 거에요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1339]
![screenshot_2016-07-21-11-34-56](https://cloud.githubusercontent.com/assets/19295794/17213065/a141c8e6-550d-11e6-8e2c-f260b2d11c5f.png)

1행의 '거기엔'은 다음 행으로 넘기는 것이 어떨까요?

**Comment by Y00N** [comment]
**보초를 어떻게 하지 않으면
거긴 들어가지도 못할 거예요.**
라고 다듬는 게 좋지 않을까요?

**Comment by jungin019** [comment]
보초를 어떻게 하지 않으면
거긴 들어가지도 못할 거예요. 로 수정
