### ISSUE TITLE
맞아요. 그 문에 있던 보초들은 항상 그곳에서 알짱거리고 있는게 아니에요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1340]
![screenshot_2016-07-21-11-35-06](https://cloud.githubusercontent.com/assets/19295794/17213097/c93e321c-550d-11e6-944e-b60c28a4d6e8.png)

'있는게'는 '있는 게' 로 띄우는 것이 좋겠습니다.

**Comment by Y00N** [comment]
**맞아요. 항상 거기서 알짱거리진 않아요.**
로도 충분하지 않을까요?

**Comment by jungin019** [comment]
알짱거리다의 어감이 그닥 좋지가 않아서 
'맞아요. 보초들이 항상 그 주위를 배회하진 않아요' 나 
'맞아요. 보초들이 항상 거기서 어슬렁거리진 않아요' 로 바꾸는 건 어떨까요

**Comment by Porowl** [comment]
어슬렁 쪽이 좋아보입니다.

**Comment by STRIKE-F** [comment]
맞아요. 보초들이 항상 거기서 어슬렁거리진 않아요

이대로 수정하겠습니다.
