### ISSUE TITLE
레이튼이 지시할 때만 그 문을 지키고 있는 녀석들이죠.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1341]
![screenshot_2016-07-21-11-35-12](https://cloud.githubusercontent.com/assets/19295794/17213123/ed7f1b82-550d-11e6-8f87-c4f291d21c20.png)

1행의 '그 문을 지키고'는 다음 행으로 넘기는 것이 어떨까요?

**Comment by STRIKE-F** [comment]
챗방에 올린 이유로 지키고만 내리겠습니다.
