### ISSUE TITLE
그 곳에서 정찰을 많이 한 터라 발각되었을 수도 있어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1342]
![screenshot_2016-07-21-11-35-26](https://cloud.githubusercontent.com/assets/19295794/17213173/2dc4ccbe-550e-11e6-83cd-014f9ffa9891.png)

'많이 한 터라' 라는 표현은 문어체스럽다고 생각합니다.

다른 표현으로 대체할 수는 없을까요?

ex) '많이 해서', ...

**Comment by Y00N** [comment]
저는 "~한 터라"는 문제가 없다고 생각합니다.
**거기서 정찰을 많이 한 터라, 이미 발각되었을지도 몰라요.**
라는 쪽으로 다듬어보면 어떨까요?

**Comment by STRIKE-F** [comment]
현로님이 올리신 대로 수정하겠습니다.
