### ISSUE TITLE
그렇구나. 하지만 어떻게 미래의 레이튼이 그렇게 지시하도록 할 수 있겠니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1343]
![screenshot_2016-07-21-11-35-35](https://cloud.githubusercontent.com/assets/19295794/17213251/8a27f512-550e-11e6-9eba-046b20c22293.png)

'하지만 어떻게' 라는 표현, 저는 조금 어색하다고 생각하는데

다른 분들은 어떻게 생각하시는지 궁금합니다.

**Comment by Y00N** [comment]
"하지만 어떻게" 자체는 큰 문제 없다고 생각합니다. 하지만 문장 뒤의 "지시하도록 할 수 있겠니?"가 부자연스럽기에 다소 문장의 수정이 필요하다고 생각합니다.
**하지만, 어떻게 하면 미래의 레이튼이 그런 지시를 하겠니?
하지만, 어떻게 하면 미래의 레이튼이 그렇게 지시하겠니?**
따위로 다듬으면 어떨까요?

**Comment by STRIKE-F** [comment]
그렇구나. 하지만, 어떻게 해야 미래의 레이튼이 우리 뜻대로 움직여 줄까? 는 어떨까요

**Comment by Porowl** [comment]
^ 이쪽이 더 나아 보입니다.

**Comment by STRIKE-F** [comment]
그럼 제가 쓴 대로 수정하겠습니다.
