### ISSUE TITLE
그러고 보니 말야, 예전에 강가에서 만난 네 친구가 목소리의 귀재 아니었니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1344]
![screenshot_2016-07-21-11-36-01](https://cloud.githubusercontent.com/assets/19295794/17213302/c96009f4-550e-11e6-9c15-e5b065fb4427.png)

그러고 보니 말야, 
예전에 강가에서 만난 네 친구가
목소리의 귀재 아니었니?

로 개행 수정하면 어떨까요?

**Comment by Y00N** [comment]
목소리 자체는 귀재가 될 수 없지 않나요.
**~ 네 친구가 목소리 변조의 귀재 아니었니?** 라는 식으로 고쳐보는 건 어떨까요?

**Comment by STRIKE-F** [comment]
-네 친구가 성대모사의 달인 아니었니? 는 어떨까요
개행은 공백 때문에 보류하겠습니다.

**Comment by Porowl** [comment]
^ 이쪽이 나아 보입니다.

**Comment by jungin019** [comment]
저도 스프님 의견이 좀 더 괜찮은 것 같네요

**Comment by STRIKE-F** [comment]
이대로 수정하겠습니다.
