### ISSUE TITLE
하지만 꼭 필요해요. "썩 꺼져" 가 없으면 보스트로가 아니라고요. 항상 그러고 다니거든요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1345]
![screenshot_2016-07-21-11-36-14](https://cloud.githubusercontent.com/assets/19295794/17213356/0695dc5e-550f-11e6-84da-f41304fe16a6.png)

2행의 '항상 그러고'는 다음 행으로 넘기는 것이 어떨까요?

**Comment by Y00N** [comment]
"썩 꺼져" 가 없으면 은 **"썩 꺼져"가 없으면** 으로 붙여 써주세요.

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
