### ISSUE TITLE
요 며칠 동안 미행을 해 봤어요. 하루에도 수십 번을 쓰더라고요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1346]
![screenshot_2016-07-21-11-36-17](https://cloud.githubusercontent.com/assets/19295794/17213385/2ac89508-550f-11e6-932b-0ceaf07ef54c.png)

1행의 '하루에도' 는 다음 행으로 넘기는 것이 어떨까요?

**Comment by Y00N** [comment]
틀린 건 아니지만 **해봤어요**도 붙여쓰죠.

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
