### ISSUE TITLE
아무튼 "썩 꺼져"가 차이나 타운으로 들어가는 열쇠야. 어서 보스트로를 찾기 시작해야 해.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1347]
![screenshot_2016-07-21-11-36-25](https://cloud.githubusercontent.com/assets/19295794/17213493/71c40cd0-550f-11e6-95ab-e502cfea8f29.png)

아무튼 "썩 꺼져" 가 차이나타운으로
들어가는 열쇠야.
어서 보스트로를 찾아야 해.

로 개행과 내용 수정하는 것은 어떨까요?

**Comment by Y00N** [comment]
**"썩 꺼져"가** 로 붙여 써야 합니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
