### ISSUE TITLE
저렇게 생긴 흰 줄무늬 옷을 입고 다니는 녀석은 보스트로밖에 없지. 다들, 빨리 숨어요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1348]
![screenshot_2016-07-21-11-37-17](https://cloud.githubusercontent.com/assets/19295794/17213555/bb675db0-550f-11e6-895c-9a7cd625bbf9.png)

공간이 된다면 2행의 '다니는' 은 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
