### ISSUE TITLE
아니긴 뭐가 아니야! 마음가짐이 그 꼴이니 네가 말단에서 허드렛일이나 하고 있는 거지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1349]
![screenshot_2016-07-21-11-37-36](https://cloud.githubusercontent.com/assets/19295794/17213578/df2ed2d2-550f-11e6-8097-2be915dde38c.png)

아니긴 뭐가 아니야!
마음가짐이 그 꼴이니 네가 말단에서
허드렛일이나 하고 있는 거지.

로 개행 수정하는 것은 어떨까요?

**Comment by STRIKE-F** [comment]
공백 문제로 보류하겠습니다.

**Comment by STRIKE-F** [comment]
아니긴 뭐가 아니야! 그런 마음가짐이니
네가 말단에서 허드렛일이나 하는거지.

이렇게 수정했습니다.
