### ISSUE TITLE
그건 안 돼요, 두목! 잘리는 것만은 안 돼요! 갈 곳도 없단 말이에요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1350]
![screenshot_2016-07-21-11-37-46](https://cloud.githubusercontent.com/assets/19295794/17213636/1d46deca-5510-11e6-8ead-4103362c234c.png)

그건 안 돼요, 두목!
잘리는 것만은 안 돼요!
갈 곳도 없단 말이에요!

로 개행 수정하는 것은 어떨까요?

**Comment by Y00N** [comment]
"잘리는 것만은 안 돼요!"를 **잘리는 것만은 봐주세요!** 로 바꾸어보는 건 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.

**Comment by STRIKE-F** [comment]
첫줄 공백 문제 때문에 보류합니다

**Comment by STRIKE-F** [comment]
그건 안 돼요, 두목! 해고만 하지 마세요! 
갈 곳도 없단 말이에요!

이렇게 수정해 봤는데, 어떤가요.

**Comment by STRIKE-F** [comment]
이대로 수정하겠습니다.
