### ISSUE TITLE
대체 어떤 바보가 자기 카지노를 이렇게까지 부술 수 있죠?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1351]
![screenshot_2016-07-21-11-38-23](https://cloud.githubusercontent.com/assets/19295794/17213710/70071b2a-5510-11e6-8dc9-aadc9fea10ed.png)

1행의 '자기'는 다음 행으로 넘기는 것이 어떨까요?

**Comment by STRIKE-F** [comment]
공간이 부족해서 넘길 수가 없습니다.
