### ISSUE TITLE
이 동상을 보니 왜 있잖아요, 미래에 대해서 생각하게 돼요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1352]
![screenshot_2016-07-21-11-38-43](https://cloud.githubusercontent.com/assets/19295794/17213747/9acdfd38-5510-11e6-9ce6-ee917644b86f.png)

1행의 '미래에' 는 다음 행으로 넘기는 것이 어떨까요?

**Comment by STRIKE-F** [comment]
약간 오역이 있어서 현재는

이 동상을 보면... 그...
미래에 대해서 생각하게 돼요.

이렇게 수정했습니다.
