### ISSUE TITLE
어려운 문제인데... 우리의 만남이 우리 둘을 많이 바꿔놓았잖아.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1353]
![screenshot_2016-07-21-11-39-14](https://cloud.githubusercontent.com/assets/19295794/17213789/dcda3e08-5510-11e6-8461-178e308c1b3f.png)

1행의 '우리'는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
번역을 약간 수정해서 현재는

어려운 문제인데... 우리가 만나며
많은 게 달라졌어.

이렇게 수정했습니다.
