### ISSUE TITLE
비극이 그 추악한 앞발을 내밀때, 진짜 사나이는 어떻게 대처할 지 알겠지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1354]
![screenshot_2016-07-21-11-39-48](https://cloud.githubusercontent.com/assets/19295794/17213845/29130bec-5511-11e6-83b2-43360452cf05.png)

'내밀때,' 는 '내밀 때,' 로 띄우고, '대처할 지' 는 '대처할지' 로 붙이는 것이 좋겠습니다.

그리고 1행의 '진짜' 는 다음 행으로 넘기는 것이 어떨까요?

**Comment by Y00N** [comment]
진짜 사나이는 대처하는 방법을 안다는 말은 
다른 사람들이 비극이 앞발을 내밀면 혼란스러워하고 갈팡질팡한다는 의미를 내포할텐데
그렇다면, 
**비극이 추악한 앞발을 내밀더라도
진짜 사나이는 결코 두려워하지 않아**.
라는 편이 좀 더 자연스럽지 않을까요?

**Comment by STRIKE-F** [comment]
비극이 추악한 앞발을 내밀더라도
진짜 사나이는 결코 두려워하지 않아.

이렇게 수정했습니다.
