### ISSUE TITLE
조사 메모 - 전망대에서의 대화

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1356]
![screenshot_2016-07-21-11-40-59](https://cloud.githubusercontent.com/assets/19295794/17234829/45015852-5577-11e6-92a3-7ac85f3d21d7.png)

개행을 수정하고 싶은데 그러려면 칸에 다 안 들어갈 것 같아서...;;

'미래의 나의' 에서 '~의' 라는 표현이 반복되어 어색해 보이는데

수정할 수 없을까요?

**Comment by STRIKE-F** [comment]
오역을 고쳐서 현재는

드디어 미래의 루크를 만났다.
차이나타운에 들어가려면 
출입구를 지키고 있는 경비들을 
먼저 처리해야 하는 듯하다.
미래의 루크가 말하길 그들은
미래의 나의 오른팔인 보스트로의
명령만 있으면 떠난다고 한다.
그런고로 우리는 카지노로 가서
보스트로가 오기를 기다리기로 했다.

로 고쳤습니다.
-의 -의는 좀 고민해 봐야 할 문제 같습니다.

**Comment by STRIKE-F** [comment]
미래의 루크가 말하길 그들은
미래의 내 오른팔인 보스트로가
명령만 하면 바로 떠날 거라 했다.

최종적으로 이렇게 수정했습니다.
