### ISSUE TITLE
조사 메모 - 경비병을 피해서

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1357]
![screenshot_2016-07-21-11-41-04](https://cloud.githubusercontent.com/assets/19295794/17234896/c4321d1e-5577-11e6-9cfb-4627a1e41cd7.png)

'기억하도록 하는 것에 성공했다.' 는 약간 번역체스러운 느낌이 있다고 생각하는데

수정할 수는 없을까요?

**Comment by STRIKE-F** [comment]
앵무새가 보스트로의 목소리를 따라하게 하는 데 성공했다
로 수정하겠습니다.
