### ISSUE TITLE
날 비난하지 말라고. 인생이 꼭 장밋빛이리란 보장은 없지만 난 지금 같이 얘기할 사람도 없어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1364]
![screenshot_2016-07-21-11-42-49](https://cloud.githubusercontent.com/assets/19295794/17235047/f3ee5404-5578-11e6-8a6f-742b455ed27d.png)

날 비난하지 말라고.
인생이 꼭 장밋빛이리란 보장은 없지만
난 지금 같이 얘기할 사람도 없어.

로 개행 수정하는 것은 어떨까요?

**Comment by STRIKE-F** [comment]
공백 문제로 보류합니다.

**Comment by Porowl** [comment]
다른 이슈에서 다룬 문제입니다
