### ISSUE TITLE
정말 똑똑하구나! 언제 한번 다시 찾아오렴. 알겠지?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1366]
![screenshot_2016-07-21-11-54-25](https://cloud.githubusercontent.com/assets/19295794/17235091/346f13f6-5579-11e6-8f74-9d2a08637b1e.png)

정말 똑똑하구나!
언제 한 번 다시 찾아오렴. 알겠지?

로 개행과 내용 수정하는 것은 어떨까요?

**Comment by STRIKE-F** [comment]
띄어쓰기는 수정했습니다.
