### ISSUE TITLE
힌트 파일 띄어쓰기[공포를 불러일으키는 모자]

### ISSUE THREAD

**Issue by rabbitdoggy** [elfinlazz/lt3translation#137]
![screenshot_2016-05-09-18-51-14](https://cloud.githubusercontent.com/assets/19265174/15121999/076106c2-1658-11e6-97f6-822e850d33c1.png)

듯 한 느낌이다. -> 듯한 느낌이다.

**Comment by kaleidoscope531** [comment]
'아주 오래된 도로인 미드랜드 길도 완전히 새 길 같다. 그리고 나의 모자는 사람들을 약간 당황시키는 것 같다.'
이 부분 원문이
Not only does gloomy old Midland Road look like a whole new place, it would also seem that my hat is causing people some consternation.
인데요. 제가 느낀 뉘앙스는 '뭐 일단 오래 된 미들랜드 도로의 풍경이 완전히 처음 보는 것처럼 바뀐건 둘째 치고 왜 사람들이 내 모자를 보고 무서워하지?' 이런 느낌인데 두 문장을 나눠놓아서 느낌이 잘 안 사는 것 같아요
굳이 제안을 하자면
오래 된 미들랜드 도로의 풍경이 완전히 처음 보는 것처럼 바뀐건 둘째 치고 나의 모자가 사람들을 놀라게 하는 것 같다.
정도가 좋지 않을까요?

**Comment by Porowl** [comment]
우선 Kaleidoscope531님이 말씀하신대로 수정해 뒀습니다. 이슈는 아직 닫지 않겠습니다.

**Comment by jungin019** [comment]
둘째 치고 보다는 '~처음 보는 것처럼 바뀐데다 사람들이 내 모자를 두려워하는 것 같다' 정도로 하는 게 어떨까요

**Comment by kaleidoscope531** [comment]
Not only ~~ also %%%이니까 '둘째 치고'는 너무 과했을지도 모르겠군요. jungin019씨의 생각도 맞는 것 같습니다.

**Comment by Porowl** [comment]
토의나온대로 수정하겠습니다.
