### ISSUE TITLE
선생님 말씀대로 하죠. 다시 말하지만 만나서 반가워, 작은 루크!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1377]
![screenshot_2016-07-15-08-40-54](https://cloud.githubusercontent.com/assets/19295794/17235460/314cd020-557c-11e6-9634-10bc4a34218c.png)

3행의 '작은 루크!' 는 2행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by Porowl** [comment]
좁아요.
