### ISSUE TITLE
발표가 곧 시작하려나 봐요

### ISSUE THREAD

**Issue by Glacie** [elfinlazz/lt3translation#139]
![screenshot_2016-05-10-02-22-14](https://cloud.githubusercontent.com/assets/19269458/15121557/2b0143aa-1656-11e6-81e1-ca3b2924f01a.png)

[발표가 곧 시작하려나 봐요]를

[발표'를' 곧 시작하려나 봐요]로 고치는 것과 그대로 두는 것

어느쪽이 더 자연스러울지 의견을 묻고 싶습니다.

**Comment by Y00N** [comment]
개인적으로는 '발표'는 그 자체가 능동적으로 시작할 수 있는게 아니고 관계자에 의해 시작되어지는 것이기 때문에 주어가 아닌 목적어로 보는 게 맞다고 생각합니다.

**Comment by kaleidoscope531** [comment]
저도 '를'에 한 표 던지겠습니다.

**Comment by STRIKE-F** [comment]
를로 바꾸는 게 맞는 것 같네요. 그렇게 수정하겠습니다.
