### ISSUE TITLE
정말 다행이군. 만약 너였다면 네녀석의 골빈 짓에 대해 끔찍한 설교를 할 뻔 했거든.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1391]
![screenshot_2016-07-15-10-21-48](https://cloud.githubusercontent.com/assets/19295794/17235792/d1e460a0-557e-11e6-97d3-42c9ee2b07d0.png)

정말 다행이군.
만약 너였다면 네 녀석의 골빈 짓에 대해
끔찍한 설교를 할 뻔 했거든.

으로 내용과 개행 수정하는 것은 어떨까요?

**Comment by Porowl** [comment]
좁아요.
