### ISSUE TITLE
여기 이 루크가 아무리 사소한 사실이라도 자기랑 이야기하기 전까지는 알려주지 말라 해서요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1396]
![screenshot_2016-07-15-10-30-33](https://cloud.githubusercontent.com/assets/19295794/17235907/c289c310-557f-11e6-8f37-7031b861de52.png)

여기 이 루크가 아무리 사소한 사실이라도
자기랑 이야기하기 전까지는
알려주지 말라 해서요.

로 개행 수정을 했으면 하는데 공간이 되나요?

**Comment by Porowl** [comment]
좁습니다.
