### ISSUE TITLE
그러면 좋겠지만, 여기서 미래의 너에게서 올 명령을 기다려야 하니까.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1410]
![screenshot_2016-07-15-10-33-31](https://cloud.githubusercontent.com/assets/19295794/17236212/6d67b40c-5582-11e6-982c-b2a9bfa96756.png)

1행의 '여기서' 는 다음 행으로 넘기는 것이 어떨까요?

그리고 '~서' 라는 표현이 반복되어 이상하다고 생각하는데 수정할 수는 없을까요?

**Comment by Porowl** [comment]
그러면 좋겠지만, 여기서
미래의 네가 전달할 사항을
기다려야 하니까.

1차 수정

**Comment by STRIKE-F** [comment]
그러면 좋겠지만, 여기에 있어야
미래의 너에게서 올 명령을
받을 수 있으니까.

는 어떠련지요
