### ISSUE TITLE
그렇군요. 도와줘서 고맙습니다 쉬플리 씨. 가자, 루크. 여기서 시간을 낭비할 순 없잖니.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1411]
![screenshot_2016-07-15-10-33-39](https://cloud.githubusercontent.com/assets/19295794/17236234/9a5fe560-5582-11e6-8bc8-53f6d730b82e.png)

표현하기는 좀 어려운데... 문장 전체가 조금 어색하다고 생각합니다.

다른 분들은 어떻게 생각하시나요?

**Comment by Porowl** [comment]
그렇군요. 도와줘서 고맙습니다
쉬플리 씨.가자, 루크. 여기서 시간을
낭비할 순 없잖니. 

라고 1차 수정
