### ISSUE TITLE
붙잡으려 해서 미안하지만 아주 맛 좋은 요크셔 푸딩을 놓치는구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1414]
![screenshot_2016-07-15-14-50-50](https://cloud.githubusercontent.com/assets/19295794/17236302/15d2b182-5583-11e6-811b-6e9553630a17.png)

1행의 '아주 맛 좋은' 은 다음 행으로 넘기는 것이 어떨까요?

그리고 요크셔 푸딩은 우리나라 사람들이  잘 모르는 음식이니

잘 알 만한 다른 음식으로 표현을 대체하는 것은 어떻게 생각하시나요?

원문과 달라지기는 하겠지만요.

**Comment by Porowl** [comment]
붙잡으려 해서 미안하지만 
아주 맛 좋은 요크셔 푸딩이
널 기다리고 있는데 말야.

으로 1차 수정해두었습니다.

**Comment by jungin019** [comment]
그냥 푸딩이라고만 해도 되지 않을까요 그럼

**Comment by Porowl** [comment]
계란 푸딩은 어떨까요

**Comment by STRIKE-F** [comment]
꼭 가야 한다면 어쩔 수 없지만
정말 맛 좋은 푸딩을 준비해 뒀는데 말야.

이건 어떠련지요
