### ISSUE TITLE
딩동댕! 그래, 뭔가 의심스러워 보이는 곳이 있다면, 그냥 몇 번 터치 해보기만 하면 돼.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1418]
![screenshot_2016-07-15-14-57-08](https://cloud.githubusercontent.com/assets/19295794/17236432/e7b05df8-5583-11e6-89c8-c071ff35347a.png)

딩동댕! 
그래, 뭔가 의심스러워 보이는 곳이 있다면,
그냥 몇 번 터치해 보기만 하면 돼.

로 내용과 개행 수정하는 것은 어떨까요?

**Comment by Porowl** [comment]
딩동댕! 맞아, 어딘가가 조금 
의심스러워 보이는 곳이 있다면, 
그냥 몇 번 터치 해보기만 하면 돼.
