### ISSUE TITLE
이 부분은 의도적으로 숨긴건가요?

### ISSUE THREAD

**Issue by Glacie** [elfinlazz/lt3translation#144]
![screenshot_2016-05-10-17-07-28](https://cloud.githubusercontent.com/assets/19269458/15139575/d09b4588-16d1-11e6-849a-37f608303b8e.png)

제목 그대로입니다.

대사를 숨긴건지 아니면 실수인지 여쭙고 싶습니다.

**Comment by jungin019** [comment]
오타네요. 수정했습니다.
