### ISSUE TITLE
달달한 간식거리들은 언제나 우리 마음을 편안하게 해 주지. 정말 신기하다니까?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1443]
![screenshot_2016-07-15-15-06-02](https://cloud.githubusercontent.com/assets/19295794/17237061/073c4600-5589-11e6-9642-7a6e7ddeaab8.png)

달달한 간식거리들은
언제나 우릴 마음을 편안하게 해 주지.
정말 신기하다니까?

로 개행 수정하는 것은 어떨까요?

그리고 첫 번째 문장은 번역체스러운 느낌이 있다고 생각하는데 다른 분들은 어떻게 생각하시나요?

**Comment by Porowl** [comment]
달달한 간식거리는 언제 먹어도 기분이
좋아진단 말야. 정말 신기하지 않아?
