### ISSUE TITLE
수상해 보이는 건 아무 것이나 터치해봐. 좋은 걸 발견할 수 있을지도 몰라!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1445]
![screenshot_2016-07-15-15-06-30](https://cloud.githubusercontent.com/assets/19295794/17237105/670fae32-5589-11e6-9e92-da66886beb47.png)

수상해 보이는 건 아무 것이나 터치해봐.
좋은 걸 발견할 수 있을지도 몰라!

로 개행 수정하는 것은 어떨까요?

그리고 '보이는 건 아무 것이나' 를 풀어서 쓰면

'보이는 것은 아무 것이나' 가 되는데 '~것' 이라는 표현이 반복되어 이상하다고 생각합니다.

수정할 수는 없을까요?

**Comment by Porowl** [comment]
수상해 보이는 건 아무거나 터치해봐. 
좋은 걸 발견할 수 있을지도 몰라!
