### ISSUE TITLE
아마 수상님은 10년 전에 납치된 게 아닌 모양이구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1462]
![screenshot_2016-07-15-15-17-54](https://cloud.githubusercontent.com/assets/19295794/17237830/f1150710-5590-11e6-8aa0-14f2a6470669.png)

뒤에 '아닌 모양이구나.' 가 있으므로 앞부분의 '아마' 는 생략하고

수상님은 10년 전에 
납치된 게 아닌 모양이구나.

로 내용과 개행 수정하는 것은 어떨까요?

**Comment by Porowl** [comment]
<T><A3/1>그렇다면 수상님은 10년 전에
납치된 게 아닌 모양이로군.
