### ISSUE TITLE
혹시 저 동상은 옛 영웅을 기념하는 상인 걸까요? 제가 먼저 가서 몰게요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1466]
![screenshot_2016-07-15-15-18-29](https://cloud.githubusercontent.com/assets/19295794/17237932/2bad5cf0-5592-11e6-9183-8b741bf927ed.png)

혹시 저 동상은 옛 영웅을
기념하는 걸까요?
제가 먼저 가서 볼게요.

로 내용과 개행 수정하는 것은 어떨까요?

**Comment by STRIKE-F** [comment]
저건 옛 영웅을 기리는 동상일까요?
제가 가서 보고 올게요! 

로 수정하겠습니다.
