### ISSUE TITLE
만약 교수였다면 엄청난 우연이었겠네요! 좀 더 읽어 볼게요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1469]
![screenshot_2016-07-15-15-19-01](https://cloud.githubusercontent.com/assets/19295794/17237972/9de727d8-5592-11e6-979c-509f7b960a77.png)

공간이 된다면 2행의 '우연이었겠네요!' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by Porowl** [comment]
이게 애매하긴 한데,,, 패치때 어떨지 봅시다.
