### ISSUE TITLE
어떤 사람들은 평생 동안 그런 경험을 못 하기도 하니깐.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1471]
![screenshot_2016-07-15-15-19-33](https://cloud.githubusercontent.com/assets/19295794/17238001/e61c12ca-5592-11e6-90ed-eaa4a8f969c1.png)

어떤 사람들은
평생 그런 경험을 못 하기도 하니까.

로 내용과 개행 수정하는 것은 어떨까요?

**Comment by Porowl** [comment]
어떤 사람들은 평생 그런 경험을 
못 하기도 하니까.
