### ISSUE TITLE
음, 그건 내가 아무 할 일이 없기 때문이야. 하지만 내 삶의 목표를 잃어버렸기 때문이기도 하지. 이젠 틀렸어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1477]
![screenshot_2016-07-15-16-36-46](https://cloud.githubusercontent.com/assets/19295794/17238139/189c6c80-5594-11e6-8175-d3d183830f4a.png)

글씨가 연필 표시에 가리는데 문장을 조금 줄여 볼 수는 없을까요?

**Comment by Porowl** [comment]
수정되어 있습니다.
