### ISSUE TITLE
[건의사항]이건 기계 쪽으로 가는 입구인 것 같구나.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#149]
![image](https://cloud.githubusercontent.com/assets/19265176/15140497/51c61f58-16d6-11e6-8dde-15ef426aac9f.png)

이건 기계 쪽으로 가는 입구인 것 같구나. 이 문장을
이건 저 기계의 입구인 것 같구나. 로 바꾸는 편이 더 낫지 않을까요?

**Comment by jungin019** [comment]
기계의 입구가 더 좋은 표현일 것 같네요
