### ISSUE TITLE
또 보는구려, 똑똑이들! 너희들의 힘으로 빛나는 멋진 힌트 코인을 찾는 데에는 성공했니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1499]
![screenshot_2016-07-18-14-12-54](https://cloud.githubusercontent.com/assets/19295794/17242283/5d0e42fe-55b1-11e6-8d59-5a943e23f0fc.png)

'궁금이들' 이슈는 아직 처리가 되지 않은 것으로 알고 있습니다. 그럼 그 부분은 두고,

두 번째 문장에서 번역체스러운 느낌이 난다고 생각합니다. 수정할 수는 없을까요?

**Comment by jungin019** [comment]
이거 그냥 닫으신 건가요?
