### ISSUE TITLE
[건의사항]사람 몇 명이 창문에서 지켜보고 있어요

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#150]
![image](https://cloud.githubusercontent.com/assets/19265176/15140545/922dc992-16d6-11e6-8e4d-3d8e534563ce.png)
사람 몇 명이 창문에서 지켜보고 있어요. 이 문장을
몇 몇 사람들이 창문에서 지켜보고 있어요. 이렇게 바꾸는 것이 더 자연스럽지 않을까 생각해 봅니다.

**Comment by jungin019** [comment]
몇몇이 좀 더 좋을 것 같네요

**Comment by bombomS2** [comment]
저도 몇몇 사람들이 창문에서 지켜보고 있어요. 쪽이 더 좋을 것 같습니다.
