### ISSUE TITLE
그런 의미에서, 그래도 우리는 꽤 운이 좋았던 것 같아요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1509]
![screenshot_2016-07-18-14-17-46](https://cloud.githubusercontent.com/assets/19295794/17242921/bef70606-55b4-11e6-80f6-f0ae83c917ee.png)

앞의 '그런 의미에서,' 는 생략하고,

그래도 우리는 꽤 운이 좋았던 것 같아요.

로 수정하면 어떨까요?

**Comment by Porowl** [comment]
In that sense, it seems we got
pretty lucky, huh?

이라... 아얘 그래도를 빼야할지도

**Comment by jungin019** [comment]
저는 딱히 문장이 이상하진 않은 것 같은데...
