### ISSUE TITLE
[오역]수수께끼 1번 인트로

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#151]
![image](https://cloud.githubusercontent.com/assets/19265176/15140611/ee109b0e-16d6-11e6-95ed-3c485a15cab3.png)

터치펜을 이용해 경호원을 탁자의 아래쪽에 끌어 넣습니다.
원문이
Use the stylus to drag the guard in the bottom corner of the Touch Screen to a table.
입니다. 

제 생각엔 번역이 조금 이상한 것 같습니다. 일단 제가 생각한 번역은 다음과 같습니다.

->터치펜을 이용하여 터치스크린 아래쪽 모퉁이에 있는 경호원을 탁자에 끌어다 놓습니다.
->터치펜을 이용하여 터치스크린 왼쪽 아래에 있는 경호원을 탁자에 끌어다 놓습니다.

둘 중 하나를 사용하는 것이 좋을 것 같습니다.

**Comment by jungin019** [comment]
'터치펜을 이용하여 터치스크린 왼쪽 아래에 있는 경호원을 탁자에 끌어다 놓습니다.'
이게 좀 더 좋을 것 같네요.
@itstake

**Comment by itstake** [comment]
터치펜을 이용하여
스크린 아래 모퉁이에 있는
경호원을 탁자에 끌어
넣습니다.

로 수정
