### ISSUE TITLE
제 눈은 절대로 못 속인다구요. 그 누나가 선생님을 보는 눈빛 보셨어요? 완전 불여우라구요! ...그게 뭔진 모르겠지만.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1517]
![screenshot_2016-07-18-14-19-38](https://cloud.githubusercontent.com/assets/19295794/17243385/7f6e40a0-55b7-11e6-8adb-efcc2929373c.png)

제 눈은 절대로 못 속인다구요.
그 누나 눈빛 보셨어요? 완전 불여우라구요!
... 그게 뭔지는 모르겠지만.

으로 개행과 내용 수정하는 것은 어떨까요?

**Comment by Porowl** [comment]
제 눈은 절대로 못 속여요. 그 누나가 
선생님을 보는 눈빛 보셨어요? 완전
불여우라구요! ...그게 뭔진 모르겠지만.

어떻게 고쳐도 공간이 좁고, 별 수 없이 이렇게 수정했습니다.
