### ISSUE TITLE
[건의사항][스포일러성] 스턴건: 그러고 보니 수상님께서는 이전부터 과학보다는 다른 것들을 훨씬 더 좋아하셨죠.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#152]
![image](https://cloud.githubusercontent.com/assets/19265176/15140767/9ea135be-16d7-11e6-898b-125db16f860e.png)
위의 문장의 원문은 다음과 같습니다. 
I realize it’s been some time since you traded in the hard sciences for the softer variety.
직역하자면 
저는 당신이 여러 가지를 위하여 자연과학을 거래에 이용해버린지 시간이 좀 지난 것을 기억해냈습니다.
가 되겠네요.
이 부분은 빌 호크가 드미트리(였나요?)와 옛 과학자 동료고 앞으로 밝혀질 여러 일들을 저지른 것에 대해서 빈정대면서 도발하는 부분이라고 저는 받아들였습니다. 그래서 빌 호크는 바로 다음에 자신이 자원하겠다고 객기를 부리는 것이죠.
사실 다시 해 보면서 저 부분 보고 좀 놀랐네요.

그런데 현 번역은 그 맛이 잘 안 사는 것 같아서  일단 제가 해 본 번역은 이렇습니다. 

->그러고 보니 수상님께선 다른 여러 가지를 위해 자연과학을 버리신 지 좀 되셨군요.

해 놓고 보니 한 나라의 수상한테 너무 도발적인 것 같기는 하지만 일단 제 생각은 이렇습니다.

**Comment by jungin019** [comment]
이 부분은 의역입니다. 처음에 말씀하신 것과 비슷하게 번역을 했으나 팀 내 의견으로(당시에도 '너무 도발적이지 않는가'가 이유였습니다) 좀 더 부드럽게 순화했습니다. 일단 건의가 들어왔으니 토의 태그를 달아놓겠습니다.

**Comment by STRIKE-F** [comment]
돈에 눈이 멀어 동료들의 목숨과 과학의 진보를 팔아먹은 거로 본다면 '과학보다는 돈을 훨씬 더 좋아하셨죠' 이런 뉘앙스로도 볼 수 있을 것 같습니다.

**Comment by Y00N** [comment]
'수상님께선 과학보단 다른 데 관심이 많으셨죠.' 어떻습니까?

**Comment by itstake** [comment]
논의 결과
> 수상께서 언제는 과학 따위에 신경이나 쓰셨나요. 안 그렇습니까?

로 최종 결정되었습니다.
