### ISSUE TITLE
별 말씀을요. 저도 꽤나 즐거웠습니다..

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1521]
![screenshot_2016-07-18-14-21-36](https://cloud.githubusercontent.com/assets/19295794/17243509/33204ef4-55b8-11e6-861e-28eba157f326.png)

말줄임표는 마침표 세 개를 사용하는 것이 좋겠습니다.

**Comment by Porowl** [comment]
.이 하나 잘못 찍혀 있었습니다.
