### ISSUE TITLE
가까이 좀 와 보게나. 이게... 음, 다른 사람 귀에는 들어가면 안 된다네.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1523]
![screenshot_2016-07-18-14-22-09](https://cloud.githubusercontent.com/assets/19295794/17243555/6f75f282-55b8-11e6-8ec2-91ac3b2ff546.png)

가까이 좀 와 보게나. 음...
이게 다른 사람 귀에는 들어가면 안 된다네.

로 내용과 개행 수정하는 것은 어떨까요?

**Comment by Porowl** [comment]
가까이 좀 와 보게나. 음... 이건
다른 사람 귀에는 들어가면 안 된다네.

으로 타협보겠습니다.
