### ISSUE TITLE
이 수수께끼를 푸는 데에 자네의 도움을 받았단 건 자네와 나와 이 방 사이의 비밀로 하는 게 어떤가?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1526]
![screenshot_2016-07-18-14-23-22](https://cloud.githubusercontent.com/assets/19295794/17243677/ffee075a-55b8-11e6-8eee-b7fedc19b4e5.png)

문장 자체가 조금 어색하다고 생각하는데 수정할 수는 없을까요?

**Comment by Porowl** [comment]
원문은 Let's keep the fact that you helped
me with this puzzle between you,
me, and the wall, shall we? 입니다.
