### ISSUE TITLE
내 동료는 오늘 쉬는 날인가 보구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1527]
![screenshot_2016-07-18-14-23-58](https://cloud.githubusercontent.com/assets/19295794/17243717/30ebcbf8-55b9-11e6-8c67-12057bd0f04f.png)

'~는' 이라는 표현이 반복되는데 수정할 수는 없을까요?

**Comment by Porowl** [comment]
내 동료는 오늘 하루 
쉬시는가 보구나.
