### ISSUE TITLE
[건의사항] 타임머신 폭발하는 영상 중_ 사회자: 이거 정말 큰일이군요! 실험은 실패한 걸까요?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#153]
![image](https://cloud.githubusercontent.com/assets/19265176/15140949/87d85a32-16d8-11e6-8f68-03b5f5b92073.png)
![image](https://cloud.githubusercontent.com/assets/19265176/15140953/8d9607d0-16d8-11e6-9e09-a21221319f58.png)

저 부분 귀에 들리는 말은 이렇습니다.
Ladies and gentleman please remain calm and refrain from panicking.
일어판에서는 어떻게 되어 있는지 모르겠지만, 동영상에서 보면 타임머신이 터지면서 사람들이 패닉에 휩싸여 있고 아수라장이 연출되고 있습니다. 그런데 사회자의 저 말은 이 상황에서 불난 집에 부채질하는 꼴로 보입니다. 북미판 원문과도 전혀 맞지 않고요.

제가 해 본 번역은 다음과 같습니다.

신사 숙녀 여러분 
부디 진정하시고 침착해주시길 바랍니다.

**Comment by jungin019** [comment]
네 영어 원문은 저게 맞습니다. 제가 기억하기로도 저 문장이었던 것 같네요. 다만 음성이 나오는 부분은 더빙팀에서 임의로 수정하기도 하기 때문에 아마 이렇게 되지 않았을까 싶습니다. 아무래도 음성이 나오는 부분은 우리나라 정서와 좀 더 맞거나 문장 길이가 비슷한 일어판을 참고하기도 해서요.

**Comment by jungin019** [comment]
@Latteria

**Comment by Latteria** [comment]
大変なことになりました
実験は 失敗なのでしょか 가 일본어 원문입니다.

사실 Ladies and gentleman please remain calm and refrain from panicking. 을 신사 숙녀 여러분, 당황하지 마시고 제발 진정해주십시오! 라고 시도했다가 더빙 담당자의 요구로 일본어 쪽 원문을 택하게 되었습니다
