### ISSUE TITLE
선생님, 그러시면 안 되죠! 한 번 하신 말을 스스로 취소하는 것은 전혀 신사답지 않다고요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1530]
![screenshot_2016-07-18-14-25-12](https://cloud.githubusercontent.com/assets/19295794/17243854/bc14923c-55b9-11e6-9102-909825e49d1b.png)

선생님, 그러시면 안 되죠!
한 번 하신 말씀을 바꾸시는 것은
전혀 신사답지 않다고요.

로 내용과 개행 수정하면 어떨까요?

**Comment by Porowl** [comment]
선생님, 그러시면 안 되죠!
그렇게 말을 바꾸시는 것은 
전혀 선생님답지도 않고요.

로 수정되어 있습니다.
