### ISSUE TITLE
조사 메모 - 스코틀랜드 야드로

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1534]
![screenshot_2016-07-18-14-26-52](https://cloud.githubusercontent.com/assets/19295794/17244040/b7008084-55ba-11e6-9c77-73d4598ccc92.png)

플로라를 두고 가는 것은 미안하지만,
나는 플로라가 이런 위험한 상황에
연루되도록 할 수 없었다.
플로라도 이해해줄 것이라고 믿는다.

우리의 다음 목적지는
체르미 경감님이 계신
스코틀랜드 야드이다.
타임머신 발표회 때 무슨 일이
일어났는지 그의 의견을 듣고 싶다.

로 개행과 내용 수정하면 어떨까 하는데 공간이 되나요?

**Comment by Porowl** [comment]
플로라를 두고 가는 것은 미안하지만
플로라가 이런 위험한 상황에
연루되도록 할 수 없었다.
플로라도 이해해줄 것이라고 믿는다.

우리의 다음 목적지는,
다행이라면 체르미 경감님이 계실
스코틀랜드 야드이다. 
타임머신 발표회 때 사건에 대한
그의 의견을 듣고 싶다.

라고 1차 수정해두었습니다.
