### ISSUE TITLE
수수께끼를 풀고 싶으신거라면 처음부터 말씀하시지 그러셨어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1535]
![screenshot_2016-07-18-14-28-01](https://cloud.githubusercontent.com/assets/19295794/17244077/f82ce67e-55ba-11e6-88da-6a3659b78af7.png)

1행의 '처음부터' 는 다음 행으로 넘기는 게 어떨까요?

그리고 '싶으신거라면' 은 '싶으신 거라면' 으로 띄워도 좋겠습니다.

**Comment by Porowl** [comment]
수수께끼를 풀고 싶으신 거라면
처음부터 그렇게 말씀하시지 그러셨어요.
