### ISSUE TITLE
선생님 제자한테 나쁜 말을 하면 안되는건 알지만, 더 이상은 못 참아요. 저 누나는 좋은 학생이 전혀 아니라구요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1538]
![screenshot_2016-07-18-14-28-50](https://cloud.githubusercontent.com/assets/19295794/17244165/755099b6-55bb-11e6-9783-d59b6bbc11bd.png)

선생님 제자분께 나쁜 말을 하면
안 되는 건 알지만, 더 이상은 못 참아요.
저 누나는 절대 좋은 학생이 아니라구요!

로 내용과 개행 수정하면 어떨까요?

**Comment by Porowl** [comment]
선생님 제자한테 나쁜 말을 하면 
안 되는 건 알지만, 더는 못 참아요.
저 누나는 절대 좋은 학생이 아니라구요!
