### ISSUE TITLE
수 년 전에 일어난 일이란다, 루크. 네가 아주 작았을때 말이다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1539]
![screenshot_2016-07-18-14-29-21](https://cloud.githubusercontent.com/assets/19295794/17244204/a54a9e8c-55bb-11e6-802b-ed9813c24a2e.png)

수 년 전에 일어난 일이란다, 루크.
네가 아주 작았을 때 말이다.

로 내용 수정하면 어떨까요?

**Comment by Porowl** [comment]
중복 및 수정 완료됨
