### ISSUE TITLE
[건의사항] 레이튼: 편지에 들어 있던 지도를 볼 때 같구나

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#154]
![image](https://cloud.githubusercontent.com/assets/19265176/15141024/12da054a-16d9-11e6-8075-46f91fe05910.png)
물론 제 어휘력이 부족한 것일수도 있겠습니다만은, 저는 저 문장을 봤을 때 살짝 당황했습니다.
원문이 이렇더군요.
This seems an ideal time to consult the map that accompanied the letter.
저는 위의 번역을 조금 다듬을 필요가 있을 것 같다고 생각했습니다.

일단 제가 몇 가지 생각해본 것은 다음과 같습니다.
->지금이 편지에 동봉된 지도를 볼 때로 보이는구나.
->지금이 바로 편지에 동봉된 지도를 찾아 볼 때로 보이는구나.

**Comment by jungin019** [comment]
말씀하신 걸 보니 중의적인 의미가 될 수도 있겠네요. 
'편지에 들어 있던 지도를 보는 게 좋겠구나.' 정도로 바꾸면 어떨까 합니다.

**Comment by kaleidoscope531** [comment]
저도 그 정도로 바꾸면 좋을 것 같습니다.
