### ISSUE TITLE
죄송하지만, 체르미 경감님은 지금 매우 바쁘셔서요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1544]
![screenshot_2016-07-18-14-30-54](https://cloud.githubusercontent.com/assets/19295794/17244376/777c743e-55bc-11e6-8f0b-5b035e5fd06a.png)

1행의 '체르미 경감님은 지금 매우' 는 다음 행으로 넘기는 게 어떨까요?

그리고 '매우' 는 생략해도 좋을 것 같은데 다른 분들은 어떻게 생각하시나요?

**Comment by Porowl** [comment]
Unfortunately, the inspector is
terribly busy right now.

원문이 이렇기에..
개행은 

죄송하지만, 체르미 경감님께선
지금 매우 바쁘셔서요.

으로 두었습니다.
