### ISSUE TITLE
경감님 사무실은 2층에 있습니다. 저 계단을 올라가시면 됩니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1546]
![screenshot_2016-07-18-14-32-18](https://cloud.githubusercontent.com/assets/19295794/17244420/b6c8a6e4-55bc-11e6-89f5-94c28dd8ec38.png)

1행의 '저' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by Porowl** [comment]
수정됨
