### ISSUE TITLE
폭발이 있었을 당시, 자네도 현장에 있었다는 것을 확인했다네.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1548]
![screenshot_2016-07-18-16-32-14](https://cloud.githubusercontent.com/assets/19295794/17244483/105343a4-55bd-11e6-9aa9-b59731e76eb0.png)

1행의 '자네도 현장에' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by Porowl** [comment]
기각. 좁습니다. 유지할게요.
