### ISSUE TITLE
[건의사항] 레이튼 : 자, 루크. 혼자서 가게의 위치를 찾아보지 않겠니?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#155]
![image](https://cloud.githubusercontent.com/assets/19265176/15141113/82d90616-16d9-11e6-86d6-a0cd883b9957.png)

 자, 루크. 혼자서 가게의 위치를 찾아보지 않겠니?
 이 문장에서 yourself를 '혼자서' 대신에 '직접'으로 바꾸는 것이 더 자연스럽지 않을까 생각합니다.
예를 들자면
자, 루크. 어디 한 번 직접 가게의 위치를 찾아보지 않겠니?
이런 식으로요.

**Comment by jungin019** [comment]
원문을 보면 
See if you can't find
the shop's location 'by yourself.'로 
by yourself는 alone의 의미가 더 맞긴 합니다. 
토의를 열어놓을게요

**Comment by Y00N** [comment]
스스로는 어떨까요?

**Comment by jungin019** [comment]
스스로도 괜찮을 것 같네요

**Comment by kaleidoscope531** [comment]
스스로 좋아보입니다.

**Comment by bombomS2** [comment]
자, 루크. 스스로 가게 위치를 찾아보지 않겠니?
딱히 없어도 되는 '의'를 빼는 것도 자연스러울 것 같습니다.

**Comment by jungin019** [comment]
'자, 루크. 스스로 가게 위치를 찾아보지 않겠니?'로 수정했습니다.
