### ISSUE TITLE
기억하시는 것으로 알겠습니다. 그 사건에 대한 모든 자료를 봐야겠습니다. 하나도 빼놓지 않고요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1551]
![screenshot_2016-07-18-16-34-15](https://cloud.githubusercontent.com/assets/19295794/17244591/a3a94bee-55bd-11e6-9878-0d66fa11c824.png)

'~습니다.' 라는 표현이 반복되는데 수정할 수 없을까요?

**Comment by Porowl** [comment]
기억하시는 것으로 알겠습니다.
그 사건에 대한 모든 자료를 봐야합니다. 
하나도 빼놓지 않고요.
