### ISSUE TITLE
뭔가가 있는 것이군, 레이튼. 무얼 알고있는 겐가?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1552]
![screenshot_2016-07-18-16-34-19](https://cloud.githubusercontent.com/assets/19295794/17244619/bc671bb6-55bd-11e6-94df-2cf42999f694.png)

뭔가가 있는 거군, 레이튼.
무얼 알고 있는 겐가?

로 내용과 개행 수정하는 것은 어떨까요?

**Comment by Porowl** [comment]
뭔가가 있군, 레이튼. 
무얼 알고있는 겐가?

**Comment by Y00N** [comment]
@Porowl  -고 뒤에 있다가 나올 땐 띄어 써야 합니다.

**Comment by Porowl** [comment]
고쳤습니다
