### ISSUE TITLE
흠. 자네를 돕고 싶군. 진심으로. 하지만 그 문서들은 일급 기밀이라 정보 열람 허가가 있어야 해.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1553]
![screenshot_2016-07-18-16-34-33](https://cloud.githubusercontent.com/assets/19295794/17244651/de5fa5a8-55bd-11e6-8385-c18ef21fded4.png)

흠, 진심으로 자네를 돕고 싶군.
하지만 그 문서들은 일급 기밀이라
정보 열람 허가가 있어야 해.

로 내용과 개행 수정하는 것은 어떨까요?

**Comment by Porowl** [comment]
흠. 진심으로 자네를 돕고 싶다만,
그 문서들은 일급 기밀이라
정보 열람 허가가 있어야 해.
