### ISSUE TITLE
어... 기다리게, 레이튼. 내가... 사건 파일을 보게 해줄 수 있을지도 모르겠네.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1554]
![screenshot_2016-07-18-16-35-25](https://cloud.githubusercontent.com/assets/19295794/17244688/0b785382-55be-11e6-992f-455906f00f28.png)

2행의 '보게 해줄 수 있을지도' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by Porowl** [comment]
어... 기다리게, 레이튼. 내가... 사건 
파일을 보게 해줄 수 있을지도 모르겠네.

**Comment by Y00N** [comment]
@Porowl <내가... 사건 파일을 구할 수 있을지도 모르겠네.> 라고 쓰면 좀 더 깔끔하게 문제가 해결되지 않을까요?
