### ISSUE TITLE
물론입니다. 자료를 보고 제 가설이 맞다고 확신이 서면 모든 것을 말하겠습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1555]
![screenshot_2016-07-18-16-35-40](https://cloud.githubusercontent.com/assets/19295794/17244710/2bd3a3b6-55be-11e6-92d7-82933603a2de.png)

물론입니다. 자료를 보고
제 가설이 맞다고 확신이 서면
모든 것을 말하겠습니다.

로 개행 수정하는 것은 어떨까요?

**Comment by Porowl** [comment]
물론입니다. 자료를 보고
제 가설이 맞다는 확신이 서면 
모든 것을 말씀드리겠습니다.
