### ISSUE TITLE
폭발과 관련된 자료들을 모두 모아놨습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1557]
![screenshot_2016-07-18-16-36-24](https://cloud.githubusercontent.com/assets/19295794/17244767/703e2daa-55be-11e6-8b61-cd12e9918366.png)

1행의 '모두' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by Porowl** [comment]
폭발과 관련된 자료들은
모두 모아놨습니다.
