### ISSUE TITLE
윽! 이 문서들 전부 곰팡이에 먼지 투성이에요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1559]
![screenshot_2016-07-18-16-36-34](https://cloud.githubusercontent.com/assets/19295794/17244792/9ced34e0-55be-11e6-9593-6d6ed4a591a8.png)

1행의 '이 문서들 전부 곰팡이에 먼지' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by Porowl** [comment]
기각... 너무 어색해 보일듯 합니다.

대신 

윽! 이 문서들 전부 곰팡이에
먼지 투성이에요!

으로 수정
