### ISSUE TITLE
[건의사항] 수수께끼 2번 정답 화면

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#156]
![image](https://cloud.githubusercontent.com/assets/19265176/15141202/e3c7fc66-16d9-11e6-8307-098178d756b6.png)

시각은 우리에게 다음 골목에 어떤 방향으로 가야 할지 알려주는 단서였다.

이 문장이 조금 어색한 것 같아서 사족일 수 있지만 이렇게 건의사항을 넣어 봅니다.
일단 제가 생각해 본 것은 다음과 같습니다.

옆에 적혀있던 시각은 우리가 마주치는 골목마다 어떤 방향으로 가야 할지 알려주는 단서였다.

물론 더 좋은 번역이 있을테니 이 글을 읽어보시는 분들께서도 부디 좋은 의견 주시면 감사하겠습니다.

**Comment by jungin019** [comment]
개인적으로는 
'옆에 적혀있던 시각은 교차로에서 어떤 방향으로 가야 할지 알려주는 단서였다' 
정도가 좋을 것 같네요.

**Comment by kaleidoscope531** [comment]
저도 jungin019님의 의견에 동의합니다.

**Comment by Y00N** [comment]
저는 2번 수수께끼는 앞에서는 '시각들'이라고 하고 뒤에서는 '시각'이라고 하는 점도 문제라고 생각합니다.
좀 더 적극적으로 이야기하자면 이 게임의 번역엔 '~들'이 너무 많다고 생각해요.

**Comment by jungin019** [comment]
1 그 부분은 고쳤습니다

**Comment by yhwon90** [comment]
저는 그 다음 문장도 마음에 걸렸는데 새로 글을 쓰는 것보다는 이 스레드에 이어서 쓰겠습니다.
매 교차로마다 아날로그 시계의 시침이 가리키는 방향을 순서대로 따라가면 된다.
가 더 이해하기 쉬운 설명이 될 것 같아서요.

**Comment by jungin019** [comment]
1 현재는 '매 교차로에서 각 시각마다 아날로그 시계의 
시침이 가리키는 곳을 따라가면 된다.'로 되어있는데 어떤 게 나을지 얘기해주세요

**Comment by kaleidoscope531** [comment]
'매 교차로에서 오른쪽에 적힌 시각마다 아날로그 시계의 시침이 가리키는 방향을 순서대로 따라가면 된다.'
 두 개를 섞어봤습니다.

**Comment by yhwon90** [comment]
두 개를 섞은 문장에서 '오른쪽에 적힌 시각마다'나 '순서대로' 중 하나를 빼면 더 자연스러울 것 같습니다
개인적으로는 '오른쪽에 적힌 시각마다' 문구 자체가 조금 어색해보입니다만 다른 분들 생각은 어떠신지 들어보고 싶네요.

**Comment by Porowl** [comment]
정답!

H가 시계 가게이다.

오른쪽에 표시한 시각은 교차로에서 
어디로 향해야 할지 알려주는 단서였다

매 교차로마다 아날로그 시계의 시침이 
가리키는 방향을 순서대로 따라가면 된다.
