### ISSUE TITLE
루크, 이리 와 보거라. 내가 원하던 걸 찾은 것 같구나!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1562]
![screenshot_2016-07-18-16-50-35](https://cloud.githubusercontent.com/assets/19295794/17244923/20069222-55bf-11e6-86e7-b5d44a43abce.png)

1행의 '내가 원하던 걸' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by Porowl** [comment]
루크, 이리 와 보거라. 드디어 필요한 
정보를 찾은 것 같구나!
