### ISSUE TITLE
[건의사항] LAYTON'S LESSONS LESSON1 : MOVING

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#157]
![image](https://cloud.githubusercontent.com/assets/19265176/15141308/675e0606-16da-11e6-8926-672635afc511.png)

저 위에 LAYTON'S LESSONS LESSON1 : MOVING 이 부분의 번역이 안 되어 있습니다. 
뭐 저 정도는 게임하는데 아무 지장도 없고 멋스러움을 위해 놔둔 것으로 해도 상관 없어 보입니다.
다만 일단 언급은 하는 편이 좋을 것 같아 이렇게 올립니다.

**Comment by itstake** [comment]
닌텐도 코리아의 정식 발매판에 따라 번역을 하지 않았습니다.
