### ISSUE TITLE
어쩌면. 경감님께 이 사실을 알리러 가자.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1573]
![screenshot_2016-07-18-16-55-22](https://cloud.githubusercontent.com/assets/19295794/17245359/22993ba0-55c1-11e6-9722-abceecaa32df.png)

2행의 '가자.' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by Porowl** [comment]
비좁아요
