### ISSUE TITLE
그렇군요. 그리고 폭발 사건의 용의자였던 과학자들의 이름도 기억이 나십니까?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1575]
![screenshot_2016-07-18-16-55-57](https://cloud.githubusercontent.com/assets/19295794/17245445/74acd906-55c1-11e6-9c9a-cb32bd7a02a0.png)

'~의' 라는 표현이 반복되는데 수정할 수는 없을까요?

**Comment by Porowl** [comment]
그렇군요. 그리고 폭발 사건 용의자였던
과학자들의 이름도 기억이 나십니까?

**Comment by Y00N** [comment]
@Porowl 띄어쓰기 두 번 된 것도 고치신거죠?

**Comment by Porowl** [comment]
고쳤습니다.
