### ISSUE TITLE
...너무 오래 전 일이라 기억이 잘 안 나는군.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1576]
![screenshot_2016-07-18-16-56-05](https://cloud.githubusercontent.com/assets/19295794/17245466/8c28c018-55c1-11e6-8f25-d498490c5d1a.png)

... 너무 오래 전 일이라
기억이 잘 안 나는군.

으로 내용과 개행 수정하는 것은 어떨까요?

**Comment by Porowl** [comment]
...너무 오래 전 일이라 기억이 나지 
않는군
