### ISSUE TITLE
수상님은 스코틀랜드 야드의 관할 밖의 어딘가에 잡혀 있는 것 같습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1578]
![screenshot_2016-07-18-16-59-50](https://cloud.githubusercontent.com/assets/19295794/17245529/d6de7ecc-55c1-11e6-91ac-17f7fade24eb.png)

2행의 '밖의' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

그리고 '~의' 라는 표현이 반복되는데 수정할 수는 없을까요?

**Comment by Porowl** [comment]
수상님은 스코틀랜드 야드 관할 밖의 
어딘가에 잡혀 있는 것 같습니다.
