### ISSUE TITLE
[오역] 루크 : 그치만...차가 왜요?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#158]
![image](https://cloud.githubusercontent.com/assets/19265176/15141436/f78ac1ba-16da-11e6-9be9-ed969149c51f.png)
그치만... 차가 왜요?
이 부분은 오역으로 봐야 할 것 같습니다. 
->하지만...... 차는 어떡하죠?
로 바꾸는 편이 좋을 것 같습니다.

**Comment by jungin019** [comment]
상황상 '그런데... 차는 어떡하죠?'가 좋을 것 같네요.
저희가 번역할 때 텍스트만 보고 하다보니 이런 실수가 나옵니다.
