### ISSUE TITLE
이봐, 지금 여기가 농담 따먹기 하는 곳인 줄 아는 겐가!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1580]
![screenshot_2016-07-18-17-00-02](https://cloud.githubusercontent.com/assets/19295794/17245579/1898b27e-55c2-11e6-9904-dc76e51b45c3.png)

'곳인 줄 아는 겐가!' 를 풀어 쓰면 '곳인 줄 아는 것인가!' 가 되는데

조금 어색하다고 생각합니다. 다른 분들은 어떻게 생각하시나요?

**Comment by Porowl** [comment]
전 괜찮다고 보는데. 열어두겠습니다.

**Comment by Y00N** [comment]
지금 여기서 농담 따먹기나 하자는 건가? 뭐 이런 식으로 바꾸자는 말씀이신가요?
