### ISSUE TITLE
그래서... 아직도 어디 가는지 가르쳐 줄 마음은 없는 거니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1584]
![screenshot_2016-07-18-17-15-38](https://cloud.githubusercontent.com/assets/19295794/17245728/bda0da44-55c2-11e6-8a51-1a7ee74d6661.png)

1행의 '가르쳐 줄' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by Porowl** [comment]
가르치다...는 약간 과한 것 같고

그래서... 아직도 어디 가는지 알려줄
마음은 없는거니?

로 고쳤습니다. 우선. 
개행은 고려해보겠습니다.

**Comment by Porowl** [comment]
그래서... 어디 가는지 
알려줄 마음은 없는 거니?
