### ISSUE TITLE
좀 그ㄹ... 그렇지 않아요! 혼자만 아니라면 괜찮다고요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1585]
![screenshot_2016-07-18-17-15-54](https://cloud.githubusercontent.com/assets/19295794/17245738/d7d0f32c-55c2-11e6-9f99-3d550c8dad38.png)

좀 그러... 그렇지 않아요!
혼자만 아니라면 괜찮다고요.

로 내용과 개행 수정하는 것은 어떤가요?

**Comment by Y00N** [comment]
@Porowl  위 상황에선 줄임표보단 쉼표가 적절하다고 생각합니다.
