### ISSUE TITLE
정확히 무슨 폭발 사건을 조사하고 계신 것이셨나요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1587]
![screenshot_2016-07-12-07-03-29](https://cloud.githubusercontent.com/assets/19270364/17268700/57085ad6-566d-11e6-8cb6-1112b66e5444.png)

조사하고 계신 것이셨나요? 라는 부분이? 다소 깔끔하지 않단 생각이 듭니다.

정확히 무슨 폭발 사건을 조사하시던 건가요? 
정확히 무슨 폭발 사건을 조사하고 계셨나요?
정도는 어떨까요

**Comment by Porowl** [comment]
정확히 무슨 폭발 사건을 조사하고
계셨나요?

로 1차 수정해뒀습니다.

정확히 **어떤** 폭발 사건을 조사하고
계셨나요?

으로 고쳐써야할 것 같아 열어둡니다.

**Comment by Y00N** [comment]
어떤 좋습니다.
