### ISSUE TITLE
현장에서 발견된 것이라고는 타임머신을 이루고 있던 엄청난 양의 고철 뿐이었다네.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1589]
![screenshot_2016-07-12-07-58-45](https://cloud.githubusercontent.com/assets/19270364/17268958/fb7729e6-5675-11e6-96ad-8d42dd762cfb.png)

앞의 문장이 '시체나, 옷이나, 신발이나, 심지어 회중시계나 반지도 발견되지 않았다네.' 인데
굳이 다음 문장에서 '현장에서 발견된 건'이라고 발견하다를 받을 필요가 있나 라는 생각이 듭니다.
그리고 '-다네'를 반복하는 것도 어색하고요.
마지막으로 타임머신을 '이루고 있던' 이라는 표현이 다소 자연스럽지 않다는 생각이 드네요.

현장엔 타임머신이었던 엄청난 양의 고철 뿐이었지.
현장엔 엄청난 양의 고철이 되어버린 타임머신 뿐이었지.

정도로 다듬어보면 어떨까요?

**Comment by Porowl** [comment]
현장에 있는 거라고는 
타임머신을 이루고 있던 
엄청난 양의 고철 뿐이었어.
