### ISSUE TITLE
시체나, 옷이나, 신발이나, 심지어 회중시계나 반지도 발견되지 않았다네.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1590]
![screenshot_2016-07-12-07-57-34](https://cloud.githubusercontent.com/assets/19270364/17268985/c4654518-5676-11e6-9d2f-e80649317134.png)

이 문장에서 반복되어 사용하는 '-나'는 다음의 뜻으로 보입니다.
![default](https://cloud.githubusercontent.com/assets/19270364/17268990/00f27e74-5677-11e6-8532-16fb28f268b7.PNG)
그런데 이렇게 되면 <심지어>가 나타나서는 안됩니다. <심지어>는 "더욱 심하다 못하여 나중에는"이라는 뜻을 가지고 있기 때문이죠.
그리고 접속사 뒤의 쉼표가 불필요하게 많습니다.

시체도 옷도 신발도, 심지어 회중시계나 반지도 발견되지 않았다네.
로 고치는 게 더 자연스럽다고 생각합니다.

**Comment by Porowl** [comment]
시체, 옷, 신발, 심지어 회중시계나
반지조차도 발견되지 않았다네.
