### ISSUE TITLE
심심하면, 복도에서 바튼과 노는 것은 어떻겠니?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1591]
![screenshot_2016-07-12-08-02-12](https://cloud.githubusercontent.com/assets/19270364/17269045/bb117066-5678-11e6-9cfe-fe835bd701e7.png)

심심하면 뒤에 쉼표를 빼는 건 이미 #645 에서 해결이 되었군요.
하지만 첨언하자면 ~하는 것은 어떻겠니? 라는 말이 다소 부자연스럽다고 생각합니다.

심심하면 바튼과 복도에 나가 놀지 그러니?
심심하면 바튼과 복도에 나가 놀으렴.
심심하면 바튼과 복도에 나가 놀지 않겠니?

따위로 다듬어보는 게 어떨까요?

**Comment by Porowl** [comment]
심심하면 복도에 나가 바튼과 놀으렴.
