### ISSUE TITLE
뭐라고?! 나를 멍청이처럼 머리나 긁게 만들지 말게나 레이튼. 설명해보게

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1593]
![screenshot_2016-07-12-08-03-30](https://cloud.githubusercontent.com/assets/19270364/17269060/2f844806-5679-11e6-9bec-beac5f3cebfc.png)

그... 멍청이처럼 머리나 긁게 만든다는 표현이 굉장히 낯선데요...
좀 더 직관적인 표현으로 바꾸는 게 낫지 않을까 싶어요.

**뭐라고? 왜 진작 말하지 않았는가, 레이튼. 빨리 설명해보게!**
라고 생각해보긴 했는데 뭐 더 좋은 표현은 없을까요?

**Comment by Porowl** [comment]
한국 정서에 이게 더 맞아 보입니다
