### ISSUE TITLE
그 사건에 대한 모든 자료를 봐야겠습니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1595]
![screenshot_2016-07-12-08-05-46](https://cloud.githubusercontent.com/assets/19270364/17269114/115982cc-567b-11e6-82e0-0d50261bac7d.png)

뭐... 문장 자체는 딱히 건드리고 싶지는 않습니다만
뭔가 그 (엔터) 사건에 대한 모든 자료를 봐야겠습니다. 가 약간 보기에 어색하지 않나 싶어서요.
칸이 모자라서 그런거라면 어차피 앞에서 그 사건에 대한 이야기를 계속 하고 있었으니
**그것에 대한 모든 자료를 봐야겠습니다.** 로 문장을 대체해도 괜찮지 않을까 싶어요.

**Comment by Porowl** [comment]
현제 

기억하시는 것으로 알겠습니다.
그 사건에 대한 모든 자료를 봐야합니다. 
하나도 빼놓지 않고요.

으로 수정되어 있습니다.

**Comment by Y00N** [comment]
그것도 나쁘진 않네요
