### ISSUE TITLE
안됐지만 너무 기대를 많이 한 것 같군요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1596]
![screenshot_2016-07-12-08-10-29](https://cloud.githubusercontent.com/assets/19270364/17269157/6b962de8-567c-11e6-9dd3-98eab4368e58.png)

딱히 안됐지만을 써야 하나 의문입니다.

제가 지나치게 기대했나 보군요.
정도만 써도 충분하지 않을까요?

**Comment by Porowl** [comment]
아무래도 넘치는 기대였나 보군요.

**Comment by Y00N** [comment]
아무래도 제가 괜한 기대를 했군요. 는 어때요?
