### ISSUE TITLE
물론입니다. 자료를 보고 제 가설이 맞다고 확신이 서면 모든 것을 말하겠습니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1597]
![screenshot_2016-07-12-08-14-04](https://cloud.githubusercontent.com/assets/19270364/17269198/489168d4-567d-11e6-9cf4-ea771f4a3ffe.png)

"듣고 싶네." 의 대답으로 "물론입니다."는 다소 번역투 느낌이 물씬 나지 않나요?
"좋습니다.", "알겠습니다." 정도가 어떨까요?

**Comment by Porowl** [comment]
좋습니다
