### ISSUE TITLE
내 명령으로 왔다고 말하라고.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1598]
![screenshot_2016-07-12-08-15-13](https://cloud.githubusercontent.com/assets/19270364/17269218/ba420434-567d-11e6-8ac6-72f9de2357f6.png)

그냥 "**내 명령으로 왔다고 말하고.**" 라고 하는 편이 좀 더 자연스럽지 않을까요?

**Comment by Porowl** [comment]
수정됨
