### ISSUE TITLE
[건의사항] 조사 메모_ 타임 머신 발표회

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#160]
![image](https://cloud.githubusercontent.com/assets/19265176/15143079/dd4f8044-16e2-11e6-92d9-2c88999275ff.png)

나는 이 편지가 지난주에 일어난 타임머신 발표회에서의 사고와 연관이 되어있다고 생각한다.
이 문장을

나는 이 편지가 지난주에 타임머신 발표회에서 일어난 사고와 연관되어 있다고 생각한다.
이렇게 바꾸는 편이 더 자연스럽지 않을까 생각합니다. 
많은 의견 부탁드립니다. 

추가로 게임 내에서 타임 머신과 타임머신 두 가지로 혼용되고 있는데, 이를 통일하는 것이 어떨까 합니다.

**Comment by jungin019** [comment]
'나는 이 편지가 지난주에 타임머신 발표회에서 일어난 사고와 연관되어 있다고 생각한다.'로 고쳤습니다. 
타임머신으로 통일했는데 아무래도 고쳐지지 않은 부분이 있나보네요..
