### ISSUE TITLE
나만 쉽게 난처한 상황에 빠지는 건 아니었군.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1603]
![screenshot_2016-07-12-14-56-14](https://cloud.githubusercontent.com/assets/19270364/17269368/093718ce-5681-11e6-9ec0-04fbf3a060ef.png)

이런 상황이 닥치면 나만 난처한 게 아니었구나.
정도로 다듬는 게 좋지 않을까요?

**Comment by Porowl** [comment]
easily stumped 이니....

**Comment by jungin019** [comment]
현로님 의견도 괜찮을 것 같습니다.
