### ISSUE TITLE
선생님 없이는 나가지 않는 게 좋겠어.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1608]
뭐.. 스크린 샷이 없긴 한데 아마 저 문장이 맞을 겁니다.

선생님도 안 계시는데 함부로 나가지 말자.
라고 다듬는 게 어떨까요?

**Comment by Porowl** [comment]
아마 레이튼 교수가 문서 뒤적거릴동안 밖으로 나가려고 하면 나오는 문장 같은데...

흐음...

**Comment by jungin019** [comment]
영찬님이 말씀하신 상황이 맞을 거예요. 전 다듬는 것도 나쁘지 않네요
