### ISSUE TITLE
[건의사항] 레이튼: 아, 힌트코인에 대해서 말해주시려는 것이라면, 안 하셔도 됩니다.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#161]
![image](https://cloud.githubusercontent.com/assets/19265176/15143148/3707d4ba-16e3-11e6-8084-321b41445816.png)

사실 괜한 소리일 수도 있지만, 안 하셔도 됩니다라고 딱 잘라 말하는 것은 레이튼 교수의 신사적인 면모와 약간 거리가 있는 것 같습니다. 
안 하셔도 됩니다를 괜찮습니다로 바꾸면 어떨까 생각하는데요, 어떻게 생각하시나요?

**Comment by jungin019** [comment]
저는 그렇게 바꾸는 편이 좋을 것 같네요

**Comment by kaleidoscope531** [comment]
추가로 '것이라면'을 '거면'으로 바꾸는 것도 좋을 것 같습니다.

**Comment by bombomS2** [comment]
아, 힌트코인에 대해서 말씀하시려는 거라면 괜찮습니다.
는 어떨까 싶어요.

**Comment by jungin019** [comment]
'아, 힌트코인에 대해서 말씀하시려는 거라면 괜찮습니다.' 이게 좋을 것 같군요

**Comment by kaleidoscope531** [comment]
'아, 힌트코인에 대해서 말씀하시려는 거라면 괜찮습니다.'  좋습니다.
