### ISSUE TITLE
그러니까, 다른 나라에 납치되어 있다는 말인가?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1616]
![screenshot_2016-07-12-15-53-36](https://cloud.githubusercontent.com/assets/19270364/17269569/e8b2a7b6-5686-11e6-9d18-75a43260c55a.png)

**그러니까, 다른 나라에 납치되셨다는 말인가?**
로 다듬는 게 어떨까요?

**Comment by Porowl** [comment]
그러니까, 다른 나라로 납치되셨다는 말인가?
