### ISSUE TITLE
호크스 수상님은 미래로 납치된 것 같습니다. 

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1617]
![screenshot_2016-07-12-16-01-52](https://cloud.githubusercontent.com/assets/19270364/17269573/10201c70-5687-11e6-83d4-d4112fc59710.png)

~한 것 같습니다. 라는 표현을 다듬어 보는 게 어떨까요? 여기에 두둥 하는 효과음도 나오는 부분인데.
**호크스 수상님은 미래로 납치되었습니다.** 라거나 이게 좀 부담스럽다면
**호크스 수상님은 미래로 납치되셨을 겁니다.** 라는 쪽이 좋다고 생각합니다.

**Comment by Porowl** [comment]
호크스 수상님은 미래로 납치된 것으로 보입니다.
