### ISSUE TITLE
[오역] 루크 : 우와, 큰일 날 뻔 했네. 신발이 푹 빠질 뻔 했어요!

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#162]
![image](https://cloud.githubusercontent.com/assets/19265176/15143258/c2472e72-16e3-11e6-9d02-0b2285f08c20.png)

저 부분의 땅을 보면 벽돌로 되어 있는 것 같은데 물 좀 고였다고 푹 빠질 정도의 진창이 생기지는 않을 것 같습니다. 
그냥 신발이 흠뻑 젖을 뻔 했어요! 로 하는 편이 좋을 것 같습니다.

**Comment by jungin019** [comment]
음...; 이건 열어 두겠습니다

**Comment by rabbitdoggy** [comment]
예전에 제보했던 내용인데, 뻔 했네. 를 뻔했네. 로 붙여 써야 합니다.

**Comment by jungin019** [comment]
뻔했네 수정했습니다.

**Comment by STRIKE-F** [comment]
바로 밑 문장에서 뻔했어요를 붙였을 때 한 줄 안에 들어가는지도 테스트해 봐야겠네요.

**Comment by Porowl** [comment]
'흠뻑 젖을 뻔' 이 나은듯 싶네요.
일단은 그렇게 수정했어요.

**Comment by itstake** [comment]
> 우와, 큰일 날 뻔 했네.
> 신발이 젖는 줄
> 알았어요!

로 최종 결정
