### ISSUE TITLE
이 길은 버스가 다니기엔 조금 좁아 보이는데요...

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1620]
![screenshot_2016-07-12-16-12-10](https://cloud.githubusercontent.com/assets/19270364/17269637/db97dc52-5688-11e6-9caa-927e1ad3ed4c.png)

어떤 약간의 정도를 나타내는 부사로 '조금'이 압도적으로 많이 쓰이네요.
다소, 약간 따위로 다양한 표현을 사용하는 게 어떨까요?

**Comment by Porowl** [comment]
약간
