### ISSUE TITLE
줄임표의 사용에 관하여

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1621]
![-1](https://cloud.githubusercontent.com/assets/19270364/17269678/08fada72-568a-11e6-8a8d-98a3abdea200.png)

본 작 내에서 위와 같이 줄임표를 사용해 문장을 마무리짓는 경우가 경우가 왕왕 있는데요
국립국어원의 문장 부호 해설 (2014)에 따르면 줄임표 뒤엔 마침표를 쓰는 게 원칙이라고 합니다.

![default](https://cloud.githubusercontent.com/assets/19270364/17269685/41fe6d5c-568a-11e6-9716-afe134d01380.PNG)

문장 부호 사용에 관해 더 관심이 있으신 분들은 
[문장+부호+해설(2014년).pdf](https://github.com/elfinlazz/lt3translation/files/391818/2014.pdf)
직접 읽어보시는 것도 좋겠습니다 :)

**Comment by Porowl** [comment]
말을 흐린다는건 어떻게 표현해야 할까요 (...)

**Comment by Y00N** [comment]
그러니까 그걸 표현할 때 말줄임표와 마침표를 사용해야 한다는 거죠.

**Comment by Porowl** [comment]
아아. 근데 그게 프로그래밍 상 어떻게 될지 모르겠네요. 여쭤보겠습니다.

**Comment by Y00N** [comment]
프로그래밍상요? 지금처럼 말줄임표 대신에 마침표 3개 쓰던 것에 마침표를 하나 더 첨가하면 해결되는 문제 아닌가요
