### ISSUE TITLE
이 작은 눈으로도 네가 올바른 일을 하고 있다는 것을 알 수 있거든.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1628]
![screenshot_2016-07-12-16-34-39](https://cloud.githubusercontent.com/assets/19270364/17269854/71ec0da8-568f-11e6-808f-852db6fdca39.png)

**이 작은 눈으로도 네가 올바른 일을 하는 게 훤히 보이거든.** 어떨까요?
그런데 원문에서도 올바른 일이라고 하나요? 개인적으로 **~ 네가 무슨 일을 하는지 훤히 보이거든**쪽이 더 좋아서...

**Comment by Porowl** [comment]
law's right on your tail!

이라...
