### ISSUE TITLE
[건의사항] 스프링: 죄송하지만, 그렇답니다. 하지만 당신이 누구인지는 알죠. 레이튼 교수님이시죠?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#163]
![image](https://cloud.githubusercontent.com/assets/19265176/15143326/06c52572-16e4-11e6-8472-4eaef1ae96a6.png)

사실 이 부분도 문장 자체는 자연스럽고, 따라서 괜한 오지랖이 될 수도 있겠습니다만

하지만 당신이 누구인지는 알죠, 레이튼 교수님.

이렇게 쓰는 것이 뭐랄까 더 압박이 느껴진다고 해야 할까 그렇습니다. 
이에 대해서 많은 의견 부탁드립니다.

**Comment by jungin019** [comment]
아이러니하게도 원문이 
'But I do know who you are,
Professor Layton!'로 직역하면 말씀하신 게 맞습니다 ㅎㅎ
열어둘게요

**Comment by itstake** [comment]
최종 결정:
> 죄송합니다. 잘 모르겠네요. 하지만 당신이 누구인지는 알아요, 레이튼 교수님!
