### ISSUE TITLE
다시 오신것을 환영해요, 교수님.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1631]
![screenshot_2016-07-12-16-39-33](https://cloud.githubusercontent.com/assets/19270364/17269952/899e10de-5691-11e6-94eb-d12466a6fed5.png)

**다시 오신 것을 환영합니다, 교수님.**

**Comment by Porowl** [comment]
다시 오신 것을 환영해요, 교수님.

으로 수정해 두었는데
환영합니다 로 써야 할까요?
