### ISSUE TITLE
체르미 경감님이 왜 여기 오신걸까요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1638]
![screenshot_2016-07-12-16-47-37](https://cloud.githubusercontent.com/assets/19270364/17270039/bc738028-5693-11e6-9e2b-4025e539f242.png)

**체르미 경감님이 왜 여기 오신 걸까요?**
**체르미 경감님이 왜 여기 오셨을까요?**
등으로 고쳐 써야 합니다. 전 개인적으로 후자가 낫네요.

**Comment by Porowl** [comment]
체르미 경감님께선 왜 여기 오셨을까요
