### ISSUE TITLE
[건의사항] 레이튼: 그래, 그리고 이것들은 전부 엄청난 작품인걸. 누군지는 몰라도 이걸 만든 사람은 굉장한 실력자 같구나.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#164]
![image](https://cloud.githubusercontent.com/assets/19265176/15143373/57515e66-16e4-11e6-9c26-3f74f46a91a6.png)

저 부분에서 레이튼 교수는 특정한 시계 하나만을 두고 말하는 것이 아닌 것 같습니다. 
따라서 이걸 만든 사람-> 이것들을 만든 사람 으로 하는 것이 더 좋을 것 같습니다.

**Comment by jungin019** [comment]
'누군지는 몰라도 굉장한 실력자가 만든 게 분명해'로 고쳤습니다.
