### ISSUE TITLE
출발해야 할 것 같습니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1648]
![screenshot_2016-07-12-17-08-30](https://cloud.githubusercontent.com/assets/19270364/17270266/a6af739a-5699-11e6-95be-ba68196c7c6f.png)

**이제 출발해야겠습니다.** 정도로 쓰는 건 어떨까요?

**Comment by Porowl** [comment]
바로 뒷 대사의 ~겠습니다가 중복되어서

음, 끼어들어서 죄송합니다만, 더 이상
루크를 기다리게 할 수가 없군요.
이제 출발해야합니다.

가 어떨까요.
