### ISSUE TITLE
[건의사항] 루크: 시계가 똑딱거리는 걸 본 순간, 더이상 거부할 수 없어...

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#165]
![image](https://cloud.githubusercontent.com/assets/19265176/15143451/c94fd8c6-16e4-11e6-9f14-f0064b6fecc3.png)

일단 원문을 찾아보니 이렇습니다.
Once you notice the ticking of a clock, it’s impossible to ignore...
말은 맞는데 너무 직역한 느낌이라 조금 부드럽게 만들면 더 좋을것 같습니다.

일단 제가 생각해 본 것들은 이렇습니다.

정말 보면 볼 수록 빠져드는 시계들이에요
정말 귀에 박히는 똑딱 소리네요.
시계의 똑딱 소리를 들은 순간부터 머리에서 떠나지 않아요.

부디 참조하시어 더 좋은 의견 부탁드립니다.

**Comment by Porowl** [comment]
전 이거 노래가사 패러디인줄 알았는데, 딱히 찾아보지는 않았습니다만 ㅋㅋㅋ
확실히 어색하게 느껴지긴 했습니다.

**Comment by jungin019** [comment]
저는 패러디라고 생각해서인지 그다지 어색하지는 않았습니다

**Comment by kaleidoscope531** [comment]
아 저게 노래가사 패러디였나요? ㅎㅎ 제가 유행가에 둔감해서 전혀 생각도 못했습니다;;;
무슨 노래가사 패러디인가요?

**Comment by jungin019** [comment]
거부할 수 없는 너의 마력은 루시ㅍ...

**Comment by Y00N** [comment]
이게 패러디였군요? 저도 이 부분에서 뭘 거부할 수 없단 건지 이해할 수 없었어요.

**Comment by Porowl** [comment]
패러디가 아니라면 수정하는게 맞겠죠?
괜히 혼란을 야기하기보다.

**Comment by itstake** [comment]
똑딱거리는 시계 소리가
아무래도 신경 쓰여요...
