### ISSUE TITLE
지금이라고 하셨습니까? 그렇지만, 이 일과 상관없는 사람이 몇 명이나 있는걸요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1650]
![screenshot_2016-07-12-17-09-25](https://cloud.githubusercontent.com/assets/19270364/17270276/eb1dbaa0-5699-11e6-8e29-b8fabd6f46ff.png)

**지금이라고 하셨습니까? 그렇지만 이 일과 상관없는 사람들이 있잖습니까?**
라고 다듬는 게 어떨까요?

**Comment by Porowl** [comment]
지금이라고 하셨나요? 그렇지만 이 일과
상관없는 사람이 몇 명이나 있는걸요.

로 수정되어 있습니다.

지금이라고 하셨나요? 그렇지만 이 일과
상관없는 사람들이 있잖습니까?

는 어떻나요?

**Comment by Y00N** [comment]
있는걸요 는 있는 걸요로 띄어 써야 합니다
전 영찬님 의견 중 후자가 좋아요.
