### ISSUE TITLE
"아니타의 카페" 구나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1662]
![screenshot_2016-07-12-18-22-50](https://cloud.githubusercontent.com/assets/19270364/17270461/002068cc-569e-11e6-819d-79abb97ea942.png)

**"아니타의 카페"구나.** 로 붙여쓰도록 합시다.

**Comment by Porowl** [comment]
표지판에 
''아니타의 카페''라고 
쓰여 있구나.

라고 수정되어 있습니다.
