### ISSUE TITLE
[건의사항] 레이튼 : 이 곳에 일찍이 왔을 땐 가게가 닫혀 있는 것을 보았습니다. 왜 저녁이 돼서야 가게를 여시는 겁니까?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#167]
![image](https://cloud.githubusercontent.com/assets/19265176/15143570/58dbfe2a-16e5-11e6-844b-ab0776410d52.png)

이 부분도 앞서 언급한 바와 같이 레이튼의 신사적인 면모와 말투가 조금 안 맞는 것 같아서 올렸습니다. 

조금 말투를 부드럽게 하면 더 좋지 않을까 생각합니다. 
예를 들면 마지막에 '겁니까?'를 '건가요?'로 바꾼다던지?
아니면 가게를 여시는지 여쭤봐도 되겠습니까? 라던지?

많은 의견 부탁드립니다.

**Comment by jungin019** [comment]
~여쭤봐도 되겠습니까는 좀 길 것 같네요

**Comment by Porowl** [comment]
앞전에 왔을땐 가게가 닫혀 있던데, 왜 저녁이 돼서야 가게를 여신 건가요?

**Comment by bombomS2** [comment]
앞전에라는 단어가 없다고 하네요. 예전에로 쓰면 적절할까요?
예전에 왔을 땐 문이 닫혀 있던데, 왜 저녁이 돼서야 가게를 여시는 건가요?

**Comment by bombomS2** [comment]
아니면 그냥 전에 왔을 땐~ 이라고 해도 되겠군요.

**Comment by jungin019** [comment]
앞전은 의미 중복으로 없는 말입니다. 예전보다는 '전에 왔을 땐'이 어떨까요

**Comment by bombomS2** [comment]
네, 그게 제일 자연스러운 것 같습니다.
전에 왔을 땐 문이 닫혀 있던데, 왜 저녁이 돼서야 가게를 여시는 건가요?

**Comment by kaleidoscope531** [comment]
'전에 왔을 땐 문이 닫혀 있던데, 왜 저녁이 돼서야 가게를 여시는 건가요?' 좋은 것 같습니다.
