### ISSUE TITLE
아무도 여기를 돌보지 않은 것 같아요...

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1678]
![screenshot_2016-07-12-20-33-38](https://cloud.githubusercontent.com/assets/19270364/17270653/d640ecac-56a2-11e6-9998-b5f11b87c502.png)

'~것 같다"를 다듬어서 **아무도 여기를 돌보지 않나 봐요....** 로 쓰는 게 어떨까요?

**Comment by Porowl** [comment]
이 근처는 아무도 관리를 
안 한 것 같아요.

로 수정되어 있나 봅니다
