### ISSUE TITLE
[맞춤법] 수수께끼 마담 : 이런 말을 꺼내기는 미안하지만, 나는 먼저 가봐야겠구나.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#168]
![image](https://cloud.githubusercontent.com/assets/19265176/15143647/c6b9fd0c-16e5-11e6-8839-36d5edb52713.png)

중간에 엔터가 한 번 더 들어가서 한 줄이 더 띄어졌고, 그에 따라 마지막 줄이 짤려있습니다. 

그리고 마지막 줄 얼핏 보면 내게 주어진 휴가를 즐기러 뭐뭐뭐 같은데

내게 주어진 휴가라는 표현이 뭔가 어색한 것 같습니다. 

많은 의견 부탁드립니다.

**Comment by jungin019** [comment]
엔터 부분은 고쳤고, 잘린 부분은 '휴가를 즐겨야 하거든'입니다. 
표현이 어색하시다면 토의를 붙이겠습니다.

**Comment by itstake** [comment]
> 벌써 이런 말을 꺼내서 미안하지만 나는 먼저 가봐야겠구나. 이제 신나게 놀아야 하거든.
