### ISSUE TITLE
또다른 귀여운 숙녀를 안다면 인사하러 와!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1689]
![screenshot_2016-07-12-21-08-23](https://cloud.githubusercontent.com/assets/19270364/17270757/adf41f5a-56a5-11e6-900d-8cb28d4c0c05.png)

**또 다른 귀여운 숙녀를 안다면 인사하러 와!**

**Comment by Porowl** [comment]
중복
