### ISSUE TITLE
[건의사항][맞춤법] 레이튼 : 흔치 않은 대화를 나눈 것 같구나. 꼭 이곳에 다시 돌아오자구나.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#169]
![image](https://cloud.githubusercontent.com/assets/19265176/15143705/0c422994-16e6-11e6-83a5-fb35f29f7e60.png)

일단 마지막에 돌아오자구나-> 돌아오자꾸나 로 바꿔야 할 듯 합니다. 

그리고 '흔치 않은' 이 부분이 어색한 것 같습니다.
'참 비범한 대화를 나눈 것 같구나'로 바꾸는 것이 더 좋지 않을까요?

**Comment by jungin019** [comment]
돌아오자꾸나는 고쳤습니다.

**Comment by kaleidoscope531** [comment]
범상치 않은 이야기를 나눈 것 같은걸. 꼭 이곳에 다시 돌아오자꾸나. 좋은 것 같습니다.
