### ISSUE TITLE
카지노에서 모자파가 우리를 반기던 모양새로 보아하니 아무 일 없이 가기는 힘들어 보이는구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1699]
![screenshot_2016-07-18-17-16-28](https://cloud.githubusercontent.com/assets/19295794/17320555/2eac38be-58cf-11e6-8031-ef2e383a4844.png)

카지노에서 모자파가
우리를 맞이하던 모양새로 보아하니
아무 일 없이 가기는 힘들겠구나.

로 개행과 내용 수정하면 어떨까요?

그리고 모자파는 레이튼과 루크를 싫어할 텐데
'반기던' 이라는 단어를 쓰는 것은 좀 어색하지 않나요?

**Comment by jungin019** [comment]
'Considering the warm welcome we received from the Family at the casino, I'd say anything's possible.'
원문이 이건데 여기서 warm welcome이 약간 비꼬는(?) 느낌인 것 같네요.
