### ISSUE TITLE
[건의사항] 레이튼 : 마을에서 가장 고상한 부분이라고는 말할 수 없겠구나.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#170]
![image](https://cloud.githubusercontent.com/assets/19265176/15143786/7037f37a-16e6-11e6-8c5c-b696d9b4ed67.png)

말은 맞는 것 같은데 문장이 깔끔하게 읽히지가 않는 것 같습니다. 

일단 주어는 필요할 것 같습니다. 그리고 저 어떤 전제를 두고 부정하는 식의 말을 고치면 어떨까 합니다.

예로 그냥 담백하게 '이 곳은 고상하다고 말하기는 힘들겠구나.' 뭐 이런 식일까요?

이 문장도 뭔가 이상한 것 같긴 한데 제 국어 실력으로는 일단 이게 한계 같습니다;;;

많은 의견 부탁드립니다.

**Comment by jungin019** [comment]
원문이 'This cannot be said to be the most elegant part of town.' 인데 
의역이 필요할 것 같네요. 
'이 구역은 고상함과는 거리가 멀구나.' 정도가 어떨까요?

**Comment by kaleidoscope531** [comment]
'이 구역은 고상함과는 거리가 멀구나.' 좋은 것 같습니다.

**Comment by bombomS2** [comment]
저도 그렇게 바꾸는 편이 좋을 것 같아요.
