### ISSUE TITLE
크크크! 찾긴 힘들겠지만 나도 눈은 있다고.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1701]
![screenshot_2016-07-18-17-17-40](https://cloud.githubusercontent.com/assets/19295794/17321323/eb1c13c2-58d2-11e6-907a-d333bf7cc369.png)

1행의 '찾긴 힘들겠지만 나도 눈은' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
너무 칸이 비어 그냥 닫겠습니다.
