### ISSUE TITLE
이제 가 봐야겠다, 루크. 앞으로 일이 점점 더 재밌어질 것 같은 느낌이 드는구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1704]
![screenshot_2016-07-18-17-17-57](https://cloud.githubusercontent.com/assets/19295794/17321511/e3c467b8-58d3-11e6-999b-9f90ddfa668d.png)

이제 가 봐야겠다, 루크.
앞으로 일이 점점 더 재밌어질 것 같은
느낌이 드는구나.

로 개행 수정할 수 있나요?

**Comment by jungin019** [comment]
이제 가 봐야겠다, 루크.
앞으로 일이 점점 더 재밌어질거란
느낌이 드는구나. 
로 수정되어 있습니다.

**Comment by jungin019** [comment]
+) 질 거란
