### ISSUE TITLE
흠? 아! 허허허! 내가 방금 루크를 도련님이라고 불렀니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1706]
![screenshot_2016-07-18-17-19-21](https://cloud.githubusercontent.com/assets/19295794/17321807/64111442-58d5-11e6-9097-1152cdd0b96c.png)

1행의 '내가 방금 루크를' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 비어 그냥 넘기겠습니다
