### ISSUE TITLE
[건의사항] 레이튼 : 이 이상한 곳을 둘러보다 보면 우리에게 뭔가를 알려줄지도 몰라.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#171]
![image](https://cloud.githubusercontent.com/assets/19265176/15143878/f8b03532-16e6-11e6-9126-3f3060856fd6.png)

저 문장이 약간 직역된 느낌이 나는 것 같습니다. 
일단 원문을 보면
Let’s see what else we can find out by exploring this strange place.
이렇게 되는데요,

일단 제가 생각한 것은 

좀 더 이 이상한 장소를 둘러보면서 다른 단서를 찾아보자꾸나.

이렇게 해 봤습니다. 

이렇게 놓고 보니 너무 단순화한 것 같기도 하네요. 많은 의견 부탁드립니다.

**Comment by jungin019** [comment]
좀 더 이 이상한 장소를 둘러보면서 다른 단서를 찾아보자꾸나. 가 좋긴 하겠군요

**Comment by bombomS2** [comment]
이 기이한/기묘한 곳을 좀 더 둘러보면서 다른 단서가 될 만한 걸 찾아보자꾸나.
는 어떤가요?

**Comment by kaleidoscope531** [comment]
확실히 '이 이상한 장소'도 대체가 가능하면 대체할 필요성이 있어 보입니다.
그리고 기묘한이 기이한 보다는 나아 보이네요.

**Comment by STRIKE-F** [comment]
이 기묘한 곳을 좀 더 둘러보면서 다른 단서가 될 만한 걸 찾아보자꾸나. 로 수정했습니다.
