### ISSUE TITLE
그거 아나 레이튼? 이 숙녀가 자네에게 한방 먹인 것 같구만.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1710]
![screenshot_2016-07-18-17-21-04](https://cloud.githubusercontent.com/assets/19295794/17322190/3dd86bb6-58d7-11e6-8b3d-05a91e8a1458.png)

그거 아나 레이튼? 
이 숙녀가 자네에게 한 방 먹인 것 같구만.

으로 개행 수정할 수 있나요?

**Comment by jungin019** [comment]
칸이 안 되어 닫겠습니다.
