### ISSUE TITLE
레이튼! 이...이게 다 뭔가? 도대체 런던에 무슨 일이 일어난겐가?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1713]
![screenshot_2016-07-18-17-47-43](https://cloud.githubusercontent.com/assets/19295794/17323081/79022c82-58db-11e6-9f65-af9c4ad4b84c.png)

레이튼! 이... 이게 다 뭔가?
도대체 런던에 무슨 일이 일어난 겐가?

로 내용과 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
