### ISSUE TITLE
네. 확신할 수는 없습니다만, 그럴 가능성이 매우 높습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1714]
![screenshot_2016-07-18-17-47-58](https://cloud.githubusercontent.com/assets/19295794/17323154/f780b290-58db-11e6-822b-d649503b6d3b.png)

1행의 '그럴' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
