### ISSUE TITLE
미래요! 여긴 10년 후의 런던이라고요, 바튼 순경님!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1716]
![screenshot_2016-07-18-17-48-21](https://cloud.githubusercontent.com/assets/19295794/17323776/4f93f86e-58de-11e6-8c33-7c2c162dc359.png)

2행의 '런던이라고요,' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
