### ISSUE TITLE
그래, 내가 수염머플러 씨다! 그런데 네 옆에 그 퍼덕거리는 친구는 누구니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1718]
![screenshot_2016-07-18-17-48-59](https://cloud.githubusercontent.com/assets/19295794/17324768/f4f36aa2-58e2-11e6-9632-2af7a9ef91d5.png)

그래, 내가 수염머플러 씨다!
그런데 네 옆에 그 퍼덕거리는 친구는
누구니?

로 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
