### ISSUE TITLE
뭐가 그리 어렵다고 그래, 그냥 버섯만 하나 가져오는 것 뿐이잖아. 빨리! 버섯 좀 부탁해!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1719]
![screenshot_2016-07-18-17-51-12](https://cloud.githubusercontent.com/assets/19295794/17324857/726f6fda-58e3-11e6-9b6d-f5ed7aab8c5e.png)

뭐가 그리 어렵다고 그래.
그냥 버섯만 하나 가져오는 것 뿐이잖아.
빨리 버섯 좀 부탁해!

로 개행과 내용 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
현재는

뭐가 그리 어렵다고 그래?
그냥 버섯 하나 가져오는 것뿐이잖아. 
빨리! 버섯 좀 부탁해!

로 수정되었습니다.
