### ISSUE TITLE
[건의사항] 루크의 편지 : 비극이 내린 런던을 어서 해방시키고 싶습니다.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#172]
![image](https://cloud.githubusercontent.com/assets/19265176/15143961/7ada8eea-16e7-11e6-88dd-632890dc248c.png)

일단 원문이
I wish to enlist your help in freeing this town from the tragedy that has befallen it.
이렇습니다. 

제 생각엔 너무 축약을 많이 한것 같아 이렇게 올리게 되었습니다.

일단 제가 생각해 본 것은

이 곳에 닥친 비극에서 런던을 자유롭게 하기 위하여 교수님의 도움이 꼭 필요합니다.

이 정도입니다. 좋은 의견 기다리겠습니다.

**Comment by Porowl** [comment]
@Latteria

**Comment by Latteria** [comment]
"이 곳에 닥친 비극에서 런던을 자유롭게 하기 위해서라도 교수님의 도움이 꼭 필요합니다."로 채택하겠습니다.
