### ISSUE TITLE
앵무새 - 수염머플러의 버섯

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1720]
![screenshot_2016-07-18-17-52-00](https://cloud.githubusercontent.com/assets/19295794/17350616/361b1fe0-5963-11e6-88de-e525a06f26c8.png)

케헤헤! 잘 들어. 걱정하지 마.
이건 그렇게 어렵진 않으니까!
나한테 버섯을 좀 가져다 줬으면 좋겠어.
멋지고 빛나는 사랑스런 빨간 버섯 말야.
가지고 올 수 있겠지?

로 내용과 개행 수정하면 어떨까요?

그리고 '멋지고 빛나는 사랑스런 빨간 버섯' 이라는 표현이 조금 걸리는데 다른 분들은 어떻게 생각하시나요?

**Comment by STRIKE-F** [comment]
개행은 수정했습니다.
