### ISSUE TITLE
네가 그럴 때까지, 여기서 내 버섯을 기다리고 있을게!! 그러니까, 날 잊지 마!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1721]
![screenshot_2016-07-18-17-52-16](https://cloud.githubusercontent.com/assets/19295794/17350667/9219a960-5963-11e6-9eb7-27d1a5484a90.png)

네가 가져다줄 때까지, 
여기서 내 버섯을 기다리고 있을게!!
그러니까, 날 잊지 마!

로 개행과 내용 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
오역을 좀 수정해서 현재는

난 네가 버섯을 가져올 때까지 
여기서 언제까지나 기다릴 거야.
그러니까, 날 잊지 마!

로 수정했습니다.
