### ISSUE TITLE
그러고보니, 깜빡한게 있단다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1722]
![screenshot_2016-07-18-17-52-39](https://cloud.githubusercontent.com/assets/19295794/17350683/c1ce393c-5963-11e6-8943-2ebf12d2ddb3.png)

그러고 보니, 깜빡한 게 있단다.

로 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
