### ISSUE TITLE
그러곡보니 그렇네요! 완전히 깜빡하고 있었어요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1723]
![screenshot_2016-07-18-17-52-48](https://cloud.githubusercontent.com/assets/19295794/17350707/e24dd366-5963-11e6-9fd4-a1a97e107d75.png)

그러고 보니 그렇네요!
완전히 깜빡하고 있었어요!

로 개행과 내용 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
현재는 

아 맞다! 완전히 깜빡하고 있었어요!

로 수정했습니다.
