### ISSUE TITLE
지친다고 했니? 음, 지칠 때 항상 힘이 되어주는 게 뭔지 아니? 맛있는 초콜릿 한 조각이지!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1724]
![screenshot_2016-07-18-17-53-49](https://cloud.githubusercontent.com/assets/19295794/17350725/0c1da8ce-5964-11e6-8caa-646c1a9dd4e3.png)

지친다고 했니? 음, 지칠 때
항상 힘이 되어주는 게 뭔지 아니?
맛있는 초콜릿 한 조각이지!

로 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
지친다고 했니? 음, 지칠 때 항상 
힘이 되어주는 게 뭔지 아니?
맛있는 초콜릿 한 조각이지!

이런 개행은 어떨까요
