### ISSUE TITLE
제가 좀 봐도 될까요? 제가 해결할 수 있을지도 몰라요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1725]
![screenshot_2016-07-18-17-54-02](https://cloud.githubusercontent.com/assets/19295794/17350751/4ed3d65c-5964-11e6-903a-2163b60efe50.png)

제가 좀 봐도 될까요?
제가 해결할 수 있을지도 몰라요.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 남아 그냥 닫겠습니다.
