### ISSUE TITLE
미래의 루크와 만난 후, 레이튼과 일행은 미래의 레이튼의 본거지에 잠입하기로 했다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1728]
![screenshot_2016-07-29-12-42-21](https://cloud.githubusercontent.com/assets/19295794/17350829/df1d6d18-5964-11e6-9175-4de51be5bfa1.png)

미래의 루크와 만난 후,
레이튼 일행은 미래의 레이튼의 본거지에
잠입하기로 했다.

로 내용과 개행 수정하면 어떨까요?

그리고 '~의' 라는 표현이 반복되는데 수정할 수는 없을까요?

**Comment by STRIKE-F** [comment]
비어 보이는 문제 때문에 개행은 

미래의 루크와 만난 후, 레이튼 일행은
미래의 레이튼의 본거지에 
잠입하기로 했다.

로 했습니다.
