### ISSUE TITLE
[오역] 베키 : 우리 호텔은 까다로운 신사 숙녀분들을 대접하는 호텔이거든.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#173]
![image](https://cloud.githubusercontent.com/assets/19265176/15144006/c48bd3c8-16e7-11e6-855c-41083a402d16.png)

일단 베키가 저 말을 하는 것은 루크가 호텔을 무시하는 듯한 발언을 했기 때문에 반박 + 조롱용으로 하는 말입니다. 
물론 제가 예민한 걸 수도 있겠습니다만은 까다로운 신사 숙녀분 이 부분 조금 '손님을 대접하느라 고생이 많은 호텔'이라는 느낌을 주는 것 같습니다.

따라서 '까다로운'을 '안목 있는'으로 바꾸는 편이 더 의미 전달에 있어서 좋지 않을까 합니다.

**Comment by Porowl** [comment]
안목 있는에 찬성입ㄴ니다.

**Comment by jungin019** [comment]
수정했습니다.
