### ISSUE TITLE
그러니까, 내 원대한 사업 계획을 고백하려는 거지!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1730]
![screenshot_2016-07-29-12-42-54](https://cloud.githubusercontent.com/assets/19295794/17350933/9c095af4-5965-11e6-9d65-0e4d72b43caa.png)

1행의 '내 원대한 사업 계획을' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by Porowl** [comment]
보류
