### ISSUE TITLE
그래. 마침내 나의 아름다운 여신 벨은 내 가슴 깊숙히 있는 비밀을 알게 되겠지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1731]
![screenshot_2016-07-29-12-42-59](https://cloud.githubusercontent.com/assets/19295794/17350975/eb91d664-5965-11e6-97d7-22e7e17f2946.png)

그래. 마침내 나의 아름다운 여신 벨은
내 가슴 깊숙히 있는 비밀을 알게 되겠지.

로 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
