### ISSUE TITLE
어...잘 되기를 바라요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1732]
![screenshot_2016-07-29-12-43-16](https://cloud.githubusercontent.com/assets/19295794/17351032/5392b6f2-5966-11e6-95c8-7203a5b0662a.png)

말줄임표와 '잘' 사이에 한 칸을 띄는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
