### ISSUE TITLE
안녕하세요, 마우이씨. 여기가 만나니 반갑군요. 이번엔 어딜 가려고 하셨나요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1733]
![screenshot_2016-07-29-12-43-33](https://cloud.githubusercontent.com/assets/19295794/17351051/7477b0fc-5966-11e6-9a48-42bf71be6f21.png)

안녕하세요, 마우이씨.
여기서 만나니 반갑군요.
이번엔 어딜 가려고 하셨나요?

로 개행 수정하면 어떨까요?

**Comment by Y00N** [comment]
**마우이 씨**

**Comment by STRIKE-F** [comment]
개행은 보류하겠습니다. 띄어쓰기는 수정했습니다.
