### ISSUE TITLE
스페인에 거대한 지하 동굴들 있다는 놀라운 기사 봤습니다. 그래서 그 동굴 보러 왔습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1734]
![screenshot_2016-07-29-12-43-37](https://cloud.githubusercontent.com/assets/19295794/17351070/9f516bc4-5966-11e6-9ff3-552268c50875.png)

스페인에 거대한 지하 동굴들 있다는
놀라운 기사 봤습니다.
그래서 그 동굴 보러 왔습니다.

로 개행 수정하는 것은 어떨까요?

**Comment by STRIKE-F** [comment]
스페인 신문에 거대한 지하 동굴들 있다는 
놀라운 기사 봤습니다. 그래서 그 동굴 
보러 왔습니다.

이렇게 하는 건 어떨까요

**Comment by Porowl** [comment]
<T>스페인 신문에 거대한 지하 동**굴** 있다는 
놀라운 기사 봤습니다. 그래서 그 동굴 
보러 왔습니다.
