### ISSUE TITLE
아, 네. 한 가설에 다르면 이런 지하 동굴들이 전 세계에 걸쳐서 존재한다고 하더군요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1735]
![screenshot_2016-07-29-12-43-44](https://cloud.githubusercontent.com/assets/19295794/17351105/cb94ebd4-5966-11e6-9f3d-cb1a437dd503.png)

아, 네. 
한 가설에 따르면 그러한 지하 동굴들이
전 세계에 걸쳐서 존재한다고 하더군요.

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
