### ISSUE TITLE
네. 여행자의 길 끝없이 이어져 있습니다. 굴곡도 많습니다. 하지만 이번에는 꼭 도착할 겁니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1736]
![screenshot_2016-07-29-12-43-54](https://cloud.githubusercontent.com/assets/19295794/17351134/001f6172-5967-11e6-8171-ab6bd10a10d7.png)

네. 여행의 길 끝없이 이어져 있습니다.
굴곡도 많습니다.
하지만 이번에는 꼭 도착할 겁니다.

로 개행 수정하면 어덜까요?

**Comment by Porowl** [comment]
<T>네. 여행자 길 끝없이 이어져 있습니다. 
굴곡도 많습니다. 
하지만 이번 꼭 도착 하십니다.
