### ISSUE TITLE
[건의사항] 레이튼 : 하하하! 루크, 이 숙녀분은 호텔의 평판을 더럽히는 손님을 좋게 받지 않는구나.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#174]
![image](https://cloud.githubusercontent.com/assets/19265176/15144123/5d56dd00-16e8-11e6-8afa-29463e130fef.png)

저 문장의 의미가 잘 와 닿지 않는 것 같습니다. 일단 원문은 이렇습니다. 

Ha ha! Our friend here doesn’t take kindly to your besmirching the good name of her hotel, Luke.

일단 제가 생각해 본 바는 이렇습니다. 

하하하! 루크, 이 숙녀분은 네 이 호텔에 대한 낮은 평가를 좋아하지 않는구나.

이 말도 원문을 잘 옮겼다고는 보기 힘들 수도 있겠습니다만, 일단 많은 의견 부탁드립니다.

**Comment by jungin019** [comment]
'하하하! 루크, 이 숙녀분은 호텔을 낮게 평가하는 걸 싫어하는구나' 정도가 좋을지도 모르겠네요. 조금 생략된 느낌이 없지는 않지만....

**Comment by kaleidoscope531** [comment]
저는 '하하하! 루크, 이 숙녀분은 호텔을 낮게 평가하는 걸 싫어하는구나' 이 번역이 번역한 티도 안 나고 좋을 듯 합니다.

**Comment by Porowl** [comment]
나쁘게 평가받는걸 은 어떨까요.

**Comment by itstake** [comment]
> 하하하! 이 숙녀분께선 호텔을 얕잡아보는 손님은 싫어하시는구나.
