### ISSUE TITLE
대단합니다! 문제 풀어서 나 여행 다시 할 수 있습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1740]
![screenshot_2016-07-29-12-45-18](https://cloud.githubusercontent.com/assets/19295794/17351299/534d0ea2-5968-11e6-979f-3591f52ae80b.png)

1행의 '문제 풀어서 나' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by Y00N** [comment]
다 안 넘어 갈걸요.
**대단합니다!
문제 풀어서 나 여행 다시 합니다!** 정도는 들어가려나요...

**Comment by Porowl** [comment]
<T><A1/1>대단합니다! 
문제 풀어서 나 여행 다시 합니다.
