### ISSUE TITLE
안녕하십니다. 어딜 가시든 행운 따릅니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1741]
![screenshot_2016-07-29-12-45-21](https://cloud.githubusercontent.com/assets/19295794/17351310/6e858fbe-5968-11e6-9312-e9caa5f655f2.png)

1행의 '어딜 가시든 행운' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by Porowl** [comment]
오역이라
<T>안녕하십니다.<W><A3/1> 어딜 가시든
행복한 여행 따릅니다.
으로 고칠게요

개행은 너무 비어보여서 보류
