### ISSUE TITLE
아저씨처럼 길을 잘 잃어버리는 사람은 전엔 본 적이 없어요. 도대체 이곳인 어떻게 온 거에요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1742]
![screenshot_2016-07-29-12-45-25](https://cloud.githubusercontent.com/assets/19295794/17351336/8e229290-5968-11e6-90ff-2c036ebf4a42.png)

2행의 '도대체 이곳엔' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by Y00N** [comment]
"도대체 이곳은 어떻게 온 거에요?"를
**도대체 여긴 어떻게 왔어요?**라고 바꾸는 게 좋다고 생각합니다.

**Comment by STRIKE-F** [comment]
아저씨처럼 길을 잘 잃어버리는 분은
본 적이 없어요. 애초에 여긴 어떻게 
오셨어요?

이건 어떠련지요

**Comment by vbn2523** [comment]
두 분의 대사 모두 좋아 보입니다.
