### ISSUE TITLE
모자파를 쫓아내보자!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1746]
![screenshot_2016-07-29-12-47-26](https://cloud.githubusercontent.com/assets/19295794/17351416/3ee46f68-5969-11e6-81bd-321c3122a395.png)

'쫓아내보자!' 는 '쫓아내 보자!' 로 띄우는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
