### ISSUE TITLE
따뜻한 식사라니, 좋은데?  나도 모락모락 김이 나는 고기 파이에 버섯 그레이비 소스를 뿌려 먹고 싶어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1747]
![screenshot_2016-07-29-12-47-44](https://cloud.githubusercontent.com/assets/19295794/17351432/5f5f5d20-5969-11e6-8978-447d10616749.png)

따뜻한 식사라니, 좋은데?
나도 모락모락 김이 나는 고기 파이에
버섯 그레이비 소스를 뿌려 먹고 싶어.

로 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
