### ISSUE TITLE
- 그게 아니라! 네차례라구!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1748]
![screenshot_2016-07-29-12-48-07](https://cloud.githubusercontent.com/assets/19295794/17351485/e97415b4-5969-11e6-862d-fc965b7da61c.png)

'네차례라구!' 는 '네 차례라구!' 로 띄우는 게 어떨까요?

**Comment by Y00N** [comment]
동의합니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
