### ISSUE TITLE
밥통이라고 한 걸 보니 우리 둘 다인 것 같은데?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1749]
![screenshot_2016-07-29-12-48-18](https://cloud.githubusercontent.com/assets/19295794/17351494/10f46026-596a-11e6-8963-3e2cd792c764.png)

1행의 '우리 둘 다인 것' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
현재는

밥통이라고 한 걸 보니 우리 둘 다 아냐?

로 수정됐습니다.
