### ISSUE TITLE
[건의사항] 레이튼 : 하하, 정말 반박하기가 힘들군요, 젊은 아가씨. 장소는 매우 중요하죠.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#175]
![image](https://cloud.githubusercontent.com/assets/19265176/15144217/ff2da74e-16e8-11e6-867e-f911a28dcafa.png)

'장소는 매우 중요하죠.' 에서 저 장소가 어떤 장소를 뜻하는지를 언급하는 것이 더 좋을 것 같습니다. 
예를 들면 '묵는 장소는 매우 중요하죠.' 라던가?

그리고 반점(,)을 너무 과용하는 것 같습니다. 위 문장의 두 반점 중 하나를 없애는 편이 좋을 것 같습니다.

**Comment by jungin019** [comment]
음.... 저건 좀 애매한 게 원문이 location is everything이라서 그... 뭐라고 해야하지 살짝 관용적인 표현이라고 해야할까요? 그래서 그걸 살리려고 했던 것 같습니다.

**Comment by kaleidoscope531** [comment]
그렇군요, 그런 관용 표현이 있는지 몰랐습니다.

**Comment by STRIKE-F** [comment]
저희도 쉼표를 가급적 줄여야 한다는 점에는 찬성하는데, 앞의 쉼표는 의성어와 뜻이 있는 문장(?) 사이라서 필요하고 뒤의 쉼표는 말하는 대상이 문장 뒤에 오다 보니 필요해서 넣은 거라서요.

**Comment by itstake** [comment]
> 하하, 정말 반박하기 어렵군요.
> 물론 여기저기 다니기 편하면 좋겠죠.
