### ISSUE TITLE
그게 맞는 것 같은데! 네, 네, 보스트로 형님. 두 말 하실 필요 없이 당장 꺼지겠습니다요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1750]
![screenshot_2016-07-29-12-48-23](https://cloud.githubusercontent.com/assets/19295794/17351508/412539b4-596a-11e6-8322-5aee9a6e83b5.png)

그게 맞는 것 같은데! 
네, 네 보스트로 형님.
두 말 하실 필요 없이 당장 꺼지겠습니다요.

로 개행 수정하면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
문장이 수정되어 현재는 
'그렇구만. 네, 네, 보스트로 형님.
두 말 하실 필요 없이 
당장 꺼지겠습니다요.' 로 되어 있습니다.
