### ISSUE TITLE
훌륭해! 드디어 차이나타운으로 들어갈 수 있겠네!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1751]
![screenshot_2016-07-29-12-48-30](https://cloud.githubusercontent.com/assets/19295794/17351533/7b4f6560-596a-11e6-84b6-d242de539f77.png)

1행의 '드디어 차이나타운으로 들어갈' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 그냥 닫겠습니다.
