### ISSUE TITLE
오, 이런? 뭐가 "오, 이런" 이란 거예요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1752]
![screenshot_2016-07-29-12-48-49](https://cloud.githubusercontent.com/assets/19295794/17351548/9cd4e2be-596a-11e6-9ba0-7efffeef3b7a.png)

"오, 이런" ?
뭐가 "오, 이런" 이란 거예요?

로 개행과 내용 수정하는 것은 어떨까요?

**Comment by jungin019** [comment]
역시 칸이 너무 남아 닫음
