### ISSUE TITLE
이 장치는 네가 푼 수수께끼의 수를 세는 장치야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1753]
![screenshot_2016-07-29-12-48-53](https://cloud.githubusercontent.com/assets/19295794/17351565/c71e1bee-596a-11e6-9cd9-af0efb0a3d80.png)

이 장치는
네가 푼 수수께끼의 수를 세는 거야.

로 개행과 내용 수정하면 어떤가요?

**Comment by jungin019** [comment]
이 역시 그냥 닫겠습니다.
