### ISSUE TITLE
글쎄요, 써 보자니 좀 긴장되는데요. 미래에는 모르는 기계들이 너무 많다니까요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1755]
![screenshot_2016-07-29-12-49-16](https://cloud.githubusercontent.com/assets/19295794/17351594/0d7eb8e6-596b-11e6-95db-9e3d2e6685c1.png)

2행의 '너무' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by Y00N** [comment]
**글쎄요, 써보자니 좀 긴장되는데요. 미래엔 모르는 기계가 너무 많다니까요!**
라고 조금 손대보면 어떨까요?

**Comment by jungin019** [comment]
글쎄요, 써 보자니 좀 긴장되는데요.
미래엔 모르는 기계가 너무 많다니까요! 
로 수정
