### ISSUE TITLE
웅장한 이 구조물은 이곳 주변에 행운의 영을 부르도록 설계되어 있다네.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1757]
![screenshot_2016-07-29-12-50-08](https://cloud.githubusercontent.com/assets/19295794/17351624/4478ef24-596b-11e6-8fac-0ec30ea9c646.png)

웅장한 이 구조물은
이곳 주변에 행운의 영을 부르도록
설계되어 있다네.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
개인적으로는 
'웅장한 이 구조물은 이곳 주변에 
행운의 영을 부르도록 설계되어 있다네.' 가 나을 것 같습니다.
