### ISSUE TITLE
[건의사항] 레이튼 : 그러면, 방 하나와 가장 가까운 지하철역까지 가는 길을 주실 수 있겠습니까.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#176]
![image](https://cloud.githubusercontent.com/assets/19265176/15144261/47c4fca0-16e9-11e6-919d-9053fbbd6536.png)

위 문장에서 '방 하나'는 준비를 부탁해야 하는 것이고, '가까운 지하철역까지 가는 길'은 알려달라고 해야 하는 것인데 저 두 가지를 같이 묶어놓는 것은 좋지 않을 것 같습니다. 
따라서 저 문장을 두 부분으로 나누는 것이 더 좋을 것 같습니다. 

일단 제가 생각해본 것은

그럼 방 하나 준비를 부탁 드리고, 가장 가까운 지하철역까지 가는 길을 알려주실 수 있겠습니까?

이 정도입니다.

**Comment by Glacie** [comment]
개인적으로는 설령 문법적으로 약간 거슬리는 부분이 있다고는 해도 상당히 마음에 드는 문장이라고 생각했는데요..

**Comment by bombomS2** [comment]
'가장 가까운 지하철역까지 가는 길'의 가장 앞에 여기서를 넣어서,
그러면, 방 하나와 여기서 가장 가까운 지하철역까지 가는 길을 주실 수 있겠습니까.
는 어떨까요? 중의적인 의미를 줄일 수 있을 것 같습니다.

**Comment by kaleidoscope531** [comment]
보면 한 문장에 두 가지를 모두 요구하는 포맷을 지키고 싶으신 것 같은데, 그럼 이건 어떨까요?
'그러면, 방 하나와 여기서 가장 가까운 지하철역까지 가는 길의 안내를 부탁드려도 될까요?'

**Comment by bombomS2** [comment]
앗, 그거 좋은데요.
그러면, 방 하나와 여기서 가장 가까운 지하철역까지 가는 길의 안내를 부탁드려도 되겠습니까.
이렇게 끝맺는 것도 괜찮을 것 같아요.
