### ISSUE TITLE
안녕하세요. 여기에 차이나타운이 맞나요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1765]
![screenshot_2016-07-29-12-53-30](https://cloud.githubusercontent.com/assets/19295794/17352322/b776c9a6-5970-11e6-8204-ff47fcc9f353.png)

1행의 '여기가 차이나타운이' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 많이 남아 닫음
