### ISSUE TITLE
[건의사항] 베키 : 아, 그리고 호텔 방명록에 이름을 써주실 수 있을까요?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#177]
![image](https://cloud.githubusercontent.com/assets/19265176/15144361/e24d5f6a-16e9-11e6-85e5-103e8344f371.png)

마지막 '있을까요?'를 '있으세요?'로 바꾸는 편이 더 자연스럽지 않을까 생각합니다.

**Comment by Porowl** [comment]
있으세요나 있을까요나, '가능'한지를 물어보는 말투인 것 같습니다.
질문이라기보다 요청이니 "써 주시겠어요?" 가 더 나을 것 같습니다.

**Comment by jungin019** [comment]
저도 이왕 바꾸려면 써 주시겠어요? 가 좋을 것 같네요

**Comment by kaleidoscope531** [comment]
저도 '써 주시겠어요?' 좋을 것 같습니다.
