### ISSUE TITLE
그대로만 계속하면 우리가 현재라고 부르는 무한한 시간의 진정한 가치를 찾을 수 있을 거야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1771]
![screenshot_2016-07-29-12-55-22](https://cloud.githubusercontent.com/assets/19295794/17352441/874db00e-5971-11e6-90d8-01de51bb1fa5.png)

그대로만 계속하면
우리가 현재라고 부르는 무한한 시간의
진정한 가치를 찾을 수 있을 거야.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
전체적으로 길이가 이상해져서 그냥 놔두겠습니다.
