### ISSUE TITLE
맞아. 다른 사람들도 너희처럼 인사를 좀 한다면 세상은 훨씬 멋진 곳이 될 텐데.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1780]
![screenshot_2016-07-29-12-57-49](https://cloud.githubusercontent.com/assets/19295794/17352612/ef2eca9a-5972-11e6-9d83-057d590b2e17.png)

맞아. 다른 사람들도
너희처럼 인사를 좀 한다면
세상은 훨씬 멋진 곳이 될 텐데.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
'맞아. 다른 사람들도 그렇게 인사를
한다면 세상은 훨씬 멋진 곳이 될 텐데.'로 수정하였습니다.
