### ISSUE TITLE
혹시 저 육각거탑을 운영하는 사람에 대해 알고 계신게 있는가 해서요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1786]
![screenshot_2016-07-29-12-59-30](https://cloud.githubusercontent.com/assets/19295794/17355618/c9aab472-598c-11e6-8e7a-d7c45748a1ba.png)

혹시 저 육각거탑을
운영하는 사람에 대해
알고 계신 게 있는가 해서요.

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
애매해서 보류하겠습니다.

**Comment by Y00N** [comment]
그대로도 괜찮아 보이는데요.
