### ISSUE TITLE
이곳 사람들은 그 인간과 깡패들 때문에 겁에 질려서 밖에 잘 나오지도 않으니까요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1788]
![screenshot_2016-07-29-12-59-50](https://cloud.githubusercontent.com/assets/19295794/17355658/251bff28-598d-11e6-91d2-21cafcb38d8a.png)

2행의 '밖에 잘 나오지도' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 이상하게 남아 닫겠습니다.
