### ISSUE TITLE
[건의사항] 파이아르 : 입구에 있는 안내판을 못 봤니? 그렇게 써 있었을텐데.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#179]
![image](https://cloud.githubusercontent.com/assets/19265176/15144494/b2e7ebb8-16ea-11e6-90c4-bd1537317c02.png)

제가 예민한 걸지도 모르겠습니다만, '입구에 있는 안내판을 못 봤니?' 이 문장이 왠지 어린아이나 아랫사람에게 하는 말 같습니다. 
일단 청자가 레이튼이기 때문에 저 부분을 어떻게 해야 할 것 같습니다.

파이아르가 앞뒤로 하는 말을 들어보면 왠지 시장골목의 맛집에서 식재료 손질하는 아저씨? 같은 느낌의 캐릭터를 잡으신 것 같은데 그렇다면 마지막의 '니' 를 '나'로 바꾸면

입구에 있는 안내판을 못 봤나? 

가 되어서 딱 캐릭터에도 맞고 좋아 보입니다.

**Comment by jungin019** [comment]
아무래도 오타 같군요. 원래는 맞나 였던 것으로 기억합니다.

**Comment by rabbitdoggy** [comment]
쓰여 있었을 텐데. 로 고쳐야 하는 부분이 있습니다.

**Comment by jungin019** [comment]
아 그 부분 고치겠습니다.
