### ISSUE TITLE
안녕. 우리 신사분들은 요즘 어떻게 지내?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1791]
![screenshot_2016-07-29-13-01-11](https://cloud.githubusercontent.com/assets/19295794/17355735/9e0ebf88-598d-11e6-9073-38de0858fd38.png)

1행의 '우리 신사분들은 요즘' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다
