### ISSUE TITLE
전 페퍼예요. 혹시 먹거리를 찾아 오신 거라면, 잘 찾아 오셨어요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1798]
![screenshot_2016-07-29-13-03-29](https://cloud.githubusercontent.com/assets/19295794/17364673/7e4a15ce-59bc-11e6-9797-3e78d5adc45c.png)

전 페퍼예요.
혹시 먹거리를 찾고 계시다면, 
잘 오셨어요!

로 내용과 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 개행은 놔두고 내용은 고쳤습니다.
