### ISSUE TITLE
그건 다행입닌다만, 사실 저희는 배가 고픈게 아니라 해답이 고파서요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1799]
![screenshot_2016-07-29-13-03-33](https://cloud.githubusercontent.com/assets/19295794/17364693/a7a21de0-59bc-11e6-882b-917ac9531dda.png)

문장 전체에서 번역체스러운 느낌이 난다고 생각하는데 다른 분들은 어떻게 생각하시나요?

**Comment by jungin019** [comment]
문장이 수정되어 
'그거 잘됐군요, 하지만 저희는 지금
배보단 해답이 고파서요.'로 되어있습니다.

**Comment by Porowl** [comment]
본 이슈는 예전에 토의를 거쳐 수정한 사항입니다.
#2209
