### ISSUE TITLE
혹시 딤섬 좋아하세요? 왜, 조그마한 중국식 요리 중에 차랑 잘 어울리는 요리 말이에요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1800]
![screenshot_2016-07-29-13-03-43](https://cloud.githubusercontent.com/assets/19295794/17364715/cb059cb2-59bc-11e6-8b6a-25d8105715a8.png)

혹시 딤섬 좋아하세요?
왜, 조그마한 중국식 요리 중에
차랑 잘 어울리는 요리 말이에요.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
전체적으로 문장을 수정했습니다. 
'혹시 딤섬 좋아하세요?
왜, 조그마한 중국식 요리인데 
차와 잘 어울리는 것 말이에요.'
