### ISSUE TITLE
그럼, 우리 가게는 만두라면 소문이 쫙 퍼져 있단다. 찐빵과 무떡도 말야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1801]
![screenshot_2016-07-29-13-03-55](https://cloud.githubusercontent.com/assets/19295794/17364742/017015b6-59bd-11e6-896b-49315742f9b7.png)

그럼, 우리 가게는
만두에 대한 소문이 쫙 퍼져 있단다.
찐빵과 무떡도 말야.

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
원문이 'Yep, we've got a great assortment of dumplings, little steamed buns, and radish cakes.'네요... 
assortment 는 모음, 집합 이런 의미인데 왜 번역이 이렇게 됐지... 
'그럼, 우리 가게엔 다양한 종류의 만두가 있단다. 찐빵과 무떡도 그렇고.' 정도는 어떨까요

**Comment by Porowl** [comment]
이견 없으면 제이님이 정리해주신걸로
