### ISSUE TITLE
돼지고기 국수 둘... 그럼 잠깐만요. ...자, 국수 두 그릇 나왔습니다! 그래서 물어보시려 하신 게 뭐였죠?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1804]
![screenshot_2016-07-29-13-04-43](https://cloud.githubusercontent.com/assets/19295794/17364860/a2fa2f66-59bd-11e6-89f5-913f49d0a779.png)

돼지고기 국수 둘... 그럼 잠깐만요.
... 자, 국수 두 그릇 나왔습니다!
그래서 물어보려 하셨던 게 뭐죠?

로 개행과 내용 수정하면 어떨까요?

**Comment by Y00N** [comment]
**돼지고기 국수 둘.... 그럼 잠깐만요.
... 자, 국수 두 그릇 나왔습니다!
그래서, 물어보신다던 게 뭐죠?**
는 어떨까요?

**Comment by jungin019** [comment]
돼지고기 국수 둘... 그럼 잠깐만요.
... 자, 국수 두 그릇 나왔습니다!
그래서, 물어보신다던 게 뭐였죠?
로 수정
