### ISSUE TITLE
제가 10년 전 쯤 런던에 살았는데, 그때는 런던에 차이나타운 가은 건 없었던 것으로 기억하는데요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1805]
![screenshot_2016-07-29-13-04-48](https://cloud.githubusercontent.com/assets/19295794/17364899/e013a198-59bd-11e6-83d3-60f06c02766a.png)

2행의 '없었던' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by Y00N** [comment]
**제가 10년 전쯤 런던에 살았습니다.
그때는 런던에 차이나타운이 없었다고
기억합니다.**

는 어떨까요?

**Comment by Porowl** [comment]
너무 딱딱해 보입니다.
기억합니다 -> 기억해서요 로 바꿔서 적용시키면 어떨까요

**Comment by jungin019** [comment]
개인적으로 영찬님 의견 괜찮네요
