### ISSUE TITLE
어휴, 그건 대답해주기 힘들겠네요. 저도 이 가게를 연지 얼마 되지 않아서요. 저는 잘 모르겠는데요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1806]
![screenshot_2016-07-29-13-04-52](https://cloud.githubusercontent.com/assets/19295794/17364924/1729a36c-59be-11e6-8b1e-b2ea290e2e4f.png)

어휴, 그건 대답해주기 힘들겠네요.
저도 이 가게를 연지 얼마 되지 않아서요.
저는 잘 모르겠는데요?

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
저도를 다음 행으로 넘기면 않아서요 가 잘려서 않아서요는 다음 행으로 넘겼습니다.
