### ISSUE TITLE
친하게 지내는 언니가 여기에 새로운 상점가가 생길거라고 해서 소개받아 왔거든요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1807]
![screenshot_2016-07-29-13-04-58](https://cloud.githubusercontent.com/assets/19295794/17364959/42e297de-59be-11e6-96c6-0969654ba100.png)

친하게 지내는 언니가
여기에 새로운 상점가가 생길 거라고 해서
소개받아 왔거든요.

로 내용과 개행 수정하면 어떨까요?

**Comment by Y00N** [comment]
**친하게 지내는 언니가 여기에 상점가가 새로 생긴다고 소개해줘서 왔거든요.** 어떤가요?

**Comment by jungin019** [comment]
'친하게 지내는 언니가 여기에 새로운
상점가가 생긴다고 소개해줘서 왔거든요. '
이렇게 고쳤습니다.
