### ISSUE TITLE
흥미롭군요... 친절히 시간을 내주셔서 정말 감사합니다. 메뉴 추천도요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1809]
![screenshot_2016-07-29-13-05-07](https://cloud.githubusercontent.com/assets/19295794/17364984/790f5298-59be-11e6-9a10-38cca9ff0237.png)

흥미롭군요...
친절히 시간을 내주셔서 정말 감사합니다.
메뉴 추천도요.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 많이 남아 그냥 넘기겠습니다.
