### ISSUE TITLE
[건의사항] 레이튼 : 뭐가 문제죠?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#181]
![image](https://cloud.githubusercontent.com/assets/19265176/15144609/87968d92-16eb-11e6-818f-0baa81a47247.png)

이 부분 역시 레이튼의 신사적인 캐릭터와 약간 안 맞는 것 같아서 올려봤습니다. 

심플하게 '무슨 문제가 있으시죠?' 정도로만 해도 좋을 것 같습니다.

**Comment by Porowl** [comment]
무슨 문제라도 있습니까?

아마 캐릭터를 안보고 원문만 보고 해석해서 이렇게 되지 않았나 싶습니다.

**Comment by jungin019** [comment]
무슨 문제라도 있으신가요? 가 좋을 것 같군요

**Comment by kaleidoscope531** [comment]
무슨 문제라도 있으신가요?가 어감상 좋긴 하네요. 
하지만 레이튼 교수가 저 질문을 하기 전에 파이아르가 한 말이
'아 나도 마침 그랬는데. 지금 당장 해결해야 할 일이 생겼단 말이지.'
입니다. 따라서 앞서 당장 해결해야 할 일이 생겼다고 했는데 '무슨 문제라도 있으신가요?'는 약간 문맥상 어색하지 않나 생각합니다.

**Comment by Porowl** [comment]
무슨 일이시죠?
무슨 일이라도...?

**Comment by jungin019** [comment]
무슨 문제라도...

**Comment by bombomS2** [comment]
무슨 일이시죠?
무슨 문제가 있나요?

**Comment by kaleidoscope531** [comment]
무슨 일이시죠? 가 좋아 보이네요. 앞에서 해결할 일이 생겼다고 말한 상황이니까요.
