### ISSUE TITLE
선생님, 여기 국물맛이 장난 아니에요! 식기전에 어서 드셔보세요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1810]
![screenshot_2016-07-29-13-05-12](https://cloud.githubusercontent.com/assets/19295794/17365016/b26e474c-59be-11e6-8db0-e9a465ac7a0b.png)

'국물맛이' 는 '국물 맛이' 로, '식기전에' 는 '식기 전에' 로 띄우는 것이 좋겠습니다.

**Comment by Y00N** [comment]
"장난 아니다"란 표현도 바른 표현이 아니라고 알고 있습니다.
**엄청나요!** 정도로 대체해보면 어떨까요? 아님 **끝내줘요!**...?

**Comment by Porowl** [comment]
솔직히 얼큰하다 를 쓰고 싶었지만.
끝내줘요 가 우리가 원하는 의미를 포함하고 있습니다.
그걸로 수정할게요.
