### ISSUE TITLE
지금은 괜찮습니다. 아까의 국물 덕분에 많이 먹어서 말이죠. 아직은 배가 고프지 않습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1811]
![screenshot_2016-07-29-13-05-21](https://cloud.githubusercontent.com/assets/19295794/17365041/d6ae5520-59be-11e6-92fc-8edae78631fd.png)

지금은 괜찮습니다.
아까 국물을 많이 먹어서 말이죠.
아직은 배가 고프지 않습니다.

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
원문이 'Nothing for the moment. We're still full from that wonderful soup you served us earlier.'인데 
지금은 괜찮습니다. 아까 먹은 맛있는 
국수 덕분에 아직은 배가 고프지 않네요.' 정도는 어떨까요

**Comment by Y00N** [comment]
**지금은 괜찮습니다.
덕분에 아까 든든하게 먹었더니
아직도 배가 꺼지질 않았네요.**
는 어때요?

**Comment by Porowl** [comment]
현로님의 의견을 따라 수정했습니다. =
