### ISSUE TITLE
그렇죠. 그런데, 저희는 진짜 일이 있습니다. 레이튼 씨를 보러 왔거든요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1818]
![screenshot_2016-07-29-13-06-54](https://cloud.githubusercontent.com/assets/19295794/17365280/378963a2-59c0-11e6-9407-4645a96dd520.png)

그렇죠.
그런데, 저희는 진짜 일이 있습니다.
레이튼 씨를 보러 왔거든요.

로 개행 수정하면 어떨까요?

**Comment by Porowl** [comment]
그건 그렇습니다.
그런데, 저희는 진짜 일이 있습니다. 
레이튼 씨를 보러 왔거든요.

**Comment by yhwon90** [comment]
그건 그렇습니다.
그런데 저희는 진짜로 볼일이 있어요.
레이튼 씨를 만나러 왔습니다.

**Comment by yhwon90** [comment]
그건 그렇습니다만 저희는 진짜로 볼일이 있어요.
레이튼 씨를 만나러 왔습니다.

**Comment by sumstraw** [comment]
그렇긴 하지만 저희는 다른 용무가 있습니다.
레이튼 씨를 만나러 왔어요.

**Comment by Y00N** [comment]
그렇죠. 하지만 저희도 레이튼 씨를 보러 왔습니다.

**Comment by Porowl** [comment]
<T>그렇죠. 하지만 저희도 분명한 용무가 
있습니다. 레이튼 씨를 만나러 왔거든요.
