### ISSUE TITLE
별 볼 일 없는 건 아닌 것 같군. 그치만, 그래도 들여보내줄 수 없어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1819]
![screenshot_2016-07-29-13-07-01](https://cloud.githubusercontent.com/assets/19295794/17365300/6c0738fc-59c0-11e6-805e-3fb3eddbf8d7.png)

'그치만,' 과 '그래도' 둘 중 하나는 생략해도 좋지 않나요?

의미가 비슷한 단어인데 굳이 두 번 들어갈 필요는 없다고 생각합니다.

**Comment by Porowl** [comment]
별 볼일 없는건 아니군. 그러나 
그렇다 하더라도 들여보내줄 수는 없어.

**Comment by Y00N** [comment]
그치만 자체가 잘못된 단어라 그치만을 빼면 되겠네요.

**Comment by Porowl** [comment]
별 볼일 없는건 아니군. 그런데
그렇다 하더라도 들여보내줄 수는 없어.

는 어떨까요

**Comment by Y00N** [comment]
별 볼 일 없진 않군.
그래도 들어갈 순 없어.

는 어때요

**Comment by yhwon90** [comment]
별 볼일 없진 않군
그렇다 하더라도 들여보내줄 순 없어

**Comment by sumstraw** [comment]
별 볼 일 없는 건 아닌가보군.
그렇다고 들여보내준다는 건 아니야.

**Comment by Porowl** [comment]
<T><A3/1>정말로 별일은 아니군.<W>
<A6/0>그렇다 하더라도 들여보내줄 순 없어.
