### ISSUE TITLE
그런고로, 너희가 여기에 들어갈 이유는 전혀 없어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1821]
![screenshot_2016-07-29-13-07-11](https://cloud.githubusercontent.com/assets/19295794/17365365/d0ffd714-59c0-11e6-8db5-918cf35c5522.png)

1행의 '너희가 여기에 들어갈' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by Porowl** [comment]
공간 안맞는데다가, 훤해서 좀 그렇네요.

들어갈 부터 넘겼습니다.
