### ISSUE TITLE
수수께"끼 70 - 슈퍼힌트

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1836]
![screenshot_2016-08-03-11-24-26](https://cloud.githubusercontent.com/assets/19295794/17369522/a1bed898-59d3-11e6-8aa3-de9b673424c4.png)

1~2 행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

그리고 말줄임표는 마침표 세 개를 사용하는 것이 좋겠습니다.

**Comment by jungin019** [comment]
전체적으로 문장을 수정해 
'10명중 8번째로 나이가 많은 아이는 
3번째로 어린 아이가 된다!

루크는 당연히 여자아이는 아니니까...'로 고쳤습니다.
