### ISSUE TITLE
정말 생각이 있는거야 없는거야...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1837]
![screenshot_2016-08-03-11-25-16](https://cloud.githubusercontent.com/assets/19295794/17369705/496425b2-59d4-11e6-9fa5-b304a027f58d.png)

'있는거야 없는거야...' 는 '있는 거야 없는 거야...' 로 띄우는 것이 좋겠습니다.

**Comment by Y00N** [comment]
**정말 생각이 있는 거야, 없는 거야....** 로 쓰는 게 좋다고 생각합니다.

**Comment by jungin019** [comment]
정말 생각이 있는 거야, 없는 거야...
로 수정
