### ISSUE TITLE
무슨 문제라도 있습니까?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1838]
![screenshot_2016-08-03-11-25-20](https://cloud.githubusercontent.com/assets/19295794/17369752/793b1fde-59d4-11e6-9f8e-0f48a65004d6.png)

루크의 말투와 어울리지 않는다고 생각합니다.

**Comment by Y00N** [comment]
너 문제 있냐 어떤?

**Comment by jungin019** [comment]
'무슨 문제라도 있나요?' 는 어떨까요

**Comment by Porowl** [comment]
아마 레이튼 대사인줄 알고 그랬나 보네요.

'무슨 문제라도 있나요?' 로 할게요.
