### ISSUE TITLE
이 담벼락좀 한번 봐! 완전히 낙서 투성이잖아!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1839]
![screenshot_2016-08-03-11-25-23](https://cloud.githubusercontent.com/assets/19295794/17369979/4f1ee9dc-59d5-11e6-9d9d-a1a7197fa5bc.png)

'담벼락좀 한번' 은 '담벼락 좀 한 번' 으로 띄우는 것이 좋겠습니다.

**Comment by Y00N** [comment]
**담벼락을 봐봐! 완전히 낙서 투성이야!**
라고 쓰는 건 어떨까요?

**Comment by jungin019** [comment]
'이 담벼락을 봐! 완전히 낙서 투성이잖아!'는 어떨까요

**Comment by Porowl** [comment]
이견이 없으면 제이님의 의견으로 갑니다.

**Comment by Y00N** [comment]
담벼락이 이게 뭐야! 완전히 낙서 투성이잖아!
는 또 어떨까요

**Comment by yhwon90** [comment]
융인님 의견에 한표요

**Comment by Porowl** [comment]
제이님 의견 수용합니다.
