### ISSUE TITLE
[건의사항] 레이튼 : 출구로 나가면 병원이 있는 것 같구나

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#184]
![image](https://cloud.githubusercontent.com/assets/19265176/15144754/62f2c00e-16ec-11e6-8336-1b16c2fd5252.png)

저 문장이 조금 어색한 것 같습니다. 

일단 제가 생각해본 것은 '지하철 출입구가 병원과 맞닿아 있구나.' 이 정도? 입니다. 
좋은 의견 기다리겠습니다.

**Comment by jungin019** [comment]
원문이 'Being right outside a railway station is ideal for a hospital.' 이군요. 
오역이네요. '근처에 지하철이 있다니, 교통편이 좋은 병원이구나' 정도로 고치는 것이 좋겠습니다.

**Comment by kaleidoscope531** [comment]
저도  '근처에 지하철이 있다니, 교통편이 좋은 병원이구나'에 한 표 던집니다.

**Comment by Porowl** [comment]
그렇게 수정하겠습니다.
일단 열어두겠습니다.

**Comment by Porowl** [comment]
지하철이 근처에 있다니, 교통편이 좋은 병원이구나.
가 어떤가요?

**Comment by kaleidoscope531** [comment]
지하철이 앞으로 나오는 것이 더 좋을 것 같네요.
