### ISSUE TITLE
물론 이걸 그린사람은 재미로 했겠지만 치워야 하는 사람은 나라고!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1840]
![screenshot_2016-08-03-11-25-26](https://cloud.githubusercontent.com/assets/19295794/17370071/9f5cfb1e-59d5-11e6-87d3-cf747abae673.png)

'그린사람은' 은 '그린 사람은' 으로 띄우는 것이 좋겠습니다.

**Comment by Y00N** [comment]
**물론 누군가 재미로 그려놨겠지만, 
내가 치워야 하잖아!**
라고 하면 별로일까요?

**Comment by jungin019** [comment]
+) 치워야 하는 을 지워야 하는 으로 바꾸는 게 어떨까요

**Comment by Y00N** [comment]
**물론 재미있다고 그린 사람도 있겠지만
치우려면 내가 고생해야 하잖아!**
어떤가여

**Comment by Porowl** [comment]
물론 누군가 재미로 그려놨겠지만,
지우려면 내가 고생해야 하잖아!

정도일까요.

**Comment by yhwon90** [comment]
물론 누군가는 재미로 그렸겠지만 지우느라 고생하는 사람은 바로 나라고!
