### ISSUE TITLE
흠. 완전히 말라 붙어버려서 긁어내긴 힘들겠는데요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1841]
![screenshot_2016-08-03-11-25-30](https://cloud.githubusercontent.com/assets/19295794/17370118/cca750ec-59d5-11e6-8054-305c549b4411.png)

흠. 완전히 말라버려서
긁어내긴 힘들겠는데요?

로 내용과 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
말라붙어버려서는 그냥 놔두는 게 어떨까 합니다. 
'흠. 완전히 말라붙어버려서
긁어내긴 힘들겠는데요?'

**Comment by Y00N** [comment]
보조용언이 두 개라 **말라붙어 버려서** 로 띄어 써야 할걸요?

**Comment by jungin019** [comment]
아 네 띄어쓰기는 그게 맞네요
