### ISSUE TITLE
그냥 덧칠해버려야 할 까봐.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1842]
![screenshot_2016-08-03-11-25-33](https://cloud.githubusercontent.com/assets/19295794/17370152/f3d3975c-59d5-11e6-84cf-e3cf078379e3.png)

그냥 덧칠이나 할까봐.

로 수정하면 어떨까요?

**Comment by jungin019** [comment]
'덧칠해야 할까봐'는 어떨까요

**Comment by Y00N** [comment]
그냥 덧칠해버릴까 봐.

**Comment by Porowl** [comment]
그냥 덧칠해버릴까 봐.

**Comment by yhwon90** [comment]
그냥 덧칠해버릴까 봐

**Comment by sumstraw** [comment]
첫 댓글이 좋다고 생각합니다

**Comment by Porowl** [comment]
다수결로 그냥 덧칠해버릴까 봐.
