### ISSUE TITLE
똑똑한데! 그리고 있지 방금 네 덕분에 정말 멋진 아이디어가 떠올랐어!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1845]
![screenshot_2016-08-03-11-26-33](https://cloud.githubusercontent.com/assets/19295794/17370338/a2852892-59d6-11e6-9cb5-6f554596ffd5.png)

똑똑한데!
그리고 있지 방금 네 덕분에
정말 멋진 아이디어가 떠올랐어!

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
