### ISSUE TITLE
내가 이 벽을 하얀색으로 칠해버리면 사실상 낙서해 달라고 광고하는 꼴이잖아?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1846]
![screenshot_2016-08-03-11-26-40](https://cloud.githubusercontent.com/assets/19295794/17370385/d6f9fdbe-59d6-11e6-8d45-7efe66a14ea8.png)

2행의 '광고하는' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 좀 이상해서 보류하겠습니다.
