### ISSUE TITLE
흰 벽도 좋지만, 낙서보단 벽화가 낫잖아?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1847]
![screenshot_2016-08-03-11-26-47](https://cloud.githubusercontent.com/assets/19295794/17370416/f45dfe82-59d6-11e6-8182-6972441c56dc.png)

1행의 '낙서보단 벽화가' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 비어 닫겠습니다.
