### ISSUE TITLE
나는 이 벽에 원대한 계획을 세워 뒀지. 난 여기에 정말 멋있는 걸 그려줄 사람을 구할 거야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1848]
![screenshot_2016-08-03-11-27-03](https://cloud.githubusercontent.com/assets/19295794/17370495/34ee5992-59d7-11e6-9742-de76c69a0ee7.png)

2행의 '뒀지.' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by Y00N** [comment]
**내가 원대한 계획을 세웠어.
이 벽에다 정말 멋진 그림을 그려줄 
사람을 구할 거야.**
로 바꾸면 어떨까요?

**Comment by jungin019** [comment]
음 현로님 말씀이 좋다고 생각하는데 원대한을 아예 '엄청난'정도로 바꾸는 건 어떨까요

**Comment by Porowl** [comment]
사람을 구할거야.

쪽으로.

원대한 -> 엄청난 찬성합니다.
