### ISSUE TITLE
아, 내가 내 소개를 안 했던가? 난 슬레이트야. 만나서 정말 반가워.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1849]
![screenshot_2016-08-03-11-27-08](https://cloud.githubusercontent.com/assets/19295794/17370587/8e85b68a-59d7-11e6-94a9-39b27bfe4de6.png)

1행의 '난' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by Y00N** [comment]
"내가 내"가 다소 깔끔하게 보이지 않아서요
**어라, 아직 내 소개를 안 했던가? 
난 슬레이트야. 만나서 정말 반가워.**
라고 하면 어떨까요?

**Comment by jungin019** [comment]
어라, 아직 내 소개를 안 했던가? 
난 슬레이트야. 만나서 정말 반가워.
로 수정
