### ISSUE TITLE
벽화가 잘 그려지고 있는 것 같네요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1850]
![screenshot_2016-08-03-11-27-20](https://cloud.githubusercontent.com/assets/19295794/17370609/ae4bf93e-59d7-11e6-9671-884ab8601468.png)

2행의 '것 같네요.' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by Y00N** [comment]
**벽화가 잘 되어가나 보네요.**
는 어떨까요?

**Comment by jungin019** [comment]
벽화가 잘 진행되나 보네요.(?)는 어떨까요 
뭔가 좋은 문장이 없으려나..

**Comment by Porowl** [comment]
벌써붙어 좋아 보이는데요?
