### ISSUE TITLE
순조롭게 진행되고 있지. 다음에 올 일 있으면 한 번 보라고!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1852]
![screenshot_2016-08-03-11-27-58](https://cloud.githubusercontent.com/assets/19295794/17370679/e815057a-59d7-11e6-849d-925b23aa6559.png)

1행의 '다음에' 는 다음 행으로 넘기는 게 어떨까요?

그리고 '순조롭게 진행되고 있지.' 는 문어체스러운 느낌이 있다고 생각하는데 다른 분들은 어떻게 생각하시나요?

**Comment by jungin019** [comment]
개인적으로 그다지 문어체스러운지 모르겠습니다...

**Comment by Porowl** [comment]
문제없어 보입니다.
