### ISSUE TITLE
그렇고말고! 완성되면 그야말로 걸작이 나올 것 같아!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1853]
![screenshot_2016-08-03-11-28-44](https://cloud.githubusercontent.com/assets/19295794/17370745/2b350efe-59d8-11e6-9683-e1cca633f11a.png)

그렇고 말고!
완성되면 그야말로 걸작이 나올 것 같아!

로 개행과 내용 수정하면 어떨까 하는데 공간이 되나요?

**Comment by Y00N** [comment]
**그렇고말고! 
완성되면 그야말로 걸작이 될 거야!**
로는 어떤가요?

**Comment by jungin019** [comment]
칸이 너무 남아 개행은 수정하지 않았고 나올 것 같아는 될 거야로 수정했습니다.
