### ISSUE TITLE
계획대로만 착착 진행된다면 네가 다음에 올 때 쯤에는 제법 모양새가 잡힐 것 같아!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1854]
![screenshot_2016-08-03-11-28-54](https://cloud.githubusercontent.com/assets/19295794/17370765/4d18538c-59d8-11e6-952b-21d21a2e74c9.png)

계획대로만 착착 진행된다면
네가 다음에 올 때 쯤에는
제법 모양새가 잡힐 것 같아!

로 개행 수정하면 어떨까요?

**Comment by Y00N** [comment]
**네가 다음에 올 때쯤에는
제법 모양새가 잡혔을 거야.**
는 어떤가요?

**Comment by jungin019** [comment]
'계획대로만 착착 진행된다면 
네가 다음에 올 때 쯤에는 
제법 모양새가 잡혔을 거야!' 로 수정
