### ISSUE TITLE
물론! 색칠이 끝나면 형형색색의 벽화가 정말 아름다울 거야! 시간은 조금 걸리겠지만.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1856]
![screenshot_2016-08-03-11-29-44](https://cloud.githubusercontent.com/assets/19295794/17370838/9aa71e26-59d8-11e6-8821-e773ec70c562.png)

물론! 색칠이 끝나면
형형색색의 벽화가 정말 아름다울 거야!
시간은 조금 걸리겠지만...

으로 개행과 내용 수정하면 어떤가요?

**Comment by Y00N** [comment]
**물론! 벽화를 형형색색으로 색칠하는 게 
끝나면 정말 아름다울 거야! 
시간은 다소 걸리겠지만.**
라고 바꾸어 보면 어떨까요?
