### ISSUE TITLE
[건의사항] 나탈리아 : 아. 하긴 312호 분이 팬이 좀 많더군요. 아닌가요?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#186]
![image](https://cloud.githubusercontent.com/assets/19265176/15144837/ea54605c-16ec-11e6-951c-3fe1313a73e0.png)

일단 원문은 이렇습니다. 

Oh. Old 312 has quite the fan club, doesn’t he?

'아. 312호 분이 팬이 좀 많군요. 안 그래요?' 이 편이 더 좋지 않을까요?

이 부분은 제가 괜한 소리를 한 것 같기도 하네요;;;

**Comment by jungin019** [comment]
'아. 312호 분이 팬이 꽤 많군요. 아닌가요?' 가 좋을지도 모르겠네요. 
현재형이니 앞부분은 말씀대로가 맞고, 뒤는 살짝 비꼬는(?) 느낌 같네요

**Comment by kaleidoscope531** [comment]
하긴 말씀 듣고 보니 안 그래요? 는 조금 비꼬는 감이 있는것도 같네요 ㅎㅎ

**Comment by STRIKE-F** [comment]
312호 분(의) 팬이 꽤 많군요, 아닌가요? 는 어떨까요. 의는 넣을지 말지 좀 고민되네요.

**Comment by Y00N** [comment]
312호 분은 팬이 꽤 많더군요.

**Comment by itstake** [comment]
312호 분은 찾아오는 사람이 많네요. 무슨 팬클럽이라도 있나?
