### ISSUE TITLE
감사합니다. 벽화가 잘 완성되기를 바랍니다. 완성되면 정말 아름다울 것 같네요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1860]
![screenshot_2016-08-03-11-31-01](https://cloud.githubusercontent.com/assets/19295794/17371015/4f460a0e-59d9-11e6-8cf6-f1f8c454a2ef.png)

감사합니다.
벽화가 잘 완성되었으면 좋겠군요.
그러면 정말 아름다울 것 같습니다.

로 내용과 개행 수정하면 어떨까요?

**Comment by Y00N** [comment]
**감사합니다.
벽화를 잘 마무리 지으시길 바랍니다.
틀림없이 아름다운 작품이 되겠지요.**

라고 하면 어떨까요?

**Comment by Porowl** [comment]
공간이 너무 비어보여서
<T><A1/2>감사합니다. 벽화를 잘 
마무리 지으시길 바랍니다.
틀림없이 아름다운 작품이 되겠지요.
으로 하겠습니다.
