### ISSUE TITLE
수수께끼 72 - 제목

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1866]
![screenshot_2016-08-03-11-33-45](https://cloud.githubusercontent.com/assets/19295794/17371259/2fb2476a-59da-11e6-93d1-17aeef16852d.png)

'탬플릿' 은 '템플릿' 으로 표시해야 하는 것이 아닌가요? 저도 헷갈리네요 ;_;

**Comment by jungin019** [comment]
굳이 말하면 템플릿이 맞을 것 같지만 제목을 바꾸는 게 어떨까하는 생각이 드는군요...
근데 템플릿을 뭐라고 해야할지는 좀 막막하네요...

**Comment by Porowl** [comment]
템플릿을 굳이 번역하면 서식 이라는 단어도 있지만요.
삼색 서식 은 이상하니까.
