### ISSUE TITLE
너희가 다음에 오면 아이들이 이 벽화에 색을 칠하고 있겠지. 정말 기대돼!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1868]
![screenshot_2016-08-03-11-34-47](https://cloud.githubusercontent.com/assets/19295794/17371332/6dd84062-59da-11e6-8d8d-fc9165d888a9.png)

너희가 다음에 오면
아이들이 이 벽화에 색을 칠하고 있겠지.
정말 기대돼!

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 비어 
'너희가 다음에 오면 아이들이 
이 벽화에 색을 칠하고 있겠지. 
정말 기대돼!'로 수정했습니다.
