### ISSUE TITLE
아이들요? 그림을 직접 그리시지 않는 건가요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1869]
![screenshot_2016-08-03-11-35-10](https://cloud.githubusercontent.com/assets/19295794/17371360/88928462-59da-11e6-8297-5c1d06d366ce.png)

1행의 '그림을 직접 그리시지 않는' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
