### ISSUE TITLE
맞아, 거의 다 했어, 그리고 아름답지. 런던 다른 곳에서 이런 벽화는 찾아볼 수가 없을껄?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1870]
![screenshot_2016-08-03-11-36-15](https://cloud.githubusercontent.com/assets/19295794/17371395/a7aa3a20-59da-11e6-9b3c-412e7f29015b.png)

쉼표와 쉼표 사이에 어구가 들어가는 것은 영어에서 사용하는 삽입구문의 느낌을 주는데 수정할 수는 없을까요?

그리고 '이런 벽화는 찾아볼' 은 다음 행으로 넘기는 게 어떨까요?

그리고 '없을껄?' 은 '없을걸?' 로 수정하는 것이 좋겠습니다.

**Comment by Y00N** [comment]
**맞아, 거의 다 했지. 아름답지 않아?
이런 벽화는 여기 말고 다른 곳에선
눈 씻고 찾아도 없을걸?**
어떤가요?

**Comment by jungin019** [comment]
'맞아, 거의 다 했지. 아름답지 않아?
아무리 눈 씻고 찾아봐도 런던에
이렇게 멋진 벽화는 또 없을걸?' 는 어떨까요

**Comment by Porowl** [comment]
조금 수정된 제이님 의견이 더 좋아 보입니다.
