### ISSUE TITLE
말 그대로 말야. 페인트를 얼마나 많이 날랐는데!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1871]
![screenshot_2016-08-03-11-36-38](https://cloud.githubusercontent.com/assets/19295794/17371468/e92cd3d6-59da-11e6-82ce-cdab3aa007eb.png)

1행의 '페인트를 얼마나 많이' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by Y00N** [comment]
**말 그대로, 내가 페인트를 얼마나 많이 날랐는데!**
어떤가요

**Comment by jungin019** [comment]
현로님 의견이 괜찮다고 생각하지만 이건 의견을 좀 더 들어봤으면 좋겠네요

**Comment by Porowl** [comment]
하지만 무거운 짐을 진건 나라고.

뒤에 오는거라

말 그대로 말야. 아니면 문자 그대로 말야.
가 더 적합하지 않을까요?
