### ISSUE TITLE
어떤 페인트 통 옆에는 이런 수수께끼가 붙어 있더라고. 한 번 볼래?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1872]
![screenshot_2016-08-03-11-36-44](https://cloud.githubusercontent.com/assets/19295794/17371499/0c9a7c60-59db-11e6-893d-ef766597add9.png)

어떤 페인트 통에는
이런 수수께끼가 붙어 있더라고.
한 번 볼래?

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
