### ISSUE TITLE
이 종은 매일 똑같은 시간에 울려요. 곧 익숙해질 거예요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1875]
![screenshot_2016-08-03-11-43-29](https://cloud.githubusercontent.com/assets/19295794/17371740/00d5959e-59dc-11e6-865d-8f59a595a021.png)

이 종은
매일 똑같은 시간에 울려요.
곧 익숙해질 거예요.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
곧 만 개행하겠습니다.
