### ISSUE TITLE
이 퍼즐은 조금 신중히 생각해야 하는 것 같더라고.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1876]
![screenshot_2016-08-03-11-44-02](https://cloud.githubusercontent.com/assets/19295794/17371795/316fac08-59dc-11e6-9a31-ce08a5aa12a0.png)

이 수수께끼는
조금 신중히 생각해야 하는 것 같더라고.

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
