### ISSUE TITLE
벽화 작업이 거의 끝나 가! 너네들도 머지않아 볼 수 있을거야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1878]
![screenshot_2016-08-03-16-02-48](https://cloud.githubusercontent.com/assets/19295794/17371890/9d583afc-59dc-11e6-86e2-4ce4a7ff329c.png)

벽화 작업이 거의 끝나 가!
너희들도 머지않아 볼 수 있을 거야.

로 개행과 내용 수정하면 어떨까요?

**Comment by Y00N** [comment]
**벽화 작업이도 이제 막바지야.
곧 완성된 모습을 보여줄게.**
어떤가요?
