### ISSUE TITLE
와, 멋진데요! 이건 그야말로 걸작이에요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1879]
![screenshot_2016-08-03-16-03-24](https://cloud.githubusercontent.com/assets/19295794/17371927/c26c1372-59dc-11e6-9bc5-2384021e254d.png)

1행의 '이건 그야말로' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by Y00N** [comment]
**와, 멋진데요! 그야말로 걸작이네요!**
어떤가요?

**Comment by jungin019** [comment]
와, 멋진데요! 그야말로 걸작이네요! 로 수정
