### ISSUE TITLE
고마워! 하지만 그건 내가 아니라 꼬마 화가들이 들어야 할 대사라고.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1880]
![screenshot_2016-08-03-16-03-27](https://cloud.githubusercontent.com/assets/19295794/17372551/45b6da4e-59df-11e6-8085-83516043fb49.png)

고마워!
하지만 그건 내가 아니라
꼬마 화가들이 들어야 할 대사라고.

로 개행 수정하는 건 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
