### ISSUE TITLE
하하! 고마워! 벽화가 발이 달려서 어디 도망가는 것은 아니니까 보고 싶을 때마다 한 번씩 찾아와.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1881]
![screenshot_2016-08-03-16-03-42](https://cloud.githubusercontent.com/assets/19295794/17372676/d842edb2-59df-11e6-968d-0b4bebf35fba.png)

2행의 '보고 싶을' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by Y00N** [comment]
벽화가 발이 달려서 어디 도망가는 것은 아니니까는 다소 중의적인 문장이라고 생각합니다.
"(벽화가 발이 달려서 어디 도망가는 것)은 아니니까"와 "벽화가 발이 달려서 (어디 도망가는 것은) 아니니까"로 말이죠. 
그러니
**하하, 고마워! 벽화에 발이 달린 것도 
아니고 어디 도망가진 않으니까, 
보고 싶으면 언제든지 찾아와.**
라고 대체해보면 어떨까요?
