### ISSUE TITLE
육각거탑의 주인을 만나러 갔는데 자리에 없대. 그 사람이 어디에 있는지 알아?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1882]
![screenshot_2016-08-03-16-04-10](https://cloud.githubusercontent.com/assets/19295794/17372787/3fe609b8-59e0-11e6-9734-eb713223133b.png)

육각거탑의 주인을 만나러 갔는데
자리에 없대.
그 사람이 어디에 있는지 알아?

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
가운데 줄은 너무 칸이 남아 알아 만 개행했습니다.
