### ISSUE TITLE
아마도... 근데 말 안 할래. 위험한 사람이라고. 그 사람이랑 얽히지 않는 게 좋을걸.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1883]
![screenshot_2016-08-03-16-04-17](https://cloud.githubusercontent.com/assets/19295794/17372927/e894d6e8-59e0-11e6-8e4d-48a544d2c1bf.png)

아마도... 근데 말 안 할래.
위험한 사람이라고.
그 사람이랑 얽히지 않는 게 좋을걸.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
'아마도... 근데 말 안 할래. 
위험한 사람이라고. 그 사람이랑 
얽히지 않는 게 좋을걸.' 로 개행 수정
