### ISSUE TITLE
자자, 우리에게 그 사람이 어디있는지 말해줘도 아무 일도 없을 거란다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1884]
![screenshot_2016-08-03-16-04-22](https://cloud.githubusercontent.com/assets/19295794/17373040/6b54de20-59e1-11e6-8957-63086dad5453.png)

자자, 우리에게 그 사람이
어디에 있는지 말해줘도
아무 일도 없을 거란다.

로 개행 수정하면 어떨까요?

**Comment by Y00N** [comment]
**자, 우리에게 그 사람이 어디있는지
말해준다고 나쁜 일이 벌어지진
않는단다.**
는 어떤가요?

**Comment by jungin019** [comment]
전 현로님 대사 괜찮은 것 같네요
