### ISSUE TITLE
정말 아무 일도 없진 않겠지만 ...제가 들은 걸 말씀드리긴 할게요. 그냥 소문일 뿐이지만요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1885]
![screenshot_2016-08-03-16-04-25](https://cloud.githubusercontent.com/assets/19295794/17373075/91ea9fb6-59e1-11e6-894c-871918ffa681.png)

정말 아무 일도 없지는 않겠지만...
제가 알고 있는 걸 말씀드릴게요.
그냥 소문일 뿐이지만요.

로 개행과 내용 수정하면 어떨까요?

**Comment by Y00N** [comment]
정말은 명사입니다. 부사인 정말로를 사용합시다.
**정말로 그럴 거라고 생각하진 않지만....
제가 들은 이야기를 말씀드릴게요.
그냥 소문일 뿐이지만요.**
어떤가요?
