### ISSUE TITLE
근데 정말 아셔야겠어요? 진심으로 얘기하는데, 이 사람하고 얽히면 곤란해질 수도 있다구요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1886]
![screenshot_2016-08-03-16-04-29](https://cloud.githubusercontent.com/assets/19295794/17373109/bb5593e2-59e1-11e6-8f23-7a6122d240e7.png)

1행의 '진심으로' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
'근데 정말 아셔야겠어요? 
진심으로 얘기하는데, 이 사람하고 
얽히면 곤란해질 수도 있다구요.' 로 수정
