### ISSUE TITLE
...사람들이 그러는데 그 자가 변장을 하고 마을을 돌아다닌대요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1887]
![screenshot_2016-08-03-16-04-34](https://cloud.githubusercontent.com/assets/19295794/17373402/fc296da2-59e2-11e6-858a-dfa73047c38b.png)

... 사람들이 그러는데
그 자가 변장을 하고
마을을 돌아다닌대요.

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
'... 사람들이 그러는데 그 자가 
변장을 하고 마을을 돌아다닌대요.'로 수정
