### ISSUE TITLE
코앞에 두고도 그 사람인지 모를 수도 있다는 거죠!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1888]
![screenshot_2016-08-03-16-04-38](https://cloud.githubusercontent.com/assets/19295794/17374640/8bec382a-59e8-11e6-8016-c737c3aece7f.png)

1행의 '그 사람인지 모를 수도' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by Y00N** [comment]
**코앞에 두고도 그 사람인지 아닌지
못 알아볼 수도 있다 이거죠!**
어떤가요?
