### ISSUE TITLE
죄송하지만 식사를 하러 온 게 아니라서요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1889]
![screenshot_2016-08-03-16-05-07](https://cloud.githubusercontent.com/assets/19295794/17374794/36cc9e1a-59e9-11e6-9471-829a26b9d920.png)

2행의 '아니라서요.' 는 1행 끝부분에 붙여 쓰면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
칸이 모자라 닫겠습니다.
