### ISSUE TITLE
[건의사항] 1번 동화책 : 수염이 있는 ()는 내가 들고 있는 물건을 힐끗 보면서,

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#189]
![image](https://cloud.githubusercontent.com/assets/19265176/15144986/e9e7874c-16ed-11e6-9461-7a6fdb1c3a10.png)

'수염이 있는 남자는 내가 들고 있는 물건을 힐끗 보면서,' 이 부분이 어색한 것 같습니다. 

'수염이 있는 남자는 내가 들고 있는 물건을 훑어보더니 말했습니다.' 로 하는 편이 좋지 않을까 생각합니다.

**Comment by jungin019** [comment]
음 원문이 glance at인데 이건 원래는 힐끗 보다 가 맞긴 합니다. 토의는 열어둘게요
