### ISSUE TITLE
게다가 이렇게 좁고 허름한 곳에서는 절대 형님을 못 찾을 걸. 고급 레스토랑이라면 모를까.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1891]
![screenshot_2016-08-03-16-05-48](https://cloud.githubusercontent.com/assets/19295794/17374967/f2581c86-59e9-11e6-8727-9b9425f8d2ba.png)

게다가 이렇게 좁고 허름한 곳에서는
절대 형님을 못 찾을걸.
고급 레스토랑이라면 또 모르지.

로 개행과 내용 수정하면 어떤가요?

**Comment by Y00N** [comment]
**게다가 이렇게 좁고 허름한 곳에서
형님을 찾을 수나 있겠냐?
고급 레스토랑이라면 또 몰라도.**

어떤가요?
