### ISSUE TITLE
이 흔들목마는 꽤 멋지구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1892]
![screenshot_2016-08-03-16-06-08](https://cloud.githubusercontent.com/assets/19295794/17375034/47e354f4-59ea-11e6-8436-bf885eed4327.png)

2행의 '멋지구나.' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by Y00N** [comment]
**꽤 멋진 흔들목마구나.** 라고 고치면 한 줄에 다 들어갈 것 같은데요.

**Comment by jungin019** [comment]
꽤 멋진 흔들목마구나.로 수정
