### ISSUE TITLE
예전에는 좋아했어요! 지금은 좀 더 컸으니까, 장난감 가지고 놀 만한 시간이 별로 없거든요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1894]
![screenshot_2016-08-03-16-06-42](https://cloud.githubusercontent.com/assets/19295794/17387636/758d7d08-5a30-11e6-90f2-f959123d144c.png)

예전에는 좋아했어요!
지금은 좀 더 컸으니까,
장난감 가지고 놀 만한 시간이 없거든요.

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
'예전에는 좋아했어요! 
지금은 좀 더 커서 장난감 가지고 
놀 만한 시간이 없거든요.' 로 수정
