### ISSUE TITLE
어떤 사람들은 백발이 사람을 기품있어 보이게 한다고 하지만 난 내 갈색 머리가 훨씬 좋았다네.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1897]
![screenshot_2016-07-13-00-29-34](https://cloud.githubusercontent.com/assets/19270364/17388836/c0778b98-5a39-11e6-8634-4052a8291a4c.png)

백발이 무엇한다라는 표현이 다소 영어투가 아닌가 싶어서요.

**기품이 있어 보이려면 머리카락이 희끗해야 한다고 말하는 사람들도 있던데, 난 갈색 머리일 때가 훨씬 좋았다네.**

라고 다듬어 보면 어떨까요...? (사실 다듬어도 별로라는 게 함정)

**Comment by Porowl** [comment]
백발을 가진 사람이 기폼있어 보인다고
말들 하지만, 난 갈색 머리일 때가
훨씬 더 좋았다네.

**Comment by Y00N** [comment]
머리칼이 허옇게 세고 그래야 
기품 있어 보인다고도 하던데
난 갈색 머리일 때가 훨씬 더 좋았네.

**Comment by sumstraw** [comment]
백발이 기품있어 보인다지만 난 내 머리가 갈색인게 더 좋았네.
