### ISSUE TITLE
분명 쉬플리가 이 레스토랑 안에서 기다리고 있을 거야.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1900]
![screenshot_2016-07-13-00-57-52](https://cloud.githubusercontent.com/assets/19270364/17389334/579810fc-5a3e-11e6-88fb-fefe29c1e18a.png)

분명 쉬플리가 레스토랑 안에서 기다릴 거야.
로도 충분하지 않을까요?

**Comment by jungin019** [comment]
'이쪽으로 오거라. 분명 쉬플리 씨가
이 레스토랑 안에서 기다리실 거야.'로 수정
