### ISSUE TITLE
그게 말이죠, 숫자가 그려진 접시들을 주문했는데, 공장에서 실수를 해서 말입니다...

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1901]
![screenshot_2016-07-13-00-59-35](https://cloud.githubusercontent.com/assets/19270364/17389395/cce94c0e-5a3e-11e6-965a-ab7d83edcab2.png)

그게 말이죠, 숫자가 그려진 접시들을 주문했는데, 공장에서 실수를 해서 말입니다...

그... "말이다."라는 표현이 사실 그리 권해지는 표현은 아닙니다.
가끔 한 두번 쓸 수는 있겠지만 이렇게 반복해서 사용되는 건 지양했으면 하네요.

**그게 말이죠, 숫자가 그려진 접시를 주문했는데 공장에서 실수를 해서요...
그게, 숫자가 그려진 접시를 주문했는데 공장에서 실수를 해서요...**
뭐 이런 식으로요

**Comment by jungin019** [comment]
'그게, 숫자가 그려진 접시를 주문했는데 
공장에서 실수를 해서요...' 로 수정
