### ISSUE TITLE
제 접시문제의 해결방안이라도 떠올리신 건가요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1902]
![screenshot_2016-07-13-01-01-15](https://cloud.githubusercontent.com/assets/19270364/17389519/0956986c-5a40-11e6-9fc2-6057d1abeeca.png)

**제 접시 문제의 해결방안이 떠오르셨어요?
제 접시 문제의 해결방안이라도 떠오르셨어요?
제 문제의 해결방안이 떠오르셨어요?**

라는 식으로 다듬길 권합니다.
개인적으로는 마지막이 제일 좋습니다.

**Comment by jungin019** [comment]
'제 문제의 해결방안이 떠오르셨나요?'는 어떨까요

**Comment by yhwon90** [comment]
제 접시 문제를 해결할 방법이 떠오르셨나요?

**Comment by Y00N** [comment]
정인님 의견도 좋습니다
일단 한 줄에 깔끔하게 들어가서 좋아요.
