### ISSUE TITLE
방금 장난감 자동차라고 했니? 잠깐만 보자... 역시 내 작품중 하나였구만.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1904]
![screenshot_2016-08-03-16-07-33](https://cloud.githubusercontent.com/assets/19295794/17389605/c4f21128-5a40-11e6-93d5-6d0711c069a4.png)

방금 장난감 자동차라고 했니?
잠깐만 보자...
역시 내 작품 중 하나였구만.

으로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
'방금 장난감 자동차라고 했니? 
잠깐만 보자... 역시 내 작품 중 
하나였구만.'로 수정
