### ISSUE TITLE
헤헤! 고맙다. 내 장난감 자동차를 그렇게 좋아하니 너에게 특별한 제안 하나만 하마.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1905]
![screenshot_2016-08-03-16-07-42](https://cloud.githubusercontent.com/assets/19295794/17389625/00a53402-5a41-11e6-868c-7c53272d18dc.png)

헤헤! 고맙다.
내 장난감 자동차를 그렇게 좋아하니
너에게 특별한 제안 하나만 하마.

로 개행 수정하면 어떨까요?

**Comment by Y00N** [comment]
"하나만"을 빼고 **너에게 특별한 제안을 하마** 는 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 개행은 하지 않고 너에게 특별한 제안을 하마 로 수정했습니다.
