### ISSUE TITLE
내 수수께끼를 푼다면 이 특별한 트랙을 공짜로 줄게. 어때?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1906]
![screenshot_2016-08-03-16-07-49](https://cloud.githubusercontent.com/assets/19295794/17389640/208d610e-5a41-11e6-8f44-90bbacf4ce8a.png)

1행의 '이 특별한 트랙을' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
