### ISSUE TITLE
수수께끼만 풀어도 특별한 트랙을 공짜로 준다고요? 오늘 정말 운이 좋은데요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1907]
![screenshot_2016-08-03-16-07-57](https://cloud.githubusercontent.com/assets/19295794/17389662/433bdabe-5a41-11e6-8e6a-6b9e6ba1bc4c.png)

수수께끼만 풀어도
특별한 트랙을 공짜로 준다고요?
오늘 정말 운이 좋은데요!

로 개행 수정하면 어떨까요?

그리고 두 번째 문장은 번역체스러운 느낌이 있다고 생각하는데 다른 분들은 어떻게 생각하시나요?

**Comment by jungin019** [comment]
칸이 남아 개행은 하지 않겠습니다.

**Comment by Porowl** [comment]
괜찮아 보입니다
