### ISSUE TITLE
내 이름은 체커야. 시간 날 때 한 번씩 찾아오려무나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1914]
![screenshot_2016-08-03-16-10-06](https://cloud.githubusercontent.com/assets/19295794/17389789/2e5a368a-5a42-11e6-9426-f7335518b688.png)

1행의 '시간 날 때 한 번씩' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
