### ISSUE TITLE
조사 메모 - 내가 어디로 갈 수 있었을까?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1915]
![screenshot_2016-08-03-16-10-18](https://cloud.githubusercontent.com/assets/19295794/17389803/48c33fa8-5a42-11e6-9b87-514bd8f671a9.png)

'페퍼의 국수 천국' 의 주인인 페퍼 씨는
미래의 내가 차이나타운 밖으로
나간 것 같다고 한다.
지금 그를 찾는 유일한 방법은
주변 사람들에게
미래의 내가 어디로 갔을지
짚이는 곳이 있나 물어보는 것 밖에는
없을 것 같다.

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
페퍼는 여자인데 굳이 씨로 바꿔야할까요

**Comment by Y00N** [comment]
저는 기왕이면 남자와 여자를 가르는 표현보단 좀 더 중성적인 단어를 쓰는 게 좀 더 성평등적이지 않나 생각하긴 합니다 :)

**Comment by jungin019** [comment]
음... 그건 맞는 말이긴 하지만요
