### ISSUE TITLE
여기 누군가는 바나나를 매우 좋아하지만 청소하는건 싫어하는  것 같구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1922]
![screenshot_2016-08-03-16-13-57](https://cloud.githubusercontent.com/assets/19295794/17389920/1aed6e2c-5a43-11e6-843e-f55d65f1ef24.png)

'청소하는 건' 을 풀어 쓰면 '청소하는 것은' 인데
'청소하는 것은 싫어하는 것' 이라는 표현에서는 '~것' 이 반복되어 이상하다고 생각합니다.
다른 분들은 어떻게 생각하시나요?

**Comment by Y00N** [comment]
**누군지는 모르겠지만 바나나를 먹을 땐 좋아하지만, 치울 땐 싫어하나 보구나.**
어때요?

**Comment by yhwon90** [comment]
여기 있는 누군가는 바나나를 매우 좋아하지만 청소는 싫어하나보다
바나나를 먹을 땐 좋아하지만 껍질을 치우기는 싫어하는 사람이 있나보다
바나나는 좋아하지만 청소를 싫어하는 누군가가 있는 모양이다
바나나를 좋아하는 누군가는 청소가 아주 싫은가보다
누군지는 모르겠지만 바나나는 아주 좋아하고 청소는 아주 싫어하는 듯 하구나

**Comment by Y00N** [comment]
누군지는 모르겠다만 바나나를 잘 먹어 놓고 왜 치우지는 않았는지 모르겠구나.

**Comment by Porowl** [comment]
<T><A1/1>바나나를 좋아하는건 둘째치고
왜 껍질을 치우지 않는지는 모르겠구나.
