### ISSUE TITLE
방금 바나나에 대한 다른 수수께끼가 떠올랐단다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1924]
![screenshot_2016-08-03-16-14-08](https://cloud.githubusercontent.com/assets/19295794/17389958/768f5ed4-5a43-11e6-99c0-536c0990edba.png)

1행의 '다른' 은 다음 행으로 넘겨도 좋겠습니다.

**Comment by Y00N** [comment]
**방금 바나나 수수께끼가 하나 더 생각났단다.
방금 바나나 수수께끼가 하나 더 떠올랐단다.**
라고 문장을 다듬어보면 어떨까요?

**Comment by yhwon90** [comment]
방금 바나나와 관련된 수수께끼가 ~는 어떤가요
바나나 수수께끼는 너무 줄인 느낌이라...

**Comment by Porowl** [comment]
<T><A2/2>방금 바나나 수수께끼가 
하나 더 떠올랐단다.

영문으로 도 banana puzzle이라 이걸로 합니다.
