### ISSUE TITLE
[맞춤법] 슈레이더 : 허셜, 전에 말했듯이, 자넨 분명 가장 명석한 학생이었지만, 자네에게 근접한 학생이 하나 더 있었다네

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#193]
![image](https://cloud.githubusercontent.com/assets/19265176/15145271/90d9cd8e-16ef-11e6-8589-5799968329c9.png)

반점을 너무 과용한 것 같습니다. 

허셜 전에 말했듯이 자넨 분명 가장 명석한 학생이었지만, 자네에 근접한 학생이 하나 더 있었다네. 

이 정도로 하면 어떨까요? 더불어 '자네에게'에서 게도 빼봤습니다.

**Comment by jungin019** [comment]
개인적으론 '허셜. 전에 말했듯이 자넨 분명 가장 명석한 학생이었지만, 자네에게 근접한 학생이 하나 더 있었다네.'가 좋을 것 같네요

**Comment by STRIKE-F** [comment]
위에 적힌 대로 고쳤습니다.
