### ISSUE TITLE
드,듣고 있어요!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1933]
![screenshot_2016-07-13-01-51-17](https://cloud.githubusercontent.com/assets/19270364/17390317/09b9513a-5a47-11e6-97d7-9229abc34da1.png)

**드, 듣고 있어요!**

근데 이 전까지만 해도 체르미를 개무시하더니 갑자기 왜 이렇게 저자세입니까?

**Comment by Porowl** [comment]
고, 고마워! 자, 잘 듣는 중이야
