### ISSUE TITLE
여긴 정말 동굴 같아요. 움직일 때마다 메아리가 치는 것 같아요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1934]
![screenshot_2016-07-13-01-53-01](https://cloud.githubusercontent.com/assets/19270364/17390344/3af255f8-5a47-11e6-8a62-21f27eecbf79.png)

움직일 때마다 메아리가...?
정확히 뭘 의도한 문장인가요?

**Comment by Porowl** [comment]
여긴 정말 동굴 같아서
발자국 소리마저 메아리치네요.

정도로 보시면 됩니다.

**Comment by jungin019** [comment]
차라리 찬님이 말씀하실 걸로 바꾸는 게 낫겠네요.
