### ISSUE TITLE
모든 사람은 인생의 시련을 직면하게 되지만, 진짜 사나이는 이 모든 것을 인내하는 사람이지.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1936]
![screenshot_2016-07-13-02-03-58](https://cloud.githubusercontent.com/assets/19270364/17390397/b4559720-5a47-11e6-9de7-bb6268ca3a42.png)

**인생의 시련은 누구에게나 닥쳐오지만, 진짜 사나이만이 그 모든 것을 인내하지.**
정도로 다듬어보면 어떨까요?
더 좋은 문장을 제안해주시면 몹시 감사하겠습니다.

**Comment by Porowl** [comment]
인생의 시련은 누구에게나 닥쳐오지만,
그 모든 것을 인내하는 사람은 진짜 사나이지.

**Comment by yhwon90** [comment]
인생의 시련은 누구에게나 닥쳐오지만,
그 모든 것을 인내하는 사람만이 진짜 사나이라고.

**Comment by Porowl** [comment]
'지'
