### ISSUE TITLE
인생이 꼭 장밋빛이라는 보장도 없지만 난 지금 같이 얘기할 사람도 없어.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1943]
![screenshot_2016-07-13-02-28-07](https://cloud.githubusercontent.com/assets/19270364/17391004/4fb56eac-5a4d-11e6-9f3b-88d32b4600d6.png)

이 문장... 의도하는 바가 뭔가요?

**Comment by Porowl** [comment]
Can you blame me? Life's not
exactly a rosy rose bed, and I
don't have anyone to talk to.

뭐 어쩌겠니? 인생이 장밋빛도 아니고, 
이젠 이야기를 나눌 사람도 없다고

**Comment by jungin019** [comment]
그러니까 '인생이 장미빛으로 아름답다는 보장은 없지만 이야기 나눌 사람조차 없는 건 좀 심하지 않은가'라는 뜻정도가 아닐까 생각합니다.

**Comment by Y00N** [comment]
내 인생이 순탄했던 적이 없지만
더욱이 지금은 같이 이야기할 사람도 없다구.

**Comment by sumstraw** [comment]
날 비난하지 말라고.늘 행복한 인생은 없다지만 하소연할 사람도 없는걸.
