### ISSUE TITLE
[맞춤법]? 루크 : 도대체 누가 이런 장난을 불쌍한 슈레이더 박사님에게 한 걸까요?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#195]
![image](https://cloud.githubusercontent.com/assets/19265176/15145488/d4f9df62-16f0-11e6-878a-767a6f3c7a04.png)

저 부분에서 '도대체 누가 이런 장난을 불쌍한 슈레이더 박사님에게 한 걸까요?' 이 부분이 어색한 것 같습니다.

'도대체 누가 (불쌍한) 슈레이더 박사님에게 이런 장난을 한 걸까요?'

로 중간 부분을 도치시키는 편이 더 자연스럽게 보이지 않나 싶습니다. 
불쌍한에 괄호를 쳐 놓은 것은 루크가 까마득한 연장자에게 불쌍한을 붙이는 것이 안 어울리는 것 같아서 쳐 놓았습니다. 
이에 관련하여 여러 의견 기다리겠습니다.

**Comment by jungin019** [comment]
불쌍한 뺐습니다
