### ISSUE TITLE
예리한 제 눈이 숨겨진 수수께끼를 찾았군요!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1955]
![screenshot_2016-07-13-02-57-27](https://cloud.githubusercontent.com/assets/19270364/17391493/7767c8ec-5a51-11e6-9250-c34c209cc48c.png)

제 예리한 두 눈으로 숨겨진 수수께끼를 찾아냈어요!

쪽은 어떨까요? 괜히 바꾸자고 하는 건가...

**Comment by jungin019** [comment]
전 말씀하신 문장 괜찮네요

**Comment by yhwon90** [comment]
저도 바꾸신게 좋아요
