### ISSUE TITLE
심심풀이용으로는 좀 버거운 문제인 것 같구나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1959]
![screenshot_2016-07-13-03-09-28](https://cloud.githubusercontent.com/assets/19270364/17391666/f9b2f3ca-5a52-11e6-92cd-a14f49c9f961.png)

**심심풀이용으로는 다소 버거운 문제였구나.**
쪽으로 다듬는 게 좋지 않을까요?

**Comment by Porowl** [comment]
Nothing like a bit of exercise
for the brain.

오역입니다.

뇌 운동 (에는 수수께끼) 만한게 따로 없더구나.
정도로 생각되는데, 굳이 바꾸지 않아도 될꺼에요.

**Comment by jungin019** [comment]
그래도 오역이니 찬님이 말씀하신 쪽으로 바꾸는 게 어떨까요

**Comment by yhwon90** [comment]
오역은 고칩시다

**Comment by sumstraw** [comment]
저도 고치는 쪽에 찬성합니다

**Comment by Porowl** [comment]
뇌 운동에는 수수께끼 만한게 따로 
없더구나.
