### ISSUE TITLE
[오역] 레이튼 : 잠깐 루크, 성급하게 결론을 내리지 말자꾸나. 이 의사선생님은 장난을 좋아하는 것처럼 보인단다.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#196]
![image](https://cloud.githubusercontent.com/assets/19265176/15145565/482491f8-16f1-11e6-9447-64cbdd186ba1.png)
![image](https://cloud.githubusercontent.com/assets/19265176/15145566/4c04ba00-16f1-11e6-8726-b827a7ee709e.png)
![image](https://cloud.githubusercontent.com/assets/19265176/15145568/4e4462c0-16f1-11e6-8fd6-34f75a0788ef.png)

일단 이 부분은 제 영어가 짧아서 오히려 제가 오역한 것일수도 있음을 미리 밝힙니다. 

일단 위의 말의 원문은 이렇습니다. 

Ho ho! Let’s not jump to any conclusions, Luke. The doctor is quite the prankster himself.

It’s entirely possible that he faked this whole X-ray and placed it here to surprise his visitors.

If that’s the case, he sure got me good. I was really worried for a moment there!

저는 저 문장을 다음의 뜻으로 해석하였습니다. 

Ho ho! Let’s not jump to any conclusions, Luke. The doctor is quite the prankster himself.
하하! 그렇게 성급하게 결론짓지 말자꾸나, 루크. 이 장난을 꾸민 것은 슈레이더 교수님 본인이란다.

It’s entirely possible that he faked this whole X-ray and placed it here to surprise his visitors.
교수님께서 가짜 엑스레이 사진을 만드셔서 방문하는 사람들을 놀래려고 가져다 놓았다고 보는 것이 타당하지 않겠니?

If that’s the case, he sure got me good. I was really worried for a moment there!
그렇다면 교수님께선 제대로 성공하셨네요. 전 정말 걱정했다고요.

저 'The doctor'가 칭하는게 박사님이라고 놓은거죠. 저는 이 편이 맞다고 생각합니다. 다른 분들은 어떻게 생각하시는지요.

**Comment by jungin019** [comment]
아 저도 보니 오역인 것 같군요. 

'하하! 그렇게 성급하게 결론짓지 말자꾸나, 루크. 슈레이더 박사님도 꽤나 장난을 좋아하신단다.

박사님께서 방문객들을 놀래키려고 가짜 엑스레이 사진을 만드셔서 가져다 놓으셨을 수도 있을 것 같구나. 

그게 사실이라면 박사님께 완전히 속았네요. 전 정말 걱정했다고요.'
로 번역하는 게 좋을 것 같습니다.

**Comment by kaleidoscope531** [comment]
저도 위의 번역이 좋을 것 같습니다.

**Comment by bombomS2** [comment]
교수님 말투 특성상 어쩔 수 없이 ~구나가 자주 나오는군요…
박사님께서 방문객들을 놀라게 하려고/놀래려고 가짜 엑스레이 사진을 만들어서 가져다 놓으셨을 수도 있잖니.
이 문장만 이렇게 고치면 중복을 피할 수 있지 않을까 합니다. 놀라게 하려고의 준말은 놀래려고이지만 잘 알려지지 않은 표현인지라 어느 것이 나을지 일단 둘 다 적어 보았습니다.

**Comment by kaleidoscope531** [comment]
확실히 전반적으로 어미의 중복이 많이 보이는데요. 이 참에 피할 수 있으면 피해두는 것이 더 좋을 것 같습니다. 
그리고 놀래려고 이 부분은 사실 어감만 따지면 놀래키려고가 좋은데 현재 비표준어라는 점이 마음에 걸리네요.

**Comment by Porowl** [comment]
'놀래키려고' 때문에 열어두겠습니다.

**Comment by bombomS2** [comment]
'놀래키려고'가 확실히 친숙하긴 한데… 표준어가 아닌지라 사용하기에는 무리가 있을 것 같습니다. 차라리 '놀라게 하려고'가 나을지도 모르겠네요. 놀래다를 쓰려면 '놀래 주기 위해'와 같은 표현으로 사용하는 게 더 자연스러울 듯해요.

**Comment by itstake** [comment]
논의 결과:
> 하하! 그렇게 성급하게 결론짓지 말자꾸나, 루크. 슈레이더 박사님도 꽤나 장난을 좋아하신단다.
> 
> 박사님께서 장난을 치려고 가짜 엑스레이 사진을 가져다 놓으시지는 않았을까?
> 
> 그게 사실이라면 박사님께 완전히 속았네요. 전 정말 걱정했다고요.
