### ISSUE TITLE
선생님, 이제 우리가 할 일은 다 끝난 것 같아요!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1961]
![screenshot_2016-07-13-03-14-12](https://cloud.githubusercontent.com/assets/19270364/17391823/372074fc-5a54-11e6-9e63-49c11f34cdd0.png)

선생님, 이제 우리가 할 일은 다 끝나지 않았어요?
라는 쪽이 자연스럽지 않을까요?

**Comment by Porowl** [comment]
루크가 그냥 단정짓고 나가자고 때쓰는(?) 부분이라 둬도 괜찮을 것 같은데, 열어둘게요.
