### ISSUE TITLE
그런 것 같구나. 하지만 이 엑스레이에는 아주 이상한 점이 몇 가지 있단다. 루크, 이것을 한 번 봐 보겠니?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#1965]
![screenshot_2016-07-13-03-21-59](https://cloud.githubusercontent.com/assets/19270364/17392212/d354095e-5a56-11e6-9e46-b90d9687741e.png)

**그렇구나. 하지만 이 엑스레이는 약간 이상한데. 루크, 여기를 한 번 보겠니?**

라고 다듬어보는 게 어떨까요?

**Comment by Porowl** [comment]
흠... 슈레이더 박사님의 것일까요?

뒤이고, I believe so 로 대답합니다.

그렇단다, 라던가 그래 보이는구나. 라던가

**Comment by jungin019** [comment]
전 앞 문장은 그런 것 같구나 로 그냥 놔두는 게 좋을 것 같네요

**Comment by yhwon90** [comment]
저도... 추측이기에 그런 것 같구나 알맞아보입니다

**Comment by Porowl** [comment]
그런 것 같다 라는 말이 안맞는 표현이라 하니,
그래 보이는구나 가 나을지도요.
