### ISSUE TITLE
[건의사항] 루크의 편지 : 이제 진도가 같으니, 런던을 망가트리고 있는 비밀을 알려드리겠습니다. 

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#197]
![image](https://cloud.githubusercontent.com/assets/19265176/15145687/02e69d88-16f2-11e6-9a1a-2b59726eec40.png)
![image](https://cloud.githubusercontent.com/assets/19265176/15145689/06e37c4e-16f2-11e6-82f0-4a7cb7a4ea93.png)

위의 문장에서 '이제 진도가 같으니'라는 말이 무슨 말을 의미하는지는 알겠는데, 조금 어색한 감이 있는것 같습니다. 

그런데 사실 저도 저걸 저 상황에 딱 맞게 바꿀 말은 잘 떠오르지 않네요. 

일단 생각해 본 것은

'이제 본격적으로 런던을 망가트리고 있는 비밀을 알려드리겠습니다.'
혹은
'본론으로 들어가서, 런던을 망가트리고 있는 비밀을 알려드리겠습니다.'

이정도일까요? 

그리고 다음에 이어서 나오는 '하지만, 이 이야기는 만나서 하는 것이 좋을 것 같습니다.' 이 부분에서 '하지만'을 '다만'으로 바꾸는 것은 어떨까요? 

여러분의 의견 기다리겠습니다.

**Comment by jungin019** [comment]
'이제 어느정도 이해하고 계신 것 같으니, 런던을 망가트리고 있는 비밀에 대해 설명해드리겠습니다.' 정도는 어떨까요?

다만은 고쳤습니다.

**Comment by kaleidoscope531** [comment]
'이제 어느정도 이해하고 계신 것 같으니,'에 한 표 던지겠습니다.

**Comment by bombomS2** [comment]
'이제 어느 정도 이해하고 계신 듯하니, 런던을 망가트리고 있는 비밀에 대해 말씀드리겠습니다.' 는 어떤가요?

**Comment by itstake** [comment]
편지인 만큼 이해하신 에서 이해하실 으로 바꾸는 것이 좋지 않을까요?

**Comment by bombomS2** [comment]
'이해하고 계실'로 바꾸는 게 좋을 것 같군요.

**Comment by bombomS2** [comment]
갑자기 생각나서 답니다. 이제 어느 정도 이해하셨을 듯하니, 는 어떨까요?

**Comment by kaleidoscope531** [comment]
그럼 최종적으로 
'이제 어느 정도 이해하셨을 듯하니, 런던을 망가트리고 있는 비밀에 대해 말씀드리겠습니다.' 가 되는 건가요?
처음 문장보다 매우 좋아진 것 같습니다.

**Comment by jungin019** [comment]
@Latteria 대사 수정
