### ISSUE TITLE
세상에, 저 작은 사람때문에 정말 놀랐어요! 저 짧은 다리로 저렇게나 빨리 달리 수 있다는 걸 누가 알았겠어요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1984]
![screenshot_2016-08-03-16-15-56](https://cloud.githubusercontent.com/assets/19295794/17394344/92002ad4-5a63-11e6-97ed-652a0a9c0c48.png)

일단 연필 표시 때문에 글씨가 가리고 개행이 좀 어색한데 문장을 줄여 볼 수는 없을까요?

**Comment by Porowl** [comment]
세상에, 저 작은 사람 때문에 정말
놀랐어. 어쩜 저렇게 짧은 다리로
빨리 달리지?
