### ISSUE TITLE
이 책들은 제가 읽을 수준은 아닌 것 같아요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1988]
![screenshot_2016-08-03-16-16-37](https://cloud.githubusercontent.com/assets/19295794/17394447/0e453242-5a64-11e6-822a-900e6956253a.png)

2행의 '수준은' 은 1행 끝부분에 붙여 쓰면 어떨까 하는데 공간이 되나요?

**Comment by Porowl** [comment]
안되네요...
