### ISSUE TITLE
선생님이 읽고 계신 책은 저도 이해할 수 있을 거 같아요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1989]
![screenshot_2016-08-03-16-16-45](https://cloud.githubusercontent.com/assets/19295794/17394461/2dde4ddc-5a64-11e6-8287-209bac7d355f.png)

2행의 '책은' 은 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by Porowl** [comment]
지금 선생님이 읽고 계신 
책은, 저도 읽을 수 있을
수준이네요.
