### ISSUE TITLE
[맞춤법] 무슨 소리예요, 경감님. 이 음식들 제게는 깨나, 와구와구, 마잇는걸요.(바튼)

### ISSUE THREAD

**Issue by bombomS2** [elfinlazz/lt3translation#199]
게임 초반 디미트리의 타임머신 발표 현장에서, 터치해 보세요 문구가 뜰 때 체르미 경감을 터치하면 나오는 바튼의 대사입니다.
'제게는 깨나' 에서 깨나라는 표현이 쓰였지만 이는 보조사로, 문장에서처럼 부사어로는 사용할 수 없습니다. 깨나 → 꽤나로 고치는 것이 적절한 것 같습니다.
그리고 '마잇는걸요'는 의도된 부분이지요...?

**Comment by jungin019** [comment]
이 부분은 바튼이 음식을 먹으면서 말하는 부분이라 맞춤법에 맞지 않는 것은 의도한 부분입니다 ㅎㅎ
