### ISSUE TITLE
그렇지만 어쩔 수 없어요, 플로라누나. 그 수 말고는 조사를 진전시킬 수 있는 방법이 없잖아요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1997]
![screenshot_2016-08-03-16-18-09](https://cloud.githubusercontent.com/assets/19295794/17394646/45df1d02-5a65-11e6-9a6c-2e7ba9264fca.png)

'플로라누나.' 는 '플로라 누나.' 로 띄우는 것이 좋겠습니다.

그리고 '~ 수' 라는 표현이 반복되는데 수정할 수는 없을까요?

**Comment by Porowl** [comment]
그렇지만 어쩔 수 없어요, 플로라 누나.
그 방법 말고는 조사를 진전시킬 수
있는 방법이 없잖아요.

**Comment by vbn2523** [comment]
그러면 '방법' 이라는 표현이 반복되는걸요...

**Comment by yhwon90** [comment]
그렇지만 어쩔 수 없어요, 플로라 누나.
그 방법 말고는 조사를 진전시킬 수가 없잖아요.
그 수 말고는 조사를 진전시킬 방법이 없잖아요.
