### ISSUE TITLE
그냥 몇몇 사람은 낯선 사람과 얘기를 나누는 것을 별로 안 좋아한다는 것을 말해주려던 것 뿐야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#1998]
![screenshot_2016-08-03-16-18-14](https://cloud.githubusercontent.com/assets/19295794/17394682/702c587c-5a65-11e6-8e18-9cdfb50bec35.png)

'~것' 이라는 표현과 '~ 을(를)' 이라는 표현이 반복되는데 수정할 수는 없을까요?

**Comment by Y00N** [comment]
**그냥 어떤 사람들은 낯선 사람과 이야기하기를 좋아하지 않는다고 말해주려던 것 뿐이야.**
어떤가요?
