### ISSUE TITLE
- 도 널 정말 좋아하는 것 같은데, 안 그래?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2012]
![screenshot_2016-08-03-16-27-00](https://cloud.githubusercontent.com/assets/19295794/17395137/d38bacb8-5a67-11e6-8c27-25e46b7c599c.png)

2행의 '것 같은데,' 는 1행 끝부분에 붙여 쓰는 게 어떨까요?

**Comment by Porowl** [comment]
앵무새 이름이 길 경우를 고려해 남겨둔 공간입니다.
