### ISSUE TITLE
... -, 여긴 그런 말을 할 곳은 아니라고.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2013]
![screenshot_2016-08-03-16-27-07](https://cloud.githubusercontent.com/assets/19295794/17395158/fd0792d2-5a67-11e6-97f6-4daa89bd9575.png)

1~2 행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by Porowl** [comment]
앵무새 이름이 길 경우를 고려해 남겨둔 공간입니다.
