### ISSUE TITLE
자동차 미니게임 04 사막탐험

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2028]
![screenshot_2016-07-13-07-02-33](https://cloud.githubusercontent.com/assets/19270364/17396267/94c7afbc-5a6d-11e6-8b3a-f4c12a40c67d.png)

아마 이 것만 캐릭터의 특성에 맞게 작성되지 않은 것 같은데요
마우이 말투로 다시 써야하지 않을까요?

**Comment by jungin019** [comment]
아... 이게 원래 말투가 어느정도 반영되어 있었는데 처음에 줄이 4줄로 제한이라 좀 줄여서 이렇게 됐습니다. 
근데 사실 원문도 첫문장하고 마지막 문장 빼고는 그냥 보통 문장이에요 
'Oh, nyet, I'm lost again, and this time, in the desert! I've got to get to town for some agua before
I dry up like a prune... But how? Oh, bitte, amigo-kun! Help me!'

**Comment by Porowl** [comment]
이런, 또 길을 잃었습니다. 이번 사막 
한가운데라니! 건포도 처럼 말라 버리기
전 마을로 돌아가 물 마십니다. 하지만...
어떻게? 오, 제발, 도와줘!
