### ISSUE TITLE
확실히 이상한 기분이 드는 건 부정할 수 없겠구나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2030]
![screenshot_2016-07-13-07-14-17](https://cloud.githubusercontent.com/assets/19270364/17396658/5cd053dc-5a6f-11e6-8cb3-3e20d38e8f80.png)

**확실히 이상한 기분이 드는구나.**
**아무래도 이상한 기분이 자꾸만 드는구나.**
로도 충분한 문장으로 보이는데요...

**Comment by Porowl** [comment]
확실히 긴장할 만한 상황이란 건 
인정해야겠구나.

라고 고쳐저/더빙되어 있습니다.
