### ISSUE TITLE
게다가 매번 외식할만큼 돈을 벌 수 있는 것도 아니라고!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2033]
![screenshot_2016-08-03-16-29-37](https://cloud.githubusercontent.com/assets/19295794/17440535/f743bc8a-5b67-11e6-8382-370aab9e88c3.png)

게다가 외식을 매번 할 만큼
돈을 버는 것도 아니라고!

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
전 내용은 그냥 놔두는 게 나을 것 같네요

**Comment by yhwon90** [comment]
저도 원문 내용이 더 좋습니다
