### ISSUE TITLE
죄송해요, 선생님. 분위기가 엄청나게 안 좋아지기 시작해서요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2036]
![screenshot_2016-08-03-16-30-19](https://cloud.githubusercontent.com/assets/19295794/17440699/a3484564-5b68-11e6-8a0f-e9a7cfa16a7a.png)

1행의 '분위기가 엄청나게' 는 다음 행으로 넘기면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
