### ISSUE TITLE
오호호호. 이런이런. 아무래도 오해가 좀 있는 모양이구먼.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2038]
![screenshot_2016-08-03-16-31-07](https://cloud.githubusercontent.com/assets/19295794/17440844/56b88730-5b69-11e6-9e4a-2149d1b3e3c6.png)

1행의 '아무래도 오해가 좀' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
