### ISSUE TITLE
그렇게 하겠습니다. 도움을 주셔서 감사합니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2041]
![screenshot_2016-08-03-16-32-25](https://cloud.githubusercontent.com/assets/19295794/17441054/554f207e-5b6a-11e6-8ea5-6726d9f9469b.png)

1행의 '도움을 주셔서' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
