### ISSUE TITLE
잠깐만 기다리게! 요즘 젊은이들은 너무 급하다니까. 자, 이걸 가져가게.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2042]
![screenshot_2016-08-03-16-32-30](https://cloud.githubusercontent.com/assets/19295794/17441108/8ad84090-5b6a-11e6-959f-4ac0cc4e840b.png)

잠깐만 기다리게!
요즘 젊은이들은 너무 급하다니까.
자, 이걸 가져가게.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
