### ISSUE TITLE
휴식을 취하기에 정말 좋은 곳 같군요. 여유가 된다면 꼭 한 번 들러 보겠습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2044]
![screenshot_2016-08-03-16-33-13](https://cloud.githubusercontent.com/assets/19295794/17441187/d3ce2b84-5b6a-11e6-8465-5e6f40f19205.png)

휴식을 취하기에 정말 좋은 곳 같군요.
여유가 된다면 꼭 한 번 들러 보겠습니다.

로 개행 수정하면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
칸이 조금 모자라 보겠습니다는 개행했습니다.
