### ISSUE TITLE
죄송합니다, 저흰 그저 바지와 신발이 젖어 있다고 말하려던 것 뿐인...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2047]
![screenshot_2016-08-03-16-36-51](https://cloud.githubusercontent.com/assets/19295794/17441315/7504a762-5b6b-11e6-9a1f-3cd26594189b.png)

죄송합니다,
저흰 그저 바지와 신발이 젖어 있다고
말하려던 것 뿐인...

으로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 
'죄송합니다, 저흰 그저 바지와 신발이 
젖어 있다고 말하려던 것 뿐인...'로 수정했습니다.
