### ISSUE TITLE
내 바지가 젖은 건 지금 나한테는 하나도 중요하지 않아.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2048]
![screenshot_2016-08-03-16-36-58](https://cloud.githubusercontent.com/assets/19295794/17441535/7080b04a-5b6c-11e6-9a18-b1f8374f34a0.png)

1행의 '지금 나한테는' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
