### ISSUE TITLE
아, 교수님이시군요. 다행히도 이번엔 오시는 걸 보아서 그런지 깜짝 놀라진 않았네요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2052]
![screenshot_2016-08-03-16-39-42](https://cloud.githubusercontent.com/assets/19295794/17441886/20d16196-5b6e-11e6-8766-2db39936b4ed.png)

아, 교수님이시군요.
다행이도 이번엔 오시는 걸 보아서 그런지
깜짝 놀라진 않았네요.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
