### ISSUE TITLE
템스 강 주변을 조사해 보는 건 어떻겠나?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2061]
![screenshot_2016-08-03-16-43-04](https://cloud.githubusercontent.com/assets/19295794/17442606/6f20f2aa-5b71-11e6-83c9-a830b377f9ff.png)

1~2행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
칸이 안 되어 닫겠습니다.
