### ISSUE TITLE
누군가가 듣게 된다면 큰 문제가 생길 수도 있다고. 난 그런 일에 연루되고 싶지 않아!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2065]
![screenshot_2016-08-03-16-43-41](https://cloud.githubusercontent.com/assets/19295794/17442800/96b74412-5b72-11e6-8199-d9b444ab4b8c.png)

누군가가 듣게 된다면
큰 문제가 생길 수도 있다고.
난 그런 일에 연루되고 싶지 않아!

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 남아 그냥 닫겠습니다.
