### ISSUE TITLE
...솔직히 말하면 너무 작고 구슬같이 반짝거려서 모르겠어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2068]
![screenshot_2016-08-03-16-44-51](https://cloud.githubusercontent.com/assets/19295794/17443161/0b484410-5b74-11e6-84fe-761dab80fc7d.png)

... 솔직히 말하면 
너무 작고 구슬같이 반짝거려서 모르겠어.

로 개행 수정하면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
