### ISSUE TITLE
거의 다 왔어요! 와, 여기서 보니 템스 강 정말 멋있는걸요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2071]
![screenshot_2016-08-03-16-45-34](https://cloud.githubusercontent.com/assets/19295794/17443323/0266d3c4-5b75-11e6-9baa-026b3e98c375.png)

1행의 '와, 여기서 보니 템스 강' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 남아 
'거의 다 왔어요! 와, 여기서 보니 
템스 강 정말 멋있는걸요.' 로 수정하겠습니다.
