### ISSUE TITLE
이 계단이 강가 쪽으로 내려가는 계단이에요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2072]
![screenshot_2016-08-03-16-45-57](https://cloud.githubusercontent.com/assets/19295794/17443358/383d6bc0-5b75-11e6-914d-0818c070de94.png)

이 계단으로 내려가면
강 쪽으로 갈 수 있어요.

로 수정하면 어떨까요?

**Comment by yhwon90** [comment]
이 계단을 내려가면
강가로 or 강으로
갈 수 있어요
