### ISSUE TITLE
가까이서 보니까 강이 생각했던 것보다 많이 더럽네요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2075]
![screenshot_2016-08-03-16-52-59](https://cloud.githubusercontent.com/assets/19295794/17443537/1aa0b8fa-5b76-11e6-996e-871ebb5fefce.png)

가까이서 보니까
강이 생각했던 것보다
많이 더럽네요.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
현재 
'가까이서 보니까 강이 
생각보다 많이 더럽네요.'로 되어 있습니다.
