### ISSUE TITLE
루돌프와의 대화로 육각거탑의 주인이 대부분의 시간을 강 근처에서 지낸다는 것을 알게 된다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2081]
![screenshot_2016-08-04-18-18-03](https://cloud.githubusercontent.com/assets/19295794/17443873/fbf4d86c-5b77-11e6-833c-bd8ed65f53a6.png)

루돌프와의 대화로
육각거탑의 주인이 대부분의 시간을
강 근처에서 지낸다는 것을 알게 된다.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
