### ISSUE TITLE
그 연구 시설은 지구에서 가장 절망적인 곳이더라고.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2086]
![screenshot_2016-08-04-18-21-47](https://cloud.githubusercontent.com/assets/19295794/17444248/eaaa01ca-5b79-11e6-8f2c-c226c98b7eaa.png)

1행의 '지구에서 가장 절망적인' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 많이 남아 닫겠습니다.
