### ISSUE TITLE
그 사람들이 가장 좋아하는 실험 중 하나를 말하자면 말야...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2090]
![screenshot_2016-08-04-18-22-16](https://cloud.githubusercontent.com/assets/19295794/17444350/7560ccb8-5b7a-11e6-8110-6c9f3c51d5a1.png)

2행의 '중 하나를' 을 1행 끝부분에 붙여 쓰면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
칸이 모자라 닫겠습니다.
