### ISSUE TITLE
정신을 차리니, 난 다른 방에 있더라고! 대체 뭘 하려던 건지 난 아직도 모르겠어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2092]
![screenshot_2016-08-04-18-22-24](https://cloud.githubusercontent.com/assets/19295794/17444406/c0e3d766-5b7a-11e6-9c8f-f28c92efb7b5.png)

3행의 '모르겠어.' 는 2행 끝부분에 붙여 쓰면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
칸이 모자라 닫겠습니다.
