### ISSUE TITLE
실험체 3호의 끔찍한 이야기 들으셨어요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2093]
![screenshot_2016-08-04-18-22-33](https://cloud.githubusercontent.com/assets/19295794/17444457/fe263736-5b7a-11e6-94d5-2e70d58015d5.png)

2행의 '들으셨어요?' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by jungin019** [comment]
칸이 모자라 닫겠습니다.
