### ISSUE TITLE
좋은 일이 생길 거란 희망은 빨리 버리면 버릴수록 좋아.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2096]
![screenshot_2016-08-04-18-22-57](https://cloud.githubusercontent.com/assets/19295794/17444544/79e0fd5c-5b7b-11e6-8d89-7ff518c601b0.png)

이 문장에서 실험체 3호는 '버린다' 라는 행위보다는 '빨리' 라는 표현을 강조하고 싶은 것 같은데,

좋은 일이 생길 거란 희망을 버리는 건
빠르면 빠를수록 좋아.

정도로 수정하면 어떨까 했는데, 이러면 '~거' 라는 표현이 반복됩니다.

다른 분들 생각은 어떤가요?

**Comment by yhwon90** [comment]
좋은 일이 생긴다는 희망을 버리는 건
이건 어떤가요?

**Comment by Y00N** [comment]
좋은 일이 생긴다는 희망 따위는 
후딱 버려.

**Comment by jungin019** [comment]
실험체 3호 음성이라 닫겠습니다.
