### ISSUE TITLE
도대체 그건 무슨 태도예요? 이젠 자유롭잖아요. 아직 남은 인생이 많이 있어요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2097]
![screenshot_2016-08-04-18-23-03](https://cloud.githubusercontent.com/assets/19295794/17444593/ca9fa9fa-5b7b-11e6-9828-2b66dada5f37.png)

도대체 그건 무슨 태도예요?
이젠 자유롭잖아요.
아직 인생이 많이 남았어요!

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 남아 둘째 줄은 개행하지 않았습니다.
