### ISSUE TITLE
반가워, 실험체 1호. 부리는 계속 깨끗이 하고 있지?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2103]
![screenshot_2016-08-04-18-25-43](https://cloud.githubusercontent.com/assets/19295794/17445223/d64c0138-5b7e-11e6-8978-21efed00364d.png)

1행의 '부리는 계속' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
