### ISSUE TITLE
아, 나? 난 비컨이야. 이 강에 있는 등대의 등대지기지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2104]
![screenshot_2016-08-04-18-26-18](https://cloud.githubusercontent.com/assets/19295794/17445283/1f66d78a-5b7f-11e6-8560-1150a418c636.png)

1행의 '이 강에 있는' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
