### ISSUE TITLE
난 도저히 풀 수 없는 수수께끼가 있거든. 이걸 풀려고 밤새 한숨도 못 잤어. 잠 좀 자고 싶은데 말야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2105]
![screenshot_2016-08-04-18-26-30](https://cloud.githubusercontent.com/assets/19295794/17445338/6c66d670-5b7f-11e6-8771-354b233374da.png)

2행의 '있거든.' 은 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by jungin019** [comment]
칸이 모자라서 붙이지 않았고 못 잤어는 개행했습니다.
