### ISSUE TITLE
그저, 등대지기로써 등대를 관리하지 않고 이곳에서 뭘 하고 계신지 궁금하던 차 입니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2109]
![screenshot_2016-08-04-18-28-42](https://cloud.githubusercontent.com/assets/19295794/17445682/e1dc5898-5b80-11e6-8e8c-205124f26316.png)

그저, 등대지기로서 등대를 관리하지 않고
이곳에서 뭘 하고 계신지
궁금하던 차입니다.

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 모자라 않고는 붙여쓰지 않고 궁금하던은 개행했습니다.
