### ISSUE TITLE
그런데 어느 날 내 고용인이 들인 자동 조종 시스템이 내 자리를 차지하더군.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2111]
![screenshot_2016-08-04-18-28-56](https://cloud.githubusercontent.com/assets/19295794/17445820/73cf80a4-5b81-11e6-87d8-88d266307848.png)

그런데 어느 날
내 고용인이 들인 자동 조종 시스템이
내 자리를 차지하더군.

으로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
