### ISSUE TITLE
비컨의 이야기는 확실히 의심스러운데요, 선생님.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2112]
![screenshot_2016-08-04-18-29-36](https://cloud.githubusercontent.com/assets/19295794/17445902/d128bf90-5b81-11e6-90eb-5a0df6551bf2.png)

1행의 '확실히' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 많이 남아 닫겠습니다.
