### ISSUE TITLE
어쩔 수 없구나. 다음에 다시 한 번 들려 보기로 하고, 지금은 가던 길을 계속 가도록 하자.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2114]
![screenshot_2016-08-04-18-30-06](https://cloud.githubusercontent.com/assets/19295794/17446008/49614eaa-5b82-11e6-891f-ffc4142fde20.png)

어쩔 수 없구나.
다음에 다시 한 번 들려 보기로 하고,
지금은 가던 길을 계속 가도록 하자.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
