### ISSUE TITLE
런던에 괜히 온 것 같아. 정말 도버를 떠나는 게 아니었어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2115]
![screenshot_2016-08-04-18-30-19](https://cloud.githubusercontent.com/assets/19295794/17446062/88e1620e-5b82-11e6-9f47-d052030ee3a5.png)

1행의 '정말' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
그냥 정말을 뺐습니다.
