### ISSUE TITLE
약속은 약속이니까요. 아까 오신 손님은... 좀 별난 분이라고 말할 수 있겠네요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2122]
![screenshot_2016-08-04-18-36-10](https://cloud.githubusercontent.com/assets/19295794/17454264/2e617ab0-5bca-11e6-84b6-9bc438ce9b14.png)

약속은 약속이니까요.
아까 오신 손님은...
좀 별난 분이라고 말할 수 있겠네요.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
'약속은 약속이니까요. 
아까 오신 손님은... 좀 별난 분이라고 
말할 수 있겠네요.' 로 수정
