### ISSUE TITLE
그렇다는건, 변장하고 다니신다는 거에요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2123]
![screenshot_2016-08-04-18-36-18](https://cloud.githubusercontent.com/assets/19295794/17454275/6af8064c-5bca-11e6-9357-a3166183e4d5.png)

'그렇다는건,' 은 '그렇다는 건,' 으로 띄워야 하지 않을까 싶은데 공간이 모자랄 것 같네요.

다른 분들은 어떻게 생각하시나요?

**Comment by jungin019** [comment]
'그렇다는 건, 변장하고 다니신다는 
거예요?' 로 수정
