### ISSUE TITLE
그리고 그 분은 차이나타운에서 오셨구요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2125]
![screenshot_2016-08-04-18-36-28](https://cloud.githubusercontent.com/assets/19295794/17454284/c9a6136e-5bca-11e6-9efb-5f425f03f554.png)

2행의 '오셨구요?' 는 1행 끝부분에 붙여 쓰면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
공간이 안 되어 닫겠습니다.
