### ISSUE TITLE
오, 로그. 이번엔 나쁜남자 컨셉이야? 내가 기절하는 모습을 보구 싶구나?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2149]
![screenshot_2016-08-04-18-49-14](https://cloud.githubusercontent.com/assets/19295794/17455052/af414ac6-5be7-11e6-97af-09183bf52755.png)

'나쁜남자' 는 '나쁜 남자' 로 띄우고, '보구' 는 '보고' 로 수정하면 어떨까요?

**Comment by Porowl** [comment]
보구는 일부러 남겨두겠습니다.
