### ISSUE TITLE
잠시 먹으려고 쉬고 있... 그러니까 낮에 있었던 사건에 대한 생각을 정리하기 위해 잠시 쉬러 온거야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2173]
![screenshot_2016-08-04-21-00-42](https://cloud.githubusercontent.com/assets/19295794/17456459/fa6b1196-5c12-11e6-93dd-edfbbf775fbd.png)

잠시 먹으려고 쉬고 있...
그러니까 낮에 있었던 사건에 대한 생각을
정리하기 위해 잠시 쉬러 온거야.

로 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 안 되어 
'잠시 먹으려고 쉬고 있... 그러니까 
낮에 있었던 사건에 대한 생각을 
정리하기 위해 잠시 쉬러 온 겁니다.'로 수정
