### ISSUE TITLE
수수께끼 145- 힌트 2

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2178]
![screenshot_2016-08-04-21-03-51](https://cloud.githubusercontent.com/assets/19295794/17456502/80c3465e-5c14-11e6-8449-a42a2d19adf6.png)

어떤 카드는 숫자를 두 개 표현할 수 있다!

로 내용과 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
'어떤 카드는 숫자 두 개를 표현할 수 있다!'로 수정
