### ISSUE TITLE
어쩐지 오면 안되는 곳에 온 것 같은 기분이네요, 교수님.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#218]
![kakaotalk_20160511_005416062](https://cloud.githubusercontent.com/assets/19270364/15153644/f9c76db8-1714-11e6-9152-63c41f5d73c9.jpg)

게임을 플레이하다보니 '~것 같다' 라는 표현이 많이 쓰이는 걸로 보입니다.
위 문장은 '어쩐지 오면 안되는 곳에 온 기분이네요, 교수님.' 정도가 어떨까요?

**Comment by jungin019** [comment]
저도 좀 많이 쓰는 것 같다고 느끼긴 합니다. 
해당 부분은 음성이 포함된 부분이므로 더빙팀이 생각해보는 편이 좋겠네요 
@Latteria

**Comment by bombomS2** [comment]
제 생각에도 문장은 '어쩐지 오면 안 되는 곳에 온 기분이네요, 교수님.'이 좋을 것 같아요. 더빙하시는 분이 괜찮다면 바꾸는 편이 좋겠습니다.

**Comment by itstake** [comment]
그리고 교수님이 아니고 선생밈이 되어야죠

**Comment by Latteria** [comment]
* '어쩐지 오면 안 되는 곳에 온 기분이네요, 선생님. 으로 채택하겠습니다.
