### ISSUE TITLE
네게는 아직 배울게 많지만, 배우는 동안 네 개성을 잃어버리지 않도록 조심해. 사람들을 보고 배우다간 그러기 쉽상이야.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2187]
![screenshot_2016-07-13-07-19-23](https://cloud.githubusercontent.com/assets/19270364/17460983/520bfe98-5cb7-11e6-9de3-fb1bdcb52869.png)

**넌 앞으로도 많이 배워야해. 그 과정에서 네 개성을 잃지 않도록 조심하렴.
타인을 따라하다간 개성을 잃기 십상이야.**

오자도 좀 고치고, 저 정도로 문장을 좀 손질해보면 어떨까요?

**Comment by jungin019** [comment]
괜찮은 것 같네요

**Comment by yhwon90** [comment]
넌 앞으로도 많이 배워야해. 그 도중에 네 개성을 잃지 않도록 조심하렴.
다른 사람을 따라하다간 개성을 잃기 십상이야.
이건 어떤가요?

**Comment by Porowl** [comment]
영호님껀 너무 길어요.

<T>넌 앞으로도 많이 배워야해. 그 과정에서 
네 개성을 잃지 않도록 조심하렴. 타인을 
따라하다간 개성을 잃기 십상이야.

해야 겨우 들어가서
