### ISSUE TITLE
아, 보세요, 발표가 곧 시작하려나 봐요!  /// 발표가 시작되려 한다!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#219]
![kakaotalk_20160511_005439060](https://cloud.githubusercontent.com/assets/19270364/15153716/4a229a58-1715-11e6-83e2-8ffe5f5cad54.jpg)
![kakaotalk_20160511_005429530](https://cloud.githubusercontent.com/assets/19270364/15153719/4dbefa9e-1715-11e6-93f1-e85be6980564.jpg)

발표를 시작하든, 발표가 시작하든, 발표가 시작되든 통일하는 게 좋겠습니다.
개인적으로는 '발표를 시작하다'가 더 좋습니다.

**Comment by jungin019** [comment]
위에 있는 건 이전과 중복이지만 아래 때문에 이것도 열어놓겠습니다.

**Comment by Y00N** [comment]
ㄴ 전에 을린 건 발표를 이냐 발표가 이냐의  문제였지만 시작하다와 시작되다도 다른 걸 발견해서 조금 다른 이야기가 아닐까 싶어 다시 올려봤습니다.

**Comment by bombomS2** [comment]
그런데 개인적으로는, 첫 번째 문장은 '발표를 곧 시작하려나 봐요!'로, 두 번째 문장은 '발표가 시작되려 한다!'로 해도 괜찮을 것 같아요. 첫 번째 문장은 발표가 주어가 되면 어색하기 때문에 저렇게 고치기로 했던 건데, 두 번째 문장은 문제 될 만한 부분은 없는 것 같습니다. 하나씩 봤을 때 그다지 어색한 부분이 없으니 헷갈릴 일은 없을 거라 생각해요.

**Comment by itstake** [comment]
> 아, 보세요, 발표를 곧 시작하려나 봐요!
> 자리로 돌아가요.
> /
> 발표가 곧 시작된다!
