### ISSUE TITLE
허허허! 꽤나 돌직구를 잘 날리는 친구로구만, 그렇지 꼬마야? 그건 참 맘에 드는구만.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2190]
![screenshot_2016-07-13-07-32-39](https://cloud.githubusercontent.com/assets/19270364/17461060/a2fdb538-5cb9-11e6-8730-e49a51db1369.png)

#1760 관련

돌직구를 날리다는 표현은 신조어이기에 다소 적절하지 못하다고 생각합니다.

**허허허! 꽤나 거침없이 말하는 친구로구만, 그렇지 꼬마야? 그건 참 맘에 드는구만.**

정도로 다듬는 건 어떨까요?

**Comment by Y00N** [comment]
혹은 뭐 "**당돌한**"이라든가, "**솔직한**"이라든가...

**Comment by yhwon90** [comment]
당돌한이 좋습니다

**Comment by Porowl** [comment]
<T>허허허! 꽤나 당돌한 친구로구만,
그렇지 꼬마야? 그건 참 맘에 드는구만.
