### ISSUE TITLE
차이나타운에서 좋은 시간 보내게. 좋은 하루 되시게나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2196]
![screenshot_2016-07-13-07-37-40](https://cloud.githubusercontent.com/assets/19270364/17461128/eff25de2-5cbb-11e6-9eee-4acf927d4f45.png)

"좋은 하루 되시게나."는 문법적으로도 틀린 표현이고 이미 앞에 좋은 시간 보내라는 말이 있으니 그냥 빼 버리고 
**차이나타운에서 좋은 시간 보내게.**
만으로도 충분하지 않을까요?

**Comment by Porowl** [comment]
작별인사로 한 말입니다.
난 이만. 으로 줄이면 어떨까요?

**Comment by yhwon90** [comment]
난 이만
보다 개인적으론
그럼 이만
이 좋습니다
