### ISSUE TITLE
수수께끼 1번 탁자/테이블 //// 경비/경호원

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#220]
![kakaotalk_20160511_005439060](https://cloud.githubusercontent.com/assets/19270364/15153783/954af606-1715-11e6-85ca-66d224b49f98.jpg)
![kakaotalk_20160511_005441201](https://cloud.githubusercontent.com/assets/19270364/15153785/9680cfaa-1715-11e6-931f-2e5dd01aa3ec.jpg)
![kakaotalk_20160511_005425447](https://cloud.githubusercontent.com/assets/19270364/15153806/a3917690-1715-11e6-943a-db6903241ce3.jpg)
![kakaotalk_20160511_005435117](https://cloud.githubusercontent.com/assets/19270364/15153821/ad7fc116-1715-11e6-8746-5d3496f7caa0.jpg)
![kakaotalk_20160511_005437081](https://cloud.githubusercontent.com/assets/19270364/15153829/b50e6f36-1715-11e6-900a-28526b5e8b12.jpg)

수수께기 전의 레이튼과 루크의 대화에서는 '경비'라고 칭하고 수수께기 내에서는 '경호원'이라고 칭합니다.
그리고 메인화면에선 '테이블'이라고 나오고 터치화면에선 '탁자'라고 나옵니다.

**Comment by jungin019** [comment]
음... 전 경호원과 탁자로 고치는 편이 좋을 것 같군요 (아무래도 이미지보다 텍스트 수정이 쉬운 점도 있고...)

**Comment by bombomS2** [comment]
수정이 쉽군요… 경비와 테이블이 좋을 것 같다고 생각했었는데 그렇다면 경호원과 탁자가 좋을지도요. 그렇게까지 의미에 차이가 있는 건 아니니까요.

**Comment by STRIKE-F** [comment]
위에 적힌 대로 고쳤습니다.
