### ISSUE TITLE
누가 개념없게 바나나 껍질을 버려놨어요!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2203]
![default](https://cloud.githubusercontent.com/assets/19270364/17461261/fab0dbaa-5cc0-11e6-9e89-6e3e32358265.png)

개념없다는 말도 신조어니 다듬으면 좋겠습니다.

**누가 바나나 껍질을 버려놨어요! 에티켓도 모르는 사람인가 봐요.
누가 바나나 껍질을 버려놨어요! 에티켓도 모르나 봐요.**

혹-시 에티켓도 외국어니 바꿔야 할까요? 공중도덕? 공공예절?

**Comment by Porowl** [comment]
Some litterbug dropped a banana peel over here.
어떤 (쓰래기버리는충)이 바나나 껍질을 여기 버려놨어요.
 How disgusting.
으으으 더러워

...영어문이 저렇기 때문에
이정도로 순화해서

누가 버릇없게 바나나 껍질을
버려놨어요! 으으... 더러워.

**Comment by Y00N** [comment]
음....
**어떤 무뢰한이 바나나 껍질을 
버려놨어요! 으으... 더러워.**
정도면 원문의 뉘앙스를 살릴 수 있지 않을까요?

**Comment by Y00N** [comment]
고약한 인간?
