### ISSUE TITLE
그건 다행입니다만, 사실 저희는 배가 고픈게 아니라 해답이 고파서요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2209]
![screenshot_2016-07-13-08-16-16](https://cloud.githubusercontent.com/assets/19270364/17461327/a3ca9846-5cc3-11e6-85ef-6d25c066b48c.png)

페퍼네 가게에 잘 오셨어요! 다음에 "그건 다행입니다만"이 나오는 건 다소 어색해 보입니다.

**감사합니다만, 저희는 지금 배가 고프지 않아서요.
대신, 해답엔 늘 굶주려 있죠.**

정도로 다듬어보는 게 어떨까요?

**Comment by Porowl** [comment]
감사합니다만, 저희는 지금 배 대신
해답이 고파서요.

는 어떨까요?

**Comment by Y00N** [comment]
@Porowl 그러면 
**감사합니다만, 저희는 지금
배보단 해답이 고프군요.**
는 어떤가요?
어, 그런데 사실 저는 게임하다가 갑자기 레이튼이 왜 이렇게 뜬금포 인사를 하는지 이해가 잘 안되더라구요.

**Comment by Porowl** [comment]
전 페퍼예요. 혹시 먹거리를 찾아
오신 거라면, 잘 찾아 오셨어요!

다음 대사입니다.

**Comment by Porowl** [comment]
차라리, 그거 잘됐군요. 로 바꾸는것은 어떨까 싶네요

**Comment by Y00N** [comment]
아 그 전 대사는 알고 있습니다만
뜬금없이 해답에 굶주려있대서... 뭐 그렇게 안달난 사람도 아니잖아요? 허허
"그거 잘됐군요."도 맥락상 나쁘지 않다고 생각합니다.
"마침 잘 찾아왔네요." 라든가...

**Comment by Porowl** [comment]
그게, 안달난 사람이 맞을지도요.
아직 '그' 수수께끼를 보지 못하신것 같은데
아마 보면 납득이 갈껍니다.
