### ISSUE TITLE
아, 이런 용기있는 모습이야말로 우리가 두려움 없는 리더에게 바라는 것이죠.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#221]
![kakaotalk_20160511_005445851](https://cloud.githubusercontent.com/assets/19270364/15153944/43602fe0-1716-11e6-81fe-6efaf68888f3.jpg)

일단 '용기있는'은 '용기가 있는'에서 조사를 생략한 형태이기 때문에 '용기 있는'으로 쓰는 게 맞다고 생각합니다.

그리고 용기 있는 모습은 두려움 없는 리더에게 바라는 점이라고 하는데 '용기 있는' 건 '두려움 없다'와 거의 같은 말이라고 생각합니다. '아, 이런 용기 있는 모습이야 말로 우리가 리더에게 바라는 것이죠.' 정도로도 충분하지 않을까요?

**Comment by jungin019** [comment]
용기 있는 으로 고쳤습니다. 
사실 좀 중복된 의미긴 한데 원문을 따르느라 고민했던 부분입니다. 
건의하신 걸로 고치는 게 좋겠군요.

**Comment by jungin019** [comment]
@Latteria

**Comment by Latteria** [comment]
* 채택하겠습니다.
