### ISSUE TITLE
우리도 그렇게 생각해. 인사를 받으면 나도 정중하게 인사해야지. 신사라면 말이야!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2211]
![screenshot_2016-07-13-15-43-34](https://cloud.githubusercontent.com/assets/19270364/17461413/77019b2c-5cc6-11e6-8b49-4d2a2115e9c0.png)

어... 문장이 꽤 어색한데 뭔가 해결책이 없을까요?

**우리도 그렇게 생각해. 신사라면 모름지기 인사를 받으면 정중하게 인사해야지.**
일단 이렇게 생각해보긴 했는데, 더 좋은 제언 부탁드립니다.

**Comment by Porowl** [comment]
좋습니다.

**Comment by jungin019** [comment]
괜찮은 것 같네요

**Comment by yhwon90** [comment]
저도 좋습니다

**Comment by vbn2523** [comment]
그렇게 되면 '~면' 이라는 표현이 반복되지 않나요?

**Comment by yhwon90** [comment]
인사를 받았을 때

**Comment by Y00N** [comment]
굳이 바꾼다면 **신사는 모름지기**로 바꿀 수 있겠다만,
지적하신 건 관형절과 본 문장의 관계를 지적하신 건데
이중 주어의 문제도 아니고 굳이 바꿀 필요가 있을까요?

**Comment by Porowl** [comment]
<T><A3/2>우리도 그렇게 생각해. 
신사는 모름지기 인사를 받으면 
정중하게 인사해야지.
