### ISSUE TITLE
넹. 아빠가 여기에 저랑 엄마도 끌고 이사를 왔어요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2214]
![screenshot_2016-07-13-15-45-17](https://cloud.githubusercontent.com/assets/19270364/17461480/7a77e23c-5cc8-11e6-9b4e-6cef9d1f1c23.png)

**네. 아빠가 여기로 이사하자고 저랑 엄마를 끌고 왔어요.**
**네. 아빠가, 엄마랑 저를 데리고 여기로 이사왔어요.**

라고 쓰면 어감이 좀 달라지나요?

**Comment by Porowl** [comment]
Yup. 이 원문이기 때문에 넹. 으로 대체했습니다.

넹. 아빠가, 엄마랑 저를 데리고
여기로 이사왔어요.
