### ISSUE TITLE
도대체 무슨 일을 하시길래 여기에 내내 지내셔야만 하는 거야?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2215]
![screenshot_2016-07-13-15-47-58](https://cloud.githubusercontent.com/assets/19270364/17461504/9771eb98-5cc9-11e6-90e3-6885f92263d0.png)

앞 문장이 아빠가 집에 오는 걸 한 번도 못 봤다라는 내용인데 적절하지 않은 문장이라고 생각합니다.
**도대체 무슨 일을 하시길래 집에도 못 오시고 일하시니?** 뭐 이런 내용이 와야하는 거 아닌감여?

**Comment by Porowl** [comment]
도대체 무슨 일을 하시길래 
집에도 못오고 일만 하시는거야?

**Comment by Porowl** [comment]
오역이었습니다
