### ISSUE TITLE
일단은 머리를 좀 식혀야 할 것 같아. 그래도 반드시 다시 올 거야! 진정한 신사로서 말이야!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2217]
![screenshot_2016-07-13-15-53-19](https://cloud.githubusercontent.com/assets/19270364/17461612/8bf0c8a8-5ccd-11e6-9785-15c62e2f4241.png)

진정한 신사로서 말이야! 라는 말이
자신이 진정한 신사이기에 다시 온다는 건지
진정한 신사가 되어서 다시 온다는 건지 다소 불분명하게 와닿는데요
이를 명확히 했으면 좋겠습니다.

**일단은 머리를 좀 식혀야겠어.
그래도 반드시 다시 오겠어!
난 진정한 신사니까!**

정도로 다듬어보면 어떨까요?

**Comment by Porowl** [comment]
일단은 머리를 좀 식혀야겠어.
그래도 반드시 다시 올꺼야!
난 진정한 신사니까!

**Comment by jungin019** [comment]
올 거야 로 수정
