### ISSUE TITLE
이 거대한 판다 좀 보세요!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2218]
![screenshot_2016-07-13-15-56-19](https://cloud.githubusercontent.com/assets/19270364/17461644/b250326c-5cce-11e6-9406-becf9e3a84cc.png)

**봐요! 엄청 큰 판다예요!
귀엽지 않나요, 선생님?**
다소 직역투가 나서 조금 손을 대봤는데 어떤가요?

**Comment by Porowl** [comment]
보세요! 엄청 큰 판다에요!
귀엽지 않나요, 선생님?

**Comment by jungin019** [comment]
판다예요 로 수정
