### ISSUE TITLE
너도 알다시피, 네가 가족 같은 지붕이라고 하니까 저번에 들었던 수수께끼가 하나 생각나는데 말이지.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2223]
![screenshot_2016-07-13-16-22-56](https://cloud.githubusercontent.com/assets/19270364/17461836/80be4418-5cd4-11e6-8504-ff24388c87cf.png)

음... 이거 루크가 뭘 알아서 루크가 알다시피라고 말하는 건가요?

**Comment by jungin019** [comment]
....원문이 you know, 네요...
저기 있잖아, 정도로 바꾸는 게 어떨까 합니다..

**Comment by yhwon90** [comment]
You know라면 그냥 생략해도 되지 않을까요?
네가 가족 같은 지붕이라고 하니까~

**Comment by jungin019** [comment]
생략도 괜찮을듯요

**Comment by Porowl** [comment]
생략합니다.
