### ISSUE TITLE
좌절할 필요는 없어.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2224]
![screenshot_2016-07-13-16-23-58](https://cloud.githubusercontent.com/assets/19270364/17461852/ba99e8ea-5cd4-11e6-8112-8c8f76678e4f.png)

~할 필요가 없다도 번역투에서 많이 나오고 지적되곤 하는 표현인라서요....

**좌절하진 마.
좌절하진 않았으면 해.
좌절하진 않아도 돼.**
라는 뉘앙스로 대체해보면 어떨까요?

**Comment by jungin019** [comment]
전 좌절하지마에 한 표요

**Comment by yhwon90** [comment]
저도 좌절하진 마 에 한 표
