### ISSUE TITLE
철도가 유용하긴 하지만 몰렌트리 열차만 하진 않네요...

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2225]
![screenshot_2016-07-13-16-26-05](https://cloud.githubusercontent.com/assets/19270364/17461862/11a10768-5cd5-11e6-8f81-e8f269d6360c.png)

**지하철이 편하긴 한데, 몰렌트리 열차만큼은 아니네요.
지하철이 편하긴 한데, 몰렌트리 열차만 못하네요**
정도로 다듬어보는 게 어떨까요?

**Comment by yhwon90** [comment]
두번째 문장이 마음에 듭니다

**Comment by jungin019** [comment]
전 사실 첫 번째가 조금 더...
