### ISSUE TITLE
헤헤, 정말로 재미있을 것 같은데?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2226]
![screenshot_2016-07-13-16-31-49](https://cloud.githubusercontent.com/assets/19270364/17461946/f8a46e88-5cd6-11e6-9d05-5f960e90d88f.png)

**헤헤, 정말로 재미있겠지?**
와 같은 말로 대체하는 건 어떨까요?

**Comment by jungin019** [comment]
원문이 
'Hyuh hyuh! Yeah, I'm pretty
excited about it myself. '인데 그냥 
'나도 그렇게 생각해' 정도로 하는 것도 괜찮을 것 같네요
