### ISSUE TITLE
힌트 코인을 얻었습니다! // 그건 힌트코인이라는 건데 ... // 아, 힌트코인에 대해서 말해주시려는 ... // ... 하지만 힌트코인을 설명하는 건 ...

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#223]
![kakaotalk_20160511_005500410](https://cloud.githubusercontent.com/assets/19270364/15154139/2142269c-1717-11e6-87d1-afd19dc1e125.jpg)
![kakaotalk_20160511_005502852](https://cloud.githubusercontent.com/assets/19270364/15154142/22aa34de-1717-11e6-9d7f-4ec89585cc09.jpg)
![kakaotalk_20160511_005507461](https://cloud.githubusercontent.com/assets/19270364/15154143/2570820e-1717-11e6-8022-80cb4ac697ac.jpg)
![kakaotalk_20160511_005509543](https://cloud.githubusercontent.com/assets/19270364/15154293/b013727c-1717-11e6-8beb-9953564595d8.jpg)

'힌트코인' 과 '힌트 코인'을 혼용하고 있습니다.

**Comment by jungin019** [comment]
힌트코인이 나으려나요...

**Comment by bombomS2** [comment]
붙여 적는 게 나을 것 같기도 합니다.

**Comment by Y00N** [comment]
고유명사로 보면 붙여쓸 수도 있겠지만, 띄어쓰기의 원칙인 의미 단위로 띄어 씀을 생각하면 띄어 쓰는 게 좋다고 생각합니다.

**Comment by bombomS2** [comment]
그러고 보니 이유를 안 적었군요… 원칙 상 띄어 적는 게 맞는데, 제 생각엔 붙여 적는 편이 보기에 좀 더 편할 것 같아요.

**Comment by kaleidoscope531** [comment]
일단 이상한 마을에선 '힌트 코인'
악마의 상자에선 '반짝코인'
으로 되어 있더군요.
제 생각은 '힌트코인' 자체를 고유명사로 봐도 될 것 같습니다.

**Comment by bombomS2** [comment]
그러고 보니 정발에선 힌트 코인 반짝코인 힌트메달 등등 많았죠… 힌트코인을 고유명사로 취급하는 것도 좋겠습니다.

**Comment by Porowl** [comment]
'힌트코인' 으로 고정하겠습니다.
