### ISSUE TITLE
이 아이들에게 도와달라고 하길 정말 잘한 것 같아.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2239]
![screenshot_2016-07-13-16-43-21](https://cloud.githubusercontent.com/assets/19270364/17462037/1618853c-5cda-11e6-8d53-1b46e1830272.png)

**이 아이들에게 도와달라고 하길 정말 잘했지 뭐야.**
어떨까요?

**Comment by jungin019** [comment]
전 괜찮네요
