### ISSUE TITLE
오른쪽 아래에 표시되는 답하기 버튼을 누르면 다음과 같은 화면이 표시됩니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#224]
![kakaotalk_20160511_005513055](https://cloud.githubusercontent.com/assets/19270364/15154393/3fd014e2-1718-11e6-94fb-5be0804d6f44.jpg)

표시라는 말이 적절하지 않다고 생각했습니다.
'오른쪽 아래에 위치한 답하기 버튼을 누르면 다음과 같은 화면이 나타납니다.' 정도는 어떨까요?

**Comment by itstake** [comment]
터치펜으
