### ISSUE TITLE
벽화가 거의 다 끝난 것 같군요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2251]
![Uploading Screenshot_2016-07-13-17-40-22.png…]()

**벽화도 이제 마무리만 남은 모양이군요.**

라는 쪽은 어떨까요? 좀 더 자연스럽고 뒤에 거의 다 했어. 라고 받기에도 더 깔끔하지 않을까 싶은데요.

**Comment by jungin019** [comment]
전 괜찮은 것 같습니다.
