### ISSUE TITLE
우와, 너네는 내가 본 사람 중에 가장 수수께끼를 잘 푸는 것 같아!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2256]
![screenshot_2016-07-13-17-47-58](https://cloud.githubusercontent.com/assets/19270364/17462117/9fa022a8-5cdd-11e6-9a63-b67275710199.png)

**와, 너희는 내가 봐온 사람 중에서 수수께끼를 가장 잘 푸는구나!
와, 너희는 내가 봐온 사람 중에서 수수께끼를 가장 잘 푸는 사람이야!**
**와, 살면서 너희처럼 수수께끼를 잘 푸는 사람은 처음 봐!**

**Comment by jungin019** [comment]
전 마지막 문장이 좋네요

**Comment by yhwon90** [comment]
저도 마지막에 한 표
