### ISSUE TITLE
연습을 많이 하거든요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2258]
![screenshot_2016-07-13-17-48-07](https://cloud.githubusercontent.com/assets/19270364/17462122/fbc37972-5cdd-11e6-816e-85f066087ce4.png)

레이튼의 대사같은 느낌이 잘 안 드는데... 저만 그런가요?

**하하, 수수꼐끼야 늘 달고 삽니다.**
와 같은 말은 어떨까요?

**Comment by jungin019** [comment]
음 번역이 틀린 건 아닌데 제안하신 문장도 나쁘지 않네요

**Comment by Porowl** [comment]
찬성
