### ISSUE TITLE
냠...꿀꺽! 이 고기의 맛은 정말 꿈만 같군.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2260]
![screenshot_2016-08-04-21-16-40](https://cloud.githubusercontent.com/assets/19295794/17462125/372feb58-5cde-11e6-82d4-cf6950463897.png)

말줄임표와 '꿀꺽!' 사이에 한 칸을 띄우는 것이 좋겠습니다.

그리고 바튼이 먹고 있는 건 고기가 아니라 만두 같은데... 원문에는 고기인가요?

**Comment by jungin019** [comment]
어 pork bun이네요; 고기 찐빵으로 고치겠습니다.

**Comment by Y00N** [comment]
美味!
