### ISSUE TITLE
나도 그게 의문이군. 항상 선생님의 행동엔 이유가 있지만 달아나신 이유는 모르겠는데.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2269]
![screenshot_2016-08-04-21-34-52](https://cloud.githubusercontent.com/assets/19295794/17462188/be4825f0-5cdf-11e6-9418-8d21a01c3357.png)

나도 그게 의문이군.
항상 선생님의 행동엔 이유가 있지만
달아나신 이유는 모르겠는데.

로 개행 수정하면 어떨까요?

그리고 '달아나신' 이라는 표현은, 뭔가 나쁜 짓 하고 도망가는 느낌인데... 다른 표현은 없을까요?

**Comment by Y00N** [comment]
**나도 알 수가 없구나.
선생님의 행동엔 늘 이유가 있었는데,
그렇게 사라지신 이유는 도통 모르겠다.**
어떤가요?

**Comment by yhwon90** [comment]
Y00N님 의견이 좋아보입니다
