### ISSUE TITLE
잠깐, 플로라 누나, 등에 쪽지가 붙어있어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2270]
![screenshot_2016-08-04-21-34-56](https://cloud.githubusercontent.com/assets/19295794/17462194/f5844b02-5cdf-11e6-9672-9125f8feed5f.png)

'붙어있어.' 는 '붙어 있어.' 로 띄워서 1행 끝부분에 붙여 쓰면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
칸이 안 되어 붙어 있어 만 고쳤습니다.
