### ISSUE TITLE
응? 큰 형님? 내가 여기 있는 건 큰 형님에 대한 생각을 하지 않기 위해서라고. 알아 들어?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2273]
![screenshot_2016-07-13-17-57-33](https://cloud.githubusercontent.com/assets/19270364/17462222/370b76da-5ce1-11e6-9938-1ca19587ede6.png)

**응? 큰형님? 내가 여기 왜 있겠어?
당연히 큰형님 생각을 안 하려고 
그러는 거라고. 알아들어?** 

어떤가요?
"큰형님에 대한 생각을"을 고치다가 꽤나 전체적으로 다듬게 되었네요.

**Comment by yhwon90** [comment]
응? 큰형님? 내가 여기 왜 있겠어?
당연히 큰형님 생각을 하지 않으려고
그러는 거라고. 알아들어?
요건 어떤가요...? 별반 다르진 않지만......

**Comment by Y00N** [comment]
하기 싫으니까...?

**Comment by jungin019** [comment]
두 분 의견 다 괜찮네요

**Comment by Porowl** [comment]
하지 않으려고.
