### ISSUE TITLE
생각해보니 그쪽이 찾는 사람은 여기 안 왔을 것 같네요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2274]
![screenshot_2016-07-13-18-00-43](https://cloud.githubusercontent.com/assets/19270364/17462247/fbf92d34-5ce1-11e6-8608-3ec89e6076eb.png)

**생각해보면, 그쪽이 찾는 사람은 
여기에 오지 않을 테죠.**
쪽이 더 자연스럽지 않을까요?

**Comment by jungin019** [comment]
음 그게 좋을 것 같기도 하네요

**Comment by yhwon90** [comment]
좋아보입니다
