### ISSUE TITLE
제 말은, 그쪽 같으면 상사가 언제라도 들이닥칠 수 있는 곳에서 빈둥대겠어요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2276]
![screenshot_2016-07-13-18-01-05](https://cloud.githubusercontent.com/assets/19270364/17462254/2e9ac496-5ce2-11e6-8cd7-eeeb1ad61e66.png)

그러니까, 그쪽 같으면 상사가 언제라도
들어닥칠지 모를 곳에서 빈둥대겠어요?

쪽이 좀 더 자연스럽지 않을까요?

**Comment by yhwon90** [comment]
들이닥칠지
가 맞는 표현이라는 것 말고는 이의 없습니다

**Comment by Y00N** [comment]
오, 지적 감사합니다.
