### ISSUE TITLE
저 짧은 다리로 저렇게나 빨리 달릴  수 있다는 걸 누가 알았겠어요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2279]
![screenshot_2016-07-13-18-05-09](https://cloud.githubusercontent.com/assets/19270364/17462274/cec5ecca-5ce2-11e6-8cf0-25fe07360d32.png)
, 
**저 짧은 다리로 그렇게 빨리 달릴 줄 누가 알았겠어요?**
이렇게 쓰면 되지 않을까요?

**Comment by jungin019** [comment]
현재 수정되어 
'세상에, 저 작은 사람 때문에
정말 놀랐어. 어쩜 저렇게 짧은 다리로 
빨리 달리지?'로 되어 있습니다.
