### ISSUE TITLE
하하. 나이가 들면 이런 걸 알아볼 수 있는 안목을 가지게 된단다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#228]
![kakaotalk_20160511_005531311](https://cloud.githubusercontent.com/assets/19270364/15154617/727b90a0-1719-11e6-80b2-b610de05c0ac.jpg)

안목을 가지게 된다는 말이 다소 어색하게 느껴집니다.
원문을 확인하진 않았지만 have를 번역한 것인가 싶네요.
'하하. 나이가 들면 이런 걸 알아볼 수 있는 안목이 생긴단다.' 정도는 어떨까요?

**Comment by jungin019** [comment]
'안목을 가진다'도 틀린 어구는 아닙니다^^;
일단 어색하다고 생각하시니 열어두겠습니다.

**Comment by Y00N** [comment]
ㄴ 오히려 '안목을 가져라!' 정도면 좀 더 익숙한 표현이겠지만-물론 전 이것도 키워라! 넓혀라! 등으로 쓰는 편이긴 합니다- 갖게 된다란 표현은 뭐랄까요... 신경쓰이네요.
안목을 가지다도 맞는 말이긴 하지만 그보다 안목이 있다가 널리 쓰이는 표현이기도 하구요다.

**Comment by Porowl** [comment]
'안목이 생긴다'가 나을 듯 싶네요.

**Comment by kaleidoscope531** [comment]
'안목이 생긴다' 좋습니다.

**Comment by jungin019** [comment]
하하. 나이가 들면 이런 걸 알아볼 수
있는 안목이 생긴단다.
로 수정
