### ISSUE TITLE
맞아요. 아마 이것도 선생님이 준비하시는 기발한 계획의 한 부분일 것 같네요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2280]
![screenshot_2016-08-04-21-35-19](https://cloud.githubusercontent.com/assets/19295794/17462285/16fe548c-5ce3-11e6-9c93-db5bbf0095f8.png)

문장에 번역쳇스러운 느낌이 있다고 생각하는데 수정할 수는 없을까요?

**Comment by jungin019** [comment]
'기발한 계획의 일부일지도 모르겠네요' 정도는 어떨까요

**Comment by Y00N** [comment]
**맞아요. 아마 이것도 선생님의 기발한 계획 중 하나가 아닐까요?**
