### ISSUE TITLE
네, 봤어요. 빨리 달려가던데요. 바지랑 신발도 젖었더라구요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#2281]
![screenshot_2016-07-13-18-05-43](https://cloud.githubusercontent.com/assets/19270364/17462290/30209fe2-5ce3-11e6-9929-7d696a6e3d62.png)

**네, 봤어요. 급하게 달려가던데요. (or 엄청 빠르던데요.)
바지랑 신발도 젖었더라구요.**
어떤가요?

**Comment by jungin019** [comment]
전 말씀하신 것 둘 다 괜찮은 것 같네요

**Comment by yhwon90** [comment]
둘 다 좋습니다.

**Comment by Porowl** [comment]
급하게 달려가던데요. 로 수정했습니다.
