### ISSUE TITLE
우리 형님만 있었다면 너희는 지금쯤 벌벌 떨고 있었을 거다!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2287]
![screenshot_2016-08-04-21-40-56](https://cloud.githubusercontent.com/assets/19295794/17462339/a715b1b8-5ce4-11e6-939a-bc48906fd4d7.png)

1행의 '너희는 지금쯤' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 남아 닫겠습니다
