### ISSUE TITLE
두 톱니바퀴 사이에 톱니의 개수가 홀수라면, ... (후략)

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#229]
![kakaotalk_20160511_005537936](https://cloud.githubusercontent.com/assets/19270364/15154783/56fc6d3a-171a-11e6-9eb6-8a26ec0bee09.jpg)

'톱니'와 '톱니바퀴'가 혼용되고 있는데, 톱니는 톱니바퀴 자체를 의미하지 않으므로 '톱니바퀴'로 통일해야 한다고 생각합니다.

**Comment by jungin019** [comment]
이 문제 전체적으로 고쳤습니다.
