### ISSUE TITLE
분명 이 안경에는 쓴 사람만 볼 수 있는 수수께끼가 있을 거야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2293]
![screenshot_2016-08-04-21-46-19](https://cloud.githubusercontent.com/assets/19295794/17462366/81f10814-5ce5-11e6-92f6-d780888e9517.png)

분명 이 안경에는 이것을 쓴 사람만
볼 수 있는 수수께끼가 있을 거야.

로 개행과 내용 수정하면 어떨까요?

**Comment by vbn2523** [comment]
사실 이렇게 수정해도 '~있다' 라는 표현이 반복되어 어색하기도 합니다.

**Comment by yhwon90** [comment]
분명 이 안경에는 이것을 쓴 사람에게만 보이는 수수께끼가 있을거야

**Comment by Y00N** [comment]
영호님 의견에 동의합니다.
