### ISSUE TITLE
이 문을 열려면 그걸 푸는 수밖엔 없겠지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2294]
![screenshot_2016-08-04-21-46-24](https://cloud.githubusercontent.com/assets/19295794/17462374/b13ceeb2-5ce5-11e6-9775-b2845534f400.png)

2행의 '없겠지.' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by jungin019** [comment]
칸이 모자라 닫겠습니다
