### ISSUE TITLE
첨단 기술로 이루어 탑인데도 올라갈 수 있는 방법이 이 계단 뿐이구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2296]
![screenshot_2016-08-04-21-47-57](https://cloud.githubusercontent.com/assets/19295794/17467357/45c62766-5d58-11e6-9203-1313bd25a832.png)

'이루어' 는 '이루어진' 으로 표현하려던 의도가 아니었나 싶습니다.

**Comment by jungin019** [comment]
수정되어 
'계단으로밖에 올라갈 수 
없다니. 탑이 그렇게 
최신식은 아니군...'로 바뀌었습니다.
