### ISSUE TITLE
제 두목에게 꼰지르는 꼴이라니. 저런 용기는 내 평생에 본 적이 없군.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2299]
![screenshot_2016-08-04-21-49-04](https://cloud.githubusercontent.com/assets/19295794/17470954/5f8bfe50-5d7b-11e6-9c3e-c966eb9183d8.png)

음, 모자파의 두목은 보스트로인 것으로 알고 있는데,

별 건 아니지만 '두목' 을 '상관' 으로 수정하면 어떨까 합니다.

그리고 1행의 '저런' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by Y00N** [comment]
왜 상관으로 바꿔요?

**Comment by Porowl** [comment]
모자파의 두목은 보스트로인데,
여기선 자기 바로 윗 사람에게 꼰지른 꼴이니

보스트로가 아니라 바로 윗 사람을 지칭하기 위해서
상관이라는 말을 쓰자,라고 말씀하시는 듯 싶네요

**Comment by Porowl** [comment]
개행은 하되 두목은 보류합니다
