### ISSUE TITLE
주먹을 못 쓰니 대신 내 강렬한 수수께끼로 강타를 날려주마!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2303]
![screenshot_2016-08-04-21-56-10](https://cloud.githubusercontent.com/assets/19295794/17486412/aacb217a-5dcb-11e6-9154-609aeff1839e.png)

1행의 '내 강렬한' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
