### ISSUE TITLE
어차피 이곳에서 평생 살 수는 없을테니 밖으로 나오면 보자. 밤길 조심하는게 좋을거다!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2307]
![screenshot_2016-08-04-21-57-45](https://cloud.githubusercontent.com/assets/19295794/17486837/5411a51e-5dcd-11e6-894f-9089adf09636.png)

어차피 이곳에서 평생 살 수는 없을 테니
밖으로 나오면 보자. 
밤길 조심하는 게 좋을 거다!

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 개행은 수정하지 않았습니다.
