### ISSUE TITLE
내가 너였다면 아래를 보지 않았을 거야...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2309]
![screenshot_2016-08-04-21-58-03](https://cloud.githubusercontent.com/assets/19295794/17486901/9c9363cc-5dcd-11e6-893f-54c62344179e.png)

1행의 '아래를' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
'나라면 아래를
보지 않을 거야...'로 수정되어 있습니다.
