### ISSUE TITLE
음식들은 그다지 맛이 특출나지 않군 / 기다릴 동안 즐길 만한 음식이 있잖아요.  // 수수께끼 6번 /// 질문포함!!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#231]
![-2](https://cloud.githubusercontent.com/assets/19270364/15155442/67cc69b4-171d-11e6-99b4-55913807d950.jpg)

복수 형태를 의미하는 조사 '-들'이 통일되지 않습니다.

[음식들]은 그다지 맛이 특출나지 않군
기다릴 동안 즐길 만한 [음식]이 있잖아요

[바늘들]과 [실]을 보는 것이 너무 어려워
[실]*은 A와 B 두 개가 있다. 얼마나 많은 [바늘]이 A에 꿰어있을까?
실 A에 꿰인 [바늘]은 총 10개이다.
[바늘들]을 세는 게 꽤나 어렵긴 하다. 

*함께 언급되는 바늘은 [바늘들]인데. 두 가닥의 실은 [실]로 표현되어 있어 두 명사의 복수 표현이 통일되지 않습니다.

저번에 말씀드렸던 수수께끼 2번의 시각들 뿐 아니라
전체적으로 '-들'을 자주 사용하는 것 같습니다.
한국어에선 수의 개념의 일치에 민감하지 않지요. 
다수의 00을 보고 '00'이라고도 '00들'이라고 하는 것 모두 맞다고 합니다.
그런데 저는 오히려 수의 개념에 민감하지 않기 때문에, 언어의 경제성 측면에서 '-들'을 사용을 그리 권하지 않는 편입니다.
그런데 일일히 말씀드리자니 뭔가 글을 많이 올리게 될 것만 같더군요.
그래서 가급적이면 앞에선 '-들'이 사용되었는데 뒤에선 사용되지 않는다거나 그 반대의 경우와 같은 경우에만 말씀드리고 있습니다만, 어디까지 말씀드려야 할지 솔직히 잘 모르겠네요.
에니그마 팀에서는 '-들'의 사용을 어떻게 생각하시는지 궁금합니다.

**Comment by bombomS2** [comment]
음, 개인적으로는 첫 문장의 음식들을 음식으로 고치고 이중 주어인 맛을 합쳐서, '흠. 음식 맛은 그다지 특출나진 않군.'으로 고치는 것이 보기에 편할 것 같아요.
실과 바늘의 경우는 둘 다 복수기 때문에 모두 복수 표현하는 것은 의미가 없는 듯합니다. 이왕 바꾸는 거 바늘과 실의 순서를 비롯해 좀 더 자연스럽게 바꾸어서
'이 조그만 실과 바늘을 보는 게 너무 어려워.'
'A에 꿰여 있는 바늘은 모두 몇 개일까?'
'바늘을 센다는 게 꽤나 어려운 일이긴 하다.'
정도로 고치는 게 어떨까 해요.

**Comment by bombomS2** [comment]
참, 바튼의 대사 중 여기엔과 반점 사이에 공백이 있네요.

**Comment by Porowl** [comment]
우선 답을 해드리자면
팀 탓이 아니라 제 탓입니다.
제가 맞춤법이 약해서요.

우선 이슈된 부분은 수정했습니다.
