### ISSUE TITLE
그렇지만 무작정 저 어둠속으로 뛰어 들어갈 순 없지. 무슨 함정이 도사리고 있을지 모르니까.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2313]
![screenshot_2016-08-04-22-01-47](https://cloud.githubusercontent.com/assets/19295794/17487095/50531e34-5dce-11e6-8d4e-acbc52d178aa.png)

그렇지만 무작정 저 어둠 속으로
뛰어 들어갈 순 없지.
무슨 함정이 도사리고 있을지 모르니까.

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 
'그렇지만 무작정 저 어둠 속으로 
뛰어 들어갈 순 없지. 무슨 함정이 
도사리고 있을지 모르니까.' 로 수정했습니다.
