### ISSUE TITLE
그런데 저렇게나 큰 구멍을 어떻게 건너가죠?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2316]
![screenshot_2016-08-04-22-21-37](https://cloud.githubusercontent.com/assets/19295794/17487254/fe934618-5dce-11e6-8c09-f4cc71277606.png)

1행의 '어떻게' 는 다음 행으로 넘기는 게 어떨까요?

그리고 '구멍을 건넌다' 는 표현이 살짝 어색하다고 생각하는데 다른 분들은 어떻게 생각하시나요?

**Comment by jungin019** [comment]
'바닥에 저렇게 큰 구멍이 있는데 어떻게 지나가죠?' 는 어떨까요

**Comment by yhwon90** [comment]
융인님 말씀에 동의합니다.

**Comment by Y00N** [comment]
융인님 말씀에 동의합니다.
