### ISSUE TITLE
아래는 많이 어두워 보여요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2318]
![screenshot_2016-08-04-22-26-28](https://cloud.githubusercontent.com/assets/19295794/17487338/5ee4886a-5dcf-11e6-8672-43c4b39c0b36.png)

1~2행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
'아래가 칠흙같이 어두워요!'로 수정되어 있습니다.
