### ISSUE TITLE
꽤나 엄청난 짓을 했지만, 내가 보기에 당신은 그저 권력욕에 불타는 사람으로밖에 안 보이는군요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2319]
![screenshot_2016-08-04-22-27-58](https://cloud.githubusercontent.com/assets/19295794/17487386/83d00d52-5dcf-11e6-87af-bf9e68d677a1.png)

꽤나 엄청난 짓을 했지만,
내가 보기에 당신은 그저 권력욕에
불타는 사람으로밖에 안 보이는군요.

로 개행 수정하면 어떨까요?

**Comment by vbn2523** [comment]
그리고 '~에' 라는 표현이 반복됩니다.

**Comment by yhwon90** [comment]
내가 보기에 -> 내게
이건 어떤가요? 일단 '에'는 아니긴한데........

**Comment by Y00N** [comment]
-에 가 반복되는 건 별 문제가 아니고, 
이 문장에서 더 큰 문제는 "내가 보기에"와, "보이는군요"가 의미상 중복되는 거라고 생각합니다

**꽤 엄청난 짓을 했지만,
내가 보기에 당신은 그저 권력욕에
불타는 사람일 뿐이에요.**
정도가 어떨까요
