### ISSUE TITLE
루크, 간단한 수수께끼를 하나 풀어주겠니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2321]
![screenshot_2016-08-04-22-28-14](https://cloud.githubusercontent.com/assets/19295794/17487445/cdad64ba-5dcf-11e6-92cd-f6d5473df6d9.png)

1~2 행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

아니면 1행의 '하나' 를 다음 행으로 넘겨도 좋겠습니다.

**Comment by jungin019** [comment]
붙여쓰는 건 칸이 안 되고 하나를 개행하는 건 칸이 너무 남아 닫겠습니다.
