### ISSUE TITLE
당신의 대답을 들어보니 이런 중요한 사건을 잊어버린 것 같군요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2328]
![screenshot_2016-08-04-22-31-04](https://cloud.githubusercontent.com/assets/19295794/17487718/09d1d10a-5dd1-11e6-9a5a-5a2ad9c36148.png)

1행의 '이런 중요한' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 남아 닫겠습니다.
