### ISSUE TITLE
하나를 빼낸다면 그 위에 있는 블럭들은 모두 바닥으로 굴러 떨어지기 마련이지요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2329]
![screenshot_2016-08-04-22-31-09](https://cloud.githubusercontent.com/assets/19295794/17487748/29428a34-5dd1-11e6-92d3-ddf39dc1354e.png)

2~3행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
칸이 애매하게 남아 보류하겠습니다.
