### ISSUE TITLE
[건의사항] 레이튼: 그래, 그 실종 사건들이 이 모든 것들과 연관되어 있는 것 같구나. 어쨌든, 지금 우리가 할 수 있는 최선의 일은 편지에 쓰인 장소로 가는 것인 것 같구나.

### ISSUE THREAD

**Issue by bombomS2** [elfinlazz/lt3translation#233]
게임 초반 열차 안에서 레이튼과 루크의 대화 중 레이튼의 대사입니다.
앞 문장은 '그래, 그 실종 사건들이 이 모든 것과 연관되어 있는 것 같구나.'로 고쳐진 것으로 알고 있습니다.
그런데 바로 다음 문장에도 -구나가 반복되고, 문장이 어색한 느낌이 들더라고요. 그래서 조금 고치는 게 어떨까 해서 건의드립니다.
두 문장을 함께 보았을 때,
그래, 그 실종 사건들이 이 모든 것과 연관되어 있는 것 같아. 어쨌든, 지금은 편지에 쓰여 있는 장소로 가는 게 우리가 할 수 있는 최선인 것 같구나.
로 고쳐서 적용하는 것이 어떨까 합니다. 의견 있으시면 꼭 부탁드려요.

**Comment by rabbitdoggy** [comment]
말씀하신 대로 수정하는 게 나아 보입니다.

**Comment by Y00N** [comment]
기왕이면 (연관되어 있는 것 같아)도 (연관된 것 같아)로 줄이면 좋겠습니다.

**Comment by bombomS2** [comment]
연관도 좋은데, 관련은 어떤가요?

**Comment by kaleidoscope531** [comment]
연관이나 관련이나 뜻은 거의 같으니 어감이 붙는 쪽을 택하면 되겠군요.

**Comment by bombomS2** [comment]
개인적으로는 관련이 더 익숙해서 어감이 잘 붙는 거 같습니다.

**Comment by Latteria** [comment]
그래, 그 실종 사건들이 이 모든 것과 연관된 것 같아. 
어쨌든, 지금은 편지에 쓰여 있는 장소로 가는 게 우리가 할 수 있는 최선인 것 같구나.
* 채택하겠습니다.
