### ISSUE TITLE
뭐, 이미 말했으니... 주머니의 펜은 무슨 색이지?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2330]
![screenshot_2016-08-04-22-31-21](https://cloud.githubusercontent.com/assets/19295794/17487820/78539cda-5dd1-11e6-8dcc-baf702ffa528.png)

1행의 '주머니의 펜은' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
