### ISSUE TITLE
자네의 기억은 내가 그 운명의 날의 실험을 재현하는데 필요한 정보를 담고 있거든.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2339]
![screenshot_2016-08-04-22-33-28](https://cloud.githubusercontent.com/assets/19295794/17504821/2d91d2f0-5e37-11e6-9929-4514fcbfa44e.png)

'~의' 라는 표현이 반복됩니다. 그리고 '재현하는데' 는 '재현하는 데' 로 띄우는 게 어떨까요?

**Comment by yhwon90** [comment]
띄어쓰기에는 동의하지만 '~의' 반복은 잘 모르겠네요..

**Comment by Y00N** [comment]
문장이 길어지면 어쩌면 어쩔 수 없는 거라고 생각합니다.
위 문장이 안은 문장과 안긴 문장의 관계이기도 하고요.

**Comment by jungin019** [comment]
따로 의견 없으시면 닫겠습니다
