### ISSUE TITLE
[건의사항] 레이튼: 우리 열차가 출발하는 승강장은 어디니, 루크야?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#234]
![image](https://cloud.githubusercontent.com/assets/19265176/15179992/f8197088-17b9-11e6-94a1-93724c155bac.png)

마지막에 루크야? 에서 야를 안 붙이는 편이 좋을 것 같아서 올려봅니다. 
'우리 열차가 출발하는 승강장이 어디니, 루크?' 이 편이 더 깔끔해 보인다고 생각합니다.

**Comment by jungin019** [comment]
아 이거 ~야 안 붙이기로 한 부분인데 누가 실수를 했나 보네요
