### ISSUE TITLE
자네같은 합리적인 남자는 끝이 좋으면 모든 게 좋다는 것쯤은 이해할 줄 알았는데.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2345]
![screenshot_2016-08-04-22-34-32](https://cloud.githubusercontent.com/assets/19295794/17504933/42af2b82-5e38-11e6-8e9d-b42b29e568b8.png)

자네 같은 합리적인 남자는
끝이 좋으면 모든 게 좋다는 것쯤은
이해할 줄 알았는데.

로 내용과 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
자네같은 은 붙여쓰는 걸로 알고 있습니다.
