### ISSUE TITLE
육각거탑은 내 요새야. 그 말인 즉슨 넌 내 구역에 있단 거지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2348]
![screenshot_2016-08-04-22-34-51](https://cloud.githubusercontent.com/assets/19295794/17504984/ab2e0ac0-5e38-11e6-93b8-97d8198f42a4.png)

1행의 '그 말인 즉슨 넌' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
