### ISSUE TITLE
네 쪽은 빨강측이고, 내 것은 회색측이다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2349]
![screenshot_2016-08-04-22-35-24](https://cloud.githubusercontent.com/assets/19295794/17504995/c8cbf952-5e38-11e6-8163-2d0b5b665829.png)

네 쪽은 빨강 측이고,
내 쪽은 회색 측이다.

로 내용과 개행 수정하면 어떨까요?

**Comment by jungin019** [comment]
그냥 한 줄에 쓰겠습니다.
