### ISSUE TITLE
[건의사항] 루크 : 다른 사람한테 물어봐요, 선생님. 저 사람한테 물릴까봐 눈도 못 마주치겠어요.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#235]
![image](https://cloud.githubusercontent.com/assets/19265176/15180054/4ddb76d8-17ba-11e6-95ff-91e6335a4608.png)

일단은 '저 사람한테 물릴까봐' 라는 표현이 신경 쓰여서 올려봤습니다. 

다만 바로 다음에 레이튼이 루크 보고 '동물과 대화하는 건 특기인 줄 알았는데 말이다' 이런 말을 하기 때문에 저렇게 쓴 의도는 알 것 같습니다. 

제가 너무 오버한 감이 있지만, 일단 다른 분들의 생각을 듣고 싶어서 이렇게 올려봅니다.

**Comment by Porowl** [comment]
물어보다 <- 물리다 <- 동물

이런 말장난입니다. 포기하라면 포기하겠다만.

**Comment by Y00N** [comment]
농담임을 더 적극적으로 어필할 순 없을까요?
'다른 사람에게 가죠, 선생님. 저 사람에겐 물어보긴 커녕 물릴까봐 눈도 못 마주치겠어요.' 라는 식이라든가...

**Comment by kaleidoscope531** [comment]
'물어보긴 커녕 물릴까봐' 좋은 것 같습니다.

**Comment by itstake** [comment]
> 다른 사람에게 가죠, 선생님. 저 사람에겐 물어보긴 커녕 물릴까봐 눈도 못 마주치겠어요.
