### ISSUE TITLE
각 진영측이 두 번의 승리, 두 번의 패배, 그리고 한 번의 동점이군요. 완벽하게 비겼죠.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2351]
![screenshot_2016-08-04-22-36-14](https://cloud.githubusercontent.com/assets/19295794/17505245/e7b4344a-5e3a-11e6-872f-865ca93575ca.png)

각 진영 측이 두 번의 승리, 두 번의 패배,
그리고 한 번의 동점이군요.
완벽하게 비겼죠.

로 개행과 내용 수정하면 어떨까요?

**Comment by jungin019** [comment]
칸이 안 되어
'각 진영 측이 두 번의 승리, 
두 번의 패배, 그리고 한 번의 
동점이군요. 완벽하게 비겼죠.'로 수정
