### ISSUE TITLE
내가 한 마디만 하면 부하들이 달려올 거란 말이지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2353]
![screenshot_2016-08-05-01-31-15](https://cloud.githubusercontent.com/assets/19295794/17505372/a835e466-5e3b-11e6-984d-7a44f1f0529a.png)

1행의 '부하들이 달려올' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
