### ISSUE TITLE
날 과소평가하는 군요, 디미트리.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2354]
![screenshot_2016-08-05-01-31-19](https://cloud.githubusercontent.com/assets/19295794/17505390/d1e9889e-5e3b-11e6-996f-87c9427cedb4.png)

'과소평가하는 군요,' 는 '과소평가 하는군요,' 로 수정해야 하는 것이 맞나요?

**Comment by jungin019** [comment]
다 붙이는 게 맞습니다. 수정
