### ISSUE TITLE
함정같은 걸 숨겨 놓을 수 있을 법한 곳을 굉장히 많이 봤습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2357]
![screenshot_2016-08-05-01-31-39](https://cloud.githubusercontent.com/assets/19295794/17505466/4605795e-5e3c-11e6-9e91-32aed49d2315.png)

'함정같은' 은 '함정 같은' 으로 띄우고 2행의 '곳을' 은 1행 끝부분에 붙여 쓰면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
칸이 안 되어 개행은 하지 않았습니다.
