### ISSUE TITLE
디미트리가 알람을 작동시켰습니다. 머지않아 모자파 단원들이 이곳으로 몰려들 거에요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2358]
![screenshot_2016-08-05-01-32-19](https://cloud.githubusercontent.com/assets/19295794/17505521/95b1e028-5e3c-11e6-8355-afaf4b03dc9a.png)

2행의 '이곳으로' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
