### ISSUE TITLE
하지만 오는 길목에 디미트리의 부하틀을 처치할 장치를 해두셨다고 하셨잖아요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2359]
![screenshot_2016-08-05-01-32-28](https://cloud.githubusercontent.com/assets/19295794/17505535/bd8fb3a4-5e3c-11e6-8eb8-dd61bad285eb.png)

하지만 오는 길목에 디미트리의 부하들을
처치할 장치를 해두셨다고 하셨잖아요?

로 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
이게 개행이 될지 모르겠네요... 첫 줄이 글자수가 넘을 듯합니다

**Comment by Porowl** [comment]
<T><A1/6>하지만 오는 길목에 디미트리 일당들을 
처치할 장치를 해두셨다고 하셨잖아요?

가 공간이 되긴 합니다만

**Comment by Y00N** [comment]
일당이라고 쓰실 거면 **들**을 빼도 된다고 생각합니다.

**Comment by jungin019** [comment]
하지만 오는 길목에 디미트리 일당을 
처치할 장치를 설치했다고 하셨잖아요?
이건 어떨까요

**Comment by Porowl** [comment]
<T><A1/6>하지만 오는 길목에 디미트리 일당을 
처치할 장치를 설치했다고 하셨잖아요?
