### ISSUE TITLE
우리가 올라 온 길은 지금쯤 모자파 단원들로 들끓을 거다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2361]
![screenshot_2016-08-05-01-32-34](https://cloud.githubusercontent.com/assets/19295794/17505582/1215d930-5e3d-11e6-9d81-43f56362c2c8.png)

우리가 올라온 길은 지금쯤
모자파 단원들로 들끓을 거다.

로 내용과 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
우리가 올라온 길은 지금쯤 
모자파 단원들로 들끓을 거야.

현재 이렇게 수정됐습니다.
