### ISSUE TITLE
비상 탈출구 같은 길을 찾는 수밖에 없어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2362]
![screenshot_2016-08-05-01-32-37](https://cloud.githubusercontent.com/assets/19295794/17505602/2e963afa-5e3d-11e6-9b00-4e455ca2e9fd.png)

1~2 행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by STRIKE-F** [comment]
비상 탈출구 같은 걸 찾는 수밖에 없어.

현재 이렇게 수정했습니다.
