### ISSUE TITLE
이 곳을 샅샅이 뒤져야 해

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2363]
![screenshot_2016-08-05-01-32-41](https://cloud.githubusercontent.com/assets/19295794/17505621/58a73e16-5e3d-11e6-8cac-f159e5b13cde.png)

'해' 뒤에 마침표를 하나 사용하는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
