### ISSUE TITLE
[건의사항] 루크 : 침대는 제 거예요!

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#237]
![image](https://cloud.githubusercontent.com/assets/19265176/15180191/11d5a914-17bb-11e6-8915-72d8ffdf4bc6.png)

일단 너무 사소한 부분이라 올리기 죄송스럽습니다만;;;

저 문장 앞에 이 한글자만 더 붙여서 '이 침대는 제 거예요!'라고 하는 것이 어떨까요?

**Comment by jungin019** [comment]
원문이 'Dibs on this bed!'라 말씀하신 것처럼 이 침대가 좀 더 맞긴 합니다.

**Comment by bombomS2** [comment]
이 침대로 표기하는 편이 좀 더 낫겠군요.
