### ISSUE TITLE
빨리 여기서 나가려면 두 그룹으로 나뉘어야 할 것 같아요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2385]
![screenshot_2016-08-05-01-39-36](https://cloud.githubusercontent.com/assets/19295794/17506153/88beeb40-5e41-11e6-8acf-e1b98f0cdd49.png)

1행의 '두 그룹으로' 는 다음 행으로 넘기면 어떨까 하는데 가능할까요?

**Comment by STRIKE-F** [comment]
텍스트를 약간 수정해 현재

빨리 여기서 나가려면 두 조로 
나눠서 가야겠어요.

로 수정됐습니다.

**Comment by Porowl** [comment]
빨리 여기서 나가려면 
두 조로 나눠서 가야겠어요.
