### ISSUE TITLE
이건 저희같은 침입자를 막기 위해서 만든 함정일까요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2387]
![screenshot_2016-08-05-01-40-51](https://cloud.githubusercontent.com/assets/19295794/17506204/f317253e-5e41-11e6-94d1-7b1e26bf19a1.png)

'저희같은' 은 '우리 같은' 으로 수정하는 게 어떨까 합니다.

그리고 2행에서 글씨가 밀리는 부분을 수정하는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
이건 우리 같은 침입자를 
막으려고 만든 함정일까요?

이렇게 수정했습니다.
