### ISSUE TITLE
이것들 좀 떼는 동안 말해봐, 도대체 왜 내가 함정에 갇히는 역할이야?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2388]
![screenshot_2016-08-05-01-41-34](https://cloud.githubusercontent.com/assets/19295794/17506236/298a96a0-5e42-11e6-877f-942057682496.png)

1행의 '도대체' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
