### ISSUE TITLE
[건의사항] 청년 루크 : 그러니 우리 둘이 서로가 진짜란 것을 증명하게 우리의 지성을 각자 증명하자는 것이죠. 

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#239]
![image](https://cloud.githubusercontent.com/assets/19265176/15180356/ff674db8-17bb-11e6-9165-a59642b81fd2.png)

위에서 '증명하게' -> '증명하기 위해'로 바꾸는 것이 더 어감 상 좋을 것 같습니다.

**Comment by jungin019** [comment]
지금 보니 문장이 상당히 이상하군요... 
'그러니 우리 둘이 서로가 진짜란 것을 증명하기 위해 서로의 지성을 보여주자는 거죠.' 정도가 좋을까요

**Comment by kaleidoscope531** [comment]
'서로의 지성을 보여주자는 거죠.' 도 좋은 것 같습니다.

**Comment by bombomS2** [comment]
그러니 우리 둘이서 서로가 진짜라는 걸 증명할 수 있게 각자 지성을 보여주자는 거죠.
이렇게도 괜찮을 것 같네요.

**Comment by kaleidoscope531** [comment]
'그러니 우리 둘이서 각자 상대의 지성을 시험해봄으로써 서로가 진짜임을 증명하자는 거죠.'
아얘 삐딱선 한 번 타 봤습니다. ㅎㅎ

**Comment by bombomS2** [comment]
그러니 서로가 진짜라는 걸 증명할 수 있게 우리 둘이서 각자의 지성을 보여주자는 거죠.
어순을 이렇게 바꿀 수도 있을 것 같네요.

**Comment by STRIKE-F** [comment]
아예 어순을 바꾼다면 '그러니까 서로 지성을 증명한다면 우리 둘이 서로가 진짜라는 것도 증명할 수 있다는 거죠.' 는 어떨까요?

**Comment by Porowl** [comment]
그러니 서로가 진짜라는 것을 증명할 수
있게 각자의 지성을 보여주자는 거죠.
