### ISSUE TITLE
하! 착각하지 마라 꼬맹아. 난 이 자식 친구 아냐.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2390]
![screenshot_2016-08-05-01-41-59](https://cloud.githubusercontent.com/assets/19295794/17506269/6e71cdec-5e42-11e6-9ca1-246ef3f01cb3.png)

1행의 '난 이 자식' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
