### ISSUE TITLE
둘 다 같은 목적이 있어서 함께한 것일 뿐이라고.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2391]
![screenshot_2016-08-05-01-42-04](https://cloud.githubusercontent.com/assets/19295794/17506287/9975a036-5e42-11e6-82d7-7da1514adbdb.png)

둘이 같은 목적을 가지고 있어서
함께한 것 뿐이라고.

로 수정하면 어떤가요?

**Comment by Porowl** [comment]
개행수정 해뒀습니다.
라떼가 볼 때까지 열어둘게요

**Comment by Latteria** [comment]
외부 인력이라 더 이상 수정 불가
