### ISSUE TITLE
선생님께서 너를 반기실 때 정말 수상하더구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2392]
![screenshot_2016-08-05-01-42-15](https://cloud.githubusercontent.com/assets/19295794/17506305/c04f526a-5e42-11e6-934a-ddd69402f9cc.png)

1행의 '정말' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
정말->뭔가로 바꾸는 게 좋을 듯해서 일단 올려 봅니다.(라떼야 미안)

**Comment by Porowl** [comment]
라떼가 볼때까지 열어둡니다

**Comment by Latteria** [comment]
'선생님께서 너를 반기실 때 뭔가 수상하더구나' 로 수정함
