### ISSUE TITLE
박사님은 "꼬마 루크"를 보고도 전혀 놀라지 않으셨지?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2393]
![screenshot_2016-08-05-01-42-27](https://cloud.githubusercontent.com/assets/19295794/17506316/dfe6aed4-5e42-11e6-9c39-bfa5964bd219.png)

박사님은 꼬마 루크를 보고도
전혀 놀라지 않으셨지?

로 개행과 내용 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
저는 "를 굳이 빼야 할까 싶네요....

**Comment by Porowl** [comment]
닌텐도 특성상 **Bold** 기능이 없으니
필요하다고 생각됩니다.

**Comment by yhwon90** [comment]
저도 강조 표시로 그대로 두는 편이 좋아보입니다

**Comment by Y00N** [comment]
다른 분들의 의견에 동의합니다.
