### ISSUE TITLE
선생님은 돈 파올로가 몇 마디 하기도 전에 알아차리신 거군요! 정말 대단하신데요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2394]
![screenshot_2016-08-05-01-42-38](https://cloud.githubusercontent.com/assets/19295794/17506340/08a35728-5e43-11e6-9c22-32ef3c70aa08.png)

선생님은 돈 파올로가 몇 마디
하기도 전에 알아차리신 거군요!
정말 대단하신데요!

로 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
