### ISSUE TITLE
돈 파올로가 다른 사람으로도 변장했나요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2395]
![screenshot_2016-08-05-01-42-44](https://cloud.githubusercontent.com/assets/19295794/17506360/349e770e-5e43-11e6-8812-81407fe004d8.png)

1~2 행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by STRIKE-F** [comment]
뻑뻑하지만 됩니다. 올리신 대로 수정했습니다.
