### ISSUE TITLE
돈 파올로는 델모나 학장님이 늙은 걸 보여주려고 하얀 가발을 썼겠지만, 그게 실수였단다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2397]
![screenshot_2016-08-05-01-43-06](https://cloud.githubusercontent.com/assets/19295794/17507231/8863d6c6-5e49-11e6-9e31-cd4bf9eeb57e.png)

2행의 '그게' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
