### ISSUE TITLE
이 수수께끼를 풀기 위해 그에게 도움을 요청했단다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2398]
![screenshot_2016-08-05-01-43-22](https://cloud.githubusercontent.com/assets/19295794/17507264/c06a5afe-5e49-11e6-80e7-4a127d67ae04.png)

1행의 '그에게 도움을' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
