### ISSUE TITLE
음, 이제야 이해가 되는것 같아요. 그런데...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2399]
![screenshot_2016-08-05-01-43-25](https://cloud.githubusercontent.com/assets/19295794/17507295/e4e772cc-5e49-11e6-843a-90a0c617321c.png)

'되는것' 은 '되는 것' 으로 띄우는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
이제야 이해가 갈 듯해요로 바꾸고 싶긴 한데 라떼가 빡치겠지
일단은 띄었습니다.

**Comment by Porowl** [comment]
라떼가 볼때까지 열어둘게요

**Comment by Latteria** [comment]
전 되는 것 같아요에 걸겠습니다
