### ISSUE TITLE
관람차로 우리를 쫓아온 것도 이 사람이잖아요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2400]
![screenshot_2016-08-05-01-43-31](https://cloud.githubusercontent.com/assets/19295794/17507337/17d7ae9a-5e4a-11e6-95b1-946f77c1d94b.png)

1행의 '이' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
