### ISSUE TITLE
그녀를 마지막으로 본건 연구소에서 폭발 사고가 있던 그 날, 그녀가 그 연구소로 향할 때였단다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2401]
![screenshot_2016-08-05-01-43-52](https://cloud.githubusercontent.com/assets/19295794/17507376/4795228e-5e4a-11e6-98bb-9584103097ed.png)

그녀를 마지막으로 본 건
연구소에서 폭발 사고가 있던 그 날,
그녀가 그 연구소로 향할 때였단다.

로 개행과 내용 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
