### ISSUE TITLE
난 내가 할 수 있는 조사는 다 해보았지만, 헛수고였어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2402]
![screenshot_2016-08-05-01-44-00](https://cloud.githubusercontent.com/assets/19295794/17507405/7642ae80-5e4a-11e6-8820-fb0f71ac9b2a.png)

1행의 '다' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
