### ISSUE TITLE
디미트리는 클레어의 죽음이 자신의 책임이라고 느끼는 것 같더구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2403]
![screenshot_2016-08-05-01-44-05](https://cloud.githubusercontent.com/assets/19295794/17507462/a994deac-5e4a-11e6-99c7-40d5837e70ec.png)

1행의 '자신의' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
