### ISSUE TITLE
뭐! 왜 그리 놀라는거야! 나도... 감정이란게 있다고.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2405]
![screenshot_2016-08-05-01-44-19](https://cloud.githubusercontent.com/assets/19295794/17507548/2610be1a-5e4b-11e6-85c1-c381f080f66a.png)

뭐! 왜 그리 놀라는 거야!
나도... 감정이란 게 있다고.

로 내용과 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
띄어쓰기만 수정했습니다.
