### ISSUE TITLE
폴은 대학에서 나보다 1년 선배였지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2407]
![screenshot_2016-08-05-01-45-54](https://cloud.githubusercontent.com/assets/19295794/17507594/79860e4c-5e4b-11e6-8dfc-8d92f3334c0b.png)

1~2 행을 한 행에 합치면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
