### ISSUE TITLE
다음 목적지가 정해진 것 같군요. 어디로 가나요 선생님?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2408]
![screenshot_2016-08-05-01-46-22](https://cloud.githubusercontent.com/assets/19295794/17507645/bbff3f14-5e4b-11e6-970f-2323639af626.png)

2행의 '같군요.' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
