### ISSUE TITLE
하하 루크! 한 번 맞혀 보렴

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2409]
![screenshot_2016-08-05-01-46-27](https://cloud.githubusercontent.com/assets/19295794/17507982/8f7cf402-5e4d-11e6-845e-77b682429ad6.png)

'보렴' 뒤에 마침표를 하나 사용하는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
