### ISSUE TITLE
[건의사항] 청년 루크 : 사실 "완성되었다"라고 하기에는 뭣하지만요...그 기계는 아직 많이 불완전하거든요.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#241]
![image](https://cloud.githubusercontent.com/assets/19265176/15180449/aa560278-17bc-11e6-8880-5ab5e13e1404.png)

이 부분도 어감이 좀 안 좋은 것 같아서 올려봤습니다. 저는 두 문장 중 하나는 끝맺음을 깔끔하게 하는 편이 더 좋을 것 같습니다. 예를 들면 다음과 같습니다. 

->사실 “완성되었다”라고 하기에는 아직 뭣해요. 그 기계는 아직 많이 불완전하거든요.

->사실 “완성되었다”라고 하기에는 뭣하지만요...... 그 기계는 아직 많이 불완전해요.

**Comment by bombomS2** [comment]
사실 "완성되었다"고 하기에는 뭐합니다만… 그 기계는 아직 많이 불완전해서요.
혹은
사실 "완성되었다"고 하기에는 이릅니다. 그 기계는 아직 많이 불완전하거든요.
정도가 생각납니다.

**Comment by Y00N** [comment]
아직 '완성'이라고 하기는 이릅니다. 그 기계는 아직 불완전하거든요.
어떤가요?

**Comment by kaleidoscope531** [comment]
위의 문장의 첫 번째 '아직'을 '사실'로 바꿔서
'사실 '완성'이라고 하기에는 이릅니다. 그 기계는 아직 불완전하거든요.'
라고 하면 금상첨화일 듯 합니다.

**Comment by STRIKE-F** [comment]
좀 너무 바꾼 게 아닌지는 모르겠는데
'뭐, 그 기계는 아직 많이 불완전해서 '완성'이라고 하기는 힘들지만요.' 이렇게 하는 건 어떤가요?

**Comment by Porowl** [comment]
사실 ''완성''이라고 하기에는 일러요. 그 
기계는 아직 불완전하거든요.
