### ISSUE TITLE
왜요? 무슨 일이세요? ...아, 알 것 같아요. 또 바나나에 대한 수수께끼가 떠오르신 거죠?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2410]
![screenshot_2016-08-05-01-47-09](https://cloud.githubusercontent.com/assets/19295794/17508031/daac8fdc-5e4d-11e6-94c5-dd714b54ce11.png)

말줄임표와 '아,' 사이에 한 칸을 띄는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
