### ISSUE TITLE
바나나 껍질이 마을 사방에 다 있네요. 미래의 사람들은 쓰레기를 아무 데나 버리는 걸 좋아하는 걸까요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2412]
![screenshot_2016-08-05-01-50-19](https://cloud.githubusercontent.com/assets/19295794/17508114/5fd9ed9e-5e4e-11e6-9024-c474200fd2ca.png)

2행의 '다 있네요.' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
