### ISSUE TITLE
지금까지 본 바나나 껍질을 생각하면, 그렇다 해도 별로 놀랍지 않을 것 같구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2413]
![screenshot_2016-08-05-01-50-22](https://cloud.githubusercontent.com/assets/19295794/17508177/9e4fc4e0-5e4e-11e6-8018-8e177ef9a700.png)

지금까지 본 바나나 껍질을 생각하면,
그렇다 해도 별로 놀랍지 않을 것 같구나.

로 개행 수정하면 어떨까 하는데 공간이 되나요?

**Comment by STRIKE-F** [comment]
현재는

지금까지 본 바나나 껍질을 생각하면, 
그렇다 해도 별로 놀랍지 않구나.

로 수정했습니다,.
