### ISSUE TITLE
호텔로 돌아가는데 너무 시간을 많이 낭비하고 싶지 않으니 지하철을 타는 것이 좋겠구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2414]
![screenshot_2016-08-05-01-50-37](https://cloud.githubusercontent.com/assets/19295794/17508241/f4145b7a-5e4e-11e6-93f5-d0e50c08a8c4.png)

호텔로 돌아가는 데 너무 시간을 많이
낭비하고 싶지 않으니
지하철을 타는 것이 좋겠구나.

로 개행과 내용 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
호텔로 돌아가는  시간을 아끼게
지하철을 타자꾸나.

이렇게 바꾸는 게 어떨까 싶네요.

**Comment by yhwon90** [comment]
스프님 제안이 좋아보이네요
한가지만 첨언해보자면 호텔로 돌아가는 시간을 아끼도록~ 은 어떨까요?

**Comment by Y00N** [comment]
**호텔까지 거리가 제법 있으니까
지하철을 타면 시간을 아낄 수 있겠구나.**
어떤가요?

**Comment by jungin019** [comment]
현로님 의견도 괜찮네요
