### ISSUE TITLE
나도 마무리해야 할 일거리가 있어서 가는 것일 뿐이야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2415]
![screenshot_2016-08-05-01-50-53](https://cloud.githubusercontent.com/assets/19295794/17508278/2962faca-5e4f-11e6-9295-eaf58ad1af37.png)

나도 마무리해야 할
일거리가 있어서 가는 것 뿐이야.

로 내용과 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
현재는

나도 마무리해야 할 일거리가 있어서
가는 거라고.

로 수정했습니다.
