### ISSUE TITLE
빨리도 가 버렸네요. 선생님, 정말로 저렇게 혼자 행동하게 놔둬도 괜찮은 거예요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2416]
![screenshot_2016-08-05-01-51-04](https://cloud.githubusercontent.com/assets/19295794/17508361/8b25b2e8-5e4f-11e6-99d7-b4a2e16fdecd.png)

빨리도 가 버렸네요, 선생님.
정말로 저렇게 혼자 행동하게 놔둬도
괜찮은 거예요?

로 내용과 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
우와, 엄청 빨리도 가 버렸네요. 
선생님, 정말 저렇게 혼자 다니게 놔둬도 
괜찮은 거예요?

현재 이렇게 수정했습니다.
