### ISSUE TITLE
디미트리가 호크스 수상님을 데리고 육각거탑에서 도망쳤으니, 분명 다른 은신처가 있을 거야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2417]
![screenshot_2016-08-05-01-51-26](https://cloud.githubusercontent.com/assets/19295794/17508388/b52b0228-5e4f-11e6-8c75-fabfa163287a.png)

2행의 '데리고' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
