### ISSUE TITLE
아, 디미트리의 다른 기지를 찾아야 한다는 거군요! 알겠어요. 아, 그러기 전에 일단 호텔에 들러야죠.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2418]
![screenshot_2016-08-05-01-51-29](https://cloud.githubusercontent.com/assets/19295794/17508429/d93cb512-5e4f-11e6-8dc5-ebd9bbafb24f.png)

아, 디미트리의 다른 기지를
찾아야 한다는 거군요! 알겠어요.
아, 그러기 전에 일단 호텔에 들러야죠.

로 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
아, 디미트리의 다른 기지를
찾아야 한다는 거군요! 알겠어요.
근데, 그러기 전에 일단 호텔에 들러야죠.

오역 약간 수정해서 현재 이렇게 고쳤습니다.
