### ISSUE TITLE
밖으로 나온 후, 루크, 레이튼과 돈 파올로는 디미트리의 야망과 어두운 과거에 대해 이야기를 나눈다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2422]
![screenshot_2016-08-05-13-13-40](https://cloud.githubusercontent.com/assets/19295794/17508594/a3fe810e-5e50-11e6-9c7e-8d7af5f5c4a0.png)

밖으로 나온 후, 루크, 레이튼, 돈 파올로는
디미트리의 야망과 어두운 과거에 대해
이야기를 나눈다.

로 개행 수정하면 어떨까 하는데 공간이 되나요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
