### ISSUE TITLE
많은 의문점에 대한 해답을 얻은 후, 일행은 플로라를 만나기 위해 듀크 호텔로 돌아가기로 했다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2423]
![screenshot_2016-08-05-13-13-48](https://cloud.githubusercontent.com/assets/19295794/17508635/df6333d4-5e50-11e6-9bbb-30e61e012045.png)

2행의 '듀크' 는 다음 행으로 넘기는 게 어떨까요?

그리고 문장에서 번역체스러운 느낌이 약간 있다고 생각하는데

다른 분들은 어떻게 생각하시나요?

**Comment by yhwon90** [comment]
많은 궁금증이 해결되었고
많은 의문점이 해결되었고
정도..?ㅠ

**Comment by Y00N** [comment]
**많은 의문점을 해결한 레이튼 일행은
플로라를 만나러 듀크 호텔로
돌아가기로 했다.**

정도면 되지 않을까요?

**Comment by jungin019** [comment]
현로님 의견 괜찮은 것 같아요
