### ISSUE TITLE
친구가 적어 준 약도는 완전히 말도 안 되고요. 혹시 이것 좀 봐주실 수 있나요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2424]
![screenshot_2016-08-05-13-14-40](https://cloud.githubusercontent.com/assets/19295794/17508678/1db185be-5e51-11e6-9d60-5a287ddffbf8.png)

친구가 적어준 약도는
완전히 말도 안 되고요.
혹시 이것 좀 봐주실 수 있나요?

로 내용과 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
친구가 약도를 그려 줬는데 
도대체 이해할 수가 없더라고요 .
혹시 이것 좀 봐주실 수 있나요?

현재는 이렇게 수정됐습니다.
