### ISSUE TITLE
친구 부모님이랑 제 아빠가 집에 잘 들어오시지 않으시거든요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2425]
![screenshot_2016-08-05-13-16-00](https://cloud.githubusercontent.com/assets/19295794/17508705/42242e42-5e51-11e6-8d96-8fa81a8358d8.png)

1행의 '집에 잘' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
