### ISSUE TITLE
네. 아빠랑 이 마을의 어른들은 거의 다요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2427]
![screenshot_2016-08-05-13-16-09](https://cloud.githubusercontent.com/assets/19295794/17508758/7df63442-5e51-11e6-8e92-63c06315437c.png)

1~2 행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by STRIKE-F** [comment]
내용 수정을 약간 해서 현재는

네. 아빠랑 이 마을의 어른들 대부분이요.

로 수정되었습니다.
