### ISSUE TITLE
내가 가진 수수께끼가 조금 날 애먹여서 말야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2428]
![screenshot_2016-08-05-13-16-34](https://cloud.githubusercontent.com/assets/19295794/17508791/ab0459e6-5e51-11e6-97ce-a17abe45a443.png)

내가 가진 수수께끼가
날 조금 애먹여서 말야.

로 개행과 내용 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
이 수수께끼가 날 좀 애먹여서 말야.

현재 이렇게 수정됐습니다.
