### ISSUE TITLE
수수께끼라고요? 그럼 제대로 찾아오셨네요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2429]
![screenshot_2016-08-05-13-16-37](https://cloud.githubusercontent.com/assets/19295794/17508808/cbd92282-5e51-11e6-80ae-dbadbe74dae2.png)

1행의 '그럼' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
수수께끼라고요? 운이 좋으시네요!
제가 그쪽엔 전문가거든요.

오역(?) 비스무리한 걸 수정해서 현재 이렇게 수정했습니다.
