### ISSUE TITLE
[맞춤법] 그럼 그럼. 당연하지 내 자신조차 믿을 수 없다면 대체 누구를 믿을 수 있겠니?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#243]
![image](https://cloud.githubusercontent.com/assets/19265176/15180673/fc9c01a8-17bd-11e6-97f4-60c473b87d6d.png)

그럼 그럼 당연하지. 내 자신조차 믿을 수 없다면 대체 누구를 믿을 수 있겠니? 식으로 온점의 위치를 바꾸어야 할 듯 합니다.

**Comment by jungin019** [comment]
그럼, 당연하지. ~ 로 수정.
