### ISSUE TITLE
흥미로운 책이 정말 많은데요? 근데 전 돈이 없는데..

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2432]
![screenshot_2016-08-05-13-55-57](https://cloud.githubusercontent.com/assets/19295794/17508913/54cd20d4-5e52-11e6-873d-064d841f8d47.png)

말줄임표는 마침표 세 개를 사용하는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정헀습니다.
