### ISSUE TITLE
저, 손님들에게 도서관으로 가서 책을 읽으라고 하는건... 장사에 도움이 안 되지 않나요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2433]
![screenshot_2016-08-05-13-56-11](https://cloud.githubusercontent.com/assets/19295794/17508946/7b282580-5e52-11e6-8708-35394231dcfb.png)

저, 손님들에게 도서관으로 가서
책을 읽으라고 하는 건...
장사에 도움이 안 되지 않나요?

로 개행과 내용 수정하는 것은 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
