### ISSUE TITLE
아마도. 근데 더 많은 사람들이 책에 더 관심을 가지기만 한다면 난 별로 상관없어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2434]
![screenshot_2016-08-05-13-56-14](https://cloud.githubusercontent.com/assets/19295794/17508994/ac36e44a-5e52-11e6-99be-3214558f4247.png)

아마도. 근데 더 많은 사람들이
책에 관심을 더 가지기만 한다면
난 별로 상관없어.

로 내용과 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
번역 약간 수정해서 현재는

어쩌면. 그래도, 더 많은 사람들이
책에 관심을 더 가져 준다면 난 괜찮아!

로 수정했습니다.
