### ISSUE TITLE
고마워요. 평소에 용돈에 엄청 신경쓰며 사는 편이라 이 수수께끼는 정말 쉬웠어요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2435]
![screenshot_2016-08-05-13-59-41](https://cloud.githubusercontent.com/assets/19295794/17509048/fad57440-5e52-11e6-8b14-0d8e70fd8b1e.png)

'~에' 라는 표현이 반복되는데 수정할 수는 없을까요?

**Comment by yhwon90** [comment]
'평소에'를 빼도 좋아보이고
'평소'로 바꿔도 될 것 같고
'원래'로 바꾸면 좀 어색한데 여튼 '~에'가 반복되니 좀 이상하네요

**Comment by Y00N** [comment]
**평소에 용돈을** 이라고 하면 되지 않나요?

**Comment by Porowl** [comment]
그런 간단한 방법이...
