### ISSUE TITLE
무슨...일이 있으신가요? 평소처럼, 음, 밝은 분위기가 아닌데요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2436]
![screenshot_2016-08-05-14-00-12](https://cloud.githubusercontent.com/assets/19295794/17509073/219cf080-5e53-11e6-8e83-cb7dbc976ee8.png)

무슨... 일이 있으신가요?
평소처럼, 음, 밝은 분위기가 아닌데요.

로 개행과 내용 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
뭔가...일이라도 있으셨나요? 
평소처럼, 음, 밝은 분위기가 아니네요. 

현재는 이렇게 수정했습니다.
근데 , 음, 이게 좀 어색해 보여서 다른 아이디어가 있다면 올려 주세요.

**Comment by yhwon90** [comment]
음..., 평소처럼 밝은 분위기가 아니네요.
는 어떤가요?

**Comment by Y00N** [comment]
**무슨... 일이 있으세요?
평소엔 밝던 분이 오늘은 영 아닌데요.**
어떤가요?
