### ISSUE TITLE
정말 괜찮으신 거에요? 대화가 평소같이 생기넘치지가 않는데요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2437]
![screenshot_2016-08-05-14-00-19](https://cloud.githubusercontent.com/assets/19295794/17509106/5018cb5a-5e53-11e6-8aeb-8f3615f3ff42.png)

정말 괜찮으신 거예요?
대화가 평소 같이 생기 넘치지가 않늗데요.

로 개행과 내용 수정하면 어떨까 하는데 공간이 되나요?

**Comment by STRIKE-F** [comment]
생기 넘치지 는 수정했습니다. 같이는 조사라서 붙여 쓰는 게 맞습니다.

**Comment by Y00N** [comment]
정말 괜찮으세요?
평소같지 않게 말씀에 기운이 없는데요.

어떤가요?

**Comment by Porowl** [comment]
평소같지 않게 말씀에 기운이 없는데요.
만 적용시키겠습니다.
