### ISSUE TITLE
생기넘치지 않는다라. 흠. 그럴지도 모르겠구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2438]
![screenshot_2016-08-05-14-00-22](https://cloud.githubusercontent.com/assets/19295794/17509146/75c652aa-5e53-11e6-949b-d31fa86ac004.png)

1행의 '그럴지도' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
