### ISSUE TITLE
음. 아직 아내 분과의 오해를 풀지 않으셔서 그런 거죠?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2439]
![screenshot_2016-08-05-14-00-27](https://cloud.githubusercontent.com/assets/19295794/17509176/93ad1236-5e53-11e6-82fb-fb7e8e60fc0a.png)

1행의 '풀지' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
음. 아직 아내분과 오해를 못 푸셔서
그런 거죠?

어색해 보이는 표현을 좀 고쳐서 현재 이렇게 수정했습니다.
