### ISSUE TITLE
[건의사항] 의문점들_모자파(해결)

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#245]
![image](https://cloud.githubusercontent.com/assets/19265176/15180808/b28e6c08-17be-11e6-8507-50938b4a10a0.png)

게임 상에서 모자파는 현실의 갱단이나 마피아 같은 조직입니다. 일어판에서 갱단, 북미판에서 패밀리로 불리는 이유가 거기에 있죠. 그런데 모자파에 대한 설명이 너무 부실한 것 같아서 이렇게 올리게 되었습니다. 

일단 범죄조직이라는 것 정도를 추가해서 

'이 사람들은 미래의 레이튼이 이끄는 ‘모자파’라는 이름의 범죄조직의 일원이라고 한다. '

정도로 서술하는 것은 어떨까 합니다.

**Comment by jungin019** [comment]
원문은 'These shady characters are members of a gang called the Family that's led by the future
Professor Layton.' 입니다. 
'이 수상한 사람들은 미래의 레이튼이 이끄는 '모자파'라는 이름의 범죄조직의 일원이라고 한다.' 라고 하는 건 어떨까요?

**Comment by kaleidoscope531** [comment]
'이 수상한 사람들은 미래의 레이튼이 이끄는 '모자파'라는 범죄조직의 일원이라고 한다.' 
'이름의' 도 빼 보았습니다. 
좋은 것 같습니다.

**Comment by bombomS2** [comment]
이 수상한 사람들은 미래의 레이튼이 이끄는 '모자파'라는 범죄 조직의 일원이라고 한다.
범죄 조직은 띄어 씁니다. 처음보다 많이 좋은 문장이 된 것 같아요.

**Comment by Porowl** [comment]
위 내용으로 수정하였습니다.
