### ISSUE TITLE
저 수수께끼들이 "날 풀어주세요!" 하고 외치는 소리가 안들려? 안 풀어준다면 넌 정말 나쁜 사람이야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2450]
![screenshot_2016-08-05-14-04-35](https://cloud.githubusercontent.com/assets/19295794/17509568/938932a6-5e55-11e6-8dc3-dfb0fa0618a4.png)

저 수수께끼들이 "날 풀어주세요!" 하고
외치는 소리가 안 들려?
안 풀어준다면 넌 정말 나쁜 사람이야.

로 내용과 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
