### ISSUE TITLE
[건의사항] 의문점들_미래의 레이튼 교수

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#246]
![image](https://cloud.githubusercontent.com/assets/19265176/15180915/4a249f06-17bf-11e6-8cea-41000e385ad8.png)

'처음의 '미래의 허셜 레이튼은 런던을 그의 조직으로 강압 통치를 하고 있었다.' 이 문장이 좀 어색한 것 같습니다. 

일단 제가 좀 바꿔 본 것은 이렇습니다. 

'미래의 허셜 레이튼은 그의 범죄조직을 이용하여 런던에 강압 통치를 행하고 있었다.'

그리고 뒤에 따라 붙는 '많은 런던 사람들이 그를 "높은 모자의 악마"로 부르며 무서워 했다고 한다.' 문장 앞에 단어를 덧붙여서 원인과 결과를 확실히 하는 것도 좋을 것 같습니다. 예를 들자면 '이에'를 붙여서

'미래의 허셜 레이튼은 그의 범죄조직을 이용하여 런던에 강압 통치를 행하고 있었다. 
이에 많은 런던 사람들이 그를 "높은 모자의 악마"라 부르며 무서워했다고 한다.'

같은 식으로 하는 것이 어떨까요?

**Comment by jungin019** [comment]
말씀하신 것도 괜찮을 것 같습니다. 그리고 원문에 쓰인 단어가 terrorize : 공포에 떨게 하다 이기 때문에 꼭 강압 통치라는 말을 넣지 않아도 무방합니다.

**Comment by STRIKE-F** [comment]
특별히 다른 의견이 없는 것 같아서 위에 올라온 대로 수정하겠습니다
