### ISSUE TITLE
[건의사항] 의문점들_스턴건 박사

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#247]
![image](https://cloud.githubusercontent.com/assets/19265176/15181106/404acb4e-17c0-11e6-9f42-bb5a2d5cc744.png)

마지막에 '그래서, 그는 누구인가?'에서 그래서 대신에 그렇다면이 더 어울릴 것 같습니다. 
'그렇다면 그는 누구인가?'로 바꾸는 편이 더 좋지 않을까요?

**Comment by jungin019** [comment]
해당 문장이 'So, who is he?'라서 그렇게 번역한 것 같네요. 
'그렇다면 그는 누구인가?' 나 '그럼 그는 누구일까?' 정도가 좋을 것 같군요

**Comment by bombomS2** [comment]
그렇다면, 그는 누구일까? 가 좋을 것 같아요.
덧붙여, 과학자로써의→과학자로서의 로 고쳐야 하지 않을까 싶습니다.

**Comment by STRIKE-F** [comment]
한국어 정서에는 도대체 그는 누구일까? 가 더 자연스러울 것 같은데, 어떤가요?

**Comment by Porowl** [comment]
스턴건 박사는 타임머신 연구를 
진행한 과학자이지만, 
과학자로써의 연구 성과는 전혀 없다. 
아마도 그는 자신의 진짜 이름을 
숨기고 있는 것 같다. 
도대체 그는 누구일까?
