### ISSUE TITLE
[건의사항] 루크 : 그런 생각은 못 했네요. 타임머신이 개발되는 건 막아야겠네요!

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#248]
![image](https://cloud.githubusercontent.com/assets/19265176/15181500/9d1cb47a-17c2-11e6-8cd9-428ddaf753d6.png)

두 문장 다 ~ㅆ네요로 끝나서 조금 어색한 것 같습니다. 

'그런 생각은 못 했어요. 타임머신이 개발되는 건 막아야겠네요!' 또는
'그런 생각은 못 했네요. 타임머신이 개발되는 건 막아야겠어요!'로 하는 것이 어떨까요?

**Comment by jungin019** [comment]
'그런 생각은 못 했어요. 타임머신이 개발되는 건 막아야겠네요!' 가 좋을 것 같군요

**Comment by Porowl** [comment]
'그런 생각은 못 했어요. 타임머신이 개발되는 건 막아야겠네요! 로 수정하겠습니다.
