### ISSUE TITLE
허허. 모자파라는 게 그런 거지 뭐. 사기꾼 무리가 각자 맡은 역할을 하는 거.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2485]
![screenshot_2016-08-05-14-31-51](https://cloud.githubusercontent.com/assets/19295794/17515013/de69b8ac-5e70-11e6-9eff-dcb9805c3bba.png)

2~3 행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
칸이 안 남아 닫겠습니다.
