### ISSUE TITLE
[건의사항] 파이아르 대사 관련

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#249]
앞서 언급한 이슈도 있습니다만 가게를 열기 전의 파이아르의 대사는 이렇습니다. 

![image](https://cloud.githubusercontent.com/assets/19265176/15181583/f9c7e136-17c2-11e6-8819-c72f8b985680.png)
일단 이 부분은 못 봤니? 를 못 봤나? 로 바꾸는 걸로 이슈를 닫은 상태입니다.
 
![image](https://cloud.githubusercontent.com/assets/19265176/15181588/fea855dc-17c2-11e6-9680-c7e22dce6867.png)

이 부분도 '맥스 이 도움 안되는 녀석 같으니라고'로 바꾸는 걸로 이슈를 닫았을겁니다. 

중요한 건 이 때의 파이아르는 시장골목에서 재료 손질하는 아저씨(?) 같은 걸걸함을 가진 캐릭터의 느낌입니다. 

그런데 가게를 열고 나서 찾아가 봤을 때의 파이아르는 이렇습니다. 

![image](https://cloud.githubusercontent.com/assets/19265176/15181665/6bd4381a-17c3-11e6-87e2-b49bbe73b835.png)

말투가 매우 공손해진 것을 알 수 있습니다. 심지어 위의 상황의 청자는 레이튼 교수가 아닌 루크임에도 말입니다. 

따라서 파이아르의 말투를 전자와 후자 중 하나로 통일하는 것이 필요할 것 같습니다.

**Comment by jungin019** [comment]
아무래도 여러 사람이 번역을 하다보니 말투 등에 이런 오류가 있을 수 있습니다. 
말투는 전자로 수정을 하고 일단 이슈는 열어놓겠습니다.

**Comment by jungin019** [comment]
일단 위의 부분은 전체적으로 수정했습니다.
