### ISSUE TITLE
그게 내가 일하는 방식이란다. 설령 이런 무법천지 범죄도시라도 말이지!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2497]
![screenshot_2016-08-05-15-00-26](https://cloud.githubusercontent.com/assets/19295794/17515395/128ef2d0-5e73-11e6-9e83-7c1b8b5d2a4e.png)

2~3 행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by Porowl** [comment]
좁아요
