### ISSUE TITLE
[건의사항] 레이튼 : 큰 루크 넌 육각거탑이란 말을 잘 이해한 것 같은데. 거긴 대체 어떤 장소니?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#250]
![image](https://cloud.githubusercontent.com/assets/19265176/15181714/b782187c-17c3-11e6-8079-129967a0e5af.png)

'큰 루크 넌 육각거탑이란 말을 잘 이해한 것 같은데.' 이 부분을 좀 다듬었으면 합니다. 
'큰 루크 넌 육각거탑이라는 곳에 대해 잘 알고 있는 것 같던데.' 정도가 어떨까요?

**Comment by jungin019** [comment]
원문이 'Big Luke, you seemed apprehensive at the mention of the Towering Pagoda.
What is this place?'군요. 오역이 섞인 것 같네요. 
'큰 루크, 육각거탑 얘기가 나왔을 때 걱정을 하는 것 같던데. 어떤 곳이기에 그러니?' 정도가 좋겠네요

**Comment by bombomS2** [comment]
네, 좋은 문장 같습니다.
걱정스러워하는 것 같던데. 라는 표현도 좋을 것 같아요.

**Comment by STRIKE-F** [comment]
별다른 의견 없다면 위에 올리신 대로 수정하겠습니다
