### ISSUE TITLE
아, 우리가 여기 돌아왔더니 콧수염을 기른 한 아저씨가 로비에서 기다리고 계시더라고.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2516]
![screenshot_2016-08-05-15-12-41](https://cloud.githubusercontent.com/assets/19295794/17515907/33e0afd4-5e76-11e6-85c8-5e0becf6106d.png)

아, 우리가 여기 돌아왔더니
콧수염을 기른 한 아저씨가
로비에서 기다리고 계시더라고.

로 개행 수정하면 어떨까요?

**Comment by Porowl** [comment]
<T>아, 여기 들어올때 보니까 
콧수염을 기른 한 아저씨가 
로비에서 기다리고 계시더라고.
