### ISSUE TITLE
말도 없이 갑자기 와서 미안하네, 레이튼.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2522]
![screenshot_2016-08-05-15-13-45](https://cloud.githubusercontent.com/assets/19295794/17516067/35d49df4-5e77-11e6-8141-81193677d691.png)

1~2 행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by Porowl** [comment]
좁아요
