### ISSUE TITLE
[건의사항] 스턴건: 그런고로, 우리 특별 손님을 위해 아주 특별한 자리를 마련했습니다

### ISSUE THREAD

**Issue by yhwon90** [elfinlazz/lt3translation#253]
'우리 특별 손님'이 마음에 걸리네요ㅠ
청해로 들리는 원문은 as such, I reserved a very special seat, for a very special guest 입니다.
아주 특별한 손님을 위해 아주 특별한 자리를 마련했습니다..를 생각해봤는데 너무 반복되는 느낌이라..

**Comment by kaleidoscope531** [comment]
'이 행사의 가장 특별한 손님을 위하여 그에 걸맞는 자리를 준비했습니다. ' 같은 식은 어떨까요?

**Comment by yhwon90** [comment]
kaleidoscope 님의 번역이 마음에 드네요 ㅎㅎ

**Comment by bombomS2** [comment]
좋은 문장인 것 같습니다.

**Comment by Latteria** [comment]
채택하겠습니다
