### ISSUE TITLE
길을 잃은 것 같지는 않아서 가게 내버려 뒀는데요. 오, 이런 줄 알았으면 물어라도 보는 건데,.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2540]
![screenshot_2016-08-05-15-29-06](https://cloud.githubusercontent.com/assets/19295794/17518066/438438c4-5e81-11e6-8280-727a656b68b6.png)

길을 잃은 것 같지는 않아서
가게 내버려 뒀는데요.
오, 이런 줄 알았으면 물어라도 보는 건데.

로 개행 수정하면 어떨까 하는데 공간이 되나요?

**Comment by Porowl** [comment]
안되네요
