### ISSUE TITLE
아직 걱정할 필요는 없겠지만, 혹시 루크를 보면 저희가 찾고 있다고 전해주세요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2546]
![screenshot_2016-08-05-15-29-34](https://cloud.githubusercontent.com/assets/19295794/17518247/1549b2da-5e82-11e6-8928-29399f71eff3.png)

1행의 '혹시' 는 다음 행으로 넘기는 게 어떨까요?

그리고 2행에서 '~고' 라는 표현이 반복되는데 다른 분들은 어떻게 생각하시나요?

**Comment by Porowl** [comment]
이정도면
