### ISSUE TITLE
레이튼은 모든 음모의 배후인 클라이브의 정체를 밝혀낸다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2574]
![screenshot_2016-08-08-16-25-42](https://cloud.githubusercontent.com/assets/19295794/17522346/a0df474c-5e91-11e6-9abe-60073620e2f1.png)

'~의' 라는 표현이 반복됩니다.

**Comment by Porowl** [comment]
이정도면
