### ISSUE TITLE
수수께끼 12 그냥 옮겨놓기만 한다면 수식은 성립되지 않는다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#258]
![kakaotalk_20160511_233909305](https://cloud.githubusercontent.com/assets/19270364/15188867/db7ddb5c-17e2-11e6-8939-f33cd8b062b0.jpg)

수식이 성립[되다]와 [하다]를 혼용하고 있습니다.
특별한 이유가 있는 게 아니라면 피동 표현을 삼가고 [수식이 성립하다]로 통일하면 좋겠습니다.

**Comment by Porowl** [comment]
성립하지 않는다 가 옳은 표현인듯 싶습니다.

**Comment by kaleidoscope531** [comment]
성립하지 않는다로 통일하는 것이 좋아보입니다.
