### ISSUE TITLE
아, 매기 말이군. 무서운 면도 있지만, 그녀는 좋은 사람이지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2592]
![screenshot_2016-08-05-19-48-59](https://cloud.githubusercontent.com/assets/19295794/17539486/a14e7c2c-5ee9-11e6-94eb-fdff859f3fdb.png)

호텔 지배인의 이름은 '마가렛' 으로 알고 있는데 '매기' 는 별명인가요?

**Comment by Porowl** [comment]
애칭입니다.
