### ISSUE TITLE
흠. 알겠네. 근데 강을 건너기는 힘들 거라는 걸 미리 얘기해두지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2595]
![screenshot_2016-08-05-19-50-05](https://cloud.githubusercontent.com/assets/19295794/17539566/1b652d1c-5eea-11e6-8c23-2932366fbaeb.png)

흠. 알겠네. 근데 강을 건너기는
힘들 거라는 걸 미리 얘기해 두지.

로 수정하면 어떨까 합니다.

그리고 '~거' 라는 표현이 반복되는데 다른 분들은 어떻게 생각하시나요?

**Comment by Porowl** [comment]
흠. 알겠네. 근데 강을 건너기는 
힘들다는 건 미리 얘기해두지.
