### ISSUE TITLE
누나가 맞는 것 같아요. 이제 문을 여는 스위치만 찾으면 돼요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2598]
![screenshot_2016-08-05-20-01-02](https://cloud.githubusercontent.com/assets/19295794/17539641/b6b2223e-5eea-11e6-839e-3a4551067bee.png)

1행의 '이제 문을 여는' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by dwcy2306** [comment]
수정했습니다

**Comment by Porowl** [comment]
누나 말이 맞아요
