### ISSUE TITLE
방금 나랑 얘기하려고 한거야?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#260]
![kakaotalk_20160511_233912586](https://cloud.githubusercontent.com/assets/19270364/15189007/7d33ff30-17e3-11e6-9fae-b1ef84b4abc3.jpg)

[방금 나랑 얘기하려고 한 거야?] 라고 띄어쓰는 게 맞습니다.
그리고 기왕이면 아래 문장도 '~처럼 보이다' 라는 표현을 쓰기보다 [내가 얘기하고 싶어 보이냐?] 라는 식으로 쓰는 게 더 좋다고 생각합니다.

**Comment by jungin019** [comment]
띄어쓰기는 수정했습니다.

**Comment by bombomS2** [comment]
내가 얘기하고 싶은 걸로 보여? 는 어떤가요?

**Comment by kaleidoscope531** [comment]
여담으로 '방금 나랑 얘기하려고 한 거야?'를 '방금 나한테 말 건 거야?'로 바꾸는 것은 어떨까요?

**Comment by Porowl** [comment]
네가 누구랑 얘기하고 있는지는 알고 있냐? 는 너무 의역일까요.

**Comment by bombomS2** [comment]
영판 원문과 일판 원문을 한번 확인해 봐야 할 것 같네요.

**Comment by jungin019** [comment]
영판 원문은 'You did NOT just try to talk to me. Do I LOOK like I want to talk?' 로
직역하면 '너 방금 나한테 말 걸려고 그런 거 아니지? 내가 말을 하고 싶은 걸로 보여?' 정도가 됩니다.

**Comment by bombomS2** [comment]
어우, 대문자 강조가 무섭네요.
너 설마 방금 나한테 말 걸려고 한 거야? 내가 말하고 싶어 안달난 사람처럼 보여?
는 좀 셀까요?

**Comment by Y00N** [comment]
내가 너랑 이야기나 하게 생겼냐?

**Comment by kaleidoscope531** [comment]
합치면 '너 설마 방금 나한테 말 걸려고 한 거야? 내가 너랑 이야기나 하게 생겼냐? 응?' 인가요.
좋은데요?

**Comment by Porowl** [comment]
오, 오, 오! 너 설마 방금 나한테 
말 걸려고 한 거야? 내가 너랑 이야기나 
하게 생겼냐? 응?
