### ISSUE TITLE
저기에 커다란 흰 벽이 있는 건물이 호텔이야.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#261]
![kakaotalk_20160511_233914286](https://cloud.githubusercontent.com/assets/19270364/15189064/c7ac995a-17e3-11e6-83a7-4616394e7bb4.jpg)

[커다란]이 [흰 벽]을 꾸미는지 [건물]을 꾸미는지 명확하지 않습니다.
건물을 꾸미는 것이라면 굳이 벽을 쓰지 않고 [커다란 흰 건물이 호텔이야] 로도 충분하다고 생각합니다.

**Comment by jungin019** [comment]
커다란 흰 건물이 호텔이야 로 수정했습니다
