### ISSUE TITLE
벽이 흰색으로 칠해진 건물을 찾으시면 돼요

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#262]
![kakaotalk_20160511_233916363](https://cloud.githubusercontent.com/assets/19270364/15189131/1d07c168-17e4-11e6-8bd2-f083c3382830.jpg)

지나친 피동 표현을 피해보려 했는데 딱 맘에 드는 표현이 없어서 여러가지 생각해봤습니다. 
[벽을 흰색으로 칠한 건물을 찾으시면 돼요]
[벽이 하얀 건물을 찾으시면 돼요]
[흰색 건물을 찾으시면 돼요]
이렇게 보니 세 번째 문장이 제일 맘에 들긴 합니다.

**Comment by jungin019** [comment]
흰색 건물로 수정했습니다.
