### ISSUE TITLE
내가 스스로에게 어떻게 이런 일이 가능한지 묻고 있을 때

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#263]
![kakaotalk_20160511_233917852](https://cloud.githubusercontent.com/assets/19270364/15189299/cdc3d578-17e4-11e6-9180-22d8ce208f40.jpg)

'스스로'는 조사가 필요 없습니다. 그냥 '스스로'만 쓰거나, '-에게'를 붙이고 싶다면 '자신에게'라고 쓰면 됩니다.

**Comment by bombomS2** [comment]
스스로에 조사를 붙이는 게 문법적 오류까지 되지는 않지만, 문장이 전체적으로 다소 어색한 것 같습니다.
믿을 수 없지만 우리가 정말 10년 후의 런던으로 온 것 같다. 어떻게 이런 일이 가능한지 스스로를 의심하고 있을 때, 마치 그것을 예상이라도 한 듯 미래의 루크에게서 두 번째 편지가 도착했다. 편지에 적힌 내용으로는, 오클랜드 가에 있는 그린 병원으로 가면 더 많은 정보를 얻을 수 있을 것으로 보인다.
의미는 대충 통하게 고쳤지만 간과한 부분이 있겠지요. 새로운 의견이나 다듬어야 할 곳에 대한 지적이 많이 필요할 것 같습니다.

**Comment by STRIKE-F** [comment]
믿을 수 없지만 우리가 정말로 10년 후에 런던으로 온 것 같다. 어떻게 이런 일이 가능한지 고민하는 동안, 어디서 보기라도 한 듯이 미래의 루크가 두 번째 편지를 보내왔다. 편지를 읽어 보니, 오클랜드 가에 있는 그린 병원에서 더 많은 정보를 얻을 수 있을 것 같다.

어떤가요?

**Comment by kaleidoscope531** [comment]
믿을 수 없지만 우리가 정말로 10년 후에 런던으로 온 것 같다. 어떻게 이런 일이 가능한지 고민하는 동안, 어디서 보기라도 한 듯이 미래의 루크가 두 번째 편지를 보내왔다. 편지를 읽어 보니, 오클랜드 가에 있는 그린 병원에서 더 많은 정보를 얻을 수 있을 것 같다.

좋아 보입니다.
