### ISSUE TITLE
내가 그런 정보를 퍼뜨린다는것을 모자파 녀석들이 알기라도 해봐! 상상만 해도 끔찍하다고.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2636]
![screenshot_2016-08-05-20-32-37](https://cloud.githubusercontent.com/assets/19295794/17579816/f0992800-5fd3-11e6-9889-de189e2b3f4c.png)

호레이스가 레이튼에게 반말을 사용합니다.

**Comment by Porowl** [comment]
수정된 사항입니다.
