### ISSUE TITLE
...아뇨, 아닙니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2648]
![screenshot_2016-08-05-20-40-06](https://cloud.githubusercontent.com/assets/19295794/17580126/f2e4127a-5fd6-11e6-97a7-e1f4489812ca.png)

말줄임표와 '아뇨,' 사이에 한 칸을 띄는 것이 좋겠습니다.

**Comment by Porowl** [comment]
다른 것으로 바뀌어 있슴다
