### ISSUE TITLE
난 빌에게 실험을 연기하자고 간청했지만, 그는 들은 체도 안 하더군.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2659]
![screenshot_2016-08-05-21-22-31](https://cloud.githubusercontent.com/assets/19295794/17610070/1f51bd62-606d-11e6-8b8d-0027670f20f7.png)

2행의 '간청했지만,' 은 1행 끝부분에 붙여 쓰면 어떨까 하는데 공간이 되니요?

**Comment by Porowl** [comment]
좁아요
