### ISSUE TITLE
이곳에 버스가 다니지 않는 것이 불편하진 않으신가요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#266]
![kakaotalk_20160511_233943487](https://cloud.githubusercontent.com/assets/19270364/15189594/90952e5c-17e6-11e6-9448-3baf47f8b177.jpg)

불필요하게 '-것'을 사용해 지나치게 명사화한 문장으로 보입니다.
'이곳에 버스가 다니지 않아서 불편하진 않으신가요?' 로도 충분하다고 생각합니다.

**Comment by kaleidoscope531** [comment]
저도 찬성입니다.

**Comment by bombomS2** [comment]
좋은 것 같습니다.
