### ISSUE TITLE
누군가가 당신을 장기 말로 쓰고 있단 걸, 알고 계셨나요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2663]
![screenshot_2016-08-05-21-25-23](https://cloud.githubusercontent.com/assets/19295794/17610199/1eb22756-606e-11e6-887f-84864a8f2317.png)

2행의 '있던 걸,' 은 1행 끝부분에 붙여 쓰면 어떨까 하는데 공간이 되나요?

**Comment by Porowl** [comment]
좁아요
