### ISSUE TITLE
대단하군요, 교수님. 제 정체를 알아내셨군요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2667]
![screenshot_2016-08-05-21-43-11](https://cloud.githubusercontent.com/assets/19295794/17610295/31952be2-606f-11e6-8cbb-788abdacf013.png)

'~군요.' 가 반복되는데 수정할 수는 없을까요?

**Comment by Latteria** [comment]
일판을 참고해 "레이튼 선생님... 당신은 정말 대단하군요..."
로 채택하겠습니다.
대본이랑 같이 수정하고 닫아주세요.

**Comment by STRIKE-F** [comment]
수정 완료
