### ISSUE TITLE
기사에 따르면 그 폭발로 열 명이 죽었고, 그 중 두 명은 네 부모님이었어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2669]
![screenshot_2016-08-05-21-43-23](https://cloud.githubusercontent.com/assets/19295794/17610567/c6d9302a-6071-11e6-87c3-cc4a7da82a62.png)

2행의 '죽었고,' 는 1행 끝부분에 붙여 쓰는 것이 어떨까 하는데 공간이 되나요?

**Comment by Porowl** [comment]
좁아요
