### ISSUE TITLE
앞으로도 5년 동안은 버스가 다닐 거라고 돼있는걸요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#267]
![kakaotalk_20160511_233945845](https://cloud.githubusercontent.com/assets/19270364/15189672/f171b920-17e6-11e6-8afe-7fe38e062e87.jpg)

아래 글과 마찬가지로 지나친 명사화의 문제가 있습니다.
그리고 '돼있을걸요'라는 피동 형식을 조금 다듬어서 연결해보면

'앞으로도 5년 동안은 버스가 다닌다고 하던데요?' 정도로도 충분하지 않을까요?

**Comment by kaleidoscope531** [comment]
저도 그 의견에 찬성합니다.

**Comment by bombomS2** [comment]
2년 전요? 하지만…공지에는 앞으로도 5년 동안은 버스가 다닌다고 하던데요?
이렇게 되는군요. 좋네요. '버스가' '다닌다고' 사이에 계속을 넣어도 좋을 것 같아요.

**Comment by STRIKE-F** [comment]
앞으로도 5년 동안은 버스가 계속 다닐 거라고 적혀 있던데요?

이렇게 하면 자연스러워 보입니다

**Comment by Porowl** [comment]
2년 전요? 하지만...공지에는 앞으로도 
5년 동안은 버스가 계속 다닐 거라고
적혀 있던데요?
