### ISSUE TITLE
도브 씨는 고작 5년 뒤에 세상을 떠나셨고, 막대한 재산을 네게 유산으로 남기셨지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2671]
![screenshot_2016-08-05-21-43-41](https://cloud.githubusercontent.com/assets/19295794/17610626/6598e610-6072-11e6-8abd-088a74657251.png)

도브 양은 5년 뒤에 세상을 떠나셨고,
막대한 재산을 네게 유산으로 남기셨지.

로 내용과 개행 수정하면 어떤가요?

**Comment by yhwon90** [comment]
도브 '씨'를 '양'으로 바꾸셨는데 그 때문에 뒤에 오는 '떠나셨고'가 어색합니다
도브 양은 ~ 떠났고 또는 도브 씨는 ~ 떠나셨고 로 통일하면 괜찮지 않을까요

**Comment by Y00N** [comment]
도브 씨는 고작 5년 뒤에 세상을 
떠나셨고, 네게 막대한 재산을 유산으로
남기셨지.

**Comment by Latteria** [comment]
'도브 씨는 고작 5년 뒤에 세상을 
 떠나셨고, 네게 막대한 재산을 유산으로
 남기셨지.' 로
채택합니다. 대본이랑 같이 수정하고 닫아주세요.

**Comment by STRIKE-F** [comment]
수정 완료
