### ISSUE TITLE
내가 2년 전에 이곳에 이사왔을 때부터 버스는 다니지 않았단다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#268]
![kakaotalk_20160511_233948209](https://cloud.githubusercontent.com/assets/19270364/15189789/9e392a4e-17e7-11e6-8c1f-c6a3a7ab4998.jpg)

'2년 전에 이사왔을 때부터'라는 말이 다소 의미가 모호합니다.
버스가 2년 전부터 운행을 중단했는지, 2년 전에 이사왔을 때 이미 버스가 운행을 중단했는지 말이죠.
원문을 확인하진 않았습니다만 
전자의 경우엔 [내가 2년 전에 이곳에 이사온 후로 버스는 다니지 않았단다] 
후자의 경우엔 [내가 2년 전에 이곳에 이사왔을 때, 버스는 이미 다니지 않았단다.]
정도로 바꾸는 게 어떨까요?

**Comment by jungin019** [comment]
원문은 'Those buses were already shut down when I moved to this city two years ago.'입니다. 
후자가 의미적으로 더 맞네요.

**Comment by kaleidoscope531** [comment]
'내가 이곳에 이사온 2년 전에도 버스는 다니지 않았단다.'는 어떻습니까?

**Comment by bombomS2** [comment]
내가 이곳에 이사 온 2년 전에도 버스는 다니지 않았어.
어미를 조금 수정했습니다. 이사 오다라는 표현은 띄어 적습니다.

**Comment by STRIKE-F** [comment]
이대로 수정했습니다.
