### ISSUE TITLE
내 움직임에는 반응하지 않지만 나 이외의 사람이 움직이는 즉시 반응할 거야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2682]
![screenshot_2016-08-12-06-21-31](https://cloud.githubusercontent.com/assets/19295794/17611071/8f08c00c-6076-11e6-9019-3e99cc9279d6.png)

**Comment by Porowl** [comment]
<T>내 움직임에는 반응하지 않지만 
다른 사람이 움직이는 즉시 반응할 거야.
