### ISSUE TITLE
여기 이 스위치를 눌러서 바닥에 심어져 있는 센서들이 무더기로 작동되게 했거든.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2683]
![screenshot_2016-08-12-06-20-45](https://cloud.githubusercontent.com/assets/19295794/17612382/d44ed478-6083-11e6-8a7a-7ec023dfea86.png)

**Comment by Porowl** [comment]
<T>여기 이 스위치를 눌러서 
바닥에 심어져 있는 센서들이 
무더기로 작동되게 했거든.
