### ISSUE TITLE
전 레이튼 교수에게 도전장을 내밀겁니다. 어리바리한 경찰 나리께서는 빠져주시죠.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2684]
![screenshot_2016-08-12-06-19-47](https://cloud.githubusercontent.com/assets/19295794/17612413/22683b0e-6084-11e6-9722-7b13f0a7e00a.png)

**Comment by Porowl** [comment]
좁아요

전 레이튼 교수에게 도전장을 
내밀겁니다. 어리바리한 
경찰 나리께서는 빠져주시죠.
