### ISSUE TITLE
말이 안 되죠. ...그의 궁극적 목표를 위해 사람들을 납득시킬 필요가 있지 않았다면요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2692]
![screenshot_2016-08-12-02-27-40](https://cloud.githubusercontent.com/assets/19295794/17624845/f53f799e-60d8-11e6-80a2-ed033f091367.png)

**Comment by Y00N** [comment]
말줄임표 뒤에 띄어 써야 합니다.
