### ISSUE TITLE
...아 정말 환상적이군! 또 다른 단서가 날아갔어. 이제 어떻게 해야 할지 감도 안 오는군.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2706]
![screenshot_2016-08-12-02-19-59](https://cloud.githubusercontent.com/assets/19295794/17625358/22646bee-60db-11e6-9ff4-799e9ce90cc1.png)

**Comment by Porowl** [comment]
<T>수수께끼가 안 풀리나 보군? 
뭐, 난 이 수수께끼를 풀기 전까진 
여기 있을 듯 하네만.
