### ISSUE TITLE
어쩌면 저 여성분이 다른 길을 알고 있을지도 모르겠구나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#271]
![kakaotalk_20160511_233958333](https://cloud.githubusercontent.com/assets/19270364/15190279/0574d9fe-17ea-11e6-81e7-9eb80ec81271.jpg)

'분'은 상대방을 높이는 표현입니다. 그리고 아래 글에서 언급했듯 '~고 있다'의 표현도 삼가면 좋겠습니다.
'저 여성분께서 다른 길을 알고 계실지도 모르겠구나' 까지는 아니더라도
'저 여성분이 다른 길을 아실지도 모르겠구나' 정도로 표현해야 하지 않나 싶네요.

**Comment by kaleidoscope531** [comment]
'저 여성분이 다른 길을 아실지도 모르겠구나' 좋습니다.

**Comment by bombomS2** [comment]
알고 계실지도 모르겠구나. 도 괜찮은 것 같은걸요. 고민이네요…

**Comment by STRIKE-F** [comment]
어쩌면 저 여성분께서 다른 길을 알려 주실지도 몰라. 어떤가요?

**Comment by Porowl** [comment]
어쩌면 저 여성분이 다른 길을
알고 계실지도 모르겠구나.
