### ISSUE TITLE
다시 땅 위로 올라왔으니, 모자파 녀석들을 완전히 따돌린 것 같네요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2710]
![screenshot_2016-08-12-02-15-55](https://cloud.githubusercontent.com/assets/19295794/17625581/1440cc32-60dc-11e6-81d2-b3ff75200270.png)

**Comment by Porowl** [comment]
<T>다시 땅 위로 올라왔으니, 
모자파 녀석들을 완전히 따돌렸겠죠?
