### ISSUE TITLE
여기를 돌아다니다 어느새 여기 왔습니다. 길 잃었습니다. 어디인지 모릅니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2715]
![screenshot_2016-08-12-02-12-43](https://cloud.githubusercontent.com/assets/19295794/17625843/29b07594-60dd-11e6-998b-75d426f2ab9c.png)

**Comment by Porowl** [comment]
<T><A1/5>주변 돌아다니다 어느새 여기 왔습니다. 
길 잃었습니다. 어디인지 모릅니다.
