### ISSUE TITLE
안전을 위해 되도록이면 만나지 않는 편이 좋다고 생각했어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2738]
![screenshot_2016-08-12-02-04-54](https://cloud.githubusercontent.com/assets/19295794/17629513/56de4360-60ed-11e6-8a53-a4b9b37af36a.png)

**Comment by Porowl** [comment]
<T><A3/5>안전을 위해 되도록이면 
만나지 않는 편이 좋다고 생각했어요.
