### ISSUE TITLE
...언니랑 연락도 안 하고 떨어져서 살았거든요. 지금은 정말 후회해요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2739]
![screenshot_2016-08-12-02-04-22](https://cloud.githubusercontent.com/assets/19295794/17629602/b87bfd74-60ed-11e6-948c-ce014ad07dbd.png)

**Comment by Porowl** [comment]
정말 후회해요 때문에 남겨둡니다.
정말 후회되요 라던가?

**Comment by Y00N** [comment]
후회해요 나쁘지 않다고 생각합니다.

**Comment by Porowl** [comment]
최근 어디서 ~되요 ~하고 있어요 가 맞지 않는 표현이라는 글을 읽었습니다. 후회해요 남겨두겠습니다.
