### ISSUE TITLE
이 블럭 5개는 사실 일본어로 레이튼이란 뜻이다. 꽤 멋있지 않나?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#274]
![kakaotalk_20160511_234010233](https://cloud.githubusercontent.com/assets/19270364/15190563/7d2813e8-17eb-11e6-8368-23eb1bdc2088.jpg)

이거... 무슨 말인지 아예 모르겠어요.
그래서 올려봅니다.

**Comment by kaleidoscope531** [comment]
![image](https://cloud.githubusercontent.com/assets/19265176/15190984/8c7a6bdc-17ed-11e6-9086-98720cba6656.png)

レ  イ  ト  ン
레 이   토  ㄴㅇ

레이톤

가타카나입니다.

**Comment by Y00N** [comment]
아... 저처럼 일본어를 잘 모르는 사람을 위해 좀 더 상술하면 좋겠네요.
'5개의 블럭을 잘 나열하면 일본어로 레이튼이란 말이 나온다.' 는 어때요?

**Comment by kaleidoscope531** [comment]
'이 문제의 블럭 5개는 사실 일본어로 레이튼을 뜻하는 글자를 본따 만들었다.'

**Comment by bombomS2** [comment]
이 문제에 쓰인 블럭 5개는 사실 일본어 가타카나로, 나열하면 '레이튼'이 된다.
이렇게 적어도 괜찮을 것 같습니다.

**Comment by Y00N** [comment]
아니면 아예 가타카나로 레이튼이라고 써서 보여주는 건 어떨까요?
사실 이 문제에 쓰인 블럭 5개는 일본어 가타카나로, 나열하면 '00000', 즉 레이튼이 된다.

**Comment by jungin019** [comment]
1가타카나를 사용하려면 문자를 추가해야 합니다. 가타카나를 쓰는 걸로 정해지면 추가해야겠지만
아니라면 그냥 놔두는 방향으로 가는 것이...

**Comment by STRIKE-F** [comment]
영판에서도 카타카나를 보여주지는 않아요. 물론 보여주는 쪽이 훨씬 이해는 쉽겠네요. 전 추가에 찬성합니다

**Comment by Porowl** [comment]
사실 이 문제에 쓰인 블럭 5개는 일본어 가타카나로, 나열하면 레이튼이 된다.

**Comment by Porowl** [comment]
정답!

사실 이 문제에 쓰인 블럭 5개는 
일본어 가타카나로, 나열하면 레이튼이 된다.

꽤 신기하지 않은가?
