### ISSUE TITLE
그 난관은 이 난관을 넘고 난 뒤에 생각해 보자구요. 문에 이상한 잠금장치가 달려 있어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2743]
![screenshot_2016-08-12-02-01-33](https://cloud.githubusercontent.com/assets/19295794/17630046/2ee4a766-60f0-11e6-9d6e-299718ede0e1.png)

**Comment by Porowl** [comment]
<T>Well, our first challenge is
to get this door open. It's got
some strange lock on it.

우선 문부터 열어야 겠는데요?
이상한 잠금장치가 달려있어요.

**Comment by jungin019** [comment]
원래 문장도 그렇게 이상한 것 같지는 않은데 이상하시다면 찬님 의견대로 가는 게 어떨까 하네요

**Comment by Porowl** [comment]
보류할게요
