### ISSUE TITLE
중앙연구실은 이 복도 끝쪽에 있습니다. 경비들이 저희를 발견하기 전에 서둘러요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2747]
![screenshot_2016-08-12-01-59-15](https://cloud.githubusercontent.com/assets/19295794/17630328/6b457aea-60f1-11e6-91dc-eb86a6def738.png)

**Comment by Porowl** [comment]
<T>중앙 연구실은 이 복도 끝에 있습니다.<W> 
경비에게 발각되기 전에 서두르세요!
