### ISSUE TITLE
챕터 9 루크 대사 "아, 그런 거군요!~"

### ISSUE THREAD

**Issue by STRIKE-F** [elfinlazz/lt3translation#2748]
아, 그런 거군요! 이 시간대의 저는 꼬마가 아니군요. 근데 알아채지도 못하던걸요!

->아, 그렇군요! 저는 여기선 꼬마가 아닌데, 전혀 놀라지 않던걸요!

수정 가능하면 고쳐 주시오. 전체적으로 너무 어색해 보여서...

**Comment by Latteria** [comment]
채택합니다. 대본이랑 같이 수정하고 닫아주세요.

**Comment by STRIKE-F** [comment]
수정 완료
