### ISSUE TITLE
수수께끼 11번 아래의 블럭 5개가 있다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#275]
![kakaotalk_20160511_234011658](https://cloud.githubusercontent.com/assets/19270364/15190618/d38af87c-17eb-11e6-8cca-60f53de7f4e6.jpg)
'아래에 블럭 5개가 있다.'로 바꾸는 게 좋겠습니다.

**Comment by Y00N** [comment]
화면이 뒤집혀서 그렇지 아래에 있는 거 맞습니다.. ;;;;;
내친 김에 조금 더 수정하자면 아래 문장은 '이 블럭을 이용해'로도 충분합니다.

**Comment by jungin019** [comment]
둘 다 고쳤습니다.
