### ISSUE TITLE
엘리베이터같이 생겼구나. 요새 안을 돌아다니는 데 쓸 수 있을 거야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2752]
![screenshot_2016-08-08-21-12-56](https://cloud.githubusercontent.com/assets/19295794/17698818/d078cbfa-63ef-11e6-97ca-819ec75c7df1.png)

1행의 '요새 안을' 은 2행으로 넘기면 어떨까 하는데 공간이 되나요?

**Comment by jungin019** [comment]
공간이 안 되어 닫겠습니다.
