### ISSUE TITLE
뭐, 뭐야! 야, 멈춰! 거기로 들어가면 안 된다고!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2754]
![screenshot_2016-08-08-21-14-40](https://cloud.githubusercontent.com/assets/19295794/17699719/eacdf246-63f4-11e6-9924-7509b385a3e1.png)

1행의 '거기로 들어가면' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 너무 남아 닫겠습니다.
