### ISSUE TITLE
[토의] 저 끔찍한 물건에 플로라가 갇혀 있는 걸 보자니 더 이상 견딜수가 없구나. 어서 수수께끼를 풀자.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2755]
![screenshot_2016-08-08-21-17-06](https://cloud.githubusercontent.com/assets/19295794/17835663/5789a706-67a9-11e6-9347-34ffbb4ca16e.png)

'물건에' 보다는 '공간에' 라는 표현을 사용하면 어떨까 하는데 다른 분들은 어떻게 생각하시는지 궁금합니다.

그리고 2행의 '어서' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by Y00N** [comment]
무엇에 갇혀있었죠? 기억이 안나네요.
