### ISSUE TITLE
제발 그 말은 좀 안하면 안 돼? 내가 망친 건 맞는데, 네가 그렇게 말해도 지금 도움이 하나도 안 되거든?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2756]
![screenshot_2016-08-08-21-21-54](https://cloud.githubusercontent.com/assets/19295794/17835685/254c060c-67aa-11e6-82e7-902f964ff5e1.png)

1행의 '내가' 와 2행의 '지금' 은 각각 다음 행으로 넘기는 게 어떨까요?

**Comment by jungin019** [comment]
칸이 안 되어 내가는 개행하지 않았습니다.
