### ISSUE TITLE
그건 지금 중요한 게 아니고, 중요한 건 이겁니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#276]
![kakaotalk_20160511_234014830](https://cloud.githubusercontent.com/assets/19270364/15190657/114560ee-17ec-11e6-9842-86b96c2a99ee.jpg)

'중요한 것'이라는 명사화한 표현을 두번에 걸쳐 사용하는데요, 
'그건 지금 중요하지 않고, 이게 중요합니다.'로 바꿔보는 건 어떨까요?

사실 문장을 바꿔보고 싶긴 한데 딱히 맘에 드는 문장은 안 떠오르네요.

**Comment by jungin019** [comment]
살짝 의역을 해서 '어쨌든 중요한 건 따로 있습니다.'라든가 
'아무튼 중요한 건 이겁니다' 라고 하는 것도 괜찮을 것 같네요

**Comment by bombomS2** [comment]
지금 그게 중요한 게 아닙니다. 중요한 건 이겁니다.
로 두 문장으로 나누는 건 어떨까요?

**Comment by bombomS2** [comment]
아, 아니면
지금 중요한 건 그게 아니라 여기 이겁니다.
이 정도도 괜찮을 것 같아요.

**Comment by Porowl** [comment]
지금 그게 중요한게 아닙니다. 중요한 건
이겁니다. 당신에게 급히 전해줄 편지가
있어요.
