### ISSUE TITLE
암호를 모른다면 완전히 꼼짝마라 이거지!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2762]
![screenshot_2016-08-08-21-23-34](https://cloud.githubusercontent.com/assets/19295794/17845977/5882a5c0-6878-11e6-91b7-bf747ea5c3d2.png)

1~2행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by Porowl** [comment]
좁아요
