### ISSUE TITLE
[간단] 우리 모두 빌과 디미트리가 한 짓을 알아. 세상에 알리기만 해도 그들은 처벌받을 수 있을 거야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2765]
![screenshot_2016-08-08-21-38-23](https://cloud.githubusercontent.com/assets/19295794/17922143/1b87e876-6a10-11e6-942d-d4ba2b09082a.png)

2행의 '그들은 처벌받을' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
모두가 빌과 디미트리가 한 짓을 알아.
세상에 알리기만 해도 그들은
처벌을 받을 거야.

로 더빙 고칠 수 있다면 고쳐 주시길...

일단 개행은 수정했습니다

**Comment by Latteria** [comment]
작업중에 번역팀과 다른 대사로 바꿨습니다.
