### ISSUE TITLE
[간단] 권력자들에게 우리같은 "시민"들을 더 밝은 미래로 향하는 길의 걸림돌일 뿐이라고요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2766]
![screenshot_2016-08-08-21-38-43](https://cloud.githubusercontent.com/assets/19295794/17922283/c9790424-6a10-11e6-808e-7692df8f6542.png)

권력자들에게 우리같은 "시민" 들은
더 밝은 미래로 향하는 길의 
걸림돌일 뿐이라고요.

로 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
