### ISSUE TITLE
[단순] 이런 깡패들이 이해하는 유일한 것은 힘 뿐이에요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2767]
![screenshot_2016-08-08-21-38-46](https://cloud.githubusercontent.com/assets/19295794/17952774/29049c5c-6aa0-11e6-9f6c-c69ab4cdd5bf.png)

1행의 '힘' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
현재는

이런 짐승만도 못한 놈들은 
매가 약이에요.

로 내용이 수정됐습니다.
