### ISSUE TITLE
[단순] 금방 못나가니까요 

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2768]
![screenshot_2016-08-08-21-46-26](https://cloud.githubusercontent.com/assets/19295794/17952862/eef998b8-6aa0-11e6-91b4-446354d8d8b0.png)

'금방은 못 나가니까요.' 로 수정하면 어떨까요?

**Comment by Latteria** [comment]
작업중에 다른 대사로 바꿨습니다.
