### ISSUE TITLE
[단순] 등잔 밑이 어두운 법이란다. 이곳의 화면들은 기지의 카메라들과 연결되어 있는 것 같구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2769]
![screenshot_2016-08-08-21-47-12](https://cloud.githubusercontent.com/assets/19295794/17953282/c92aff38-6aa4-11e6-84cc-79213cfacd33.png)

등잔 밑이 어두운 법이란다.
이곳의 화면들은 기지의 카메라들과 
연결되어 있는 것 같구나. 

로 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
