### ISSUE TITLE
저 공지에 따르면 이 노선은 폐선됐대요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#277]
![kakaotalk_20160511_234020335](https://cloud.githubusercontent.com/assets/19270364/15190899/39fce1e6-17ed-11e6-85f9-ec73f894588b.jpg)

'폐선'이란 말이 '닫은 노선'의 '廢線'인거죠? 잘 쓰이는 말인지 모르겠네요.
여튼 폐선을 쓰면 '이 노선은 노선이 폐쇄됐대요.' 라는 식이 되는 거라서 이중 표현이 됩니다.
그리고 '따르면'이라는 표현도 '의하면'이라는 표현이 더 좋습니다.

'저 공지에 의하면 이 노선은 폐쇄했대요' 정도는 어떨까요?

**Comment by jungin019** [comment]
음 그러고보니 폐선이라는 건 잘 안 쓰는 것 같군요
'저 공지에 의하면 이 노선은 폐쇄됐대요'로 고치는 게 좋겠습니다. 

공지에 노선이 폐쇄된다는 얘기가 담긴 게 5년 후의 날짜이긴 합니다. 
저 시점에서 일행이 미래에 도착했다는 걸 깨닫지 못하는 시점이라 이렇게 얘기한 거죠. 
그러니까 즉 미래의(10년 후) 런던에서는 5년 전에 노선이 폐쇄된 것이지만 
일행이 원래 있었던 현재 시점에서는 5년이 지났을 시점에 열차가 폐쇄 됐다는 거죠.
(뭔가 말이 좀 이상한 것 같네요ㅠ)

**Comment by Y00N** [comment]
아 제가 플레이한 세이브 파일 중 제일 오래된 게 저 부분 직후더군요. 그래서 그 점이 확인이 안되서 좀 헤깔려서 고민고민하다가 저렇게 적었습니다. '폐쇄됐대요'가 더 맞는 문장이군요! :)

**Comment by STRIKE-F** [comment]
폐쇄됐대요로 수정하겠습니다.
