### ISSUE TITLE
[토의] 이 유리 돔은 정말 잘 보이네요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2770]
![screenshot_2016-08-08-21-47-52](https://cloud.githubusercontent.com/assets/19295794/17957557/52e6e8de-6ac5-11e6-8117-df5547d6a92e.png)

문장의 의미가 명확하지 않다고 생각하는데 다른 분들은 어떻게 생각하시나요?

**Comment by STRIKE-F** [comment]
이게 오역이었어서... 현재는

이런 곳에 갇힌 게
한두 번이 아니라고요....

로 수정됐습니다.
