### ISSUE TITLE
[단순] 여기라면 기지의 모든 곳이 다 보이겠는걸요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2771]
![screenshot_2016-08-08-21-48-16](https://cloud.githubusercontent.com/assets/19295794/17958040/4a7faff6-6ac9-11e6-8749-3168ff12c616.png)

1행의 '다' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
내용을 약간 수정해서 현재는

이 정도면 기지 전체를 한눈에
볼 수 있겠는데요.

로 수정했습니다.
