### ISSUE TITLE
[단순] 이제 그게 어떤 화면인지만 찾으면 된단다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2772]
![screenshot_2016-08-08-21-48-33](https://cloud.githubusercontent.com/assets/19295794/17958099/a956c37a-6ac9-11e6-81cc-3f6b33ecbda4.png)

1행의 '찾으면' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
