### ISSUE TITLE
[단순] 맞아. 여기로 올려달라고 떼를 좀 썼어. 그랬더니 빌려주더라고.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2773]
![screenshot_2016-08-08-22-11-26](https://cloud.githubusercontent.com/assets/19295794/17958186/40dfde66-6aca-11e6-90bf-3c186c149497.png)

2행의 '썼어.' 는 1행 끝부분에 붙여 쓰는 것이 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
