### ISSUE TITLE
[단순] 돈 파올로의 비행기계도 있겠다, 이제 마음대로 왔다갔다 할 수 있겠네요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2774]
![screenshot_2016-08-08-22-21-42](https://cloud.githubusercontent.com/assets/19295794/17958268/f44185a4-6aca-11e6-9953-297e6b9edffd.png)

1행의 '이제' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
