### ISSUE TITLE
[단순] 이거 수수께끼로 잠겨 있는데, 한 번 보실래요, 선생님?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2775]
![screenshot_2016-08-08-22-27-47](https://cloud.githubusercontent.com/assets/19295794/17958328/85137c5e-6acb-11e6-9133-093813d01a95.png)

1행의 '한 번' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
내용, 오타 수정도 조금 해서

이거 수수께끼로 잠겨 있네요.
한번 보실래요, 선생님?

로 수정했습니다.
