### ISSUE TITLE
[단순] 보시다시피, 수상님은 아주 특별한 좌석에 앉아 계시거든요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2776]
![screenshot_2016-08-08-22-35-19](https://cloud.githubusercontent.com/assets/19295794/17958411/42835476-6acc-11e6-83cf-01746fa22302.png)

2행의 '좌석에' 는 1행 끝부분에 붙여 쓰면 어떨까 하는데 공간이 되나요?

**Comment by STRIKE-F** [comment]
공간은 됩니다. 올리신 대로 수정했습니다.
