### ISSUE TITLE
[단순] 투철한 정의감은 좋지만, 잘못 건드리시면 선생님과 함께 이 요새도 날아가버릴 겁니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2777]
![screenshot_2016-08-08-22-35-24](https://cloud.githubusercontent.com/assets/19295794/17958460/c512914a-6acc-11e6-943f-a62136d63088.png)

투철한 정의감은 좋지만, 
잘못 건드리시면 선생님과 함께
이 요새도 날아가버릴 겁니다.

로 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
