### ISSUE TITLE
[단순] 전 이만! 도망가는건 아니고, 볼일이 좀 있어서요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2778]
![screenshot_2016-08-08-22-35-31](https://cloud.githubusercontent.com/assets/19295794/17958557/573101f6-6acd-11e6-85bc-5d830e30572d.png)

전 이만! 도망가는 건 아니고,
볼일이 좀 있어서요. 

로 내용과 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
내용이 약간 수정되어 현재는

전 이만! 도망가는 건 아니고, 
할 일이 좀 있어서요.

로 수정했습니다.
