### ISSUE TITLE
[단순] 기기가 반응하기 전에 두 쌍 모두 자를 수 있을 것 같지가 않아요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2779]
![screenshot_2016-08-08-22-37-46](https://cloud.githubusercontent.com/assets/19295794/17958636/e0548e9e-6acd-11e6-80ed-b6fe0c5cbdf0.png)

1행의 '자를' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
내용과 맞춤법 수정을 겸해서(전선이 2가닥이니 한 쌍인데... 어째서...) 현재는

기기가 반응하기 전에 둘 다 자를 수는
없을 거예요.

로 수정했습니다.
