### ISSUE TITLE
이 파이프는 어디로 가는 걸까요

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#278]
![kakaotalk_20160511_234022005](https://cloud.githubusercontent.com/assets/19270364/15191291/053f0c5c-17ef-11e6-8536-ad0c92c451e8.jpg)

불필요한 명사화를 제하고 '이 파이프는 어디로 갈까요?' 로도 충분합니다.

**Comment by kaleidoscope531** [comment]
명사화를 제한다고 하셨는데, '이 파이프는 어디로 이어져 있을까요?' 는 어떨까요?

**Comment by jungin019** [comment]
저도 이어져 있을까요 가 더 좋을 것 같네요

**Comment by Y00N** [comment]
그것도 좋네요 :D

**Comment by Y00N** [comment]
기왕이면 '이 파이프는 어디로 이어져 있을까요?'도 '이 파이프는 어디로 이어질까요?' 가 좋다고 생각합니다.

**Comment by jungin019** [comment]
이어질까요가 더 좋겠네요

**Comment by Porowl** [comment]
'이 파이프는 어디로 이어질까요?'에 한 표
