### ISSUE TITLE
[단순] ...아 좋은 생각이 났어요. 이걸 사용하면 어떨까요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2780]
![screenshot_2016-08-08-22-37-57](https://cloud.githubusercontent.com/assets/19295794/17958724/72a0146c-6ace-11e6-95ec-2525ec56c983.png)

... 아, 좋은 생각이 났어요.
이걸 사용하면 어떨까요? 

로 내용과 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
