### ISSUE TITLE
[단순] 이...회중 시계는 내가 오래전에 클레어에게 줬던 것이군요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2781]
![screenshot_2016-08-08-22-41-04](https://cloud.githubusercontent.com/assets/19295794/17958786/d8642252-6ace-11e6-89ff-692260d6ba88.png)

말줄임표와 '회중' 사이에 한 칸을띄우는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
내용 수정을 약간 해서 현재는

이 회중 시계는... 제가 오래전에
클레어에게 줬던 것이군요.

로 수정했습니다.
