### ISSUE TITLE
[단순] 이 시계를 어디다 쓸 수 있을지 알 것도 같군요, 스텔라.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2782]
![screenshot_2016-08-08-22-41-28](https://cloud.githubusercontent.com/assets/19295794/17958881/6d5ba4f2-6acf-11e6-8780-8fb625ee24f3.png)

1행의 '알 것도' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
내용 수정을 약간 해서 현재는

이 시계를 어떻게 써먹을지 
이제야 알겠네요.

로 수정했습니다. 아무래도 이름을 맨 뒤에 붙이는 게 좀 어색해 보인단 말이죠....
