### ISSUE TITLE
[단순] 클라이브를 멈추려면 이 방법 밖에는 없어. 성공할 가능성은 낮지만, 시도해 볼 수 밖에.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2783]
![screenshot_2016-08-08-22-47-11](https://cloud.githubusercontent.com/assets/19295794/17958963/d387b7fc-6acf-11e6-924b-e1b695f68652.png)

클라이브를 멈추려면 이 방법 밖에는 없어. 
성공할 가능성은 낮지만, 
시도해 볼 수 밖에.

로 개행 수정하면 어떨까 하는데 공간이 되나요?

**Comment by STRIKE-F** [comment]
내용/오타 수정 약간 해서 현재는

클라이브를 멈추려면 이 방법뿐이야.
성공할 가능성은 낮지만, 시도해볼 수밖에.

로 수정했습니다.
