### ISSUE TITLE
[단순] 발전기의 핵심 부분인 이 톱니바퀴가 돌아가는 방향을 반대로 돌리기만 한다면...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2784]
![screenshot_2016-08-09-00-11-04](https://cloud.githubusercontent.com/assets/19295794/17959058/7e6c552e-6ad0-11e6-9274-25df0f22350e.png)

발전기의 핵심 부분인 
이 톱니바퀴가 돌아가는 방향을
반대로 돌리기만 한다면...

으로 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
