### ISSUE TITLE
[단순] 벌써부터 계획해두셨던 거군요. 도대체 모르는 게 뭐에요, 교수님?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2785]
![screenshot_2016-08-09-00-11-13](https://cloud.githubusercontent.com/assets/19295794/17959139/0553d9fe-6ad1-11e6-92aa-4bc2fc78089f.png)

1행의 '도대체' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
'거'를 빼는 게 좋을 듯해서

벌써부터 계획해 두셨군요. 
도대체 모르는 게 뭐에요, 교수님?

로 수정했습니다.
