### ISSUE TITLE
[토의] 아직 축하하기는 이르단다, 루크. 만약 여기서 실패한다면, 많은 목숨이 희생될 거야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2786]
![screenshot_2016-08-09-00-11-21](https://cloud.githubusercontent.com/assets/19295794/17959211/7bc203f4-6ad1-11e6-98a2-c0a544d17571.png)

스텔라가 레이튼의 말투를 사용하고 있다고 생각하는데 다른 분들은 어떻게 생각하시나요?

**Comment by STRIKE-F** [comment]
아직 축하하기는 일러, 루크. 
만약 여기서 실패한다면, 많은 사람이
희생당할 거야.

이렇게 고치면 좀 더 스텔라스러울까요
