### ISSUE TITLE
[단순] 수상님이 아주 중요한 사람인 것은 저도 잘 알고 있습니다. 최대한 안전하게 운전하도록 노력하죠.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2787]
![screenshot_2016-08-09-00-26-17](https://cloud.githubusercontent.com/assets/19295794/17959280/f32f9f0a-6ad1-11e6-9c4a-c238f6e33357.png)

2행의 '최대한' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
내용 수정을 좀 해서 현재는

수상님이 아주 중요한 분이란 건
저도 잘 알고 있습니다. 
최대한 안전하게 모시겠습니다.

로 수정했는데, 좀 어색해 보여서 의견을 좀 모으고 싶습니다.
