### ISSUE TITLE
[단순] 지하 도시민은 다 대피시켜뒀다네

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2788]
![screenshot_2016-08-09-00-36-38](https://cloud.githubusercontent.com/assets/19295794/17959373/8af88da6-6ad2-11e6-90ed-16bc97cc0d76.png)

지하 도시민은
다 대피시켜 뒀다네.

로 내용과 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
