### ISSUE TITLE
[단순] 그 이야긴 나중에. 이곳은 오래가지 못할 거야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2789]
![screenshot_2016-08-09-00-37-07](https://cloud.githubusercontent.com/assets/19295794/17959437/f8bfb79c-6ad2-11e6-99c2-c7ca27368786.png)

1행의 '이곳은' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
첫 줄이 너무 짧아서 좀 그렇네요...

그 이야긴 나중에. 여기는 오래가지 
못할 거야.

일단은 이렇게 고쳤습니다.
