### ISSUE TITLE
벌써 이런 말을 꺼내기는 미안하지만, 나는 먼저 가봐야겠구나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#279]
![kakaotalk_20160511_234036143](https://cloud.githubusercontent.com/assets/19270364/15191351/5126dc8a-17ef-11e6-9ee0-c69b3d076032.jpg)

어... 이거 아무도 제보 안하셨나요?
이런 문제가 있으면 당연히 아무나 제보하셨을 것 같은데, 검색하니 안 나와서요...;;;

**Comment by kaleidoscope531** [comment]
closed issues 에 있을겁니다. 
![image](https://cloud.githubusercontent.com/assets/19265176/15191792/334df124-17f1-11e6-98d4-bf8f73c602af.png)

동그라미 친 부분을 누르시면 closed 된 이슈를 볼 수 있습니다.
