### ISSUE TITLE
[단순] 왜 당신은, 당신들은 절 도와주는 거죠?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2790]
![screenshot_2016-08-09-00-37-11](https://cloud.githubusercontent.com/assets/19295794/17959510/659ab7b8-6ad3-11e6-884e-3227bbc9b96c.png)

1~2행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by STRIKE-F** [comment]
수정 사항을 결정할 게 있어서 잠시 보류하겠습니다.
