### ISSUE TITLE
[단순] 아...알겠어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2791]
![screenshot_2016-08-09-00-37-23](https://cloud.githubusercontent.com/assets/19295794/17959567/c27c4000-6ad3-11e6-88e5-60e6bb5470d8.png)

말줄임표와 '알겠어요.' 사이에 한 칸을 띄는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
내용이 그동안 바뀌어서

그... 그렇군요.

로 수정했습니다.
