### ISSUE TITLE
[단순] 클라이브가 가져온 피해를 부정할 수는 없습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2792]
![screenshot_2016-08-09-00-43-36](https://cloud.githubusercontent.com/assets/19295794/17959644/49c1bbf8-6ad4-11e6-85c0-9139044500fd.png)

. 1행의 '부정할' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
