### ISSUE TITLE
[단순] 한가지만 묻지, 클라이브.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2793]
![screenshot_2016-08-09-00-43-44](https://cloud.githubusercontent.com/assets/19295794/17959713/c3cac57a-6ad4-11e6-8602-d6093d343074.png)

'한가지만' 은 '한 가지만' 으로 띄우는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
내용이 수정되어 현재는

클라이브, 하나만 물어보자.

로 수정했습니다.
