### ISSUE TITLE
[단순] 내가 네 계획에 방해가 될 것을 잘 알고 있었을 텐데, 왜 나에게 편지룰 보낸 거니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2794]
![screenshot_2016-08-09-00-43-50](https://cloud.githubusercontent.com/assets/19295794/17959757/00f52364-6ad5-11e6-89c4-b5c4c389d7a8.png)

2행의 '왜 나에게 편지를' 은 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
문장 길이의 조화? 를 위해 

내가 네 계획에 방해가 될 것을
잘 알고 있었을 텐데, 왜 나에게 
편지를 보낸 거니?

이렇게 고치는 건 어떨까 싶네요.
