### ISSUE TITLE
[토의] 처음엔 그저 선생님을 가지고 놀고 싶었을 뿐이었지만, 어느새부턴가 함께하는 시간이 좋았어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2795]
![screenshot_2016-08-09-00-44-07](https://cloud.githubusercontent.com/assets/19295794/17959853/7962a164-6ad5-11e6-95fc-a135b5199690.png)

'~고' 라는 표현이 반복됩니다.

그리고 '어느새부턴가' 는 '언제부턴가' 로 수정하는 게 어떨까요?

**Comment by STRIKE-F** [comment]
처음엔 그저 선생님을 가지고 놀고
싶었을 뿐이었지만, 어느새 함께하는
시간을 즐기게 됐어요.

-고 가 반복되는 것은 그닥 문제가 안 된다고 봅니다 ㅇㅅㅇ;;
더빙은 수정 가능한지 따로 알아봐야 합니다.

**Comment by Latteria** [comment]
'처음엔 그저 선생님을 가지고 놀고
 싶었을 뿐이었지만, 어느새 함께하는
 시간을 즐기게 됐어요' 로

채택합니다. 대본이랑 같이 수정하고 닫아주세요.

**Comment by STRIKE-F** [comment]
수정 완료
