### ISSUE TITLE
우리가 다시 만날 그 날을 기대하겠습니다. 그때까지 평안하시길 바라요. 선생님. 

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2796]
![screenshot_2016-08-09-00-45-09](https://cloud.githubusercontent.com/assets/19295794/17959951/0a243a5a-6ad6-11e6-981d-166e587409aa.png)

우리가 다시 만날 그 날을 기대하겠습니다. 
그때까지 평안하시길 바라요. 선생님. 

으로 개행 수정하면 어떨까 하는데 공간이 되나요?

**Comment by STRIKE-F** [comment]
공간은 됩니다. 오타 수정도 겸해서 현재
