### ISSUE TITLE
흠! 저 녀석 같은 범죄자들 때문에 세상이 미쳐 돌아가는 걸세. 비열하고 야비한 녀석들...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2797]
![screenshot_2016-08-09-00-45-22](https://cloud.githubusercontent.com/assets/19295794/17960087/87f5bcc4-6ad6-11e6-841a-e889a8d4f5c6.png)

2행의 '비열하고' 는 다음 행으로 넘기는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
