### ISSUE TITLE
[단순] 되돌아보면 볼 수록 내 행동들이 사랑에서 시작된 것이었는지 아니면 내 자존심에서였는지 모르겠다네.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2798]
![screenshot_2016-08-09-00-45-57](https://cloud.githubusercontent.com/assets/19295794/17960141/e2463640-6ad6-11e6-9eb0-a1db8b83b0e8.png)

되돌아보면 볼수록
내 행동들이 사랑에서 시작된 것이었는지
아니면 내 자존심에서였는지 모르겠다네.

로 내용과 개행 수정하면 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
