### ISSUE TITLE
[단순] 내가 준 모자를 정말 잘 간직하고 있었네...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2799]
![screenshot_2016-08-09-00-46-21](https://cloud.githubusercontent.com/assets/19295794/17960224/55517de8-6ad7-11e6-888c-11ad9ee333f4.png)

1~2행을 한 행에 합치면 어떨까 하는데 공간이 되나요?

**Comment by STRIKE-F** [comment]
공간이 안 돼서 보류하겠습니다.
