### ISSUE TITLE
당신이 없으면 우리가 풀지 못한 수수께끼들은 어떻게 되냐구요! // 아무래도 수수께끼를 돌보는 일에 ...(후략) // 수수께끼들이 내게 왔다고 하는 것이 ... (후략) // 당신이 수수께끼를 이곳에 모으고 있다는 ... (후략) 등

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#280]
![kakaotalk_20160511_234047833](https://cloud.githubusercontent.com/assets/19270364/15191511/f34fb5f4-17ef-11e6-9369-f1a3293d1942.jpg)
![kakaotalk_20160511_234049333](https://cloud.githubusercontent.com/assets/19270364/15191512/f35056f8-17ef-11e6-90cf-07319930d68e.jpg)
![kakaotalk_20160511_234038178](https://cloud.githubusercontent.com/assets/19270364/15191517/f3b37116-17ef-11e6-809b-60a6f2dbdac8.jpg)
![kakaotalk_20160511_234040195](https://cloud.githubusercontent.com/assets/19270364/15191515/f3b362c0-17ef-11e6-93a2-bcac77a3771c.jpg)
![kakaotalk_20160511_234042824](https://cloud.githubusercontent.com/assets/19270364/15191516/f3b3465a-17ef-11e6-9dbd-a235901dfe5a.jpg)
![kakaotalk_20160511_234044413](https://cloud.githubusercontent.com/assets/19270364/15191518/f3b491fe-17ef-11e6-8004-fb24bf6be56c.jpg)
![kakaotalk_20160511_234046199](https://cloud.githubusercontent.com/assets/19270364/15191514/f38bb90a-17ef-11e6-8ce2-b0d8917256ed.jpg)

수수께끼, 수수께끼들, 그것들 등 복수 형태가 일정하지 않습니다.
'-들'을 취하지 않는 편이 좋다고 생각합니다.
'그것들이'는 '그것이'나 '그게'로 바꾸면 되지 않을까요?

**Comment by jungin019** [comment]
일단 이 부근은 대충 수수께끼로 통일했습니다. 그것들도 그렇고요. 
일단 이슈는 열어두겠습니다.
