### ISSUE TITLE
[단순] 혀.. 현재로요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2800]
![screenshot_2016-08-09-00-46-48](https://cloud.githubusercontent.com/assets/19295794/17960287/b6b18088-6ad7-11e6-8bf8-5764fc4cfdc2.png)

말줄임표는 마침표 세 개를 사용하는 것이 좋겠습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정했습니다.
