### ISSUE TITLE
[토의] 그녀의 시간대로 돌아가는 것은 피할 수 없는 것 같다네... 폭발 직전으로 말이야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#2801]
![screenshot_2016-08-09-00-47-21](https://cloud.githubusercontent.com/assets/19295794/17960352/27ca9fd4-6ad8-11e6-9e1e-3a89418dd8c7.png)

'~것' 이라는 표현이 반복되는데 다른 분들은 어떻게 생각하시나요?

**Comment by Porowl** [comment]
난 그녀의 존재를 안정시키는 방법을
찾기 위해 많은 노력을 해보았지만,

그녀의 시간대로 돌아가는 것은
피할 수 없는 것 같다네...
폭발 직전으로 말이야.

가 원문입니다.
