### ISSUE TITLE
[단순] 그런데도 전 선생님이 마음대로 돌아다니시는 걸 굳이 모른 척했죠. 아닌가요?

### ISSUE THREAD

**Issue by STRIKE-F** [elfinlazz/lt3translation#2803]
원문이 Though, I suppose I still led you all the way to the heart of my base, didn't I? 긴 한데
didn't I가 아닌가요? 보다는 잘 아시죠?가 의미나 뉘앙스상 더 적당한 듯해서 바꾸면 좋겠습니다.

**Comment by Latteria** [comment]
채택합니다. 대본이랑 같이 수정하고 닫아주세요.

**Comment by STRIKE-F** [comment]
수정 완료
