### ISSUE TITLE
자네같은 합리적인 남자는  끝이 좋으면 모든 게 좋다는 것쯤은  이해할 줄 알았는데.

### ISSUE THREAD

**Issue by jungin019** [elfinlazz/lt3translation#2812]
자네같은 합리적인 남자는 끝이 좋으면 모두 좋다는 것쯤은 이해할 줄 알았는데.
자네같은 합리적인 남자는 끝이 좋으면 다 좋다는 것쯤은 이해할 줄 알았는데.

**Comment by iNSTRICA7** [comment]
자네같은 합리적인 남자는 끝이 좋으면 전부 좋다는 것쯤은 이해할 줄 알았는데는 어때요?

**Comment by Latteria** [comment]
자네같은 합리적인 남자는 끝이 좋으면 다 좋다는 것쯤은 이해할 줄 알았는데.

로 채택하겠습니다. 대본이랑 같이 수정하고 닫아주세요

**Comment by STRIKE-F** [comment]
reasonable을 합리적인으로 번역해 버리면 레이튼의 성격을 표현하기에는 다소 부적절해 보이는데

결과만 좋으면 나머지는 필요 없잖아. 자네 정도 판단력이라면 그 정도는 잘 알 텐데 말야.
는 어떠련지요...

**Comment by Latteria** [comment]
스프의견에 찬성. 대본이랑 같이 수정하고 닫아주세요.

**Comment by STRIKE-F** [comment]
수정 완료
