### ISSUE TITLE
주변을 탐색해 보자!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#285]
![kakaotalk_20160511_234106662](https://cloud.githubusercontent.com/assets/19270364/15192178/0dc9686e-17f3-11e6-84f5-40bb6ab2b618.jpg)

띄어쓰기 오류입니다.
'주변을 탐색해보자!' 혹은 '주변을 탐색하자!' 정도가 좋습니다. 
전 후자가 더 좋네요.

**Comment by bombomS2** [comment]
이 부분 궁금했는데, 허용되는 부분은 붙여 쓰기로 한 건가요? 제 생각에도 후자가 괜찮은 것 같아요.

**Comment by Y00N** [comment]
허용되는 부분은 붙여 쓰는 게 익숙지 않을까요?
생각해보니 아예 오류는 아닌데 올렸나 싶기도 하네요

**Comment by jungin019** [comment]
허용되는 부분은 붙여쓰기로 하긴 했습니다. 이슈는 주변을 탐색해보자! 와 주변을 탐색하자! 
두 개 중에 어떤 게 좋을지 때문에 열어두겠습니다.

**Comment by Porowl** [comment]
탐색해보자! 한표

**Comment by kaleidoscope531** [comment]
탐색해보자! 쪽이 더 마음에 듭니다.

**Comment by vbn2523** [comment]
저도 '주변을 탐색해보자!' 가 마음에 들어요 :)

**Comment by jungin019** [comment]
그럼 탐색해보자로 수정하겠습니다
