### ISSUE TITLE
롤리: 내가 만든 수수께끼를 들어보면 너도 '수궁'하게 '될껄'?

### ISSUE THREAD

**Issue by Glacie** [elfinlazz/lt3translation#288]
![screenshot_2016-05-12-08-09-13](https://cloud.githubusercontent.com/assets/19269458/15199444/1f40e862-1819-11e6-84f5-082a21b91768.png)

수궁 > 수긍

될껄>될걸

이 각각 옳은 맞춤법이지만 될걸은 안 바꿔도 큰 상관은 없을것 같아요

**Comment by jungin019** [comment]
아마 될껄도 쓰면 안될 겁니다. 수정했습니다.
