### ISSUE TITLE
[건의사항] 레이튼 : 그래. 그리고 강의 위엄은 언제나 당당해보이는구나. 

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#289]
![image](https://cloud.githubusercontent.com/assets/19265176/15219156/a23df104-189d-11e6-9db0-251b368eea58.png)

본 문장이 어색해서 올려봅니다. 일단 제가 생각해 본 번역은 다음과 같습니다. 
->그래. 그리고 언제나 당당하고 위엄 있는 그 모습 그대로구나.
->그래. 그리고 언제나 장엄함을 간직한 그 모습 그대로구나.
이런 식으로 강의 위엄 자체에 대해 논하는 것 보다는 그 모습 그대로라는 점을 말하는 것이 좋을 것 같습니다.

**Comment by jungin019** [comment]
원문은 'Indeed. And it looks as majestic as ever.'입니다. 
말씀하신대로 고치거나 '그리고 언제나 장엄한 모습이구나.' 정도로만 해도 될 것 같네요

**Comment by STRIKE-F** [comment]
그리고 언제 봐도 위엄 있는 그 모습 그대로구나. 라고 고치는 건 어떨까요?

**Comment by Porowl** [comment]
^

**Comment by Porowl** [comment]
그리고는 어울리지 않는 것 같아 
"그래. 언제 봐도 위엄 있는 그 모습 그대로구나."
