### ISSUE TITLE
[건의사항] 레이튼 : 무슨 문제라도 있니, 루크? 혹시 유령이 무서운 건 아니겠지?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#291]
![image](https://cloud.githubusercontent.com/assets/19265176/15219379/76f6d500-189e-11e6-9242-363931a1d054.png)

일단 이 부분은 숲이 어두컴컴해서 쫄아있는 루크에게 레이튼이 말하는 것입니다. 
여기서 '혹시 유령이 무서운 건 아니겠지?' 이 부분을
'유령이라도 나올까봐 무서워하는 건 아니겠지?'로 바꾸는 편이 더 좋지 않을까 합니다.

**Comment by Y00N** [comment]
'혹시, 유령이라도 나올까봐 겁이 나는 건 아니겠지?' 는 어떤가요? 사동사인 무서워하다를 다른 능동사로 대체해봤습니다.

**Comment by kaleidoscope531** [comment]
겁이 나는 건 아니겠지? 도 좋아 보입니다.
