### ISSUE TITLE
[건의사항][오역] 수수께끼 153번 정답화면

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#292]
![image](https://cloud.githubusercontent.com/assets/19265176/15219442/c4a94d3c-189e-11e6-840b-9be8827e004c.png)

두 번째 문단이 오역도 있고 조금 어색한 부분도 있는 것 같아서 올려봤습니다. 
일단 제가 생각해 본 번역은 다음과 같습니다. 

초록색 판은 22개의 정삼각형으로 이루어져 있다. 
그런데 여섯 개의 블럭은 모두 합쳐 24개의 정삼각형으로 이루어져 있고, 초록색 판에 넣을 수 있는 정삼각형의 수를 넘는다. 그리고 초록색 판을 다 채우고 나면 남는 정삼각형의 수는 2개이므로 정삼각형 2개로 이루어진 블럭이 답일 수밖에 없는 것이다.

**Comment by jungin019** [comment]
보니까 첫 문단도 상당히 어색하네요...ㅠ 
첫 문단은 
'Was it tough to assemble in your head? There's actually a really easy way to solve this puzzle. 
Did you figure it out?'
머리 속으로 블럭을 조립하는 게 어려웠나? 사실 이 수수께끼는 아주 쉽게 푸는 방법이 있다. 
혹시 알아냈는가? 
이정도로 고치고 

다음 문단은 원문이 
'The frame is composed of 22 identical equilateral triangles. The six blocks together are 
composed of 24 triangles, which is two too many. This means the unused block must be 
the one made from only two triangles!' 라서 말씀하신대로 고치거나 
마지막 문장을 '그러므로 2개의 정삼각형으로 이루어진 블럭이 답이 될 수밖에 없다.'로 해도 될 것 같네요

**Comment by STRIKE-F** [comment]
첫 문단은 '머릿속으로 블럭을 조립하는 게 어려웠나? 알아냈을지 모르겠지만, 사실 이 수수께끼는 아주 쉽게 푸는 방법이 있다.' 로 고치는 게 어떨까요?

초록색 판은 22개의 정삼각형으로 이루어져 있다. 
그런데 여섯 개의 블럭은 모두 합쳐 24개의 정삼각형으로 이루어져 있고, 초록색 판에 넣을 수 있는 정삼각형의 수를 넘는다. 그리고 초록색 판을 다 채우고 나면 남는 정삼각형의 수는 2개이므로 정삼각형 2개로 이루어진 블럭이 답일 수밖에 없는 것이다.
이 번역 진짜 맘에 듭니다 :D
