### ISSUE TITLE
[건의사항] 실키 : 그 수수께끼가 네게 교훈이 됐으면 좋겠구나. 조심하지 않으면 잃을 수도 있다는 것 말이다. 

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#293]
![image](https://cloud.githubusercontent.com/assets/19265176/15219777/03e4b0da-18a0-11e6-9720-b9ea5077f5c3.png)

문장이 조금 어색한 것 같아서 올려봅니다. 일단 제가 생각해 본 것은 이렇습니다. 

그 수수께끼를 교훈 삼도록 하렴. 만일 네 것을 부주의하게 다룬다면, 넌 그것을 잃을 수도 있어.

**Comment by jungin019** [comment]
원문이 'If you're careless with your things, you can lose them.'라서 
말씀하신 것처럼 고치거나 
'네 물건을 소중히 다루지 않으면 잃어버릴지도 모르지.' 정도로 고쳐도 될 것 같네요.

**Comment by STRIKE-F** [comment]
물건을 소중히하지 않으면 잃어버릴 수도 있단다. 는 어떨까요?

**Comment by Porowl** [comment]
그 수수께끼가 네게 교훈이 됐으면
좋겠구나. 네 물건을 소중히 다루지 
않으면 잃을수도 있다는 것 말이다.
