### ISSUE TITLE
[건의사항] 레이튼 : 이 안개는 오염 때문에 낀 건지 궁금하구나. 

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#294]
![image](https://cloud.githubusercontent.com/assets/19265176/15219879/5eff5b6e-18a0-11e6-8022-25ec0fbff5fc.png)

일단 이 부분 원문이 이렇습니다. 
I wonder if that haze is caused by pollution

번역 자체는 맞게 되어 있으나, 직역한 느낌이 좀 나는 것 같아서 올려봤습니다. 

I wonder ~  이 부분을 차라리 궁금해하는 걸로 처리를 해 버리는 것은 어떨까요?
예를 들면
'저 안개는 오염 물질이 원인인 건가?' 이런 식으로요.

**Comment by Y00N** [comment]
'오염이 심해서 안개가 낀 게 아닐까?' 어때요?

**Comment by bombomS2** [comment]
저 안개는 오염 때문에 생긴 걸까?
혹은
저 안개는 대기 오염으로 생긴 걸까?
는 어떨까요?

**Comment by kaleidoscope531** [comment]
'저 안개는 대기 오염으로 생긴 걸까?' 쪽이 더 좋아 보입니다.
