### ISSUE TITLE
[건의사항] 아트 : 지금은 쓸모없어졌지. 문제 상황들은 수도 없이 봐 왔지만, 널빤지가 이래서야 쓸 수가 없어.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#297]
![image](https://cloud.githubusercontent.com/assets/19265176/15220186/933349ee-18a1-11e6-94c8-d96443dd8ca8.png)

일단 이 문장의 원문은 이렇습니다. 
Nothing right now. I’ve got cases of these things, but I can’t work with them.

제 생각엔 '문제 상황들은 수도 없이 봐 왔지만,' 이 부분이 어색한 것 같습니다. 
맥락상으로 보면 저 인부가 널빤지를 필요한 만큼 잘라쓰고 하다 보니까 그렇게 남은 자투리 널빤지들은 모양이 이상해서 쓸 수가 없다. 뭐 이런 말을 하고 싶은 것 같습니다. 

따라서 이런 식으로 바꿔보는 건 어떨까 합니다. 

'지금에야 쓸모 없지. 이런 조각들은 잔뜩 있는데 다 이 모양이라 쓸 수가 있나?'

**Comment by jungin019** [comment]
좀 오역인 것 같군요. 말씀하신 게 맞겠네요

**Comment by STRIKE-F** [comment]
cases가 들어간 게 아주 한 통이나 쌓였다 이런 뜻인가 보네요. 저도 다시 읽어 보고 이제야 이해했습니다 ㅡ.ㅡ

아무데도 못 써먹지. 이런 조각만 한가득인데, 이거로는 어떻게 할 수가 없다고. 이러면 어떨까요?

**Comment by kaleidoscope531** [comment]
아무데도 못 써먹지. 이런 조각만 한가득인데, 이거로는 어떻게 할 수가 없다고.
좋습니다.
