### ISSUE TITLE
[오역?] 수수께끼 44번

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#299]
![image](https://cloud.githubusercontent.com/assets/19265176/15220458/98eb9516-18a2-11e6-9263-21beb9329cd7.png)

이 문제를 보면 갈림길에서 좌회전을 하라고 하고 있습니다. 그런데 원문을 보면 갈림길이라는 언급은 없습니다. 그리고 그 언급이 없는 점이 이 수수께끼를 푸는 매우 중요한 단서입니다. 따라서 이 부분은 수정이 필요할 것 같습니다. 

일단 제가 생각해 본 건 다음과 같습니다. 
'직진한 후에 처음으로 좌회전을 해라. 다음으로 우회전을 한 뒤에 이어서 마지막으로 좌회전을 하면 바로 앞에 시계탑이 보일 것이다.'

**Comment by jungin019** [comment]
음 듣고보니 갈림길은 살짝 오해의 여지가 있겠네요.

**Comment by STRIKE-F** [comment]
갈림길을 빼는 쪽으로 수정하겠습니다. 오역이 맞는 것 같네요.
