### ISSUE TITLE
[오역] 레이튼 : 알았다, 루크. 네가 속도를 맞출 수 있는지 한 번 보자꾸나.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#303]
![image](https://cloud.githubusercontent.com/assets/19265176/15220823/dde34136-18a3-11e6-8fa0-53cbc5e94708.png)

일단 이 부분 원문을 찾아 보니까 이렇습니다. 
Very well. Let’s see if we can bring you up to speed.

bring you up to speed 이 부분은 저 의미가 아닌 것 같습니다. 
네이버 사전에 쳐 보니 'bring a person up to speed'가 '남에게 필요한 정보를 주다, 상황을 이해시키다'로 나와 있더군요.

따라서 위 번역을 다시 해 보자면,
->매우 좋군. 우리 같이 우리가 너의 이해를 도울 수 있는지 알아보자꾸나.
또는 의역을 가미해서
->그거 좋구나. 그럼 어디 같이 하나씩 짚어 가보도록 할까?
이런 식으로 하는 편이 좋지 않을까 합니다.

**Comment by jungin019** [comment]
네 bring (someone) up to speed 는 말씀하신대로 누군가를 이해시킨다는 의미입니다.

**Comment by STRIKE-F** [comment]
와 저거 어째 저렇게 번역했지

그거 좋구나. 그럼 어디 같이 하나씩 짚어 가보도록 할까?
괜찮아 보입니다. 이거로 수정할게요.
