### ISSUE TITLE
[맞춤법] 루크 : 무슨 일이 있었길레요?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#306]
![image](https://cloud.githubusercontent.com/assets/19265176/15221166/49de4880-18a5-11e6-9f1d-6c2a46d82b78.png)

있었길레요 -> 있었기래요 라는군요, 한컴오피스가.....

아예 '무슨 일이 있었길레요?' 이 부분을 '왜 그렇게 된 거죠?'로 바꾸는 것도 나쁘지 않을 것 같습니다.

**Comment by bombomS2** [comment]
최근에 ~길래도 표준어로 허용된 것으로 알지만, 그래도 말씀하신 것처럼 왜 그렇게 된 거죠?/무슨 일이 있었던 거죠? 정도로 고치는 게 낫지 않을까 합니다.

**Comment by STRIKE-F** [comment]
앞뒤 문장을 봐서는 어떻게 그럴 수 있죠? 가 좀 더 맞아 보입니다. 폭발 사건의 자료가 죄다 사라졌다는 말에 대한 대답이라..

**Comment by kaleidoscope531** [comment]
어떻게 그럴 수 있죠? 도 좋아 보입니다.
