### ISSUE TITLE
[건의사항] 콜비 : 체르미 경감님께서 일하다 말고 멍해있는 걸로 혼내신 건 아닌가 궁금하네요.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#308]
![image](https://cloud.githubusercontent.com/assets/19265176/15221402/3d27a86a-18a6-11e6-8c3f-5aa570f91715.png)

여기도 번역된 문장을 보면 원문이 I wonder ~~~였던 것 같네요. 이 부분도 아예 궁금해 하는 형식으로 바꾸는 것이 좋지 않을까요?

일단 제가 생각해 본 건 이렇습니다. 
'체르미 경감님께서 일하다 말고 멍해있다고 혼내신 게 아닐까요?'

**Comment by Y00N** [comment]
'멍해있는'은 '멍해 있는'으로 띄어써야 합니다. 그리고 '~고 있다'라는 일본어 번역투를 피하길 권합니다.
'체르미 경감님께서 일하다 말고 멍하게 있어서 혼내신 게 아닐까요?'는 어떤가요?

**Comment by Y00N** [comment]
쓰고보니 '체르미 경감님께서'가 앞에 있기 때문에 중의적인 느낌이 나서 깔끔한 문장이 아니네요.
'일하다 말고 멍하게 있는다고 체르미 경감님께서 혼내신 건 아닐까요?' 어떤가요?

**Comment by STRIKE-F** [comment]
'일하다 말고 멍 때린다고 체르미 경감님께서 혼내신 건 아닐까요?' 라고 바꾸고 싶긴 한데 이게 표준어가 아니라...
정신줄 놓는다고는 어떤가요?

**Comment by Porowl** [comment]
일하다 말고 딴짓이나 한다고 체르미
경감님께서 혼내신 건 아닐까요?
