### ISSUE TITLE
[건의사항][맞춤법] 수염머플러 : 모르는 척 해도 소용 없어, 꼬마야! 나, 수염머플러는 네가 생각하는것 보다 훨씬 더 많이 알고 있거든.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#310]
![image](https://cloud.githubusercontent.com/assets/19265176/15221585/ff131b8a-18a6-11e6-9ade-4f9f904ba032.png)

일단 '생각하는것 보다' 를  '생각하는 것보다' 로 바꿔야 합니다. 

그리고 추가로 '훨씬 더 많이' 를 '많은 걸' 로 바꾸는 것은 어떨까요?

**Comment by jungin019** [comment]
것보다는 고쳤습니다. 
'훨씬 많은 걸 알고 있거든'은 어떨까요

**Comment by Y00N** [comment]
~것을 피해서 '네 생각보다 훨씬 더 많이 알고 있거든'은 어떻습니까

**Comment by bombomS2** [comment]
모르는 척해도 소용없어, 꼬마야! 나 수염머플러는 네 생각보다 훨씬 많은 걸 알고 있거든.
척하다와 소용없다는 한 단어이므로 붙여 씁니다. 전 이 문장이 좋을 것 같아요. 그런데 자기 이름을 스스로 언급하는군요…

**Comment by STRIKE-F** [comment]
원래 그런 놈이라서요 ㅇㅅㅇ...
위에 올라온 대로 수정하겠습니다.
