### ISSUE TITLE
[건의사항] 바튼 : 잠깐만요, 경감님. 속이 조금 안 좋아서요. 정확히는, 아주 안 좋아요.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#312]
'잠깐만요, 경감님. 속이 조금 안 좋아서요. 정확히는, 아주 안 좋아요.'

이 문장에서 '정확히는, 아주 안 좋아요.' 이 부분이 영어를 번역한 냄새가 좀 나는 것 같습니다. 

그냥 의미 전달에 초점을 맞춰서
'아주 죽을 것 같아요.' 또는 '돌아가신 할머니가 보여요.' 정도로 바꾸는 것은 어떨까요?

**Comment by STRIKE-F** [comment]
미국에 계신 할머니가 보여요!

농담이고, 바튼의 할머니가 돌아가셨는지 아닌지 모르는 일이라 좀 위험할 수도 있겠네요.
'아니, 조금이 아니라, 아, 아...' 는 어떤가요?

**Comment by Porowl** [comment]
미국이 아니라! 하늘나라겠지!
