### ISSUE TITLE
[오역][맞춤법] 수수께끼 69번

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#320]
![image](https://cloud.githubusercontent.com/assets/19265176/15222486/f519a780-18aa-11e6-8bcb-f74c8a23b82a.png)

일단, 마지막 문장에서 '도데체' 를 '도대체' 로 수정 부탁드립니다.
그리고 고양이 파랑이 이름이 '파랑' 과 '퍼렁' 두 가지로 쓰였습니다. 해답 화면에도 '파랑' 이라고 되어 있기 떄문에 '파랑'으로 통일하는 것이 좋을 것 같습니다. 

마지막으로, 네 번째 문장 " 파랑은 깜장에서 두 칸 떨어져 있어." 이 문장은 오역입니다. 
현재 저 수수께끼는 가능한 고양이의 배치가 2종류 나오게 됩니다. 물론 답은 하나로 정해지긴 했던 것 같지만요. 
저 문장의 원문은 " Blue is three over from Black." 입니다. 
따라서 "파랑은 깜장과 세 칸 떨어져 있어." 라고 번역해야 할 듯 합니다. 정답 화면에서 나오는 그림에서도 파랑과 깜장은 세 칸 떨어져 있습니다.

**Comment by jungin019** [comment]
말씀하신대로네요. 
그리고 가끔 도데체를 보실 수 있을 겁니다... 저희 팀 누군가가 자꾸 도데체라고 써서...(ㅂㄷㅂㄷ)
여담이지만 깜장도 검정으로 고치고 싶네요...

**Comment by STRIKE-F** [comment]
고양이 이름이라 색의 단어를 그대로 쓰기보다는 조금 고치고 싶은데 혹시 다른 좋은 방법 없을까요?

**Comment by STRIKE-F** [comment]
두 칸은 세 칸으로 수정했습니다.

**Comment by kaleidoscope531** [comment]
ㅇㅇ이 정도로만 해도 좋지 않을까요?
빨강이 파랑이 초록이 흰둥이 검둥이 뭐 이런 식?

**Comment by kaleidoscope531** [comment]
아 그리고 고양이 이름을 고치면 해답 화면의 그림도 고쳐야 할 겁니다.

**Comment by vbn2523** [comment]
'깜장'은 좋은데 '퍼렁'은 좀 이상하다고 생각해요.
개인적으로 문장 길이가 보기 이상할 정도로 길어지지 않는다면 ㅇㅇ이 도 좋다고 생각합니다.

**Comment by STRIKE-F** [comment]
ㅇㅇ이로 통일하겠습니다. 빨강이 파랑이 까망이 등등
