### ISSUE TITLE
[건의사항] 레이튼 : 하다못해 선풍기라도 틀어 주면 좋겠구나.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#321]
![image](https://cloud.githubusercontent.com/assets/19265176/15222689/e7881c36-18ab-11e6-9beb-a97bd1064dc2.png)

저 빨간 동그라미 친 것을 눌렀을 때 나오는 대사가 이렇습니다. 

![image](https://cloud.githubusercontent.com/assets/19265176/15222665/cdb12708-18ab-11e6-90be-ec2aed9565ab.png)

원문을 보면 fan이라고 되어 있는데, 저것은 선풍기가 아니라 환풍기 같습니다. 

따라서 '하다못해 환풍기라도 틀어 주면 좋겠구나' 라고 바꾸는 것이 좋지 않을까 합니다.

**Comment by Porowl** [comment]
Fan으로만 되어 있었기에 구분할 길이 없었는듯 합니다.

**Comment by Porowl** [comment]
수정했습니다.
