### ISSUE TITLE
[건의사항] 머틀 : 하하하하! 정말 보고만 있어도 마음이 절로 따뜻해지는 우정이구나!

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#323]
![image](https://cloud.githubusercontent.com/assets/19265176/15222914/c23fab78-18ac-11e6-893e-d457752df912.png)

문장이 좀 어색한 것 같아서 올려봤습니다. 저 문장을 '하하하하! 너희의 우정 어린 모습을 보고만 있어도 절로 내 마음이 따뜻해지는구나.' 이런 식으로 바꾸는 편이 좋지 않을까요?

**Comment by STRIKE-F** [comment]
우정이란 말을 굳이 넣을 필요가 없을 것 같네요. '너희의 다정한 모습을 보고만 있어도 절로 내 마음이 따뜻해지는구나.' 이건 어떨까요?

**Comment by Porowl** [comment]
<T><A3/2>하하하하! <A3/1>너희의 다정한 모습을 보고만 
있어도 절로 내 마음이 따뜻해지는구나
