### ISSUE TITLE
[건의사항] 루크 : 하지만 저희는 부인께서 어떻게 생기셨는지나 어디에 계신지를 모르는걸요?

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#324]
![image](https://cloud.githubusercontent.com/assets/19265176/15222967/03d5f376-18ad-11e6-97af-22520347dd32.png)

문장이 how ~~~ 나 where ~~~ 를 번역한 느낌이 나는 것 같습니다. 

'하지만 저희는 부인의 생김새나 계신 곳을 전혀 모르는걸요?' 이런 식으로 바꾸는 것은 어떨지요?

**Comment by Y00N** [comment]
'부인의 생김새나 계신 곳을'이라고 하면 '부인의 계신 곳'이 되기 때문에 적합하지 않습니다.
그리고 어떻게 생기다는 how를 번역한 게 아니지 않나요..?
저는 저 문장에서 좀 더 큰 맥락이 앞에 오도록 '부인께서 어디에 계신지도, 어떻게 생기셨는지도 모르는 걸요?' 정도로도 나쁘지 않다고 생각합니다.

**Comment by kaleidoscope531** [comment]
'부인께서 어디에 계신지도, 어떻게 생기셨는지도 모르는 걸요?' 가 좋을 듯 합니다.
