### ISSUE TITLE
[건의사항] 머틀 : 이쪽은 뼈가 나가도록 매일같이 일하는데, 그 망할 남정네는 허구한 날 쏘다니기나 한다니까요.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#326]
![image](https://cloud.githubusercontent.com/assets/19265176/15223080/97ec21fc-18ad-11e6-9056-ab58b1c8c829.png)

'이쪽은 뼈가 나가도록 매일같이 일하는데,' 이 부분을 '이쪽은 매일같이 뼈빠지게 일하는데' 로 바꾸는 편이 좀 더 일상에서 들을 수 있는 표현이 아닐까 합니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
