### ISSUE TITLE
[건의사항] 머틀 : 그 인간이 그 스프를 좋아하든 말든 내가 알 바야? 정말이지 생각이 없다니까!

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#327]
![image](https://cloud.githubusercontent.com/assets/19265176/15223114/d030fd3a-18ad-11e6-97c5-cf941f6b4723.png)

제가 게임을 하면서 본 바로는 원문에서 'soup'이었던 부분을 '국수'로 바꾼 것 같은데요. 그렇다면 저 스프도 국수로 바꿔야 하지 않나 싶습니다.

**Comment by jungin019** [comment]
soup을 국수로 바꾼 건 아니고 가게 이름이 Pepper's Noodle Palace 였던 걸 페퍼네 국수 천국으로 바꾼 것입니다.

**Comment by Porowl** [comment]
육수로 정정
