### ISSUE TITLE
[수수께끼 10] 우린 항상 시간의 흐름 속에 살고 있지만, 어떻게 흐르는지는 알기 힘들 때도 있다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#328]
![kakaotalk_20160511_234111593](https://cloud.githubusercontent.com/assets/19270364/15222906/b8e62f16-18ac-11e6-9203-2a7c590c106b.jpg)

쉼표로 이어진 두 문장을 나누어 보면, 뒷 문장의 주어가 없습니다. 뒷 문장의 주어는 '시간이'를 써야 하는데 언급된 적이 없기 때문에 생략해서는 안 됩니다.
그리고 앞 문장은 '시간의 흐름'으로, 뒷 문장은 '시간이 흐르다'로 표현하는데, 이걸 잘 맞춰주면 좀 더 나은 문장이 되지 않을까 싶네요.

'우린 시간이 흘러가는 가운데 살아가지만, 어떻게 흐르는지는 때로 잘 알지 못한다.'
고치다보니 이렇게 해봤는데... 딱 맘에 들진 않고 더 좋은 문장 있으면 좀 말씀해주시겠어요?

**Comment by STRIKE-F** [comment]
시간은 언제나 우리 주변을 흘러가지만, 우리는 어떻게 흘러가는지 알지 못할 때가 있다.
이건 어떨까요?

**Comment by kaleidoscope531** [comment]
저는 반대로 둘 다 흐름으로 바꿔봤습니다.
우리는 시간의 흐름 속을 살지만, 보통 그 흐름을 눈여겨보진 않는다.
우리는 시간의 흐름 속을 살지만, 보통 그 흐름에 관심을 갖진 않는다.

**Comment by vbn2523** [comment]
우리는 시간의 흐름 속을 살면서 그 흐름을 인식하지 못할 때도 있다.

이건 어떨까요?

**Comment by STRIKE-F** [comment]
우리는 시간의 흐름 속에서 살지만, 그 흐름을 항상 인식하지는 않는다 로 얼추 합치겠습니다.
