### ISSUE TITLE
그걸 열어보면 말이지, 책이 온통 백지 뿐이란 말이지!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#329]
![kakaotalk_20160511_234113707](https://cloud.githubusercontent.com/assets/19270364/15223218/3e49f682-18ae-11e6-8972-74c98dee1a25.jpg)

'말이지'를 자주 사용해 다소 어색한 문장입니다.
그리고 쉼표를 기점으로 뒤에서는 '책'이라고 하는데 앞 문장에서 대명사를 쓰는 것도 뭔가 이상하구요.
'그 책을 열어보면 말야, 그게 온통 백지 뿐이더란 말이지!'는 어떨까요??
수정한 게 어딘가 맘에 안드는 제안이네요.

**Comment by kaleidoscope531** [comment]
'그 책을 열어보면 말야, 그림이 온통 비어있거든!'은 어떤가요. 바로 다음에 이어지는게
그림책을 받았습니다
자두 를 받았습니다. 
그 후에 그림책 사용법 설명이니까요

**Comment by Y00N** [comment]
'그 책을 펼쳐보면 알겠지만, 사실 백지가 따로 없거든!' 은 어떤가요?

**Comment by kaleidoscope531** [comment]
사실 백지나 다름 없거든 도 좋은 것 같습니다.

**Comment by jungin019** [comment]
그 책을 펼쳐보면 알겠지만, 사실 백지나 다름 없거든! 으로 수정
