### ISSUE TITLE
[건의사항] 루돌프 : 어찌되었든, 난 이만 가보겠네. 자네들을 너무 잡아두고 있는것 같구만 저번에 약속한 정보를 주도록 하지.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#330]
![image](https://cloud.githubusercontent.com/assets/19265176/15223194/2366bb16-18ae-11e6-8c9b-f8e47dfa4471.png)

'자네들을 너무 잡아두고 있는것 같구만 저번에 약속한 정보를 주도록 하지.' 이 문장이 많이 어색합니다.
일단 제가 생각해 본 번역은 다음과 같습니다. 
'자네들을 너무 오래 잡아둔 것 같아 미안하구먼. 가기 전에 저번에 약속한 정보를 주도록 하지.'

**Comment by STRIKE-F** [comment]
문장 길이 때문에 저대로는 힘들 것 같고 전체적으로 문장을 조금 줄일 필요가 있어요.
어쨌든, 난 이만 가 봐야겠네. 내가 자네들 시간을 너무 잡아먹은 것 같군. 아, 그래. 약속했던 정보 말인데...

이렇게 하면 뒤 문장하고도 얼추 이어질 것 같습니다.

**Comment by kaleidoscope531** [comment]
좋습니다.

**Comment by Porowl** [comment]
어쨌든, 난 이만 가 봐야겠네. 내가 
자네들 시간을 너무 잡아먹은 것 같군. 
아, 그래. 약속했던 정보 말인데...
