### ISSUE TITLE
[건의사항] 루돌프 : 호호! 아까도 말했듯이 그냥 소문일 뿐이라네. 그래도 혹시 가 보게. 만날지도 모르니.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#331]
![image](https://cloud.githubusercontent.com/assets/19265176/15223291/a4272b6e-18ae-11e6-8936-f13c079429e8.png)

'그래도 혹시 가 보게. 만날지도 모르니.' 이 부분을
'그래도 일단 가 보게나. 혹시 만날지 누가 아나?'로 바꾸는 것이 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
