### ISSUE TITLE
[건의사항] 시걸 : 그래도 굳이 강가에 가겠다고 하면 최소한 저기 있는 식당이라도 한 번 들르라고.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#332]
![image](https://cloud.githubusercontent.com/assets/19265176/15223331/e0b6f2f8-18ae-11e6-9ef5-0fb8fb187b8c.png)

저 문장을 좀 다듬으면 더 좋을 것 같아 이렇게 올립니다. 
'그래도 굳이 강가에 가겠다고 한다면, 최소한 거기 있는 식당이라도 한 번 들러보라고.' 로 바꾸는 것은 어떨까요?

**Comment by Y00N** [comment]
'그래도 굳이 강가에 가겠다면, 최소한 거기 있는 식당은 한 번 들러보라고.' 어떤가요?

**Comment by Porowl** [comment]
그냥 '가겠다면'으로 줄이는건 어떨까 싶습니다.

**Comment by bombomS2** [comment]
그래도 굳이 강가에 가겠다면, 최소한 거기 있는 식당이라도 한번 들러보라고.
한번이 시도를 나타내는 표현이라 붙여 적었는데 이게 제일 애매한 것 같습니다. 둘 다 말이 되니 별 상관은 없겠지만요.

**Comment by kaleidoscope531** [comment]
'그래도 굳이 강가에 가겠다면, 최소한 거기 있는 식당이라도 한번 들러보라고.' 좋습니다.
