### ISSUE TITLE
[건의사항] 레이튼 : 물고기를 잡을 때 쓰인 것 같구나. 

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#333]
![image](https://cloud.githubusercontent.com/assets/19265176/15223384/20305b5e-18af-11e6-9f30-30724ea34283.png)

'물고기를 잡을 때 쓰던 것 같구나'로 바꾸는 편이 더 좋을 것 같습니다.

**Comment by Y00N** [comment]
'물고기를 잡으며 쓰던 것 같구나' 는 어떤가요?

**Comment by STRIKE-F** [comment]
잡으며 썼던 것 같구나는 의미가 살짝 불분명해지지 않을까요?
전 잡을 때 쓰던 것 같구나가 괜찮아 보입니다.
