### ISSUE TITLE
[건의사항] 레이튼 : 이 크리스탈은 질이 뛰어나구나.

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#335]
![image](https://cloud.githubusercontent.com/assets/19265176/15223431/5f32418c-18af-11e6-9c3f-e728f85f9a5a.png)

일단 상황 설명을 하자면, 저 말상자 뒤에 바가 있고, 뒤에 술병이나 잔들이 진열되어 있는데, 그 선반을 누르면 나오는 말입니다. 

원문을 찾아 보니 다음과 같습니다. 
'The crystal here is top notch.'

일단 crystal이 top notch 하다는 게 무슨 말인지 감이 안와서 'top notch crystal'을 구글에 검색해봤습니다. 
[https://www.google.co.kr/search?q=top+notch+crystal&hl=ko&biw=950&bih=916&site=webhp&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjqpdisitTMAhXLo5QKHWc0Du8Q_AUIBigB](https://www.google.co.kr/search?q=top+notch+crystal&hl=ko&biw=950&bih=916&site=webhp&source=lnms&tbm=isch&sa=X&ved=0ahUKEwjqpdisitTMAhXLo5QKHWc0Du8Q_AUIBigB)

결국 top notch crystal은 정밀하게 세공된 크리스탈 유리를 뜻하는 것 같습니다. 

따라서 이 말을 살려서 번역을 해야 할 듯 한데, 일단 제가 생각해 본 바는 이렇습니다. 
'이 잔들의 세공은 정말 뛰어나구나.'
'크리스탈 잔들이 참 아름답구나.'
'아름다운 잔들이구나.'

여러분의 다양한 의견 기다리겠습니다.

**Comment by jungin019** [comment]
top notch 라는 건 최상급의 라는 뜻입니다. crystal은 말씀하신대로 잔을 뜻하는 것 같네요

**Comment by Y00N** [comment]
마지막 문장이 제일 좋네요. 기왕이면 '-들'을 빼주시면 더 좋겠습니다

**Comment by kaleidoscope531** [comment]
![image](https://cloud.githubusercontent.com/assets/19265176/15243643/d5bd9c10-1937-11e6-9aaa-e34db8591a1f.png)

제가 다시 확인해 본 결과, 눌렀을 때 저 말이 나오는 부분이 이렇습니다. 
일단 '잔' 보다는 '병'으로 하는 것이 더 맞는 것 같습니다. 
그리고 YOON님은 '~들' 이라는 표현을 최대한 지양하고 계신 듯 한데, 사실 저는 정확한 국문법과 표현방법을 잘 모릅니다. 그런데 '아름다운 잔이구나' 또는 '아름다운 병이구나' 식으로 하면 저 선반에 있는 병 중 한 개만 찝어서 얘기하는 느낌이 나지 않나 생각합니다. 이에 대해 어떻게 생각하시는지요.

**Comment by kaleidoscope531** [comment]
![image](https://cloud.githubusercontent.com/assets/19265176/15243787/c99bad22-1938-11e6-8c2f-14c5ca527fb9.png)

저 부분을 확대한 일러스트도 있었네요. 밑에 잔도 있어서 굳이 병으로 바꿀 필요는 없어 보이기도 합니다.

**Comment by Y00N** [comment]
뭐 저도 국어를 전공한 사람은 아니니까요.
국문법 상 복수의 개념이 희미합니다. 사실 들을 써도 상관은 없겠죠.
언어의 경제성과 자연스러운 어구의 차원에서 지양하자고 하는 겁니다.
제가 -들을 빼자고 한 게 단수의 느낌이 물씬 난다면 아예
'훌륭한 잔이 많구나', '아름다운 잔이 많구나'라는 건 어떨까요?

**Comment by kaleidoscope531** [comment]
'아름다운 잔이 많구나' 좋은 것 같습니다.
