### ISSUE TITLE
[건의사항] 수수께끼 82번 밀짚 밀집시키기

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#336]
![image](https://cloud.githubusercontent.com/assets/19265176/15223596/424a19ea-18b0-11e6-927d-1952743b30e9.png)

일단 문제 자체는 저 세 개의 용기 중 밀가루를 가장 많이 보관할 수 있는 용기를 고르는 것입니다. 
물론 언어유희를 노리신 거겠지만, '밀짚 밀집시키기'는 수수께끼의 내용과도 거리가 있고, 밀짚을 밀집시킨다 라는 말 자체도 어색한 감이 있는 것 같습니다. 
지금은 저 언어유희도 살리면서 문제의 취지에 맞는 말이 당장 떠오르지 않아서, 일단 올려놓기만 하겠습니다. 여러분의 많은 의견 부탁드리겠습니다.

**Comment by jungin019** [comment]
원제는 Wheat Stash 입니다. 
밀 보관하기 정도겠네요

**Comment by STRIKE-F** [comment]
지푸라기 집어넣기라거나?

**Comment by STRIKE-F** [comment]
일단은 지푸라기 집어넣기로 수정하겠습니다.
