### ISSUE TITLE
02 파일 모자파 단원 대사 (61번)

### ISSUE THREAD

**Issue by jungin019** [elfinlazz/lt3translation#34]
He won't think twice about tanning
your hide if he sees you in his
casino. I'd stay away if I were you.

형님이라면 널 카지노에서 보자마자 
주저없이 네 엉덩이를 때려 팰 거다.
나라면 절대로 안 가겠어.

때려 패다를 뭔가 다른 걸로...

**Comment by Latteria** [comment]
후려칠거야 제안
