### ISSUE TITLE
오후가 되기 전까지는 정말 한산하지만,

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#340]
![kakaotalk_20160511_234121611](https://cloud.githubusercontent.com/assets/19270364/15223988/1389b6cc-18b2-11e6-8cc8-a083eca814d0.jpg)

'까지'는 어떠한 한계를 정하는 말인데, '되기 전'이라는 말 또한 한계를 정하는 말이라서 다소 의미가 겹치는 부분이 있습니다.
'오후가 되기 전엔 정말 한산하지만,' 이나, '오후가 되기까지는 정말 한산하지만,'으로 바꾸는 게 좋습니다.

**Comment by jungin019** [comment]
오후가 되기 전엔 으로 고쳤습니다
