### ISSUE TITLE
특정 동영상 스킵 문제

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#341]
스포일러성인데 좀 많이 심각한 사항이라 미리 적어놓았습니다. 

![image](https://cloud.githubusercontent.com/assets/19265176/15224008/2b5764fc-18b2-11e6-8fae-3539c64b42e0.png)

이 부분 동영상이 통째로 잘려나갔습니다. 저 스크린샷은 북미판을 플레이하여 찍은 것입니다.

**Comment by jungin019** [comment]
혹시 세이브 파일이 있으신가요?
