### ISSUE TITLE
이 곳에 일찍이 왔을 땐 가게가 닫혀 있는 것을 보았습니다. 왜 저녁이 돼서야 가게를 여시는 겁니까? // 닫혀 있었다고요? 정말로 여기를 본 것이 맞나요? 전 이 가게를 매일마다 아침 일찍 연다고요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#342]
![kakaotalk_20160511_234125388](https://cloud.githubusercontent.com/assets/19270364/15224306/9abfc69e-18b3-11e6-96e3-cc62b97bafc6.jpg)
![kakaotalk_20160511_234123428](https://cloud.githubusercontent.com/assets/19270364/15224316/9f71f2ac-18b3-11e6-927a-0b33da3527ec.jpg)

대화의 맥락을 볼 필요가 있어서 하나의 글로 엮었습니다.

먼저, '이 곳'의 띄어쓰기는 '이곳'이 맞으며, 다소 문어적인 표현이기에 구어적인 '여기'를 넣어봅니다.
굳이 '보았다'라는 표현을 쓸 필요는 없다고 봅니다. 
그리고 '닫혀 있다' 라고 쓸 필요 없이 '닫혔다'로 쓰는 것이 좋겠죠.
'저녁이 되다'란 표현은 피동을 피해 '저녁에 이르다'가 더 낫다고 생각합니다.
'마다'는 매번이란 의미를 가지고 있기에 이미 '모든' 날 이라는 의미를 가진 '매일'과는 어울리지 않습니다. 대신 '날마다', '매일', '만날' 등을 쓰길 권합니다.

의역 만땅으로 종합해봅니다.
'일찍이 여기에 왔을 땐 가게가 닫혔더군요. 어째서 저녁에 이르러서야 가게를 여시는지요?'
'닫혔다니요? 여기가요? 전 이 가게를 날마다 아침 일찍 연다고요.'

**Comment by jungin019** [comment]
전에 건의가 들어와서 현재 위의 문장은 '전에 왔을 땐 문이 닫혀 있던데, 왜 
저녁이 돼서야 가게를 여시는 건가요?'로 바뀌어 있습니다. 
아래 문장은 말씀하신대로 매일마다라고 쓰는 건 옳지 않은 것 같군요

**Comment by Y00N** [comment]
아 이미 한 번 수정한 문장이군요. 하지만 그 문장도 역시 조금 수정하면 좋겠습니다. 저녁이 돼서야는 차치하더라도, '닫혀 있다'보다는 '닫히다'의 과거형인 '닫혔다'를 쓰는 게 더 낫다고 생각합니다. '~고 있다'는 근대에 일본어를 번역하며 들어온 표현입니다.

**Comment by bombomS2** [comment]
여기서의 닫혀 있었다는 건 그 당시 닫혀 있는 걸 봤다는 일종의 과거진행 표현으로, 개인적으로는 딱히 피할 필요는 없다고 생각해요.
닫혀 있었다고요? 여기가요? 전 이 가게를 매일 아침 일찍 연다고요.

**Comment by bombomS2** [comment]
지나친 사용은 문제가 되지만, 이런 경우에서는 자연스럽게 쓰이고 있으니까요.

**Comment by Y00N** [comment]
한국어엔 본디 진행형이 없습니다. 
오늘날 우리가 쓰는 진행형 문장은 모두 일본어와 영어 번역에서 왔다고 봐도 무방합니다.

**Comment by jungin019** [comment]
@Y00N 이슈 닫으셨는데 해당 사안은 어떻게 할까요?

**Comment by Y00N** [comment]
이 이거 제가 닫은건가요? 일부러 그런 건 아닌데 실수로 그랬나봅니다ㅠㅜ 다시 열게요

**Comment by vbn2523** [comment]
일본어나 영어를 번역하며 들어온 표현이라면 지양하는 것이 좋겠다고 저도 생각하지만
그걸 대체할 만한 다른 표현이 떠오르지 않아요.

**Comment by STRIKE-F** [comment]
'일찍이 여기에 왔을 땐 가게가 닫혔더군요. 왜 저녁이 돼서야 가게를 여시죠?'
'닫혔더라고요? 여기가요? 전 이 가게를 날마다 아침 일찍 연다고요.'

임의통일 하겠습니다...
