### ISSUE TITLE
한 50년은 다 돼갈 거예요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#343]
![kakaotalk_20160511_234127044](https://cloud.githubusercontent.com/assets/19270364/15227693/6f48efa8-18c3-11e6-8fd3-ece3b5841a08.jpg)

'되어 가다'라는 번역투는 자제합니다.  '한 50년 되었을 거예요' 로도 충분하다고 생각합니다.
좀 더 엄격하게 '한 50년 되었지요'라거나요.

**Comment by jungin019** [comment]
한 50년 되었을 거예요 로 수정했습니다.
