### ISSUE TITLE
전 이 가게를 한 2년인가 3년 정도 하고 있었어요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#344]
![kakaotalk_20160511_234129061](https://cloud.githubusercontent.com/assets/19270364/15227922/6b0e0a94-18c4-11e6-9b4e-60dc699d3621.jpg)

'전 2년인가 3년 전부터 이 가게를 해왔어요' 는 어떤가요?

**Comment by bombomS2** [comment]
그러게요. 문장이 좀 많이 자연스러운 것 같네요.
말씀하신 대로 고치는 것이 좋을 듯합니다.

**Comment by jungin019** [comment]
아니면 '글쎄요, 제가 가게를 운영한 건 2년인가 3년 전부터예요' 는 어떨까요

**Comment by bombomS2** [comment]
글쎄요, 제가 가게를 운영한 건 2년인가 3년 전부터예요.
좋은 것 같아요.
