### ISSUE TITLE
정말 멋진 카페를 갖고 계시군요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#345]
![kakaotalk_20160511_234130959](https://cloud.githubusercontent.com/assets/19270364/15228170/cf8b14ca-18c5-11e6-81e3-661c8d254379.jpg)

굳이 '가지다'라는 표현을 쓸 필요가 없습니다. 
'정말 멋진 카페로군요.'로도 충분하다고 생각합니다.

**Comment by bombomS2** [comment]
동의합니다. 그와 함께
안녕하세요, 부인. 정말 멋진 카페로군요. 이 카페를 여신 지 얼마나 되었는지 여쭤봐도 될까요?
위와 같이 뒤의 문장도 고치면 좋을 것 같습니다.

**Comment by kaleidoscope531** [comment]
'안녕하세요, 부인. 정말 멋진 카페로군요. 이 카페를 여신 지 얼마나 되었는지 여쭤봐도 될까요?'
에 한 표 던지겠습니다.

**Comment by STRIKE-F** [comment]
혹시를 붙이는 건 어떨까요?
'혹시 이 카페를 ~' 이런 식으로요

**Comment by Porowl** [comment]
안녕하세요, 부인. 정말 멋진 카페로군요. 
혹시 이 카페를 여신 지 얼마나 되었는지 
여쭤봐도 될까요?
