### ISSUE TITLE
호텔에서 체크인 하자!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#346]
![kakaotalk_20160513_013700833](https://cloud.githubusercontent.com/assets/19270364/15228562/b965198c-18c7-11e6-965f-d1343f1ecfe6.jpg)
![kakaotalk_20160513_013656598](https://cloud.githubusercontent.com/assets/19270364/15228635/17dca14c-18c8-11e6-8a73-5370f00be6c9.jpg)

베키 등은 레이튼과 루크에게 방명록에 이름을 써 달라고 하지 체크인을 하라고 하지 않습니다.
물론 그게 체크인을 의미하는 것이지만, 굳이 여태 쓰지 않은 용어를 여기서만 쓸 필요는 없겠죠.

**Comment by jungin019** [comment]
이건 좀 애매한 게 호텔에서 체크인 하자! 의 원문에는 아예 check-in 이라고 되어 있습니다. 
그리고 guest book을 방명록으로 번역한데다가 호텔이기 때문에 방명록에 이름을 써달라는 것은 
말씀하신대로 체크인과 같은 의미입니다. 
위의 수수께끼는 의역한 것이 맞지만 방명록 작성 후에 마가렛이 하는 대사에 
'You're signed in,~' 을 '체크인이 되었다'로 번역한 점 등을 볼 때  
굳이 체크인을 바꿔야할지는 살짝 의문이 드네요. 
일단 이슈는 열어놓겠습니다.

**Comment by kaleidoscope531** [comment]
저는 굳이 안 바꿔도 되지 않나 생각합니다.

**Comment by STRIKE-F** [comment]
바꾸지 않고 닫겠습니다.
