### ISSUE TITLE
새 힌트를 여시겠습니까?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#347]
![kakaotalk_20160513_013646047](https://cloud.githubusercontent.com/assets/19270364/15228672/543d2c42-18c8-11e6-8dfe-4071fcbf6f40.jpg)

'열다'와 '힌트'는 어울리지 않습니다. 아예 '잠겨있는 힌트'라고 하면 또 모르지만요...
'새 힌트를 보시겠습니까?' 정도면 어떨까요?

**Comment by bombomS2** [comment]
잠김이라는 표현에 맞추어서 적은 듯한데… 애매하네요. 말씀하신 대로 고치는 게 제일 자연스럽긴 하겠습니다.

**Comment by itstake** [comment]
해당 내용은 정식 발매판과 번역이 동일합니다.

**Comment by bombomS2** [comment]
그렇군요. 그럼 그대로 두는 게 낫겠네요.

**Comment by Y00N** [comment]
그걸 몰랐군요.
