### ISSUE TITLE
상가를 통해서 북쪽으로 가는 게 어때요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#348]
![kakaotalk_20160513_013636203](https://cloud.githubusercontent.com/assets/19270364/15228785/d8cb3ce2-18c8-11e6-9e35-439a036865ba.jpg)

'통해서' 보다는 '지나서'가 더 자연스럽다고 생각합니다.

**Comment by jungin019** [comment]
여기서 상가는 arcade를 번역한 것으로 arcade는 정확히 말하면
'양쪽에 상점들이 늘어서 있는 아치로 둘러싸인 통로'를 뜻합니다. 
그래서 통해서 라는 어휘를 사용했는데 어색하신 것도 이해가 가는군요. 
이슈는 열어놓겠습니다.

**Comment by Y00N** [comment]
![kakaotalk_20160513_013633695](https://cloud.githubusercontent.com/assets/19270364/15252744/58088018-196a-11e6-9e66-b32b4285e1ed.jpg)
여기서도 기왕 지나서를 쓰고있으니...

**Comment by kaleidoscope531** [comment]
상가를 지나려면 아치를 통과할 수 밖에 없으니 그냥 '지나가면'으로 충분할 듯 합니다.
