### ISSUE TITLE
[수수께끼 15] 위쪽의 사람 A는 위에서 본 모양을 설명하고 있고 아랬쪽의 사람 B는옆에서 본 모양을 설명하고 있다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#350]
![kakaotalk_20160513_013627366](https://cloud.githubusercontent.com/assets/19270364/15228992/c0c7af1c-18c9-11e6-8c2a-83a7c060a989.jpg)

답의 선택에 A,B가 나오는 것도 아니니 불필요한 A,B를 제거하는 게 어떨까요
아랬쪽도 아래쪽으로 수정해야 합니다..

위쪽의 사람은 위에서 본 모양을 설명하고 있고
아래쪽의 사람은 옆에서 본 모양을 설명하고 있다.

**Comment by bombomS2** [comment]
좋은 것 같습니다.

**Comment by jungin019** [comment]
아랬쪽은 수정했습니다. 
허나 A와 B는 원문('The person on top (A) is looking down from above, and the person below (B)
is looking at them from one side.')을 역한 것입니다. 
이 부분은 의견에 따라 고치는 게 좋을 것 같네요.

**Comment by kaleidoscope531** [comment]
듣고 보니 A와 B가 꼭 필요하지는 않을 듯도 합니다.

**Comment by bombomS2** [comment]
영문판 원문에 있는 내용이긴 하지만…이후로 전혀 쓰이지 않는다면 버리는 게 좋을 듯하네요.
