### ISSUE TITLE
Fisheye 동태눈->동태눈깔

### ISSUE THREAD

**Issue by STRIKE-F** [elfinlazz/lt3translation#353]
동태눈깔이 좀 더 악당스러운 분위기를 줄 수 있다는 의견이 있습니다.

**Comment by vbn2523** [comment]
동태눈깔이라는 표현이 확실히 더 악당스러운 분위기를 살려주기는 하지만,
보는 사람 따라서는 조금 안 좋은 쪽으로 보일 수도 있지 않을까요?

**Comment by STRIKE-F** [comment]
동태눈깔로 수정했습니다.
