### ISSUE TITLE
베키가 여러분 방까지 안내해줄 겁니다

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#357]
![kakaotalk_20160513_013653931](https://cloud.githubusercontent.com/assets/19270364/15248826/474b25cc-1957-11e6-8306-4326fee2f3f3.jpg)

의미상으로 큰 차이가 없지만, 베키가 '여러분'을 방까지 안내한단 것인지, 베키가 '여러분 방'까지 안내한단 것인지 의미가 모호한 문장입니다.
'베키가 여러분을 방까지 안내할 겁니다.'가 더 낫지 않을까요

**Comment by kaleidoscope531** [comment]
'베키가 여러분을 방까지 안내할 겁니다.' 좋습니다.
