### ISSUE TITLE
[수수께끼 16] 일주일은 7일이니까, 며칠 후나 며칠 전이 7의 배수이기만 하면, 그 날은 무조건 오늘과 같은 요일이 된다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#358]
![kakaotalk_20160513_013524874](https://cloud.githubusercontent.com/assets/19270364/15249293/cb267ade-1959-11e6-99ac-681199dec3be.jpg)

위 문장의 앞 부분을 또 반으로 쪼갠다면 다음과 같이 되겠죠.
며칠 전이 7의 배수이다.
며칠 후가 7의 배수이다.
그런데 '며칠 전'이나 '며칠 후'가 7의 배수 자체라는 건 맞지 않는 표현이라고 생각합니다.

대충 바꿔보면
'일주일은 7일이기에, 오늘로부터 7일씩 떨어져 있는 날은 오늘과 같은 요일이다.' 는 어떱니까?

**Comment by jungin019** [comment]
원문이 'One week is seven days, so if you're ever asked what day was X days ago or
what day is X days from today, as long as X is divisible by seven, the answer
will always be the same day as today!' 네요
'일주일은 7일이므로 만약 오늘부터 X일 전이나 X일 후가 무슨 요일이냐고 물었을 때, X가 7의 배수라면 그 날은 오늘과 같은 요일이 된다!' 정도...

**Comment by STRIKE-F** [comment]
날짜 차이가 7의 배수이기만 하면
이렇게 바꾼다면 어떨까요

**Comment by vbn2523** [comment]
날짜가 7의 배수로 차이난다면 은 어떤가요?

**Comment by STRIKE-F** [comment]
날짜가 7의 배수만큼 차이난다로 수정하겠습니다.
