### ISSUE TITLE
'감히 누굴 보고 있는 거냐, 꼬맹아?' 

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#359]
![kakaotalk_20160513_013531490](https://cloud.githubusercontent.com/assets/19270364/15249610/6931d1dc-195b-11e6-895d-70bd7fb71bdd.jpg)

보다는 
'감히 누굴 쳐다보는 거냐, 꼬맹아?'가 어떤가요?
그 뒤에 루크가 하는 말이 쳐다보려던 건 아니었어요 기도 하고...

**Comment by bombomS2** [comment]
좋아요. 뒷부분을 줄여서
'감히 누굴 쳐다보냐, 꼬맹아?'도 괜찮을 거 같아요.

**Comment by kaleidoscope531** [comment]
'감히 누굴 쳐다보냐, 꼬맹아?'가 좋을 듯 합니다.
