### ISSUE TITLE
저기 통로 뒤에 상가가 있는 게 맞니? 그리고 상가를 통해서 가면 지하철역이 나오는 게 맞아?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#360]
![kakaotalk_20160513_013535492](https://cloud.githubusercontent.com/assets/19270364/15249782/6cf1cd08-195c-11e6-9139-b650de2fede3.jpg)

듀크 특성상 '딩동댕', '땡'으로만 대답합니다만...
'저기 통로 뒤에 상가가 있니? 그리고 상가를 통해서 가면(지나가면) 지하철역이 나오니?' 라고 해도 충분히 예 아니오로 대답할 수 있지 않을까요

**Comment by kaleidoscope531** [comment]
'저기 통로 뒤에 상가가 있니? 그리고 상가를 지나가면 지하철역이 나오니?'로 하는 것이 좋을 듯 합니다.
덧붙이자면 마지막 '나오니?' 를 '나오고?' 로 바꾸는 것은 어떨까요?

**Comment by Y00N** [comment]
위 의견에 찬성합니다.

**Comment by bombomS2** [comment]
저기 통로 뒤에 상가가 있니? 그리고 상가를 지나면 지하철역이 나오고?
좋은 것 같아요.
