### ISSUE TITLE
"낙서 금지!"라고 낙서가 돼있구나

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#361]
![kakaotalk_20160513_013537840](https://cloud.githubusercontent.com/assets/19270364/15250193/807dc1e0-195e-11e6-980a-ddd69764fe7f.jpg)
["낙서 금지!"라는 낙서가 있구나.] 라든지
["낙서 금지!"라는 낙서를 했구나.] 라고 수정하는 건 어떨까요?

**Comment by bombomS2** [comment]
좋은 것 같아요.
누가 "낙서 금지!"라고 낙서를 했구나…
앞에 저렇게 붙이는 것도 괜찮을 것 같네요.

**Comment by kaleidoscope531** [comment]
'누가 "낙서 금지!"라고 낙서를 했구나...' 좋습니다.
