### ISSUE TITLE
[자동차 게임] 아침에 내가 매일 운동하는 경로를 알려 드리죠!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#362]
![kakaotalk_20160513_013544263](https://cloud.githubusercontent.com/assets/19270364/15250510/17a3b524-1960-11e6-94a3-9ecb5cd4a8cf.jpg)

내가 매일 아침 운동하는 경로를 알려 드리죠!

그리고 '타일들'을 또한 '타일을'로 바꾸면 안될까요?

**Comment by kaleidoscope531** [comment]
'내가 매일 아침 운동하는 경로를 알려 드리죠!' 좋습니다. 
그리고 그냥 '타일을'로 바꾸기보단 '여러 종류의 타일을' 로 바꾸는 편이 좋지 않을까요?

**Comment by Y00N** [comment]
말씀하신 쪽이 더 친절해서 좋습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다

**Comment by STRIKE-F** [comment]
@itstake
