### ISSUE TITLE
[자동차 게임] 장난감 자동차의 모든 트랙을 클리어하면, 좋은 일이 일어날 것입니다!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#363]
![kakaotalk_20160513_013545252](https://cloud.githubusercontent.com/assets/19270364/15250600/83b312fa-1960-11e6-85c1-3d100e373154.jpg)

1. ~것 입니다를 바꾸고 반점을 뺍니다.
2. 코스를 완료할 때 뜨는 메세지는 '축하합니다! "0000" 코스를 완료하셨습니다!"' 입니다.
여기에 맞춰서 '클리어하다'를 '완료하다'로 바꾸는 게 좋겠습니다.
3. 장난감 자동차의 모든 트랙보단 장난감 자동차 미니게임의 모든 트랙이 더 자연스럽지 않을까요.
장난감 자동차를 추가할 때 '장난감 자동차 미니게임이 가방에 추가되었습니다!' 라고 나오기도 하구요.

결론 : '장난감 자동차 미니게임의 모든 트랙을 클리어하면 좋은 일이 일어납니다!' 는 어떨까요?

**Comment by kaleidoscope531** [comment]
'장난감 자동차 미니게임의 모든 트랙을 클리어하면 좋은 일이 일어납니다!' 
좋습니다.

**Comment by STRIKE-F** [comment]
올라온 대로 수정하겠습니다.

**Comment by STRIKE-F** [comment]
좋은 일보다는 멋진 일이 좀 더 괜찮은 것 같은데, 어떤가요?
장난감 자동차 미니게임의 모든 트랙을 완료하면 멋진 일이 일어납니다! <-이렇게요

**Comment by kaleidoscope531** [comment]
멋진 일도 괜찮군요

**Comment by STRIKE-F** [comment]
장난감 자동차 미니게임의 모든 트랙을 완료하면 멋진 일이 일어납니다!
로 수정하겠습니다.
