### ISSUE TITLE
만약 타일을 잘 놓았다면, 자동차는 모든 아이템을 획득하고 도착 지점으로 가게 됩니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#365]
![kakaotalk_20160513_013559832](https://cloud.githubusercontent.com/assets/19270364/15250968/3b2e2d60-1962-11e6-8424-1d9bc8e3505a.jpg)

굳이 한문을 쓸 필요 없이 한글로 풀어썼습니다. 그리고 잘 은 영어의 good을 번역하며 의미가 확대된 점도 고려해서 좀 더 어울리는 단어로 고쳐봤습니다.

'타일을 알맞게 두면, 자동차는 모든 아이템을 얻고(지나) 도착 지점으로 갑니다.' 어떤가요?

**Comment by Y00N** [comment]
근데 사실 얻다라는 표현도 신경쓰입니다. 첫 게임밖에 안 해봤는데 깃발을 그냥 쓰러뜨리고 갈 뿐이더라구요.

**Comment by kaleidoscope531** [comment]
다른 게임은 돈보따리 줍고 댕기고 케익 줍고 댕기고 그럽니다 ㅎㅎ
그렇지만 '지나'가 나아 보이기도 하네요.

**Comment by STRIKE-F** [comment]
뒤에 나올 게임들을 생각해 보면 얻고로 고치는 게 좋겠네요.
그리고 타일이니까 두면 보다는 놓으면이 더 좋아 보여요.

**Comment by vbn2523** [comment]
저는 원래 내용이 더 좋아 보입니다.

**Comment by STRIKE-F** [comment]
'타일을 알맞게 두면, 자동차는 모든 아이템을 얻고 도착 지점으로 갑니다.'
로 수정하겠습니다.
