### ISSUE TITLE
자동차가 장애물이나 트랙 밖으로 갈 경우, 처음부터 다시 시작해야 합니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#366]
![kakaotalk_20160513_013547997](https://cloud.githubusercontent.com/assets/19270364/15252425/bcf41ec6-1968-11e6-8f67-f76dd75bb3ed.jpg)

자동차가 장애물에 가로막히거나 트랙 밖으로 나가면 처음부터 다시 시작해야 합니다.
어때요?

**Comment by kaleidoscope531** [comment]
수정하는게 좋을 듯 합니다.

**Comment by STRIKE-F** [comment]
올라온 대로 수정하겠습니다.
