### ISSUE TITLE
점심에는 막 구운 부드러운 빵으로 만든 샌드위치가 나온단다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#368]
![kakaotalk_20160513_013658571](https://cloud.githubusercontent.com/assets/19270364/15254024/afe3a484-196f-11e6-8fa7-14b1dca4449e.jpg)

막 구운이 '부드러운 빵'을 꾸미는지 '샌드위치'를 꾸미는지 알기 어려운 중의적 문장입니다.
사실 전 처음 이 문장을 봤을 땐 '샌드위치를 왜 굽나?'했었어요...
 
'점심에는 샌드위치가 나온단다. 갓 구운 부드러운 빵으로 만들지.' 로 나누어 쓰는 건 어떨까요?

**Comment by kaleidoscope531** [comment]
나누는 게 더 좋을 것 같습니다.

**Comment by bombomS2** [comment]
말씀하신 게 좋은 것 같아요
