### ISSUE TITLE
그것들은 세계 최고는 아닌 건가요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#369]
![kakaotalk_20160513_013659807](https://cloud.githubusercontent.com/assets/19270364/15254156/53c2920e-1970-11e6-85be-2967c3cee001.jpg)
'그건 세계 최고는 아닌가 봐요?' 라고 쓰는 게 더 자연스럽지 않을까 싶네요.

**Comment by kaleidoscope531** [comment]
더 자연스러운 것 같습니다.

**Comment by STRIKE-F** [comment]
올라온 대로 수정하겠습니다.

**Comment by Y00N** [comment]
그것은 - 것이다. 라고 받기는 과하게 ~것을 사용하는 게 아닐는지...

**Comment by vbn2523** [comment]
'그건 세계 최고가 아닌가요?' 는 어떨까요?

**Comment by STRIKE-F** [comment]
'그건 세계 최고가 아닌가요?' 로 수정하겠습니다.
