### ISSUE TITLE
01번 파일 아치형 통로

### ISSUE THREAD

**Issue by jungin019** [elfinlazz/lt3translation#37]
터널이나 통로로 바꿀 것인가

**Comment by Latteria** [comment]
인공적으로 만든 걸 뜻하는 사전적 의미의 터널로는 통로 보다 나아보입니다

**Comment by jungin019** [comment]
아치형을 빼는게 나을까요

**Comment by Latteria** [comment]
덧붙여 하는 설명이라면 굳이 뺄 필요는 없겠죠?

**Comment by jungin019** [comment]
Tell me, is that the arcade back
through that arch? And does the
arcade lead to the station?
원문이 이거라 여기서 arch를 아치라고만 하면 부족할 것 같아
아치형 통로라고 번역했던 건데 그냥 통로나 터널로 바꾸는 게 어떨까하고 
건의가 들어와서요

**Comment by Latteria** [comment]
아 그런거라면 확실히 아치형은 좀 불필요한 설명처럼 보아네요. 통로나 터널만으로 충분해보입니다

**Comment by STRIKE-F** [comment]
아치형을 뺐습니다.
