### ISSUE TITLE
재치있게 차를 조종해 구불구불하고 장애물로 가득 찬 길을 통과하세요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#370]
![kakaotalk_20160513_013606174](https://cloud.githubusercontent.com/assets/19270364/15254340/45adf018-1971-11e6-8636-e40e2406540e.jpg)

'재치있게 차를 조종해 장애물이 가득 찬 구불구불한 길을 지나가세요.' 는 어떤가요?

**Comment by kaleidoscope531** [comment]
원래 문장보다 좋은 것 같습니다. 
추가로 미니게임을 해보셨으면 아시겠지만, 그걸 '구불구불한 길'이라고 표현해야 할지에 대해 회의가 듭니다.
다른 분들 생각은 어떠신지요.

**Comment by STRIKE-F** [comment]
저는 자동차 미니게임을 한 번도 못 해 봐서 어떤지 모르겠네요. 좀 더 많은 의견이 필요하지 싶습니다.

**Comment by Y00N** [comment]
동의합니다. '복잡한' 이면 될까요?

**Comment by kaleidoscope531** [comment]
복잡한 정도면 괜첞을 듯 합니다

**Comment by STRIKE-F** [comment]
재치있게 차를 조종해 장애물이 가득 찬 복잡한 길을 지나가세요.
로 수정하겠습니다.
