### ISSUE TITLE
[수수께끼 15] 최대 21 박스가 있을 수 있다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#371]
![kakaotalk_20160513_013625089](https://cloud.githubusercontent.com/assets/19270364/15254687/f9c0febe-1972-11e6-9409-75fd3aabaf65.jpg)

최대 21 박스이다.
로 충분하다고 생각합니다.

**Comment by STRIKE-F** [comment]
최대 21개가 들어갈 수 있다는 그림과 조금 안 맞으려나요
