### ISSUE TITLE
차를 마신 후에 가도록 하자

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#372]
![kakaotalk_20160513_013631565](https://cloud.githubusercontent.com/assets/19270364/15254710/21cac52a-1973-11e6-8c0d-1ccd35728959.jpg)

'차를 마시고 가 보자.', '차를 마시고 가자꾸나' 등이 좋겠네요.

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
