### ISSUE TITLE
[수수께끼 17] 이 문은 비밀번호를 입력해야 열리는 문인 것 같다. 비밀번호에 대한 단서는 손글씨가 안 좋은 여자가 흘겨쓴 메모밖에 없다. // 정답이 숫자니깐. 이 갈겨쓴 글씨도 숫자여야겠지? ...(후략)

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#373]
![kakaotalk_20160514_013939596](https://cloud.githubusercontent.com/assets/19270364/15255401/c7d5c444-1976-11e6-994f-b1695d9b4697.jpg)

이 문은 비밀번호로 잠긴 문이다. 그런데 비밀번호를 알 단서는 악필인 여자가 쓴 메모 뿐이다.
정답이 숫자니까 이 알아보기 힘든 글씨도 숫자겠지? 그리고 마지막 글씨는 등호처럼 보이기도 하는데?로 고치면 어떨까요

**Comment by kaleidoscope531** [comment]
동의합니다.

**Comment by STRIKE-F** [comment]
올라온 대로 수정하겠습니다.
