### ISSUE TITLE
[수수께끼 17] 완전히 빗나가고 있다. 다른 방법으로 생각해 보는 것은 어떨까?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#374]
![kakaotalk_20160514_013940644](https://cloud.githubusercontent.com/assets/19270364/15255705/9fa54e3e-1978-11e6-908a-3350951d9cea.jpg)

'완전히 빗나갔다. 다른 관점에서 생각해 보자.' 는 어떨까요?

**Comment by kaleidoscope531** [comment]
좋습니다. 
추가로 '완전히 빗나갔다. 다른 관점에서 생각해 보는 것은 어떨까?' 식으로 권유하는 질문(?) 형식은 그대로 두는 것은 어떤지요?

**Comment by STRIKE-F** [comment]
완전히 빗나갔다. 다른 관점에서 생각해 보는 것은 어떨까?'

이대로 수정하겠습니다
