### ISSUE TITLE
[수수께끼 17] 사실 글씨들은 두 개의 세자리 수를 뜻한다. 다시 한 번 잘 살펴보자!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#375]
![kakaotalk_20160514_013938441](https://cloud.githubusercontent.com/assets/19270364/15255724/c863b6bc-1978-11e6-8eca-8c107229ee19.jpg)

사실 저 글씨는 두 개의 세자리 수이다. 다시 한 번 잘 살펴보자!

**Comment by kaleidoscope531** [comment]
그 편이 더 자연스럽고 좋은 것 같습니다.
