### ISSUE TITLE
[수수께끼 17] 노트에 쓰여진 것은 "121 - 113 ="이다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#376]
![kakaotalk_20160514_013937101](https://cloud.githubusercontent.com/assets/19270364/15255767/fd049526-1978-11e6-92ba-737d5ef94588.jpg)

쓰여지다는 쓰이다 + 여지다 가 합쳐진 이중피동입니다. 
그리고 수식은 붙여 쓰는 거 아닌가요? 잘 모르겠네요.

'노트에 쓰인 것은 "121-113="이다.' 로 고쳐보았는데 어떤가요?

**Comment by kaleidoscope531** [comment]
훨씬 자연스럽습니다.
그리고 수식은 붙여 적는 것에 동의합니다만, 화면 상에서 보기에 안 좋아 보인다면 어느 정도는 재량을 발휘하셔도 될 듯 합니다.

**Comment by Porowl** [comment]
'노트에 쓰인 것은 "121-113="이다.' 로 한표

**Comment by STRIKE-F** [comment]
해상도 때문에 가독성 면에서는 띄는 편이 좋을 것 같아요.
