### ISSUE TITLE
휴! 자네 덕분에 드디어 다시 요리를 할 수 있겠군

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#378]
![kakaotalk_20160514_013934450](https://cloud.githubusercontent.com/assets/19270364/15255951/e1df8a20-1979-11e6-8da3-1585f297a94c.jpg)

'-되다'를 고쳐보는 게 어떨까요
'휴! 자네 덕분에 드디어 다시 요리를 할 수 있겠군.' 라는 식으로요.

**Comment by kaleidoscope531** [comment]
동의합니다.
