### ISSUE TITLE
그냥, 한 마디 충고나 해주려고 해서.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#379]
![kakaotalk_20160514_013929568](https://cloud.githubusercontent.com/assets/19270364/15256081/c22bac6c-197a-11e6-9c56-1d0a83ad31b2.jpg)
충고를 해줄까 해서 라는 말이 깔끔하지 못하네요.
'그냥, 충고나 한 마디 해주려고.' 는 어떤가요?

**Comment by kaleidoscope531** [comment]
'그냥, 충고나 한 마디 해주려고.' 쪽이 자연스러운 것 같습니다.
