### ISSUE TITLE
높은 모자의 악마

### ISSUE THREAD

**Issue by jungin019** [elfinlazz/lt3translation#38]
무언가 표현이 어색

**Comment by Latteria** [comment]
원문 좀 볼 수 있나요

**Comment by jungin019** [comment]
원문은 devil in the top hat이라 높은 모자의 악마가 맞지만 베타 한 분이 어색하다고 하셔서용

**Comment by Latteria** [comment]
ths top을 위대한 등으로 의역해서
위대하신 그 모자의 악마 같은 해석은 안될까요?

**Comment by STRIKE-F** [comment]
우람한 모자의 악마...는 너무 개그스럽고
드높은 모자의 악마는 어떤가요

**Comment by STRIKE-F** [comment]
거대한 모자의 악마는 뭔가 간지가 안 나...

**Comment by yhwon90** [comment]
이미 해결된 문제인지는 모르겠지만 
신사모를 쓴 악마
어떤가요

**Comment by Porowl** [comment]
윗분 글 보고 '신사의 탈을 쓴 악마'가 생각이 났습니다.

**Comment by kaleidoscope531** [comment]
저도 신사모를 쓴 악마가 좋아 보입니다.

**Comment by bombomS2** [comment]
신사모를 쓴 악마 좋네요.

**Comment by bombomS2** [comment]
참, 계속 기시감이 들다 생각난 건데 일판에서는 '실크햇의 악마'라는 표현을 썼었습니다. 참고해도 좋을 것 같아요.

**Comment by itstake** [comment]
정식 발매명을 따라 "Top hat" 를 "신사모" 로 번역, 신사모를 쓴 악마로 최종 결정되었습니다.
