### ISSUE TITLE
전부 똑같이 긴 코드와 검정 모자를 쓰고 있거든

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#380]
![kakaotalk_20160514_013927735](https://cloud.githubusercontent.com/assets/19270364/15256155/1afe3c10-197b-11e6-90d1-d7a6e19d7159.jpg)

쓰다가 코트와 호응하지 못합니다.
'전부 똑같이 긴 검정 코트를 입고 검정 모자를 쓰고 있거든.'

**Comment by kaleidoscope531** [comment]
동의합니다.

**Comment by STRIKE-F** [comment]
그렇네요. 수정하겠습니다.
