### ISSUE TITLE
그러면 왜 경찰들은 가만히 있는 건가요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#381]
![kakaotalk_20160514_013925832](https://cloud.githubusercontent.com/assets/19270364/15256213/63286d12-197b-11e6-9c64-fbec8de51927.jpg)

'그러면 경찰은 왜 가만히 있죠?' 는 어떤가요? -들을 빼고 건을 빼고 '왜'는 그냥 제가 평소 말하는 습관대로 옮겨봤습니다.

**Comment by kaleidoscope531** [comment]
'그러면 경찰은 왜 가만히 있죠?' 좋습니다.

**Comment by STRIKE-F** [comment]
이대로 수정하겠습니다.
