### ISSUE TITLE
내 말이 말야.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#382]
![kakaotalk_20160514_013923042](https://cloud.githubusercontent.com/assets/19270364/15256412/6aae0d34-197c-11e6-9248-17b376a49221.jpg)

내 말이 그 말이야.

말이 말이야 라는 표현이 매끄럽지 않다고 생각했습니다.

**Comment by kaleidoscope531** [comment]
쳐다보지 않는 게 좋아. 도 그냥 '쳐다보지마' 로 바꾸는 건 어떨지요?

**Comment by bombomS2** [comment]
내 말이 그 말이야. 좋습니다. 아니면 내 말이. 로 끝내는 것도 좋을 듯하군요.
쳐다보지 않는 편이 좋아. 는 어떤가요?

**Comment by Porowl** [comment]
내 말이 그 말이야. 나...이런, 모자파 
녀석이 하나 오고 있어. 쳐다보지
않는 편이 좋아.
