### ISSUE TITLE
그런 것 같구나 루크. 분명 10년 뒤의 날짜가 적혀 있었어.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#384]
![kakaotalk_20160514_013918047](https://cloud.githubusercontent.com/assets/19270364/15257094/b6050564-197f-11e6-84cf-5a8cb51ab234.jpg)

그렇구나, 루크. 분명 10년 뒤의 날짜였어.
가 더 매끄럽다고 생각합니다.

**Comment by kaleidoscope531** [comment]
동의합니다.

**Comment by bombomS2** [comment]
네, 좋은 것 같습니다.
