### ISSUE TITLE
그러니까, 우리가 10년 후의 런던에 와서 이곳의 모든 것이 낯설어 보였던 거군요!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#385]
![kakaotalk_20160514_013856273](https://cloud.githubusercontent.com/assets/19270364/15257184/16fc0a66-1980-11e6-8c9f-574f61bb9732.jpg)

낯설다는 보다가 전제되어 있는 말이라 '낯설게 보이다'라고 쓸 필요가 없습니다. 
'그러니까, 우리가 10년 후의 런던에 와서 모든 게 낯설었던 거군요!' 로도 충분하다고 생각합니다.

**Comment by kaleidoscope531** [comment]
'낯설었던 거군요!' 동의합니다.
