### ISSUE TITLE
생각했던 것보다는 오래 걸렸지만 드디어 역에 도착했군

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#386]
![kakaotalk_20160514_013841871](https://cloud.githubusercontent.com/assets/19270364/15257584/f596bf22-1981-11e6-963a-da4e34deee46.jpg)

불필요한 명사화입니다.
생각보다는 오래 걸렸지만 드디어 역에 도착했군

**Comment by kaleidoscope531** [comment]
'생각보다는 오래 걸렸지만 드디어 역에 도착했군' 좋습니다.

**Comment by bombomS2** [comment]
개인적인 생각이지만 뒤의 문장 어미를 조금 수정하면 어떨까 합니다…

**Comment by kaleidoscope531** [comment]
도착했어 어떤가요?

**Comment by Y00N** [comment]
"생각보다는 오래 걸렸지만 드디어 역에 도착했구나" 는 어떤가요?

**Comment by yhwon90** [comment]
@Y00N "생각보다는 오래 걸렸지만 드디어 역에 도착했구나"로 쓰기에는 바로 앞 문장이 ~ 구나로 끝나네요.
저는 '도착했군'이 마음에 듭니다

**Comment by STRIKE-F** [comment]
했네로 끝내는 건 어떨까요?

**Comment by Y00N** [comment]
저는 -했어가 좋습니다.

**Comment by vbn2523** [comment]
'생각보다 오래 걸리기는 했지만, 무사히 역에 잘 도착했어.' 는 어떤가요?

제 개인적인 생각으로는 '오래 걸렸지만 + 드디어' 도 살짝 이상하다고 생각해요.

**Comment by STRIKE-F** [comment]
생각보다는 오래 걸렸지만, 그래도 무사히 역에 도착했네.
일단은 이렇게 (맘대로..) 수정하겠습니다
