### ISSUE TITLE
꼬마야, 다치기 싫으면 그 눈 좀 저리 치우려무나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#389]
![kakaotalk_20160514_013831879](https://cloud.githubusercontent.com/assets/19270364/15266746/043f751a-19ea-11e6-8a66-2a529af6703a.jpg)
눈을 치우라는 표현이 일상적이라는 생각이 안 드네요.
"꼬마야, 다치기 싫으면 그만 좀 쳐다보지?" 
"꼬마야, 다치기 싫으면 그만 좀 쳐다볼래?" 어떤가요?

**Comment by kaleidoscope531** [comment]
"꼬마야, 다치기 싫으면 그만 좀 쳐다보지?" 쪽이 더 까칠해 보이네요

**Comment by bombomS2** [comment]
꼬마야, 다치기 싫으면 그만 쳐다보지?

**Comment by rabbitdoggy** [comment]
치우려무나는 확실히 부적절해 보이고

다치기 싫으면 그만 쳐다보는 게 좋을걸.

정도가 어떨까 합니다.

**Comment by STRIKE-F** [comment]
다치기 싫으면 그만 좀 쳐다보시지? 는 어떨까요

**Comment by Y00N** [comment]
저는 ~려므나 라는 어미가 굉장히 다정다감하게(?) 느껴졌었거든요.
꼬맹이에게 친절어린 위협을 하는(?) 뭐 그런거요.
그런 의미에서

꼬마야, 다치기 싫으면 그만 좀 쳐다볼래? 나
꼬마야, 다치기 싫으면 그만 쳐다보지? 가 좋습니다.

**Comment by Porowl** [comment]
꼬마야, 다치기 싫으면 그만 쳐다보지?
