### ISSUE TITLE
좋아. 계속 북쪽으로 가면 역이 길 오른쪽에 있을 거야.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#390]
![kakaotalk_20160514_013850688](https://cloud.githubusercontent.com/assets/19270364/15266798/f83ba166-19ea-11e6-8925-424c9af136c0.jpg)

"좋아. 계속 북쪽으로 가다보면 길 오른쪽에 역이 있을 거야." 어떤가요?

**Comment by kaleidoscope531** [comment]
좋습니다.
