### ISSUE TITLE
그래. 하지만 좀 더 조사해 볼 필요가 있겠구나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#391]
![kakaotalk_20160514_013854182](https://cloud.githubusercontent.com/assets/19270364/15266803/299d556a-19eb-11e6-8a40-8b33623511ac.jpg)

'~할 필요가 있다'는 다소 불필요하게 긴 표현이라고 생각합니다.
"그래. 하지만 좀 더 조사해봐야겠구나." 로도 충분하지 않을까요

**Comment by kaleidoscope531** [comment]
충분할 것 같습니다.
