### ISSUE TITLE
조사 메모: 미드랜드 길의 시계 가게

### ISSUE THREAD

**Issue by yhwon90** [elfinlazz/lt3translation#392]
첫 문장이 다음과 같습니다.
시계 가게는 미드랜드 길의 끝에 숨어 있었다, 그리고 그 안에는 아주 다양한 시계들이 있었고, 눈길을 끌 만한 엄청난 시계가 하나 있었다.
'있었다'가 세 번 반복되고 쉼표를 포함해서 문장이 너무 길다는 생각이 듭니다.

시계 가계는 미드랜드 길의 끝에 숨어 있었다. 그 안에는 아주 다양한 시계와 특히 눈길을 끄는 엄청난 시계가 하나 있었다. 
정도로 수정하는 편이 좋아보입니다.

**Comment by Y00N** [comment]
"다양한 시계와 특히 눈길을 끄는 엄청난 시계가 하나 있었다."는 위 말 속에서 "하나 있다"는 게 "눈길을 끄는 엄청난 시계"만을 꾸미는지 "다양한 시계"까지 꾸미는지 약간 애매하네요.
"시계 가게는 미드랜드 길의 끝에 숨어 있었다. 그 안에는 다양한 시계가 있었는데, 그 중 하나는 엄청나게 눈길을 끌었다." 어떤가요?

**Comment by yhwon90** [comment]
@Y00N 말씀하신 문장이 더 자연스러운 것 같습니다ㅎㅎ

**Comment by kaleidoscope531** [comment]
저도 YOON 님의 의견에 동의합니다.
