### ISSUE TITLE
시계 가게 안 오브젝트: 루크: 시계가 똑딱거리는 걸 본 순간 더이상 거부할 수 없어..

### ISSUE THREAD

**Issue by yhwon90** [elfinlazz/lt3translation#395]
천장 근처에 있는 시계를 선택하면 나오는 팝업입니다.

더이상-> 더 이상

그리고 거부할 수 없는게 대체 뭔지.....
이거 원문이 뭔가요??

혹시 can't resist.. 였다면
더 이상 잠을 참을 수가....
정도가 맞는 의역이 될 것이라 생각합니다

**Comment by kaleidoscope531** [comment]
밑에 제가 올린 이슈 있습니다.
오늘 미팅 때 정하면 될 것 같습니다.

**Comment by yhwon90** [comment]
아 검색으로 중복을 거르는데 놓쳤나보군요ㅠ
일단 "더 이상" 때문에 남겨놓기는 하겠습니다
