### ISSUE TITLE
세상에나 만상에나!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#397]
![screenshot_2016-05-10-21-54-12](https://cloud.githubusercontent.com/assets/19295794/15267079/843ee946-19f2-11e6-8256-edbfb750de42.png)
세상에나 마상에나! 가 맞는 표현이 아닌가 싶습니다.

**Comment by Y00N** [comment]
뭐 사실 둘 다 표준어에 맞는 표현은 아니긴 한데...
더 오래 묵은 표현은 '세상에나 만상에나'가 아니었나 싶습니다.

**Comment by kaleidoscope531** [comment]
동의합니다

**Comment by STRIKE-F** [comment]
헐 이게 틀린 표현이었다니 (사투리의 폐해인가)
수정하겠습니다.

**Comment by STRIKE-F** [comment]
는 저 표현 자체가 사투리였구나
