### ISSUE TITLE
조사 메모: 거대한 시계 & 갑자기 바뀐 도시

### ISSUE THREAD

**Issue by yhwon90** [elfinlazz/lt3translation#398]
거대한 시계에서는 코그 씨
갑자기 바뀐 도시에서는 코그가 입니다
시계 가게 주인 아저씨의 명칭을 하나로 통일하기를 요청드립니다

그런데 코그씨 이름 원래는 뭔가요? Cog라면 톱니바퀴라는 말장난 이기도 할텐데.. 이걸 어떻게 살릴 수는 없는지..

**Comment by kaleidoscope531** [comment]
Cogg입니다.
말장난 맞을겁니다. 마누라 이름은 Spring 이고

**Comment by Y00N** [comment]
호칭 통일은 스샷 찍어놓고 깜박했었네요

**Comment by jungin019** [comment]
코그 씨로 통일하는 게 좋겠네요. 그리고 코그는 말장난이 맞는 것으로 알고 있습니다만
딱히 뭐라고 해야할지 모르겠네요. 일단 이슈는 열어두겠습니다

**Comment by kaleidoscope531** [comment]
이름은 그대로 두는 편이 좋아보입니다.
역재에서도 나루호도를 굳이 과연 용일이라고 하지는 않잖아요?

**Comment by STRIKE-F** [comment]
과연 용일 ㅋㅋㅋㅋ;;;;;
코그 씨로 통일하겠습니다
