### ISSUE TITLE
레이튼: 이상한데, 방금 전까지는 이런 공사는 없었는데 말이다

### ISSUE THREAD

**Issue by yhwon90** [elfinlazz/lt3translation#400]
방금 막 지나간 문장이라 원문이 저게 확실한지 잘 모르겠습니다.
시계 가게에서 큰 시계가 돌아가는 것을 보고 밖으로 나와 만난 인부 아저씨, '아트'와의 대화인데..
레이튼의 저 대사 다음에 아트가 대답을 해요.
처음 보는 아저씨한테 반말로 갑자기 태도가 돌변하는 레이튼 교수님.

이런 공사는 없었는데 말이죠.

정도로 대사가 바뀌어야 할 것 같습니다.

**Comment by kaleidoscope531** [comment]
저는 저 말을 루크한테 하는 말인줄 알았는데 그렇게 생각할 수도 있겠군요.

**Comment by yhwon90** [comment]
저도 루크에게 한 말이겠거니 해서 넘겼더니 인부 아저씨가 대답을 하시더라구요.. 좀 어색했습니다 ㄷㄷ

**Comment by jungin019** [comment]
음... 이 부분은 레이튼의 독백? 정도로 볼 수 있겠네요. 
그리고 말씀대로 아트에게 하는 말이라고 보는 게 더 좋긴 할 것 같군요

**Comment by STRIKE-F** [comment]
정황상 대사 자체는 독백이 맞아요.
근데 뒤에 아트 대답도 있고, 말이다만 빼면 그런 대로 자연스러울 거 같아요.

이상하군... 방금 전에는 이런 공사는 확실히 없었는데. 같이요

**Comment by Y00N** [comment]
스프님 의견에 동의합니다.

**Comment by kaleidoscope531** [comment]
저도 동의합니다

**Comment by Porowl** [comment]
이상하군... 방금 전만 해도 이런 공사는
확실히 없었는데.
