### ISSUE TITLE
(Passive) 이곳 저곳 -> 여기 저기

### ISSUE THREAD

**Issue by Porowl** [elfinlazz/lt3translation#401]
제곧내

**Comment by Y00N** [comment]
![kakaotalk_20160515_002036622](https://cloud.githubusercontent.com/assets/19270364/15297644/2e4d5cda-1bd6-11e6-8b64-cc0fe801b159.jpg)

**Comment by Y00N** [comment]
![screenshot_2016-05-15-23-05-11](https://cloud.githubusercontent.com/assets/19270364/15427366/9da18b6e-1ecf-11e6-8e00-62ca93205f57.png)

**Comment by STRIKE-F** [comment]
모든 이곳->여기, 저곳->저기인가요?

**Comment by STRIKE-F** [comment]
일단 전부 수정했습니다.
