### ISSUE TITLE
스포일러에 대하여....

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#404]
스포일러성 이슈에 대해 어떻게 할 지 생각하다 제가 생각한 방법이 있습니다.
검색을 할 때 본문에 있는 내용도 같이 검색이 되더군요.
따라서 제목에는 챕터만 적어놓고 본문 시작하는 글 첫 마디에 관련 대사를 적어놓겠습니다. 

스포일러를 원하지 않으시면 현재 하고 계신 챕터 이전 챕터까지의 내용만 확인하시면 됩니다.
찾으신 내용이 올라온 이슈인지 확인하시려면 검색을 해 보시면 됩니다.
아, 검색하실 때 미리 적혀 있는 is: issue, is : open 이 부분을 지우셔야 닫힌 이슈까지 검색됩니다.

일단 시험 삼아 챕터 4까지를 이 방식으로 올려보고 있습니다. 마음에 안 드시면 적어주시면 제목을 원래 형식으로 바꾸던지 하겠습니다. 지우는 방법은 잘 모르겠네요.

**Comment by Y00N** [comment]
저는 이 의견을 존중합니다.
