### ISSUE TITLE
[오역] 챕터 3

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#412]
아니타 : 결국, 말해버렸네요! 그러니까 당신 그 모자 때문에 얼마나 곤경에 처해진 건가요?
           : So, spill the beans! Just how much trouble did that hat get you into?
레이튼 : 모자 때문이라는게 그렇게나 명백합니까?
            : Is it that obvious?
아니타 : 네, 당연하죠. 곤경에 처해서 어쩔 줄 모르는 모습이 제 눈에 선하다구요.
           : Oh, yeah. You've got a slight shell-shocked look about you.
아니타 : 이제 그건 됐어요. 이제 당신이 여기 있으니까, 내게 뭔가를 도와줘야 하겠네요.
            : But enough about that. Now that you're here, there's something I'd like your help with.
-수수께끼 41번-
아니타 : 어쨌거나, 당신 모자에는 어떤 사연이 얽혀있는 건가요?
            : What's the story with that hat of yours, anyway?
아니타 : 당신 정말 그 모자에 푹 빠졌나 보군요. 그게 위험이 될 줄 알면서도 계속 쓰고 있는걸 보면.
           : You must be awfully attached to it to keep it on knowing the kind of trouble it can cause.

![image](https://cloud.githubusercontent.com/assets/19265176/15272768/e2e24de0-1abe-11e6-98df-ced4b3281b00.png)
![image](https://cloud.githubusercontent.com/assets/19265176/15272770/e7669ac4-1abe-11e6-9bcf-39da63bbb94b.png)
![image](https://cloud.githubusercontent.com/assets/19265176/15272771/e9fba856-1abe-11e6-896d-7efe08a8b651.png)
![image](https://cloud.githubusercontent.com/assets/19265176/15272773/efcb9548-1abe-11e6-9a10-9ad859355385.png)
![image](https://cloud.githubusercontent.com/assets/19265176/15272774/f4360b18-1abe-11e6-87df-344bca398c98.png)
![image](https://cloud.githubusercontent.com/assets/19265176/15272776/f71ec1bc-1abe-11e6-9bfc-675b2f4962f5.png)
![image](https://cloud.githubusercontent.com/assets/19265176/15272778/0266927a-1abf-11e6-965f-50ba991c2116.png)

일단, 제가 좀 고쳐봤습니다. 순서는 
원래 번역
바꾼 번역
원문

입니다.

아니타 : 결국, 말해버렸네요! 그러니까 당신 그 모자 때문에 얼마나 곤경에 처해진 건가요?
           -> 어디 한 번 솔직히 말해봐요. 그 모자 탓에 얼마나 험한 일에 말려들었나요?
           : So, spill the beans! Just how much trouble did that hat get you into?
레이튼 : 모자 때문이라는게 그렇게나 명백합니까?
           -> 그렇게 티가 납니까?
            : Is it that obvious?
아니타 : 네, 당연하죠. 곤경에 처해서 어쩔 줄 모르는 모습이 제 눈에 선하다구요.
           -> 아 그렴요. 지금 댁 얼굴이 딱 일 터져서 어쩔 줄 모르는 표정인데요.
           : Oh, yeah. You've got a slight shell-shocked look about you.
아니타 : 이제 그건 됐어요. 이제 당신이 여기 있으니까, 내게 뭔가를 도와줘야 하겠네요.
           -> 뭐 그건 됐고, 기왕 온 김에 내 일이나 좀 도와봐요.
            : But enough about that. Now that you're here, there's something I'd like your help with.
-수수께끼 41번-
아니타 : 어쨌거나, 당신 모자에는 어떤 사연이 얽혀있는 건가요?
            ->그나저나 당신, 그 모자에 무슨 사연이라도 있나요?
            : What's the story with that hat of yours, anyway?
아니타 : 당신 정말 그 모자에 푹 빠졌나 보군요. 그게 위험이 될 줄 알면서도 계속 쓰고 있는걸 보면.
            -> 그 모자 때문에 위험해질 걸 뻔히 알면서도 꿋꿋하게 쓰고 있는걸 보면, 어지간히 애착이 큰 게 아닌 것 같은데
           : You must be awfully attached to it to keep it on knowing the kind of trouble it can cause.

**Comment by jungin019** [comment]
말씀하신 번역이 더 맞습니다. 일단 이슈는 열어둘게요.

**Comment by Y00N** [comment]
정말정말 좋습니다. 사소한 부분 몇 가지만 말씀드리고자 합니다.
"아 그렴요." -> "아, 그럼요."
"뭐 그건 됐고," -> "뭐... 그건 됐고" or "뭐, 그건 됐고,"
"꿋꿋하게 쓰고 있는걸 보면" -> "꿋꿋하게 쓰고 있는 걸 보면" or "꿋꿋하게 쓰고 다니는 걸 보면"
"어지간히 애착이 큰 게 아닌 것 같은데" -> "어지간히 애착이 큰가 본데"

**Comment by Y00N** [comment]
아, 그리고 여긴 챕터 3입니다.

**Comment by kaleidoscope531** [comment]
오타 수정 감사드립니다. 
제목은 챕터 3로 바꿨습니다.
제가 저 이벤트를 챕터 4에서 봐서요 ㅎㅎ
