### ISSUE TITLE
[제안] 어미 '-니깐'에 대한 제의

### ISSUE THREAD

**Issue by rabbitdoggy** [elfinlazz/lt3translation#443]
![screenshot_2016-05-11-01-17-47](https://cloud.githubusercontent.com/assets/19265174/15376451/fd7b96ba-1d8f-11e6-84bf-27059467bbe9.png)

위 스크린샷과 같이(오른쪽 화면) 가끔 어미 '니까'를 '니깐'으로 쓰는 경우가 왕왕 보입니다.

일부러 의도하신 바가 있는지는 모르겠습니다만 '니까'로 통일하는 게 어떨까 합니다. '니깐'으로 쓸 이유가 적어보입니다.

**Comment by kaleidoscope531** [comment]
좋습니다.

**Comment by STRIKE-F** [comment]
성격이 좀 더럽거나(?) 괄괄한 인물들은 말할 때 -니깐을 쓰는 것도 괜찮아 보이는데, 어떤가요?
그 외에는 -니까로 수정하겠습니다.
