### ISSUE TITLE
그러니까, 우리가 10년 후의 런던에 와서 이곳의 모든 것이 낯설어 보였던 거군요!

### ISSUE THREAD

**Issue by rabbitdoggy** [elfinlazz/lt3translation#446]
![screenshot_2016-05-11-01-22-32](https://cloud.githubusercontent.com/assets/19265174/15376689/9783b61a-1d91-11e6-8d94-aa3fd6aa733a.png)

대사 첫째 줄의 여백을 더 남기면 어떨까 합니다.

**Comment by jungin019** [comment]
현재는 '그러니까, 우리가 10년 후의 런던에 
와서 모든 게 낯설었던 거군요!'로 수정되어 있습니다.
