### ISSUE TITLE
[제안] 수수께끼 146번의 '반 마리'에 대한 문제

### ISSUE THREAD

**Issue by rabbitdoggy** [elfinlazz/lt3translation#454]
![screenshot_2016-05-11-01-36-18](https://cloud.githubusercontent.com/assets/19265174/15377043/d7a501b6-1d93-11e6-9657-9a007e7c1d6e.png)

이미 다른 분이 표현 수정 관련하여 제기하셨던 내용이고 저도 올렸다 중복임을 확인하였지만 힌트 등의 내용에서 '반 마리'라는 표현을 사용하고 있고 이 부분에 대한 내용은 올라온 바가 없어 제안합니다.

'반 마리'는 한 마리의 반절이라는 의미로 쓰이니

반 마리보다는 '반'으로 쓰는 게 나을 것 같습니다.

예컨대, '전체의 반 마리가 날아가고' 보다는 '전체의 반이 날아가고' 정도로 고치는 게 어떨까 합니다.

**Comment by jungin019** [comment]
그 때 문제는 고쳤는데 힌트는 고치지 않았었군요. 수정했습니다.
