### ISSUE TITLE
수수께끼 마담: 내가 자기소개를 할 수 있게 해주려무나!

### ISSUE THREAD

**Issue by yhwon90** [elfinlazz/lt3translation#458]
Let me introduce myself
Allow me to introduce myself
직역한 것 같은데요.. 아무래도 어색하네요
일단 자기소개부터 하게 해주려무나
라던가
자기소개를 먼저 하는게 순서에 맞겠지!
정도로 의역하는게 좋을 것 같습니다

**Comment by kaleidoscope531** [comment]
좋습니다. 전 전자가 더 좋네요.

**Comment by jungin019** [comment]
마담 대사를 한 번 훑어봐야겠군요...

**Comment by Y00N** [comment]
먼저 내 소개부터 시작하마! 어떨까요?

**Comment by STRIKE-F** [comment]
내가 누구냐면 말이다 라거나

**Comment by kaleidoscope531** [comment]
먼저 내 소개부터 시작하마! 도 좋아 보이네요

**Comment by vbn2523** [comment]
먼저 내 소개부터 해야겠어. 는 어떨까요?

**Comment by STRIKE-F** [comment]
먼저 내 소개부터 하마! 로 고칠게요.
