### ISSUE TITLE
레이튼: 우리는 숙녀가 불쾌해하기를 바라지는 않잖니?

### ISSUE THREAD

**Issue by yhwon90** [elfinlazz/lt3translation#459]
직역한 느낌이 너무 많이 납니다.
수수께끼 마담이 나이에 비해 괜찮아보인다고 하는 루크에게 하는 말이니까
숙녀분께 그런 말투는 실례잖니?
정도는 어떨까요

**Comment by yhwon90** [comment]
그리고 수수께끼 마담과의 대화가 전반적으로 좀 이런 느낌입니다.
일일이 보고하기가 좀 그래서 일단은 넘겼는데...
대사를 쭉 늘어놓은 상태에서 한 번 교정을 보고 싶네요.

**Comment by kaleidoscope531** [comment]
동감입니다.

**Comment by Y00N** [comment]
좋습니다.

**Comment by jungin019** [comment]
숙녀분께 그런 말투는 실례잖니? 로 수정
