### ISSUE TITLE
조사 메모: 공포를 불러일으키는 모자

### ISSUE THREAD

**Issue by yhwon90** [elfinlazz/lt3translation#461]
이곳이 런던이라는 사실은 변함이 없는 것 같다, 하지만 우리가 시계 가게를 나간 이후 모든 것이 이상하다.
아주 오래된 도로인 미드랜드 길도 완전히 새 길 같다.
그리고 나의 모자는 사람들을 약간 당황시키는 것 같다.
마치 우리가 무슨 환상을 보는 듯 한 느낌이다.
도대체 이게 무슨 일이지?

1. 첫 문장 쉼표를 온점으로
2. '같다'가 세 번이나 나옵니다.
미드랜드 길이 완전히 새 길처럼 보이고, 내 모자도 사람들을 약간 당황시키는 모양이다.
는 어떨까요?
3. 오역이 의심됩니다.
게임 안에서는 미드랜드 길이 새 것처럼 보이는 분위기가 아닙니다. 관리가 잘 안 된 것 같다는 묘사가 나오는 등..
아주 익숙한 길인 미드랜드 길이 달라져 보인다는 뉘앙스가 아니었을까 의심되네요.
원문이 뭔지 궁금합니다.

**Comment by jungin019** [comment]
1,2 - 현재는 '이곳이 런던이라는 사실은 변함이 없는 것 같다. 하지만 우리가 시계 가게를 나간 이후
모든 것이 이상하다. 오래 된 미드랜드 도로의 침침한 풍경이 완전히 처음 보는 것처럼 바뀐데다
사람들이 내 모자를 두려워 하는 것 같다. 마치 어떤 환상을 보는 듯한 느낌이다. 
도대체 이게 무슨 일이지?' 로 바뀌어 있습니다. 
3 - 해당 문장의 원문은 'Not only does gloomy old Midland Road look like a
whole new place,~' 입니다.

**Comment by Y00N** [comment]
여기가 런던임에는 틀림없다. 하지만 시계 가게를 나오고 모든 것이 바뀌었다. 
오래된 미드랜드 길도 예전과 달라 보인다. 심지어 사람들은 내 모자만 봐도 두려워한다. 
마치 어떤 환상을 보는 듯하다. 도대체 이게 무슨 일일까?
이렇게 하면 어떨까요?

**Comment by STRIKE-F** [comment]
좋네요. 이대로 수정하겠습니다.
