### ISSUE TITLE
수수께끼 11 힌트1/힌트 2/힌트 3

### ISSUE THREAD

**Issue by yhwon90** [elfinlazz/lt3translation#463]
힌트1
그럴려면 다른것을 다 뒤집어야 한다
-> 그러려면 다른 것을

힌트2
ㅗ을 뒤집을 것이면
-> ㅗ만을 뒤집을 생각이라면
이 문맥상 더 어울립니다.

힌트3
왼쪽 모서리에 맏추면 된다
-> 맞추면 된다

그리고 블럭 모양 글자? 뒤에 '블럭'이라는 단어를 추가하면 좋을 것 같습니다.
ㅗ을 뒤집는다..보다는 ㅗ 블럭을 뒤집는다...가 더 나아보이겠죠?

**Comment by kaleidoscope531** [comment]
동의합니다.
