### ISSUE TITLE
루크: 이건 쉽네요. 보세요, 선생님. 조금만 더 가면 병원이에요.

### ISSUE THREAD

**Issue by yhwon90** [elfinlazz/lt3translation#466]
이건 쉽네요가 불필요합니다.
원문이 that was easy 정도였을 것 같은데 우리말에서 저걸 굳이 쓸 필요가 없어보이네요.

**Comment by Y00N** [comment]
동감합니다.

**Comment by kaleidoscope531** [comment]
동의합니다.

**Comment by jungin019** [comment]
말씀대로 원문은 'Well, that was easy' 입니다. 
문맥상 이건 쉽네요 보다는 의역해서 '일이 잘 풀리네요' 정도로 번역하면 어떨까 합니다.

**Comment by kaleidoscope531** [comment]
일이 잘 풀리네요 좋습니다.

**Comment by Y00N** [comment]
찬성합니다
