### ISSUE TITLE
수수께끼 21 문제/힌트1/힌트2/힌트3/정답화면

### ISSUE THREAD

**Issue by yhwon90** [elfinlazz/lt3translation#469]
문제
도데체 어디까지 마셔야 할까 -> 도대체

힌트1
하는것이 가장 쉬울 것이다. -> 하는 것이

힌트2
정사각형을 남기는건 -> 남기는 건 or 남기는 것은
두개를 -> 두 개를 (2번 나옵니다)

힌트3
중간의 있는 정사각형과 -> 중간에 있는

정답
두개 -> 두 개 (2번 나옵니다)
정사각형 두 개가 모인 긴 직사각형을 표시된 것처럼 대각선을 그으면 똑같은 크기가 된다.
-> 정사각형 두 개가 모인 긴 직사각형에서 표시된 것처럼 대각선을 그으면 각 조각이 서로 똑같은 크기가 된다.

**Comment by Y00N** [comment]
힌트 3은 "중간에 있는" 보다는 "중간의"가 낫지 않을까요?

**Comment by jungin019** [comment]
도대체, 하는 것이, 남기는 건, 두 개, 정사각형 두 개가 모인 긴 직사각형에서 표시된 것처럼 대각선을 그으면 각 조각이 서로 똑같은 크기가 된다.
고쳤습니다. 

힌트 3의 경우 '가운데의' 는 어떨까요?

**Comment by STRIKE-F** [comment]
일단은 가운데의로 수정했습니다.
