### ISSUE TITLE
수수께끼 41번

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#471]
문제를 푸는 데 문장이 다소 매끄럽지 않아 쉬이 이해되지 않더군요.
부분부분 손을 대봤는데 하다보니 전체를 건드리게 되었네요.
무엇보다 "상자"라는 말이 이 문제를 푸는 데 가장 방해가 되지 않나 싶습니다.

![screenshot_2016-05-15-17-40-00](https://cloud.githubusercontent.com/assets/19270364/15424006/3a941186-1ebb-11e6-9453-2aa421d3bd85.png)

한 웨이터가 한숨을 내쉬며
뒷머리를 긁으면서 말했다.

"유리잔을 옮길 때 같은 상자를 쓰거든요. 
근데 이 유리잔 중 한 가지는 옮기기 정말 싫어요."

아래의 유리잔 네 개 중 
웨이터가 말하는 유리잔은 어떤 것일까?

유리잔의 무게는 종류에 상관없이 똑같다고 한다.

->

한 웨이터가 한숨을 내쉬더니
뒤통수를 긁으면서 말했다.

"유리잔을 옮길 때 같은 바구니를 쓰거든요.
근데 이 유리잔만큼은 정말 옮기기 싫어요."

아래 네 개의 유리잔 중
웨이터가 말하는 유리잔은 무엇일까?

유리잔의 무게는 모두 같다.

![screenshot_2016-05-15-17-40-18](https://cloud.githubusercontent.com/assets/19270364/15424153/08d9db20-1ebc-11e6-837a-bec8762d025c.png)

웨이터가
"이 유리잔 중 한 가지는 옮기기 정말 싫어요"
라고 한 것을 다시 한 번 떠올려 보자.

옮길 때 가장 힘든것이 무엇일까?

->

웨이터가
"이 유리잔만큼은 정말 옮기기 싫어요."
라고 한 말을 다시 한 번 떠올려 보자.

유리잔을 옮길 때 어떤 점이 가장 힘들까?

![screenshot_2016-05-15-17-40-21](https://cloud.githubusercontent.com/assets/19270364/15424246/8ff4a644-1ebc-11e6-9578-ffeb80293f26.png)

웨이터는 이 유리잔을
무게 때문에 싫어하는 것이다.

->

웨이터가 이 유리잔을 싫어하는 까닭은 이 유리잔이 무겁기 때문이다.

![screenshot_2016-05-15-17-40-25](https://cloud.githubusercontent.com/assets/19270364/15424316/e979a5e8-1ebc-11e6-954e-b3fbad82d78d.png)

상자에 유리잔이 많으면 많을 수록
무게도 점점 더해질 것이다.
웨이터가 싫어하는 유리잔은
상자안에 한개라도 더 넣을 수 있는
유리잔이다.

->

바구니에 유리잔을 많이 담을 수록
무게도 늘어난다.
웨이터가 싫어하는 유리잔은
바구니에 한 개라도 더 담을 수 있는
유리잔이다.

![screenshot_2016-05-15-17-40-28](https://cloud.githubusercontent.com/assets/19270364/15424619/a5daa3e4-1ebe-11e6-832a-40dce6e4f969.png)

만약 유리잔이 겹칠 수 있는 유리잔이라면
같은 크기의 상자라도 훨씬 더 많이 넣을 수 
있지 않을까?

->

만약 유리잔을 포개어 담을 수 있다면,
같은 크기의 바구니라도 훨씬 더 많이
담을 수 있지 않을까?

![screenshot_2016-05-15-17-41-09](https://cloud.githubusercontent.com/assets/19270364/15424400/6591f680-1ebd-11e6-9afa-38841c4ce338.png)

정답!

웨이터가 말하는 유리잔은 B 유리잔이다.
옮길 때 겹칠 수 있는 유리잔은 B 밖에 없다.
그리고 겹치면 겹칠 수록 무게는 무거워지니
옮기기 제일 힘든건 유리잔 B이다.

->

웨이터가 말하는 유리잔은 B이다.
유리잔을 옮길 때 서로 포개어 담는다면 
무게가 늘어나 힘들 것이다.
서로 포개어 담을 수 있는 유리잔은 B 뿐이다.

**Comment by kaleidoscope531** [comment]
웨이터가 이 유리잔을 싫어하는 까닭은 이 유리잔이 무겁기 때문이다.
이 부분은 유리잔의 각각의 무게는 모두 같기 때문에 의미를 잘못 전달할 우려가 있어보입니다.
이 유리잔이 무겁기 때문이다 를
옮길 때 무겁기 때문이다 로 바꾸는 것이 좋지 않을까요?

**Comment by Y00N** [comment]
웨이터가 이 유리잔을 싫어하는 까닭은 이 유리잔을 옮길 때 무거워서 힘들기 때문이다. 이런 식으로요?

**Comment by jungin019** [comment]
모두 고쳤습니다. 힌트 2 때문에 열어두겠습니다.

**Comment by kaleidoscope531** [comment]
'이 유리잔을 옮길 때 무거워서 힘들기 때문이다'
훨씬 좋은 것 같습니다.

**Comment by kaleidoscope531** [comment]
다만 '힘들기'는 빼도 되지 않을까요?

**Comment by Y00N** [comment]
그것도 좋습니다 :)

**Comment by jungin019** [comment]
'웨이터가 이 유리잔을 싫어하는 까닭은 옮길 때 무겁기 때문이다'로 수정
