### ISSUE TITLE
닫은 이슈지만 말씀드려 봅니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#478]
https://github.com/elfinlazz/lt3translation/issues/172

이 곳에 닥친 비극에서 런던을 자유롭게 하기 위하여 교수님의 도움이 꼭 필요합니다.

로 채택했는데 말입니다

"이곳"과 "런던"은 같다고 봅니다.

그렇다면 "런던에 닥친 비극에서 런던을 자유롭게 하기 위하여" 라는 다소 이상한 문장이 나오는데요

이 비극에서 런던을 구해 내기 위하여 ~
런던을 이 비극에서 구해 내기 위하여 ~

라는 쪽은 이상할까요?

**Comment by kaleidoscope531** [comment]
런던을 이 비극에서 구해 내기 위하여 ~ 가 수정한 사항보다 더 좋습니다.

**Comment by STRIKE-F** [comment]
런던을 이 비극에서 구해 내기 위하여~ 로 수정하겠습니다. 다만 더빙이 좀 걱정이네요..
