### ISSUE TITLE
[조사 메모] 그린 병원으로

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#488]
![screenshot_2016-05-18-11-16-26](https://cloud.githubusercontent.com/assets/19270364/15432866/ea90701e-1eea-11e6-836d-67ffc2bf659e.png)

지하철이 그린 방법으로 가는 유일한 방법인 것 같다.
~~(중략)~~
그곳에서 우리는 지하철을 이용해서 병원으로 갈 수 있을 것이다.

"~것 같다."나 "~수 있다"라는 표현을 다듬어 보았습니다.

그린 병원으로 가는 유일한 방법은 지하철이다.(or 지하철로 보인다)
~~(중략)~~
거기서 우리는 지하철을 타고 그린 병원으로 갈 것이다.

어떤가요?

**Comment by kaleidoscope531** [comment]
좋습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
