### ISSUE TITLE
[조사 메모] 카지노 세븐을 향해

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#489]
![screenshot_2016-05-18-11-16-48](https://cloud.githubusercontent.com/assets/19270364/15433147/016b4f42-1eec-11e6-86dc-e9998e455028.png)

미래의 루크가 나의 차에 남긴 편지는 카지노 7 이라고 불리는 카지노로 가라고 했다.
~(중략)~
우리들은 주민들에게 물어보기 위해 플랫스톤 가로 다시 돌아가기로 결정했다.
... 낡아버린 내 차를 보고 받은 충격을 극복한 후 얼마 지나지 않아서의 일이다.

-> 

미래의 루크는 나의 차에 카지노 7이라는 카지노로 가라는 편지를 남겼다.
~(중략)~
우리는 플랫스톤 가로 돌아가 주민들에게 물어보기로 결정했다.
...고물이 되어버린 내 차를 보며 받은 충격을 극복한 지 얼마 지나지 않은 때였다.

자연스럽지 않은 문장을 교정해 봤는데 어떨까요?

**Comment by jungin019** [comment]
'카지노 세븐이라는 곳으로 가라는 편지를 남겼다.'는 어떨까요?

**Comment by Y00N** [comment]
@jungin019 카지노 세븐과 카지노 7을 통일해달라는 말씀은 https://github.com/elfinlazz/lt3translation/issues/484에 남겨두긴 했습니다.
저도 카지노 세븐이 더 좋습니다.

**Comment by jungin019** [comment]
아 제 말은 카지노 세븐 전에 카지노가 문장 안에서 반복이 되어서
'미래의 루크는 나의 차에 카지노 세븐이라는 카지노로 가라는 편지를 남겼다.' 보다는 
'미래의 루크는 나의 차에 카지노 세븐이라는 곳으로 가라는 편지를 남겼다.'가 어떨까 해서 
말씀드렸어요.

**Comment by Y00N** [comment]
@jungin019 아, 제가 멍청이였군요. 훨씬 좋습니다.

**Comment by jungin019** [comment]
ㅎㅎㅎ 아니에요 수정했습니다.
