### ISSUE TITLE
[챕터2] 건의사항

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#498]
![screenshot_2016-05-18-11-22-16](https://cloud.githubusercontent.com/assets/19270364/15436212/a61cffae-1efb-11e6-8010-2788854c1507.png)

여기 짓는 데에 얼마나 들었을지 상상이 안 돼요!

여기 짓는 데에 돈이 얼마나 들었을지 상상이 안 돼요!
여기 있는 데에 얼마가 들었을지 상상이 안 돼요!

라는 식으로 바꾸어 써야 합니다.

슬슬 여기가 챕터 2인지 3인지 기억이 안나네요.

**Comment by jungin019** [comment]
여기 짓는 데에 돈이 얼마나 들었을지 상상이 안 돼요! 가 좋겠네요.
아 그리고 챕터 정확하지 않아도 됩니다^^

**Comment by STRIKE-F** [comment]
여기 짓는 데에 돈이 얼마나 들었을지 상상이 안 돼요! 로 수정했습니다.
