### ISSUE TITLE
작중 Thames 음차표기

### ISSUE THREAD

**Issue by Latteria** [elfinlazz/lt3translation#522]
Thames가 현재 작중 번역이 대부분 "템즈"로 표기돼 있습니다.
이걸 외래어 표기법상으로 고치면 "템스"로 바뀌는데
이를 바꿀지 말지 건의

+ 더빙 실정으로는 템즈가 편합니다만

**Comment by jungin019** [comment]
이거 그 때 템스로 통일하기로 했었던 걸로 기억해요 
표기법에 따르기로...

**Comment by kaleidoscope531** [comment]
템스라 쓰고 템즈라 읽으면 안됩니까? 
우리나라에서도 예전엔 한 때 자장면이라 쓰고 아나운서 빼고는 전부 짜장면이라 읽던 역사가 있잖아요 ㅎ

**Comment by Latteria** [comment]
kaleidoscope531 님  의견을 따르겠습니다.
