### ISSUE TITLE
모든걸, 올려주더라고

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#539]
![screenshot_2016-06-01-23-30-49](https://cloud.githubusercontent.com/assets/19295794/15803470/f41fd558-2b19-11e6-91ef-9cff88d18a01.png)

모든걸 -> 모든 걸
로 수정하면 좋을 것 같습니다 :)

그리고 '올려주더라고'가 맞는 표현인가요? 아니면 '올려 주더라고'가 맞나요?

**Comment by jungin019** [comment]
올려 주더라고 가 맞는 것 같네요
