### ISSUE TITLE
잆는

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#542]
![screenshot_2016-05-29-23-08-38](https://cloud.githubusercontent.com/assets/19295794/15805264/d83dcd68-2b5f-11e6-97ea-4f5e55234ed5.png)

잆는 -> 없는 으로 수정하는 것은 어떨까요?

**Comment by jungin019** [comment]
아 이 부분은 의도된 오타입니다. 이슈는 열어놓겠습니다

**Comment by kaleidoscope531** [comment]
무슨 의도인가요? 원문이 뭐길래요?

**Comment by vbn2523** [comment]
게임 플레이하는 입장에서는 의도된 것인지 모르지 않을까요?

**Comment by jungin019** [comment]
아 이 부분은 팀 내에서 혼선이 있었던 것 같네요 없는 으로 고쳐놓겠습니다

**Comment by kaleidoscope531** [comment]
의도가 아니라면
수수께끼 159 지나갈 수 잆는 문 2
수수께끼 167 지나갈 수 잆는 문 3
도 고쳐야 할 것 같습니다.

**Comment by jungin019** [comment]
네 모두 고쳤습니다
