### ISSUE TITLE
허셜

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#551]
![screenshot_2016-05-31-18-36-26](https://cloud.githubusercontent.com/assets/19295794/15805333/bc3f8866-2b61-11e6-9919-0decb1ea3b80.png)

레이튼이 말하고 있는 인물? 허셜이 아니겠지요?

**Comment by jungin019** [comment]
네... 디미트리네요
'제 생각엔 루크를 칭찬해주기는 좀 이른 것 같군요, 디미트리.'로 수정했습니다
