### ISSUE TITLE
큰 형님 / 큰형님

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#554]
![screenshot_2016-05-27-00-37-20](https://cloud.githubusercontent.com/assets/19295794/15805350/633c3182-2b62-11e6-9933-1eaeed3db0dd.png)

큰 형님 / 큰형님 하나로 통일하면 좋겠습니다.

**Comment by jungin019** [comment]
이거 뭘로 통일하기로 했는지 기억이 안 나서 열어두겠습니다.

**Comment by STRIKE-F** [comment]
일단은 큰형님을 고유명사로 보는 게 맞는 거 같아요. 물론 형님(보스트로)가 큰 건 맞지만, 그런 의미는 아닐 테니까요...

**Comment by vbn2523** [comment]
음, 그럴 수도 있겠지만 보는 사람 입장에서는
고유명사가 아니라 그냥 오타라고 볼 수도 있을 것 같아요.

**Comment by kaleidoscope531** [comment]
큰형님 이어도 상관 없을듯합니다. 큰아버지 큰할아버지와 같은 맥락 아닌가요?

**Comment by Y00N** [comment]
큰형님 동의합니다.

**Comment by Porowl** [comment]
모두 바꿨습니다.
