### ISSUE TITLE
대화 중 괄호

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#559]
![screenshot_2016-05-24-13-14-22](https://cloud.githubusercontent.com/assets/19295794/15805384/5dafefc8-2b63-11e6-962d-a88f95d2cebe.png)

괄호 부분을 좀 더 자연스럽게 수정할 수 없을까요?

**Comment by jungin019** [comment]
'내가 정말 스타일리시한 신사기는 하지. 어떤 사람은 내가 이 도시에서 가장 
옷을 잘 차려입는다고도 하더군.'로 고쳤습니다
