### ISSUE TITLE
그건 다음으로 미뤄야 할 것 같아.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#564]
![screenshot_2016-05-20-17-51-59](https://cloud.githubusercontent.com/assets/19270364/15825374/69207f2c-2c3e-11e6-801b-05657da38e80.png)

그건 다음으로 미루자. 
~같아 라는 표현을 바꾸는 게 좋다고 생각합니다.

**Comment by Porowl** [comment]
그건 다음으로 미루자.

**Comment by STRIKE-F** [comment]
그건 다음으로 미뤄야겠는데.

**Comment by kaleidoscope531** [comment]
그건 다음으로 미루자. 좋습니다.

**Comment by jungin019** [comment]
그건 다음으로 미루자. 로 수정
