### ISSUE TITLE
하지만 돌아갈 수 있는 유일한 방법은 시계 가게에 있는 웜홀을 사용하는 것 뿐이에요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#566]
![screenshot_2016-05-20-17-51-03](https://cloud.githubusercontent.com/assets/19270364/15825964/abb10cf6-2c40-11e6-8340-80c432df9142.png)

하지만 돌아갈 유일한 방법은 시계 가게의 웜홀 뿐이에요.
라고 줄이는 게 어떤가요?

**Comment by Porowl** [comment]
하지만 돌아갈 유일한 '수단'은 시계 가게의 웜홀 뿐이에요.

**Comment by Y00N** [comment]
수단이란 단어의 뉘앙스가 더 좋아 보이기도 하네요 :)

**Comment by STRIKE-F** [comment]
Sudan

수단으로 수정하겠습니다.
