### ISSUE TITLE
여기서는 아무도 엿듣지 못할 것 같습니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#569]
![screenshot_2016-05-20-17-50-30](https://cloud.githubusercontent.com/assets/19270364/15826574/095bc204-2c43-11e6-998b-22f8158de32d.png)

여기서는 아무도 엿듣지 못할 겁니다.
여기서는 아무도 엿듣지 못하겠지요.

~것 표현을 바꾸는 게 더 자연스럽지 않을까요

**Comment by Porowl** [comment]
말투고려 '못할 겁니다'가 나은듯..

**Comment by STRIKE-F** [comment]
못하겠죠는 어떤가요

**Comment by Y00N** [comment]
저는 못하겠죠가 더 좋네요 :)

**Comment by kaleidoscope531** [comment]
못하겠죠 좋습니다.

**Comment by jungin019** [comment]
못하겠죠 로 수정
