### ISSUE TITLE
원래의 시간으로 돌아갈 방법이 있지만, 숲으로 가서 자세한 이야기를 하도록 하죠.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#570]
![screenshot_2016-05-20-17-49-44](https://cloud.githubusercontent.com/assets/19270364/15826715/98b1f7de-2c43-11e6-9356-32e0046f9b56.png)

~(전략), 숲으로 가서 자세한 이야기를 하죠.
로 줄이는 게 어떨까요?

**Comment by jungin019** [comment]
아니면 '자세한 이야기는 숲으로 가서 하죠.'는 어떨까요?

**Comment by STRIKE-F** [comment]
자세한 이야기는 좀 더 깊은 곳에ㅅ...

자세한 이야기는 숲에 들어가서 하죠 는 어떤가요

**Comment by Y00N** [comment]
저는 정인님 의견이 더 좋습니다.

**Comment by Porowl** [comment]
원래의 시간으로 돌아갈 방법이 있지만, 
자세한 이야기는 숲으로 가서 하죠.
