### ISSUE TITLE
서쪽에 숲이 우거진 곳으로 가는 게 어떨까요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#571]
![screenshot_2016-05-20-17-49-30](https://cloud.githubusercontent.com/assets/19270364/15827125/3ba9187c-2c45-11e6-99c4-65fa7cac358f.png)

숲이라는 건 나무가 울창한 장소를 지칭하는 거니까요 굳이 숲이 우거진 '곳'이라고 할 필요는 없다고 생각합니다.
-> 서쪽에 우거진(울창한) 숲으로 가는 게 어떨까요?    는 어떨까요?
그런데 또 그 숲이 우거진 곳이라는 것도 '그늘진 숲'을 지칭하는 것이기에
서쪽에 그늘진 숲으로 가는 게 어떨까요? 라고 아예 바꾸는 것도 괜찮지 않나 싶습니다.

**Comment by kaleidoscope531** [comment]
서쪽에 그늘진 숲으로 가는 게 어떨까요? 
좋습니다.

**Comment by Porowl** [comment]
서쪽에 그늘진 숲으로 가는 게 
어떨까요?
