### ISSUE TITLE
제 짧은 설명이 선생님을 이해시키기엔 충분하지 않을 거란 건 어렴풋이 느끼고 있었어요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#572]
![screenshot_2016-05-19-23-31-19](https://cloud.githubusercontent.com/assets/19270364/15881974/a1cb25ba-2d75-11e6-8c83-a8f69c106da1.png)

설명이 이해시시키기엔 충분하지 않을 거란 건 어렴풋이 느낀다는 말이 조금 자연스럽지 않다고 생각이 들어서요...

→ 선생님께서 이해하시기엔 제 설명이 부족할 거라고 생각하긴 했었어요.

라는 쪽이 좀 더 자연스럽지 않을까요?

**Comment by jungin019** [comment]
저도 '선생님께서 이해하시기엔 제 설명이 부족할 거라고 생각하긴 했었어요.'가 더 좋군요

**Comment by STRIKE-F** [comment]
좋네요. 이대로 수정하겠습니다.
