### ISSUE TITLE
디미트리 앨런 / 엘런 / 알렌

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#573]
![screenshot_2016-06-08-13-19-32](https://cloud.githubusercontent.com/assets/19295794/15895435/4208e26a-2dc6-11e6-9067-4b52846ddeba.png)
![screenshot_2016-06-08-13-19-29](https://cloud.githubusercontent.com/assets/19295794/15895452/5cabe16c-2dc6-11e6-8750-cb5ab0f73326.png)

플레이 중 다양하게 사용되네요.
하나로 통일하는 것도 좋지 않을까요?

**Comment by jungin019** [comment]
디미트리 알렌으로 통일인데 혼선이 있었나 보군요... 수정하겠습니다
