### ISSUE TITLE
스케일의 

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#579]
![screenshot_2016-06-08-13-13-36](https://cloud.githubusercontent.com/assets/19295794/15988480/7ba09300-308d-11e6-9c04-69497f7858e1.png)

'스케일' 말고 다른 단어를 사용할 수는 없을까요?

예를 들면 '규모' 라던가...

**Comment by STRIKE-F** [comment]
그렇네요. 규모로 수정하겠습니다.
외래어 굳이 쓸 필요는 없으니 ㅋㅋ;;
