### ISSUE TITLE
모양이다 X 2 / 아내되시는 

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#580]
![screenshot_2016-06-08-13-00-21](https://cloud.githubusercontent.com/assets/19295794/15988536/c9fd28b8-308f-11e6-881b-42f603d5b484.png)

'모양이다' 가 두 번 들어가면 조금 어색하지 않을까요? 
둘 중 하나는 다른 표현으로 바꿔도 좋을 것 같아요.

그리고 아내되시는 -> 아내 되시는 으로 수정하면 좋을 것 같습니다 :)

**Comment by jungin019** [comment]
아내 되시는 은 수정했습니다

**Comment by STRIKE-F** [comment]
않을 듯하다로 바꾸면 좀 더 나을까요?

**Comment by kaleidoscope531** [comment]
그러면 될 듯 합니다.

**Comment by jungin019** [comment]
않을 듯하다로 고쳤습니다.
