### ISSUE TITLE
아직도 모르겠어도

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#582]
![screenshot_2016-06-08-18-52-52](https://cloud.githubusercontent.com/assets/19295794/15988568/b0d8c436-3090-11e6-8c01-6f45a8729695.png)

'아직도 모르겠어도'라는 표현, 제가 보기에는 조금 부자연스러운 것 같은데 수정할 수 없을까요?

제 생각에는 '아직 답을 찾지 못했어도', '아직 감을 잡지 못했어도', '아직 감이 오지 않아도'
등으로 바꿀 수 있을 것 같아요.

**Comment by STRIKE-F** [comment]
전 아직 감이 오지 않아도가 괜찮아 보입니다.

**Comment by kaleidoscope531** [comment]
아직 감이 오지 않아도
좋습니다.

**Comment by jungin019** [comment]
아직 감이 오지 않아도 로 수정
