### ISSUE TITLE
탈출하는동안 / 폭발하는것을 / 10분동안의 / 입었지만

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#588]
![screenshot_2016-06-08-12-56-48](https://cloud.githubusercontent.com/assets/19295794/15988989/25584cea-30a1-11e6-8225-26d5f1b29397.png)

탈출하는동안 -> 탈출하는 동안

폭발하는것을 -> 폭발하는 것을

10분동안의 -> 10분 동안의 로 수정하면 좋겠습니다.

그리고 '10분 동안의 광기는 그렇게 끝이 났고, 꽤 많은 피해를 입었지만 런던에 평화가 찾아왔다' 라는 문장에서,

'입었지만' 이라는 부분이 부자연스럽다고 생각합니다.

제 개인적인 의견일 뿐이지만,

'입었지만' 이라는 표현의 표현의 주어를 '10분 동안의 광기'로 보고

'10분 동안의 광기'가 꽤 많은 피해를 입혔다 라는 쪽으로 수정하는 것이 좋지 않을까요?

ex) 많은 피해를 입힌 10분 동안의 광기는 그렇게 끝이 났고, 마침내 런던에는 평화가 찾아왔다

**Comment by jungin019** [comment]
맞춤법은 모두 수정했습니다

**Comment by vbn2523** [comment]
감사합니다. 

많은 피해를 '불러온' 10분 동안의 광기는 끝이 났고, 마침내 런던에는 평화가 찾아왔다.

도 좋다고 생각합니다.

**Comment by STRIKE-F** [comment]
저렇게 바꾸는 거 괜찮아 보입니다. 다른 분들 의견도 들어 보죠.

**Comment by kaleidoscope531** [comment]
좋습니다.
그런데 '불러온' -> '야기한' 은 어떨지요

**Comment by Y00N** [comment]
낳은...?

**Comment by vbn2523** [comment]
낳은 도 좋네요. 야기한은 조금 이상한 것 같고 초래한도 꽤 좋다고 생각합니다.

**Comment by Porowl** [comment]
전력을 역류시키자 요새는 스스로
무너지기 시작했다. 운이 좋게도,
우리는 돈 파올로가 개조한 내 차를
타고 날아서 탈출할 수 있었다.
탈출하는 동안 우리는 기동요새가
다시 구멍으로 떨어지는 것과
폭발하는 것을 보았다.
많은 피해를 초래한 
10분 동안의 광기는 끝이 났고, 
마침내 런던에는 평화가 찾아왔다.
