### ISSUE TITLE
템즈 카페 / 들어나고 / 말햇다 / 모든것이 / 들어날

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#594]
![screenshot_2016-06-08-13-11-24](https://cloud.githubusercontent.com/assets/19295794/15989030/60f86698-30a3-11e6-9c00-b1880a3e2d43.png)

다른 이슈에서 이미 한 번 말씀드렸듯, '템즈 카페'를 '템스 카페' 라고 수정해야 하지 않을까요?

또한 들어나고 -> 드러나고, 말햇다 -> 말했다, -> 모든것이 -> 모든 것이, 들어날 -> 드러날

로 수정하면 좋을 것 같습니다.

**Comment by jungin019** [comment]
템즈 카페는 템스를 템즈로 수정하면서 모두 바꿨습니다.

**Comment by vbn2523** [comment]
그럼 템즈로 통일하는 것인가요?

**Comment by jungin019** [comment]
네 템즈로 통일입니다
