### ISSUE TITLE
템즈 카페 / 체르미경관님

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#595]
![screenshot_2016-06-08-13-13-28](https://cloud.githubusercontent.com/assets/19295794/15989047/1a0a5420-30a4-11e6-8719-c3dd317a98ca.png)

템즈 카페 -> 템스 카페로 수정하고,

체르미경관님 -> 체르미 경감 이라고 수정하는 것이 좋지 않을까요?

작중에서도 '경감'이라는 표현을 사용하고 있고,

악마의 상자를 참고하면 루크와 레이튼의 대화에서도

'경감'이라고 표현하지 '경감님'이라고 표현하지는 않았던 것 같습니다.

**Comment by jungin019** [comment]
경감으로는 모두 고쳤는데 경감님도 경감으로 고쳐야할지는 잘 모르겠군요

**Comment by vbn2523** [comment]
제 기억이 맞다면, 악마의 상자에서 루크가
'체르미 경감 치고는 꽤 정확하게 짚었네요'
라는 표현을 사용한 것으로 알고 있습니다.

**Comment by STRIKE-F** [comment]
그런데 경감이라고만 하면 높임법 상 어긋나지 않을까요?

**Comment by Y00N** [comment]
악마의 상자에서 체르미 경감이라고 했는진 몰라도 본 작 내에서는 아마 경감님이라고 하지 않던가요?

**Comment by vbn2523** [comment]
음, 그래도 정발판에서 이미 사용한 표현과 다르다는 건 마음에 좀 걸리는데요...

**Comment by Y00N** [comment]
![screenshot_2016-06-12-21-57-37](https://cloud.githubusercontent.com/assets/19270364/16356226/39f863a4-3b0c-11e6-88bc-57028c0cbb80.png)
![screenshot_2016-06-12-21-57-50](https://cloud.githubusercontent.com/assets/19270364/16356227/3ae0a5b0-3b0c-11e6-8125-d1cc4dec4875.png)

그러면 싹 다 바꾸자는 의견이신가요?

**Comment by vbn2523** [comment]
네, 악마의 상자 정발판을 확인해 보면

**Comment by vbn2523** [comment]
![1](https://cloud.githubusercontent.com/assets/19295794/16361068/c2fb16be-3bbc-11e6-8b75-43497564e29b.png)
![3](https://cloud.githubusercontent.com/assets/19295794/16361070/c98c20a4-3bbc-11e6-9cc8-6520babf3f92.png)

**Comment by vbn2523** [comment]
이러한 표현들을 사용하고 있습니다.

**Comment by STRIKE-F** [comment]
이 이슈는 일단 님을 붙이는 거로 종결하겠습니다
