### ISSUE TITLE
마음 한켠으론 ~ 인정해야겠다

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#604]
![screenshot_2016-06-08-13-05-28](https://cloud.githubusercontent.com/assets/19295794/15989134/f94ce780-30a7-11e6-8d1b-db1b07bc0941.png)

'마음 한켠으론 어려운 문제들에서는 내가 좀 더 적극적인 역할을 하고 싶다는 것은 인정해야겠다'

조금 더 자연스럽게 수정할 수는 없을까요?

그리고 레이튼 시리즈에서는 '문제'라는 표현보다는 '수수께끼'라는 표현을 많이 쓰지요.

아예 어떤 내용을 표현하려고 했던 건지 이해할 수가 없어서 저도 표현을 바꿔보기가 어렵네요 ㅠㅠ

**Comment by STRIKE-F** [comment]
번역체가 너무 많이 보여서 이 문장은 전체적으로 뜯어고치긴 해야겠네요...

당장 떠오르는 대로 쓰자면 
"육각거탑 내부는 정말 복잡하다. 이 정도라면 모자파 활동에 지장이 있지 않을까 싶지만 저쪽에선 별로 신경 쓰지 않나 보다. 지금까진 나 없이도 우리 앞을 가로막는 수수께끼들을 멋지게 풀어 냈지만, 한편으론 나도 어려운 문제에 좀 더 적극적으로 나서고 싶긴 하다.

**Comment by kaleidoscope531** [comment]
"육각거탑 내부는 정말 복잡하다. 이 정도라면 모자파 활동에 지장이 있지 않을까 싶지만 저쪽에선 별로 신경 쓰지 않나 보다. 지금까진 나 없이도 우리 앞을 가로막는 수수께끼들을 멋지게 풀어 냈지만, 한편으론 나도 어려운 문제에 좀 더 적극적으로 나서고 싶긴 하다."
좋습니다. 

그런데 마지막 '싶긴 하다' -> '싶어진다' 로 바꾸는 것은 어떨까요?

**Comment by Y00N** [comment]
읽기 편하게 문장을 좀 더 쪼개는 게 어떨까요?
육각거탑 내부는 정말 복잡하다. 이 정도라면 모자파 활동에 지장이 있지 않을까 싶다. 그러나 저쪽에선 별로 신경 쓰지 않나 보다. 지금까진 나 없이도 우리 앞을 가로막는 수수께끼들을 멋지게 풀어 냈다.
이젠 나도 어려운 문제에 좀 더 적극적으로 나서고 싶다.

**Comment by STRIKE-F** [comment]
원문이 쉼표로 연결된 문장인데 굳이 뗄 필요는 없지 않을까요?

**Comment by STRIKE-F** [comment]
육각거탑 내부는 정말 복잡하다. 이 정도라면 모자파 활동에 지장이 있을 법한데 저쪽에선 별로 신경 쓰지 않나 보다. 지금까진 나 없이도 우리 앞을 가로막는 수수께끼들을 멋지게 풀어 냈지만, 어려운 문제에는 나도 좀 더 적극적으로 나서고 싶다.

일단 이렇게 수정할게요.
