### ISSUE TITLE
조사메모 내 괄호 / 돈 폴

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#607]
![screenshot_2016-06-08-13-06-26](https://cloud.githubusercontent.com/assets/19295794/15989263/456071fa-30ad-11e6-92d7-c5350c8f7f6a.png)

인물들 간의 대화가 아니라 조사메모 내 괄호이니 아무래도 상관은 없겠지만,
조금 더 자연스럽게 수정은 안 될까요?
폴이라는 이름을 사용하시는지 아닌지 잘 모르겠어요.
영원의 가희에서는 루크가 '돈폴'이라는 표현을 사용했던 것으로 압니다.

**Comment by jungin019** [comment]
괄호는 확실히 수정해야하긴 합니다...ㅠ 
폴의 경우는 원문에서도 폴이라고 나오고 레이튼이 돈 파올로와 과거에 친분이 있었다는 걸 
보여줘서 폴을 사용하는 게 좋을 것 같네요. 다른 부분에서도 레이튼이 돈 파올로를 폴이라고 
부르는 대목이 있고요.

**Comment by kaleidoscope531** [comment]
그냥 (돈 파올로)
(돈 파올로의 별칭) 
으로 하면 되지 않을까요?

**Comment by Y00N** [comment]
저 문장 그대로를 사용한다면 괄호가 아니라 쉼표나 줄표를 사용하는 게 더 적절합니다.
폴은, 그러니까 돈 파올로 말이다, 내가 사라진 동안 홀로 조사를 하고 있었다.
폴은 ─ 그러니까 돈 파올로 말이다 ─ 내가 사라진 동안 홀로 조사를 하고 있었다.

**Comment by STRIKE-F** [comment]
폴은, 그러니까 돈 파올로는, 내가 사라진 동안 홀로 조사를 하고 있었다.

이렇게 고칠게요.
