### ISSUE TITLE
템즈 강 / 뭣 때문에 / 돌아가겠지만

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#608]
![screenshot_2016-06-08-13-08-11](https://cloud.githubusercontent.com/assets/19295794/15989275/bf4b91d4-30ad-11e6-9aa5-40c3f0f24be4.png)

템즈 강 -> 템스 강

뭣 때문에 -> 뭐 때문에 로 수정하면 좋을 것 같습니다.

그리고, '조만간'이라는 표현이 있는데 '돌아가겠지만' 이라는 표현보다는

'돌아가야겠지만' 이라는 표현이 더 자연스럽지 않나 생각합니다.

**Comment by jungin019** [comment]
맞춤법은 수정.

**Comment by STRIKE-F** [comment]
돌아가야겠지만으로 수정했습니다.
