### ISSUE TITLE
세갈 / 템즈 강 / 생각이들었다

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#609]
![screenshot_2016-06-08-13-10-27](https://cloud.githubusercontent.com/assets/19295794/15989287/390fbb30-30ae-11e6-9c95-60bdf964fb0d.png)

템즈 강 -> 템스 강, 생각이들었다 -> 생각이 들었다 로 수정하면 좋을 것 같습니다.

그리고 세갈과 시걸이 다른 인물이였나요? 헷갈리네요...

**Comment by jungin019** [comment]
아 세갈과 시걸을 동일 이름이 맞습니다. 이름을 정할 때 시걸로 하기로 했는데 혼선이 좀 있었나 보네요

**Comment by kaleidoscope531** [comment]
세갈은 전체 스크립트 놓고 모두바꾸기를 할 수 있다면 그렇게 해야 할 듯 합니다. 
스크립트에서 시걸이라고 언급된 걸 본 적이 없습니다.

**Comment by jungin019** [comment]
네 그래서 스크립트 쪽은 다 시걸로 바꾸었습니다. 이슈는 닫을게용
