### ISSUE TITLE
늙으신 나이에도

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#610]
![screenshot_2016-06-08-13-27-06](https://cloud.githubusercontent.com/assets/19295794/15989369/b40965ec-30af-11e6-97c4-461fef7d7690.png)

'늙으신 나이에도' 라는 표현은 조금 이상하지 않을까요?

조금 더 자연스럽게 바꿀 수 있으면 좋겠어요.

ex) 나이가 드셔서도

**Comment by STRIKE-F** [comment]
그만한 나이에도는 어떨까요?

**Comment by Y00N** [comment]
이상한가요? 하지만 멋을 내신다는데 나이가 많으시다는 이유로 나쁜 말을 할 수는 없던걸요.
라는 식으로 문장을 틀어버린다면 어떨까요?

**Comment by STRIKE-F** [comment]
문장이 (자기도 공감하며) 이상하죠? 라고 하는 거라 이상한가요? 는 좀 맞지 않아요.

이상하죠? 그래도 그 나이라고 멋쟁이가 되지 말란 법은 없잖아요? 
는 어떨까요. 뜻만 맞게 많이 고쳐 봤습니다.

**Comment by Porowl** [comment]
나이가 무슨 상관이냐며

**Comment by STRIKE-F** [comment]
이상하죠? 그래도 나이가 들었다고 멋 부리는 걸 뭐라 할 순 없잖아요.
일단은 이렇게 수정하겠습니다.
