### ISSUE TITLE
닯은 / 체르미 ~ 하다 / 닮은 ~ 보아하니 

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#613]
![screenshot_2016-06-08-13-07-48](https://cloud.githubusercontent.com/assets/19295794/15989430/3b0559c4-30b1-11e6-865a-dbe472746bac.png)

제목에서 닯은 -> 닮은 으로 수정하면 좋겠습니다.

'체르미 경감도 또한 그녀가 클레어와 빼닮은 것에 대해 확신을 가진 듯 하다.' 라는 표현을 조금 더 자연스럽게

수정할 수는 없을까요?

ex) 체르미 경감 또한 스텔라와 클레어가 닮았다고 생각하는 것 같다.

또한 '닮은 꼴을 보아하니' 라는 표현에서

레이튼이 사랑하는 클레어와 그녀의 동생 스텔라에게

'꼴'이라는 단어를 사용했을 것 같지는 않습니다.

'모습' 같은 표현은 어떨까요?

**Comment by jungin019** [comment]
원문을 보니 'Inspector Chelmey also seems convinced that he's seen the woman who resembles Claire.'네요. 체르미 경감도 클레어를 닮은 여자를 봤다는 걸 인정하는 눈치였다. 정도가 좋지 않을지...

**Comment by vbn2523** [comment]
음 원문이 그렇다면
'체르미 경감도 그녀가 클레어와 닮았다는 것을 인정하는 것 같다.'는 어떤가요?

**Comment by STRIKE-F** [comment]
저 문장 좋아 보입니다.

**Comment by Y00N** [comment]
~같다는 작품 내에서 온종일 쓰이고 있으니 
체르미 경감도 클레어를 닮은 여자를 봤다는 걸 인정하는 눈치였다. 정도가 좋지 않을지...
이쪽이 더 좋습니다

**Comment by vbn2523** [comment]
아, ~같다 라는 표현이 많이 쓰이고 있는 건 인정합니다.
그렇다 해도, 인정하는 눈치였다를 대체할 말한 다른 표현은 없을까요?

**Comment by STRIKE-F** [comment]
체르미 경감도 그녀가 클레어와 닮았다고 인정하는 눈치였다. 로 수정하겠습니다.
