### ISSUE TITLE
힌트 3이 ~ 알려줬다 / 한칸씩

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#616]
![screenshot_2016-06-08-19-00-59](https://cloud.githubusercontent.com/assets/19295794/15991782/188bad0c-30f8-11e6-9a4d-d4881bc13425.png)

'힌트 3이 알아야 하는 정보를 모두 알려줬다.' 라는 문장은 중의적 표현이 될 수 있잖아요?

표현하려는 의미를 좀 더 명확하게, 중의적이지 않은 표현으로 바꿀 수 없을까요?

ex) 알아야 할 정보를 힌트 3에서 모두 알려주었다.

그리고 한칸씩 -> 한 칸씩 으로 수정하는 건 어떨까요?

**Comment by jungin019** [comment]
'필요한 정보는 힌트 3에서 모두 알려줬다.' 정도는 어떨까요? 
한 칸씩은 수정했습니다.

**Comment by STRIKE-F** [comment]
일단은 제이님이 올리신 대로 수정했습니다.

**Comment by kaleidoscope531** [comment]
'필요한 정보는 힌트 3에서 모두 알려줬다.' 좋습니다.

**Comment by vbn2523** [comment]
'그러다 보면' 좋네요 :)

**Comment by jungin019** [comment]
수정.
