### ISSUE TITLE
덮어졌지만 / 막아야한다

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#621]
![screenshot_2016-06-08-13-11-40](https://cloud.githubusercontent.com/assets/19295794/15991832/82007190-30f9-11e6-9056-dfa2c6bdf3ed.png)

막아야한다 -> 막아야 한다 로 수정하면 좋을 것 같습니다.

또한 '그 일은 이미 덮어졌지만' 이라는 표현에서 '덮어졌지만' 이라는 표현이 조금 부자연스럽다고 생각합니다.

어떤 표현으로 바꾸든 조금 더 자연스럽게 할 수 없을까요?

'묵살되었지만' , '매장되었지만' ,'덮였지만', 등의 표현을 생각해 보았지만

적절한 표현을 찾기 어려운 것 같습니다.

**Comment by jungin019** [comment]
막아야 한다는 수정되었습니다. 
'그 일은 묻혀 버렸지만' 정도는 어떨까요?

**Comment by STRIKE-F** [comment]
이미 묻혀 버렸지만이라거나 
아니면 사람들은 그 일을 기억하지 못하지만

이런 식으로 고치는 건 어떨까요?

**Comment by kaleidoscope531** [comment]
(어둠에) 묻혔지만 정도면 어떨는지요?

**Comment by vbn2523** [comment]
제목에서 사용하고 있는 '은폐' 라는 표현은 어떨까요?

'은폐되었지만'으로요.

**Comment by Y00N** [comment]
'사람들의 기억에서 잊힌지 오래지만" 워떠유?

**Comment by vbn2523** [comment]
'사람들의 기억에서'를 생략하고 '잊힌지' -> '잊혀진지' 는 어떤가요?

사실 '잊혀진지'라는 표현이 문법적으로 잘못된 것 같긴 하지만
'잊힌지'가 딱 보기에는 조금 어색해 보이기도 하는 것 같아서...

**Comment by kaleidoscope531** [comment]
잊히다 라는 표현은 저도 생각해봤습니다만, 저 사건이 잊힌게 그냥 단순히 시간이 많이 지나서 잊힌 건 아니니까요......

**Comment by STRIKE-F** [comment]
의미상으로는 묻혔지만이 제일 어울리는 듯하는데..
전 어둠에 묻혔지만에 한 표 던집니다

**Comment by Porowl** [comment]
- 2016 07 03 - 은폐에 일단 의견집중

**Comment by Porowl** [comment]
10년 전에 일어난 폭발 사건을
생각에서 지울 수가 없다.
사건은 은폐되었지만,
클레어를 잃은 것과, 부모를 잃어
눈물로 범벅된 그 아이의 얼굴은
절대로 잊지 않을 것이다.
과거에 실수가 지금 또 반복되는
것이 아닌지 두렵다. 디미트리는
무슨 일이 있더라도 반드시
막아야 한다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
