### ISSUE TITLE
있을때 / 않을수가 / 끌어올리고야

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#622]
![screenshot_2016-06-08-13-16-49](https://cloud.githubusercontent.com/assets/19295794/15994161/c30b357e-3137-11e6-998e-ecabb64de798.png)

있을때 -> 있을 때

않을수가 -> 않을 수가 로 수정하면 좋을 것 같습니다.

'요새를 진짜 런던으로.. 내 시간의 런던으로. 끌어올리고야 말았다' 라는 표현에서,

'런던으로' 와 '끌어올리고야' 사이에 마침표를 하나 둔 건 의도된 것인가요?

**Comment by jungin019** [comment]
원문이 'I failed to talk any sense into him, and now he's brought his terrible weapon topside into the
real London. My London.'이라서 이렇게 번역하셨나 보네요. 
의견 들어보고 어색하면 고치겠습니다.

**Comment by STRIKE-F** [comment]
지금 보니까 저 사이에 들어간 마침표는 그다지 적절하지 않을 수도 있겠네요. 일단은 뺐습니다.

**Comment by kaleidoscope531** [comment]
일단 저 문장의 번역을 그대로 두실 거면 '런던으로' 뒤의 마침표는 써선 안될 듯 합니다. 

추가로 '한 때 피해자였던 그가' 뒤의 쉼표도 필요 없어보입니다. 
그리고 '정의라는 이름을 쓴' 을 '정의를 자(처/칭)하는' 또는 '정의를 핑계삼는' 정도로 바꾸는 게 어떨까요?

한 가지만 더 말씀드리면 
'그가 미래의 루크로 변장해 있을 때 가지고 있었던 이성은 이미 사라진지 오래였다.' 를
'그가 미래의 루크로 변장했던 때의 이성적인 모습은 이미 사라진지 오래였다.'
더 단순화하면 '그가 미래의 루크였을 때의 이성적인 모습은 이미 사라진지 오래였다.'
정도로 다듬으면 어떨까요?

**Comment by Y00N** [comment]
"씁쓸하지 않을 수 없다"도 이중부정이니 긍정으로 고치는 게 좋다고 봅니다.
그리고 자처하는 범죄자라니 에서 문장을 잘라도 되지 않을까요?

그가 미래의 루크였을 때의 이성적인 모습은 이미 사라진지 오래였다. 한 때 피해자였던 그가 지금은 정의를 자처하는 범죄자라니.(혹은 ....) 참으로 씁쓸하다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
