### ISSUE TITLE
돌려봤자 바뀌지 않는다

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#624]
![screenshot_2016-06-08-13-59-16](https://cloud.githubusercontent.com/assets/19295794/15994195/3208587a-3139-11e6-8f38-95a6f39e2e63.png)

'돌려봤자 바뀌지 않는다'라는 표현에서 '바뀌지'라는 표현도 좋지만

조금 더 자연스러운 표현이 있을 거라고 생각합니다.

다른 표현으로 바꿔봐도 좋지 않을까요?

ex) '들어가지', '맞지' , ...

**Comment by jungin019** [comment]
'들어가지' 정도가 좋을 것 같네요

**Comment by STRIKE-F** [comment]
들어가지로 수정하겠습니다.
