### ISSUE TITLE
가버렸다..

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#625]
![screenshot_2016-06-08-13-07-38](https://cloud.githubusercontent.com/assets/19295794/15994208/8b84c96a-3139-11e6-9474-576ca788a98b.png)

'어딘가로 가버렸다..' 라는 표현에서 말줄임표를 쓰신 이유가 있나요?

제가 보기에는 '가버렸다.' 라는 종결형 어미로 하는 것도 깔끔하고 좋을 것 같습니다.

**Comment by jungin019** [comment]
오타인 것 같군요. 수정했습니다
