### ISSUE TITLE
이별, 작별

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#627]
![screenshot_2016-06-08-11-02-01](https://cloud.githubusercontent.com/assets/19295794/15994254/4af7dda0-313a-11e6-8951-f3f915f61c7f.png)

사전에 '이별'과 '작별'의 사전적 의미 차이를 찾아봤는데,

의미 차이가 있기는 하지만 '이별이 아니라 작별' 이라고 표현할 정도로 큰 차이는 없었던 것 같습니다.

저도 어떤 표현으로 대체해야 할지는 모르겠지만,

'다시 만날 수 있을 것이다'라는 것을 강조할 수 있는 다른 표현은 없을까요?

**Comment by jungin019** [comment]
음.... 그러고보니 의미전달이 제대로 안 될 것 같네요

**Comment by kaleidoscope531** [comment]
앞에 까지 합치면 
아냐 루크./ 이별이 아니라 작별이겠지 
인가요
그렇다면
그렇구나. (루크)/ 하지만 (다시 만날거라 믿자꾸나./다시 만날 수 있을거야.)
는 어떨까요?

... 자꾸 님의 침묵에 집착하게 되네요

**Comment by Latteria** [comment]
계속 토의 해보겠습니다.
