### ISSUE TITLE
줄 띄움 / 와있으므로

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#628]
![screenshot_2016-06-08-13-35-05](https://cloud.githubusercontent.com/assets/19295794/16016352/9accee24-31d5-11e6-95df-49bbaf4a425d.png)

줄 띄움은 의도하신 것인가요?

또한 와있으므로 -> 와 있으므로 로 수정해도 좋지 않나 싶습니다.

**Comment by STRIKE-F** [comment]
의도된 바는 아닐 겁니다. 가끔 이런 이유불명의 개행이...
맞춤법과 함께 수정하겠습니다.

**Comment by STRIKE-F** [comment]
는 원문이 이렇게 개행이 돼 있었네요.
개행을 하는 게 좋을까요 붙이는 게 좋을까요?

**Comment by vbn2523** [comment]
원판이 그렇다면야 개행을 해도 상관은 없겠지만...

다른 힌트들은 저렇게 개행이 되지 않는데

저것만 저렇게 되어 있는 것은 좀 이상하다 싶기도 해요.

**Comment by kaleidoscope531** [comment]
저는 왠지 붙여놓으면 눈 아플것 같은데요, 한 번 다 붙여서 스샷을 보여주실 수 있나요?

**Comment by Y00N** [comment]
4=4고 5=5다.
1이 5 앞에 와있으므로 5보다 1 적다.

이렇게 고치면 되지 않을까요..?

**Comment by STRIKE-F** [comment]
그러면 붙이는 쪽으로 수정하겠습니다.
또한 올리신 대로 I이 V 앞에 있으므로 5보다 1 적다. 로 수정하겠습니다.
