### ISSUE TITLE
템즈 강에 저 등대가 세워진게 언제니?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#629]
![screenshot_2016-05-21-12-46-01](https://cloud.githubusercontent.com/assets/19270364/16125416/8192435e-342e-11e6-9d21-8763f4e4506e.png)

이거 루크가 하는 말 맞나요? 말투는 레이튼인데..?
그리고 템즈 -> 템스로 하시기로 한 걸로 알고있고요
세우다는 서다의 사동형이므로 -지다 라는 식의 피동을 더 쓰면 안됩니다.

템스 강에 등대를 세운 게 언제니? - 템스 강에 등대를 세운 게 언제에요?
저기에 등대를 세운 게 언제니? - 저기에 등대를 세운 게 언제에요?
템스 강에 등대를 언제 세운 거니? - 템스 강에 등대를 언제 세운 거에요?

라는 식으로 고치는 게 낫지 않을까요

**Comment by STRIKE-F** [comment]
사동-피동은 같이 써도 상관 없는 거로 압니다. 이중 피동이나 이중 사동이 의미 중복이라 문제가 되는 거고, 지금 같은 경우는 의미 추가니까요.
말투는 일단 "언제 템스 강에 저 등대가 세워졌죠?"로 수정했습니다.

**Comment by Y00N** [comment]
사동사의 피동형이라는 게 존재하는데 제가 개념을 혼동한 것 같습니다.
새벽에 눈비비며 작업하면 자꾸 말을 실수하는 것 같습니다 ㅡㅡ; 웬만하면 낮에 해야겠네요.

**Comment by jungin019** [comment]
수정했으니 닫겠습니다
