### ISSUE TITLE
한 5년 전일 거예요

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#630]
![screenshot_2016-05-21-12-46-11](https://cloud.githubusercontent.com/assets/19270364/16125714/d43efa24-342f-11e6-9a79-18a8bca16e7c.png)

(가운데는 메신저 메세지가 와서 지웠습니다)

한 5년 전이예요.
라고 불필요한 명사화를 피하는 게 더 자연스럽다고 생각합니다.

**Comment by STRIKE-F** [comment]
어린 루크에 대해 대답하는 거라 반말로 고치고, 지금은 "한 5년 전에야."라고 고쳤습니다.
