### ISSUE TITLE
비밀모드 인물파일 인물명이 설명과 다르다

### ISSUE THREAD

**Issue by elfinlazz** [elfinlazz/lt3translation#67]
![5200 - professor layton and the unwound future k __13436](https://cloud.githubusercontent.com/assets/2121182/13150131/ddd97018-d6a7-11e5-94b5-26d95c34d2f2.png)
![5200 - professor layton and the unwound future k __13031](https://cloud.githubusercontent.com/assets/2121182/13150132/ddd9b140-d6a7-11e5-9cc4-e946781c7cb0.png)
![5200 - professor layton and the unwound future k __12998](https://cloud.githubusercontent.com/assets/2121182/13150133/dddc3244-d6a7-11e5-8da6-31a2745f249f.png)
![5200 - professor layton and the unwound future k __12956](https://cloud.githubusercontent.com/assets/2121182/13150135/ddde2590-d6a7-11e5-8267-dfacbf717745.png)
![5200 - professor layton and the unwound future k __13710](https://cloud.githubusercontent.com/assets/2121182/13150134/ddddea44-d6a7-11e5-92d3-bcf8b29ffda1.png)
![5200 - professor layton and the unwound future k __13504](https://cloud.githubusercontent.com/assets/2121182/13150136/ddea5932-d6a7-11e5-8d67-9a06a19534b8.png)

**Comment by STRIKE-F** [comment]
일단 통일 완료했습니다

**Comment by elfinlazz** [comment]
마튼 -> 말튼
마오이 -> 마우이 로 수정했음
나머지는 이미지를 수정해야함

**Comment by elfinlazz** [comment]
말튼 -> 마튼
시걸 -> 세갈
이미지를 수정해야함
