### ISSUE TITLE
[오역] 챕터 9

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#705]
레이튼 : 내가 아는 한, 내 진영측은 1대 1로 싸우더라도 질 수가 없겠군요.

![image](https://cloud.githubusercontent.com/assets/19265176/16198139/c60fedb0-373f-11e6-9c76-1d4ac43c639b.png)

일단 번역해놓은 말로 보면 1대1로 싸우게 시켜도 절대 지지 않는다는 의미로 보입니다. 
그런데 지금 상황을 보면 1대 1로 갈 것까지 없이 지고 있습니다. 
일단 제가 이해한 바는 다음과 같습니다. 
'제가 봤을 땐 만일 이 싸움을 1대 1 격전으로 몰고 간다면 적어도 지진 않을 것 같습니다.'

**Comment by jungin019** [comment]
아 그렇네요. 말씀하신대로 고쳤습니다.
