### ISSUE TITLE
[오역][건의사항] 챕터 11

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#741]
챕터 11  타임 머신 시설

![image](https://cloud.githubusercontent.com/assets/19265176/16233123/36a3823a-3808-11e6-8799-9ce0b726634c.png)

제가 너무 과민한 걸지도 모르겠습니다만, 작중에서 디미트리가 타임머신을 완성해서 돌리고 있는 것이 아니므로 facility를 그냥 '시설' 보다는 '연구단지/연구시설'로 하는 것이 어떨까 합니다. 
그리고 타임머신 타임 머신 이거 예전에 어떻게 결론났었나요? 

그리고 비슷한 맥락에서 다른 이슈 하나를 더 보겠습니다. 
루크 : 결국 그것은 연구 시설이었군요...
![image](https://cloud.githubusercontent.com/assets/19265176/16233276/c7cf0e82-3808-11e6-9042-fcf680a1df61.png)

이 말의 원문이 'So, that's the research facility.' 입니다. 
이 부분은 '그러니까 저게 바로 그 연구단지군요/연구시설이군요. 로 하는 것이 좋을 듯 합니다.

**Comment by jungin019** [comment]
아래는 '그러니까 저게 바로 그 연구시설이군요.'로 고쳤습니다.
