### ISSUE TITLE
[건의사항] 수수께끼 123번 수수께끼를 푸는 법

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#768]
![image](https://cloud.githubusercontent.com/assets/19265176/16262667/8beba1a2-38ab-11e6-91e0-45307149ecc1.png)

마지막 '이루게 된다면 수수께끼를 풀 수 없습니다.' 이 부분을
'이루도록 돌을 놓아선 안됩니다.' 정도로 바꾸는 것이 어떨까요? 
일단 이 수수께끼를 풀어보면 돌을 놓는 판이 나오기는 하는데, 이는 그냥 참고용이고 정답은 최대로 놓을 수 있는 묘안석의 수를 적는 문제이기 때문에 올려봤습니다. 

추가로 문제 본문도 글이 잘려서 같이 올립니다. 
![image](https://cloud.githubusercontent.com/assets/19265176/16262747/ec2b6a02-38ab-11e6-8dd6-88c3fbada69c.png)

**Comment by jungin019** [comment]
줄바꿈은 수정.

**Comment by STRIKE-F** [comment]
그래픽팀에게 수정사항 전달했습니다.
