### ISSUE TITLE
[맞춤법][건의사항] 에필로그

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#791]
디미트리 : 무슨 말을 해야할지 모르겠군. 연구라는 이름 하에 내가 저지르고 겪었던 고통을 생각해 보면...

![image](https://cloud.githubusercontent.com/assets/19265176/16265083/4b6a7e34-38b8-11e6-8a4b-03f27c8a775a.png)

'해야할지' -> '해야 할지'로 수정이 필요합니다. 

그리고 뒤의 문장을 조금 다듬을 수 있지 않을까 싶어서 몇 가지 생각해봤습니다. 
'연구를 핑계로 내가 겪었고, 또 내가 자행했던 고통을 생각해 보면...'
'연구를 빌미로 내가 당했고, 또 내가 저질렀던 폭력을 생각해 보면...'
'연구를 빌미로 내가 맞이했고, 또 내가 초래했던 비극을 생각해 보면...'

**Comment by jungin019** [comment]
원문이 'I don't know what to say. When I think of all the suffering I caused in the name of research'네요.
겪었던 고통이 어디서 나왔는지 잘 모르겠는데 그냥 '연구라는 명목하에 내가 다른 사람에게 준 고통을 생각해보면...' 정도로 해도 될 것 같군요

**Comment by kaleidoscope531** [comment]
연구라는 명목하에 내가 다른 사람에게 준 고통을 생각해보면...' 도 좋네요.

**Comment by Latteria** [comment]
제이 님의 의견을 채택하겠습니다.
