### ISSUE TITLE
[맞춤법][건의사항] 에필로그

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#797]
클레어 : 벌써부터 끝내야 되는 일이였어. 디미트리.

![image](https://cloud.githubusercontent.com/assets/19265176/16266039/c3ad4c1e-38bd-11e6-863b-dc2f57aeaaaf.png)

일단 '였' -> '었' 으로 고쳐야 할 듯 합니다. 
그리고 '벌써부터' -> '진작부터' 로 고치는 것이 어떨까 합니다.

추가로 '진작부터 이랬어야 했어, 디미트리.'로 고쳐보는 것은 어떨까요?

**Comment by yhwon90** [comment]
저도
진작에 끝났어야 하는 일이었어, 디미트리
를 제안해 봅니다.

**Comment by kaleidoscope531** [comment]
앞에 말을 좀 알 수 있을까요?

**Comment by jungin019** [comment]
클레어 : (~생략) 그치만 디미트리는 내 말을 듣지 않았어.그를 막을 방법은 너 밖에 없을 거라고
생각했어. 허셜. 디미트리와 빌, 그리고 내가 한 실험은 자연의 법칙을 깨뜨리는 것이었고
이젠 그 대가를 치뤄야만 해.
레이튼 : 이 모든 게... 이해할 수가 없군.
클레어 : It's time to end this already,Dimitri.
디미트리 : 그래... 그런 것 같군.

**Comment by kaleidoscope531** [comment]
그렇다면 
진작에 끝났어야 하는 일이었어, 디미트리
가 좋을 듯 합니다.

**Comment by Latteria** [comment]
채택하겠습니다.
