### ISSUE TITLE
[오역] 번외

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#801]
레이튼 : 이 캐릭터들은 수수께끼에서 튀어나온 것처럼 느껴지는구나. 

![image](https://cloud.githubusercontent.com/assets/19265176/16266325/3cfb93ae-38bf-11e6-87fa-17f972e011be.png)

저 말은 좌상단의 세로로 되어 있는 간판을 클릭하면 나옵니다. 
일단 저기서 'character'는 간판에 써 있는 한자를 뜻할겁니다. 
제가 고쳐본 것은 다음과 같습니다. 

'이 글자들은 수수께끼에서 튀어나온 것처럼 생겼구나.'

**Comment by yhwon90** [comment]
동의합니다

**Comment by STRIKE-F** [comment]
그렇네요. 올리신 대로 수정하겠습니다.
