### ISSUE TITLE
[맞춤법][건의사항] 번외

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#804]
레이튼 : 디미트리는 분명 이 계단을 오갈때 쓸거야.

![image](https://cloud.githubusercontent.com/assets/19265176/16266505/345403de-38c0-11e6-9b3b-d442705e5772.png)

일단 오갈때-> 오갈 떄, 쓸거야 -> 쓸 거야 로 수정이 필요합니다. 
그리고 어순을 조금 바꿔서 '디미트리는 분명 오갈 때 이 계단을 쓸 거야.' 로 쓰는 것이 어떨까요?

**Comment by jungin019** [comment]
말씀하신 문장도 괜찮고, 아니면 '디미트리는 이 계단으로 건물을 오르내리는 게 분명해.' 정도는 어떨까요?

**Comment by STRIKE-F** [comment]
디미트리는 이 계단으로 건물을 오르내리는 게 분명해. 로 수정하겠습니다.
