### ISSUE TITLE
[맞춤법][건의사항] 번외

### ISSUE THREAD

**Issue by kaleidoscope531** [elfinlazz/lt3translation#811]
레이튼 : 그렇다면 말이다, 너와 우리의 존경하는 플레이어를 더이상 기다리게 하지 말자꾸나. 

![image](https://cloud.githubusercontent.com/assets/19265176/16267023/b181a648-38c2-11e6-8a28-b72eadf3002f.png)

일단 '더이상' -> '더 이상' 으로 수정이 필요합니다. 

그리고 '그렇다면 말이다, 너와 우리의' 를 그냥 '그렇다면, 우리의' 로 바꾸는 것이 더 자연스럽지 않을까요?

**Comment by jungin019** [comment]
원문이 'Well then, let's not keep you or our esteemed player in suspense any longer.'라서 
'너와 우리의' 존경하는 플레이어가 아니라 '너'와'우리의 존경하는 플레이어' 네요... 
근데 이걸 어찌 번역해야 좋을지 모르겠군요

**Comment by vbn2523** [comment]
'그렇다면 말이다, 우리와, 존경하는 플레이어를 더이상 기다리게 하지 말자꾸나.' 는 어떤가요?

'존경하는 플레이어' 앞에 '우리와'가 생략된 느낌을 줄 수 있을 거라고 생각하는데...

**Comment by kaleidoscope531** [comment]
'그렇다면, 너와 존경하는 플레이어를 더 이상 기다리게 해선 안되겠구나.' 로 바꾸는 것은 어떨까요?
아예 '우리의' 를 빼봤습니다.

**Comment by yhwon90** [comment]
"그렇다면 너와, 우리가 존경하는 플레이어를 ~~" 이건 어떻습니까

**Comment by STRIKE-F** [comment]
그렇다면, 너와 우리 존경하는 플레이어를 더 이상 기다리게 해선 안 되겠구나.
전 이게 맘에 들긴 하는데...솔직히 문장 자체가 좀 맘에 안 드네요. 문장의 의미 자체가 좀 우리 정서?에 안 맞는 듯해요.

**Comment by Y00N** [comment]
그렇다면, 너 뿐만 아니라 우리가 존경하는 플레이어를 더 이상 기다리게 해선 안되겠구나.

**Comment by STRIKE-F** [comment]
일단은 
그렇다면, 너 뿐만 아니라 우리가 존경하는 플레이어를 더 이상 기다리게 해선 안되겠구나. 
로 수정하겠습니다.
