### ISSUE TITLE
사실 그렇게 비밀인 것도 아니었으니.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#813]
![screenshot_2016-06-12-22-31-32](https://cloud.githubusercontent.com/assets/19270364/16354967/6a9660de-3ae3-11e6-80f7-837e69baa9b9.png)

비밀인 것이라면 "비밀이다 + 것" 인 셈인데...

사실 그렇게 비밀스러운 것도 아니었으니.
사실 비밀은 아니었으니까.

쪽이 더 자연스럽지 않을까요

**Comment by STRIKE-F** [comment]
비밀스러우 것도로 수정하겠습니다.
