### ISSUE TITLE
아, 반짝캐럿에 대해서 말하려고 하는 거라면, 저희는 이미 다 알고 있어요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#814]
![screenshot_2016-06-12-22-31-23](https://cloud.githubusercontent.com/assets/19270364/16354973/ae3bd986-3ae3-11e6-8c6a-86b5ea47c519.png)

아, 반짝캐럿에 대한 이야기라면 이미 다 알고 있어요.

라고 줄이는 게 어떨까요?

**Comment by jungin019** [comment]
현재는 '아, 힌트코인에 대해서 말씀하시려는 거라면 괜찮습니다.'로 수정되어 있습니다.
