### ISSUE TITLE
그러니까 잠시 쉬러 가는거죠?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#815]
![screenshot_2016-06-12-22-29-17](https://cloud.githubusercontent.com/assets/19270364/16354995/a0b1e656-3ae4-11e6-9e70-7318903587cd.png)

그러니까 잠시 쉬러 가는 거죠?
그러니까 잠시 쉬는 거죠?

라고 바꾸는 게 어떻겠습니까?

**Comment by STRIKE-F** [comment]
그러니까 잠시 쉬어가잔 거죠? 이건 어떨까요

**Comment by STRIKE-F** [comment]
그러니까 잠시 쉬어가잔 거죠?로 수정하겠습니다.
