### ISSUE TITLE
가방의 물건들을 다시 정리하시는게 어때요? 좀 엉망인데요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#816]
![screenshot_2016-05-22-00-42-53](https://cloud.githubusercontent.com/assets/19270364/16355083/909ef3fa-3ae7-11e6-9d5e-cf53b2baea65.png)

가방을 다시 정리하시는 게 어떠시겠어요? 좀 엉망이네요. 

라고 고치면 어떤가요?
사실 정확하게 틀린건 정리하시는게 뿐이었지만..;;

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다. 괜찮아 보이네요.

**Comment by STRIKE-F** [comment]
가방을

**Comment by STRIKE-F** [comment]
조작 실수 양해 바랍니다 ㅁㄴㅇㄹ

가방을 다시 정리하시는 게 어때요?
이건 어떨까요?

**Comment by STRIKE-F** [comment]
가방을 다시 정리하시는 게 어때요? 로 수정하겠습니다.
