### ISSUE TITLE
그 전에 제가 가넷을 빼낼 수 있는지 한 번 해보도록 하지요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#817]
![screenshot_2016-05-22-00-43-31](https://cloud.githubusercontent.com/assets/19270364/16355085/a43b00fc-3ae7-11e6-8494-f05e01132457.png)

그 전에 제가 가넷을 한 번 빼내보죠.

라고 정리하면 되지 않을까요..?

**Comment by STRIKE-F** [comment]
그 전에 제가 가넷을 한 번 빼내 보죠.
이렇게 수정하겠습니다.

**Comment by STRIKE-F** [comment]
그 전에 제가 가넷을 한번 빼내 보죠.
한번의 의미가 try니까 이렇게 고쳤습니다.
