### ISSUE TITLE
내가 정말 스타일리시한 신사기는 하지만 (어떤 사람은 내가 이 도시에서 가장 잘 차려입는다고도 하더군)

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#818]
![screenshot_2016-05-30-15-26-39](https://cloud.githubusercontent.com/assets/19270364/16355228/9a0ab70e-3aeb-11e6-9196-807f7fd1ce07.png)

#607 과도 연관이 있어 보여 들고왔습니다.
국립국어원의 문장 부호 해설(2014)에 따르면, 문장 중간에 끼어든 어구의 앞뒤로는 쉼표 혹은 줄표를 사용해야합니다.

내가 정말 스타일리시한 신사기는 하지만 ,어떤 사람은 내가 이 도시에서 가장 잘 차려입는다고도 하더군,
내가 정말 스타일리시한 신사기는 하지만 ─ 어떤 사람은 내가 이 도시에서 가장 잘 차려입는다고도 하더군 ─

이라는 식으로요. 저는 개인적으로 줄표를 쓰는 게 더 낫다고 생각합니다.

**Comment by kaleidoscope531** [comment]
저도 줄표를 쓰는 게 좋아보이네요.
그것보다도 우리나라 말도 문장 중간에 어구가 끼어들 수 있는거였군요

**Comment by jungin019** [comment]
대화이므로 쉼표가 낫다고 봅니다. 영어 원문에 있는 줄표도 쉼표로 대체하기로 했고요. 
해당 문장을 수정되어 '내가 정말 스타일리시한 신사기는 하지. 어떤 사람은 내가 이 도시에서 가장 
옷을 잘 차려입는다고도 하더군.'로 수정되어 있습니다.
