### ISSUE TITLE
아, 같이 놀자!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#819]
![screenshot_2016-05-30-15-28-10](https://cloud.githubusercontent.com/assets/19270364/16355261/b1fd13ce-3aec-11e6-8284-51f0bcec42bf.png)

(앵무새 이름, 위의 경우에 무새), 같이 놀자!
(앵무새 이름, 위의 경우에 무새)야, 같이 놀자!

라는 식이 더 깔끔하지 않을는지...?

**Comment by kaleidoscope531** [comment]
제 앵무새는 이름이 '장덕삼'이라 
장덕삼아, 같이 놀자! 가 더 어울렸습니다.
(앵무새 이름, 위의 경우에 무새), 같이 놀자! 이게 가장 좋을 듯 하네요.

**Comment by jungin019** [comment]
이건 나눌 수 있는 문제인지 잘 모르겠어서 프로그래밍 태그 붙이겠습니다.
'(앵무새 이름)(야), 같이 놀자' 이렇게 괄호를 쓰는 건 가능합니다.
