### ISSUE TITLE
게다가, 천재에게는 영감을 줄 수 있는 여자가 반드시 필요하지.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#820]
![screenshot_2016-05-30-15-27-19](https://cloud.githubusercontent.com/assets/19270364/16355270/e9f19ae8-3aec-11e6-8b96-dd29cb78070b.png)

게다가 뒤의 쉼표는 생략해도 되니 생략하는 게 어떨까요?
그리고 "줄 수 있는"도 "주는"으로 줄이는 게 어떨까 싶습니다.

게다가 천재에게는 영감을 주는 여자가 반드시 필요하지.

**Comment by kaleidoscope531** [comment]
게다가 천재에게는 영감을 주는 여자가 반드시 필요하지.
좋습니다.
