### ISSUE TITLE
지우기를 눌러 모든 로프를 없앨 수 있습니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#821]
![screenshot_2016-05-30-15-31-56](https://cloud.githubusercontent.com/assets/19270364/16355283/4679bb88-3aed-11e6-93cd-abf47e5363d3.png)

그림 설명은 초기화네요.
덧붙여 "~ 없앨 수 있습니다." 보다는 "초기화를 눌러 모든 로프를 없앱니다."가 더 깔끔하지 않을까요?

**Comment by STRIKE-F** [comment]
초기화를 누르면 모든 로프가 사라집니다. 
이러면 어떨까요?

**Comment by STRIKE-F** [comment]
초기화를 누르면 모든 로프가 사라집니다. 로 수정하겠습니다.
