### ISSUE TITLE
앵무새가 제한 시간 안에 도착할 수 있도록 가장 빠른 길을 알아내세요

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#822]
![screenshot_2016-05-30-15-28-42](https://cloud.githubusercontent.com/assets/19270364/16355296/a1532472-3aed-11e6-93cb-d3280920fd09.png)

앵무새가 제한 시간 안에 도착하도록 가장 빠른 길을 알아내세요.

라고 줄이는 게 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
