### ISSUE TITLE
앵무새가 도착 지점까지 잘 도착할 수 있도록 로프를 놓아 도와 주세요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#823]
![screenshot_2016-05-30-15-30-35](https://cloud.githubusercontent.com/assets/19270364/16355301/bffba3cc-3aed-11e6-9775-7bc00c0c4221.png)

앵무새가 도착 지점까지 잘 가도록 로프를 놓아주세요.

라고 줄이는 건 어떻겠습니까?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
