### ISSUE TITLE
두 점을 연결하면 로프가 만들어 집니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#824]
![screenshot_2016-05-30-15-30-59](https://cloud.githubusercontent.com/assets/19270364/16355303/cf4bd540-3aed-11e6-84b2-462199416fe2.png)

두 점을 연결하여 로프를 놓습니다.

라고 다듬으면 어떨까요?

**Comment by kaleidoscope531** [comment]
더 좋을 듯 합니다.
