### ISSUE TITLE
각 배달 요청마다 사용할 수 있는 로프의 수는 각각 다릅니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#825]
![screenshot_2016-05-30-15-31-28](https://cloud.githubusercontent.com/assets/19270364/16355310/17ec9e6a-3aee-11e6-9561-0b0753890ee0.png)

각 : 낱낱의.
각각 : 사람이나 물건의 하나하나마다.

중복된 설명이라고 생각합니다.
둘 중 하나만 써도 의미 전달은 잘 되지 않을까요?

**Comment by kaleidoscope531** [comment]
전 앞의 각을 빼는 게 더 좋네요.

**Comment by STRIKE-F** [comment]
각을 빼도록 하겠습니다.
