### ISSUE TITLE
시작! 을 터치하여 앵무새가 배달을 하도록 할 수 있습니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#826]
![screenshot_2016-05-30-15-32-04](https://cloud.githubusercontent.com/assets/19270364/16355329/6f4fa328-3aee-11e6-9f0a-02e060f8b46d.png)

시작! 을 터치하여 앵무새가 배달을 시작하도록 합니다.
로 다듬는 게 어떨까요?

**Comment by kaleidoscope531** [comment]
좋습니다.
