### ISSUE TITLE
로프의 각도와 위치에 따라 앵무새 또한 다르게 움직일 겁니다. 

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#827]
![screenshot_2016-05-30-15-31-34](https://cloud.githubusercontent.com/assets/19270364/16355336/9bbdc688-3aee-11e6-97b3-6054e2c29fc0.png)

로프의 각도와 위치에 따라 앵무새는 다르게 움직입니다.

라고 다듬으면 어떨까요?

**Comment by sumstraw** [comment]
괜찮은 것 같아요!사실?게임의 규칙?을 있는대로 표현하기에는 고친 게 더 적합하다고 생각합니다.

**Comment by STRIKE-F** [comment]
올리신 대로 고치겠습니다.
