### ISSUE TITLE
정해진 갯수만큼의 줄을 사용하세요. 앵무새가 택배를 배달할 수 있게 유도하세요

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#829]
![screenshot_2016-05-30-15-33-19](https://cloud.githubusercontent.com/assets/19270364/16355358/3766071c-3aef-11e6-99d1-b0598403e805.png)

정해진 개수만큼의 줄을 사용하세요.
앵무새가 택배를 잘 배달하도록 유도하세요.

라고 다듬는 게 어떨까요?

**Comment by itstake** [comment]
굳이 "잘" 이 라는 단어가 필요한지 의문이 듭니다.
개인적으로 지금 그대로가 낫다고 봅니다.
