### ISSUE TITLE
또한 앵무새가 제한 시간 안에 도착하지 못해도 배달을 다시 해야 합니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#830]
![screenshot_2016-05-30-15-33-01](https://cloud.githubusercontent.com/assets/19270364/16355365/85b4458c-3aef-11e6-8323-83f1ce64028a.png)

또한 앵무새가 제한 시간 안에 도착하지 못해도 다시 배달해야 합니다.

라고 다듬는 게 어떨까요?

**Comment by kaleidoscope531** [comment]
좋습니다.
