### ISSUE TITLE
만약 앵무새가 화면 밖으로 나가거나 구멍으로 떨어질 경우 배달을 다시 해야 합니다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#831]
![screenshot_2016-05-30-15-32-53](https://cloud.githubusercontent.com/assets/19270364/16355377/b86d2afc-3aef-11e6-965d-edc21a2aac55.png)

만약 앵무새가 화면 밖으로 나가거나 구멍으로 떨어지면 다시 배달해야 합니다.

라고 다듬는 게 어떨까요?

**Comment by kaleidoscope531** [comment]
좋습니다.
