### ISSUE TITLE
또 배달을 하고 싶어 질때는 그냥 빽 울기만 해. 알겠지?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#832]
![screenshot_2016-05-30-15-34-26](https://cloud.githubusercontent.com/assets/19270364/16355387/0daa1412-3af0-11e6-9ecc-f4730850204e.png)

또 배달을 하고 싶어질 때는 그냥 빽 울기만 해. 알겠지?
또 배달을 하고 싶어지면 그냥 빽 울기만 해. 알겠지?
또 배달을 하고 싶으면 그냥 빽 울어. 알겠지?

여러가지로 다듬어봤는데 어떤가요? 저는 마지막 것이 제일 좋네요.

**Comment by kaleidoscope531** [comment]
또 배달을 하고 싶으면 그냥 빽 울어. 알겠지? 좋습니다.

**Comment by STRIKE-F** [comment]
또 배달을 하고 싶으면 그냥 빽 울어. 알겠지? 
이거로 수정하겠습니다.
