### ISSUE TITLE
[수수께끼 39] 문제

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#833]
![screenshot_2016-06-01-12-43-16](https://cloud.githubusercontent.com/assets/19270364/16355453/161d8b7c-3af2-11e6-9485-846abbc4bc25.png)

수정해본 문장입니다.

네 명의 아이가 공원에서 놀다가 시간이 많이 늦어 집으로 돌아가기로 했다.
그런데 급하게 집에 갈 준비를 하다 보니 외투가 그만 뒤섞여버렸다.

A: "내 외투는 어디 갔지?"
B: "어라? 내 외투엔 A의 이름이 쓰여 있어!"
C: (수정내용 없음)
D : "이건 내 외투가 아니야..."

누가 D의 외투를 입었을까?(D의 외투를 입은 아이는 누구일까?)

------------------------------------------------------------------------------------

네 명의 아이들 -> 네 명의 아이 
: 경제성 측면에서 '들'을 빼는게 어떻겠냐고 늘 말씀드렸던 그겁니다.
시간이 많이 늦은걸 보고는 -> 시간이 많이 늦어
: 늦은 것을 보고는 이라는 말을 줄이면 어떨까 싶어서요
그런데, -> 그런데 
: 쉼표를 뺐습니다.
준비를 하다보니 -> : 준비를 하다 보니 
: 띄어쓰기 문제입니다.
어디갔지? -> 어디 갔지? 
: 띄어쓰기 문제입니다.
써져 있어 -> 쓰여 있어
: 써져 있어도 맞는 말이긴 한데... 이건 그냥 어감상 :D 
누가 D의 외투를 입고 있을까? -> 누가 D의 외투를 입었을까? D의 외투를 입은 아이는 누구일까? 
: 이 문제에서 '입고 있다'라는 식으로 서술하면 힌트들이 좀 지저분해집니다. "누가 누구의 외투를 입고 있고 누가 누구의 옷을 입고 있고.."라는 식으로요. 문제 내에서 전체적으로 '입다'라고 서술하면 좋겠습니다.

**Comment by kaleidoscope531** [comment]
동의합니다.

**Comment by jungin019** [comment]
누가 D의 외투를 입었을까?. 전체 수정.
