### ISSUE TITLE
[수수께끼 39] 힌트 1-4 

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#834]
![111](https://cloud.githubusercontent.com/assets/19270364/16355588/0e71fd46-3af6-11e6-9563-31c7e74b7a8b.jpg)

다듬어 본 내용입니다.

힌트1
누가 누구의 외투를 **입었는지** 하나씩 살펴보면, 금방 정답이 **나온다.**
**예로** B는 A의 외투를 입었다.

입고 있는지 -> 입었는지 : #833 에서도 언급했지만 이번 문제에서 '입고 있다'라고 서술하면 다소 문장이 지저분해집니다. 특히 힌트 2번이 더 그렇군요.
나올 것이다 -> 나온다 : ~ 것이다를 굳이 쓸 필요가 있을까요?
예제로 -> 예로 : 예제..는 예시로 드는 문제 아닌가요?

---------------------------------------------------------------
힌트2
A는 외투를 **입지 않았다**.
B는 A의 외투를 **입었다.**
C는 **외투를 가져오지도 않았지만...**
**어쨌거나** A의 외투는 아니다.

조금 **꼬여있지만** 정답은 분명 이 중에 있다.

입고 있지 않고, -> 입지 않았다. / 입고 있고 -> 입었다. : 읽기 편하게 문장을 끊어봤습니다. 그리고 위에서 말씀드린대로 최대한 '입다, 입었다'라고 서술하는 게 어떨까 싶습니다.
가져오지도 않았지만... -> 외투를 가져오지도 않았지만 : 목적어가 빠져서 넣어봤습니다.
분명 -> 어쨌거나 : 분명이 아래에 바로 나오니까 뭘로 바꿔볼까 하다가 넣어봤는데요. 뉘앙스는 좀 달라지지만 맥락을 해치진 않는다고 생각했는데 어떨까요?
꼬여있긴 하지만, -> 꼬여있지만 : 쉼표를 빼고 줄여봤습니다.

---------------------------------------------------------------
힌트3

C가 외투를 가져오지 않았으니 
**외투는 3벌뿐이다**. A, B, 그리고 D의 **외투다.**
A의 외투는 B가 **입었고**
D가 입은 외투는 **자기 것이 아니다.**

이제 좀 감이 잡히나?

현재 외투는 3개 뿐이다. -> 외투는 3벌뿐이다. : 옷을 세는 단위로 벌이 더 적절하다고 생각합니다. 그리고 여기서의 뿐은 조사이기에 붙여써야 합니다. 현재...를 빼봤는데 굳이 넣을 필요 없는 불필요한 말이라고 생각했습니다.
D의 외투 -> D의 외투다. : 문장이 끝나지 않았더라구요.
입고있고 -> 입었고 : 일단 입고 있고가 맞는 표기고, 저는 ~있다는 불필요하다고 생각합니다.
자기것이 아니니... -> 자기 것으로 띄어 써야 합니다. 굳이 말줄임표를 써야 하나 해서 마침표로 닫아봤는데 오지랖일 수도 있겠네요.

---------------------------------------------------------------
S.힌트

B와 D의 **외투만 찾아내면 된다.**
다시 한 번 아이들의 말을 잘 들어보면 답이 나올 것이다.

외투의 행방만 생각하면 된다 -> 외투만 찾아내면 된다 : ~의 외투의가 걸려서 문장을 틀어봤습니다.
이제..가 불필요하다고 생각되어서 빼봤는데 이것도 개인 선호가 많이 섞인 걸지도 모르겠네요.

**Comment by kaleidoscope531** [comment]
동의합니다.
