### ISSUE TITLE
[수수께끼 39] 정답해설

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#835]
![screenshot_2016-06-01-12-45-19](https://cloud.githubusercontent.com/assets/19270364/16355708/d2959350-3afa-11e6-82c0-193c98479fbe.png)

아래는 다듬어본 내용입니다.

A, B, D가 외투를 입고 왔다.
B는 A의 외투를 입었으니 B와 D의 외투를 찾는 일만 남았다.
D가 자신의 외투를 입지 않았으므로 분명 B의 외투를 입었을 것이다.

즉 D의 외투를 입은 사람은 C이다.

그리고 -> 생략 : 딱히 없어도 될 것 같은데요......?
입고 있으니 -> 입었으니 : #834 #833 에서 말씀드렸던 이야기의 연장입니다.
이제 남은 것은 B와 D의 외투의 행방이다. -> B와 D의 외투를 찾는 일만 남았다 : ~의가 두 번 나타나기에 문장을 틀어봤습니다. 역시 #834 에서 언급한 내용과 같습니다.
입고 있지 않으므로 -> 입지 않았으므로 : 위의 입었으니와 같은 이야기입니다.
입고 있을 것이다 -> 입었을 것이다 : 위와 같습니다.
이 말은, ~란 얘기다 -> 즉 이다. : 다소 매끄럽지 않다고 생각해서 다듬어봤습니다.

**Comment by kaleidoscope531** [comment]
좋습니다.
