### ISSUE TITLE
조심하지 않으면 잃게 될 수도 있다는 것 말이다.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#836]
![screenshot_2016-06-01-12-45-30](https://cloud.githubusercontent.com/assets/19270364/16355775/658fbf30-3afd-11e6-95b5-0d07c60d5525.png)

조심하지 않으면 무언가를 잃게 된단다.

목적어가 없길래... 목적어를 넣고 저렇게 좀 다듬으면 어떨까요?

**Comment by kaleidoscope531** [comment]
이전에 다뤘던 이슈입니다.
#293

**Comment by jungin019** [comment]
현재는 위 이슈를 보면 알 수 있듯 '그 수수께끼가 네게 교훈이 됐으면
좋겠구나. 네 물건을 소중히 다루지 않으면 잃을수도 있다는 것 말이다.'로 수정되어 있습니다.
