### ISSUE TITLE
문이 잠겨 있으니, 어쨌든 그 수수께끼를 풀어야 할 것 같구나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#838]
![screenshot_2016-06-02-03-06-53](https://cloud.githubusercontent.com/assets/19270364/16355821/2e343a10-3afe-11e6-82bf-b5e6dfafbf70.png)

문이 잠겨있으니, 어쨌든 그 수수께끼를 풀어야겠구나.

라고 줄이면 어떨가요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
