### ISSUE TITLE
축하하기에는 아직 이른 것 같아요, 선생님.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#839]
![screenshot_2016-06-02-03-15-34](https://cloud.githubusercontent.com/assets/19270364/16355826/438766b2-3afe-11e6-9166-ee9830be0e03.png)

축하하기에는 아직 일러요, 선생님.

라고 줄여도 무방한 상황이 아닌가 싶습니다.

**Comment by kaleidoscope531** [comment]
줄여도 좋을 듯 합니다.
