### ISSUE TITLE
문을 수수께끼로 열 수 없다면... 도대체 뭘로 열어야 한다는 거지?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#840]
![screenshot_2016-06-02-03-16-20](https://cloud.githubusercontent.com/assets/19270364/16355831/63157b0e-3afe-11e6-9cf4-a0e49f0174e9.png)

수수께끼를 풀어도 문을 열 수 없다면... 도대체 어떻게 해야 문이 열리지?

라고 문장을 좀 틀면 더 자연스러울 것 같은데 어떨까요?

**Comment by kaleidoscope531** [comment]
수수께끼를 풀어도 문을 열 수 없다면... 도대체 어떻게 해야 문이 열리지?
좋습니다.
