### ISSUE TITLE
아무래도, 다른 방법을 생각해야 할 것 같군요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#841]
![screenshot_2016-06-02-03-16-29](https://cloud.githubusercontent.com/assets/19270364/16355841/9fa13f36-3afe-11e6-9c75-1f27c388c43a.png)

아무래도 다른 방법을 생각해봐야겠어요.

쉼표도 빼고 저렇게 문장을 다듬어보면 어떨까요?

**Comment by kaleidoscope531** [comment]
좋습니다.
