### ISSUE TITLE
아무래도, 누군가를 또 겁에 질리게 한 모양이구나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#842]
![screenshot_2016-06-02-03-22-47](https://cloud.githubusercontent.com/assets/19270364/16355849/effc26f8-3afe-11e6-8e0c-7c04146e5219.png)

아무래도 누군가를 또 겁에 질리게 한 모양이구나.
아무래도 누군가에게 또 겁을 준 모양이구나.

일단 쉼표를 빼고요. 원문 그대로도 나쁘진 않은데 아래 문장은 혹시 어떨까요?

**Comment by kaleidoscope531** [comment]
저는 아무래도 누군가를 또 겁에 질리게 한 모양이구나. 가 더 좋네요.

**Comment by STRIKE-F** [comment]
아무래도 누군가를 또 겁에 질리게 한 모양이구나.
이거로 수정하겠습니다.
