### ISSUE TITLE
왜 거기 숨어 계시는 거예요!

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#844]
![screenshot_2016-06-12-21-38-26](https://cloud.githubusercontent.com/assets/19270364/16355858/5d17d57a-3aff-11e6-90ff-37f7a7dc51ae.png)

"숨어 계시는 거예요"... 풀어 쓰면 "숨어 계시는 것이에요" 라는 건데
그냥 "왜 거기 숨어 계세요!"라고 하는 게 더 자연스럽지 않을까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
