### ISSUE TITLE
그 설명을 빠트린 것 같네.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#845]
![screenshot_2016-06-12-21-39-47](https://cloud.githubusercontent.com/assets/19270364/16355864/aed30902-3aff-11e6-8fe2-938eedb2fdfe.png)

그 설명을 빠트렸네.
그 설명을 빠트렸구나.

정도로 다듬는 게 어떨까요?

**Comment by kaleidoscope531** [comment]
그 설명을 빠트렸구나. 좋습니다.
