### ISSUE TITLE
자세한 내용은 나보다 코그 아저씨가 더 잘 알려주실 수 있을꺼야. 아저씨한테 한 번 물어봐.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#846]
![screenshot_2016-06-12-21-40-07](https://cloud.githubusercontent.com/assets/19270364/16355867/ce7f0fda-3aff-11e6-95b8-a8ecc44371b2.png)

자세한 내용은 나보다 코그 아저씨가 더 잘 알려주실 거야.
아저씨께 한 번 여쭤봐.

앞의 문장은 불필요하게 길어서 줄여봤어요. 오타도 있었고요.
아저씨한테 한 번 물어봐...는 청년 루크는 좀 더 점잖으니 존대를 제대로 하는 게 어떨까 싶은데, 어떻게 생각하세요?

**Comment by Y00N** [comment]
아.. 그렇게 존칭을 하면 앞의 문장도 "아저씨께서"라고 해야할까요?

**Comment by kaleidoscope531** [comment]
동의합니다.

**Comment by STRIKE-F** [comment]
자세한 내용은 나보다 코그 아저씨께서 더 잘 알려주실 거야.
 아저씨께 한 번 여쭤봐.

이렇게 수정하겠습니다.

**Comment by STRIKE-F** [comment]
한 번->한번으로 고치겠습니다. Once의 의미가 아니라 try의 의미니까요.
