### ISSUE TITLE
[수수께끼 40]

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#847]
![screenshot_2016-06-02-03-05-06](https://cloud.githubusercontent.com/assets/19270364/16355913/793387a2-3b01-11e6-8bbc-e0d533a811a1.png)

문을 열려면 숫자가 그려진 네 개의 타일을 방정식의 조건에 만족하도록 빈 공간에 놓아야 한다.

문장이 좀 긴데 자르면 안될까요?
문을 열려면 숫자 타일 중 4개를 빈 공간에 놓아야 한다. 단 방정식의 조건에 만족해야 한다.
는 어떨까요..?

**Comment by kaleidoscope531** [comment]
일단 예전에 올렸던 이슈입니다. 
#295
하지만, 여기서 다시 논하는 것도 좋을 듯 하군요

**Comment by jungin019** [comment]
현재는 '문을 열기 위해선 주어진 조건을 만족하도록 빈 공간에 네 개의 숫자 타일을 채워 넣어야 한다.'로 수정되어 있습니다.
