### ISSUE TITLE
그러니까, 모자파들이 과학자를 고용해 타임머신을 개발하고 있으니,

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#849]
![screenshot_2016-06-12-21-48-40](https://cloud.githubusercontent.com/assets/19270364/16356092/7a7bf756-3b07-11e6-806d-1b691a00ea40.png)

그러니까 뒤의 쉼표는 뺴도 무방하다고 생각합니다

**Comment by kaleidoscope531** [comment]
동의합니다.
