### ISSUE TITLE
아무래도 내 시계를 이용해서 그 타임머신을 위한 웜홀을 만들려고 했던 것 같아.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#850]
![screenshot_2016-06-12-21-48-48](https://cloud.githubusercontent.com/assets/19270364/16356098/afadcb20-3b07-11e6-8287-5bd96fd9c8f9.png)

아무래도 내 시계로 타임머신을 위한 웜홈을 만들려던 것 같아.

라고 줄여봤는데 어떨까요..?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
