### ISSUE TITLE
그리곤 시간의 문이 코그씨의 시계나 그 근처에 열렸다는 것이군요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#851]
![screenshot_2016-06-12-21-49-52](https://cloud.githubusercontent.com/assets/19270364/16356112/3e0f0988-3b08-11e6-9ae9-421ebce7b456.png)

그리곤 시간의 문이 코그 씨의 시계나 그 근처에 열렸군요.

코그씨 -> 코그 씨
열렸다는 것이군요 -> 열렸군요.

라고 수정해 봤는데 어떤가요?

**Comment by kaleidoscope531** [comment]
좋습니다.

**Comment by STRIKE-F** [comment]
열렸고요. 는 어떨까요?
코그 씨는 수정했습니다.

**Comment by STRIKE-F** [comment]
열렸고요로 수정했습니다. -군요가 반복되면 좀 이상해 보여서요
