### ISSUE TITLE
네. 그런것 같군요. 

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#852]
![screenshot_2016-06-12-21-50-02](https://cloud.githubusercontent.com/assets/19270364/16356124/a09899ca-3b08-11e6-9cd2-dc621f6495e8.png)

#851 에서 이어지는 대사입니다.

"네. 그런 것 같군요." 라고 띄어써야 맞습니다.

생각해봤는데 "그렇게 됐습니다." 라는 느낌이 더 가까울진 않을는지...

**Comment by jungin019** [comment]
현재는 해당 대사는 수정되어 '그런 것 같습니다. 제가 보기에 이 시계는 100년도 넘게 계속 작동하고
있었으니...'라고 되어 있습니다.
