### ISSUE TITLE
말하지 않아도 이미 예상하던 것이겠지만, 코그씨는 모자파의 일원이 아니에요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#854]
![screenshot_2016-06-12-21-51-31](https://cloud.githubusercontent.com/assets/19270364/16356189/6ce10c64-3b0a-11e6-9a70-e54fb9fb5a9b.png)

말씀드리지 않아도 이미 예상하셨겠지만, 코그 씨는 모자파의 일원이 아니셔요.

라고 고치는 게 적절하지 않을는지요...?

**Comment by kaleidoscope531** [comment]
더 좋을듯 합니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
