### ISSUE TITLE
아무래도, 네 계획은 성공적이었던 것 같구나, 큰 루크.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#856]
![screenshot_2016-06-12-21-52-37](https://cloud.githubusercontent.com/assets/19270364/16356198/1f25ce00-3b0b-11e6-8fd5-99e7b35a555b.png)

아무래도 네 계획은 성공적이었구나, 큰 루크.
아무래도 네 계획은 꽤 성공적이었구나, 큰 루크.

쉼표를 뺴고 이정도로 다듬어보는 게 어떨까요?

**Comment by kaleidoscope531** [comment]
전 두 번째가 더 좋습니다.

**Comment by Porowl** [comment]
꽤 쪽에 한 표

**Comment by STRIKE-F** [comment]
아무래도 네 계획은 꽤 성공적이었구나, 큰 루크.
로 수정하겠습니다.

**Comment by STRIKE-F** [comment]
아무래도를 보아하니로 바꾸는 게 더 나아 보이는데, 어떤가요?

**Comment by STRIKE-F** [comment]
일단은 보아하니로 고쳤습니다. 아무래도는 느낌이 뭔가 여기엔 안 맞는 듯해서요...ㅇㅅㅇ
