### ISSUE TITLE
루크, 그 질문에 대한 대답은 모두가 알고 있을 것 같구나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#857]
![screenshot_2016-06-12-21-54-21](https://cloud.githubusercontent.com/assets/19270364/16356207/79596bde-3b0b-11e6-9651-7c6ca14e9d1c.png)

루크, 그 질문에 대한 대답은 모두가 알고 있을 거다.
루크, 그 질문에 대한 대답은 모두가 알 거다.

라는 식으로 다듬는 게 어떨까요?

**Comment by kaleidoscope531** [comment]
전 첫 번째가 더 좋습니다.

**Comment by Porowl** [comment]
첫 번째에 한 표

**Comment by STRIKE-F** [comment]
루크, 그 질문에 대한 대답은 모두가 알잖니.
이건 어떤가요?

**Comment by STRIKE-F** [comment]
루크, 그 질문에 대한 대답은 모두가 알잖니. 로 고쳤습니다. 이게 좀 더 구어체에 가까워 보여요.
