### ISSUE TITLE
얼굴이 완전 녹색이구나.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#859]
![screenshot_2016-06-12-22-25-42](https://cloud.githubusercontent.com/assets/19270364/16356232/63922808-3b0c-11e6-944a-9aea5f859eab.png)

얼굴이 완전 하얗게 질렸구나.

라는 쪽이 자연스러운 우리말 표현에 가깝지 않을까 싶습니다.

**Comment by jungin019** [comment]
완전을 빼고 '얼굴이 하얗게 질렸구나'는 어떨까요?

**Comment by Porowl** [comment]
완전을 빼는 편에 한표

**Comment by Y00N** [comment]
좋네요

**Comment by STRIKE-F** [comment]
얼굴이 하얗게 질렸구나
로 수정하겠습니다.

**Comment by STRIKE-F** [comment]
이미 수정 됐네요
