### ISSUE TITLE
그래, 아마 시간 여행 후유증 같네. 내가 처음 시간 여행을 했을 때도 너처럼 느꼈어.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#860]
![screenshot_2016-06-12-22-26-12](https://cloud.githubusercontent.com/assets/19270364/16356248/b1c9b5ae-3b0c-11e6-8586-1a2e89d63df0.png)

그래, 아마 시간여행 후유증일 게다. 내가 처음 시간여행을 했을 때도 그렇게 느꼈어.
라고 다듬는 게 어떨까요?

그리고 보다보니까 "시간 여행"과 "시간여행"을 혼용하는 것 같습니다. 
#115 에서는 시간여행이라고 썼고요.
하나로 통일하는 게 어떨까 싶습니다.
개인적으로는 "시간여행"이 더 나을 것 같은데 어떻게들 생각하세요?

**Comment by kaleidoscope531** [comment]
다듬는 게 좋을 것 같습니다.
시간여행 이 더 좋습니다.

**Comment by jungin019** [comment]
시간여행, 시간 여행 때문에 열어놓겠습니다.

**Comment by Porowl** [comment]
시간여행 으로 붙히는게 더 낫지 않을까 싶네요

**Comment by STRIKE-F** [comment]
저도 붙이는 쪽에 한 표 던집니다.

그래, 아마 시간여행 후유증일 게다. 내가 처음 시간여행을 했을 때도 그렇게 느꼈어.
 이렇게 수정할게요.

**Comment by STRIKE-F** [comment]
뭐야 이미 고쳐졌잖아
