### ISSUE TITLE
코그 씨, 저희는 이만 나가서 조사를 진행해야 할 것 같군요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#861]
![screenshot_2016-06-12-22-26-24](https://cloud.githubusercontent.com/assets/19270364/16356273/346d45c0-3b0d-11e6-85ef-10df27a7f238.png)

코그 씨, 저희는 이만 나가서 조사를 진행해보겠습니다.

라는 쪽이 더 자연스럽지 않을까요?

**Comment by kaleidoscope531** [comment]
더 좋습니다.
