### ISSUE TITLE
그렇군요. 전 여기서 기다리도록 할게요. 비밀 노크를 하시면 바로 들여보내 드릴게요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#862]
![screenshot_2016-06-12-22-26-55](https://cloud.githubusercontent.com/assets/19270364/16356280/51e80126-3b0d-11e6-8a34-f8535c70a333.png)

#861 에서 이어지는 내용입니다.

그러시죠. 전 여기서 기다리겠습니다. 비밀 노크를 하시면 바로 들여보내 드리죠.

라는 쪽이 더 자연스럽지 않을까 싶습니다.

**Comment by kaleidoscope531** [comment]
이전에 다뤘던 이슈입니다. 
#429

**Comment by jungin019** [comment]
'그렇군요. 전 여기서 기다리겠습니다. 비밀 노크를 하시면 바로 들여보내 드리죠.'로 수정되어 있습니다.
