### ISSUE TITLE
알겠습니다. 마침 저도 코그 씨가 미래로 돌아갔을 때 어떻게 연락을 해야 할지 고민하고 있었습니다만, 다행이군요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#863]
![screenshot_2016-06-12-22-27-11](https://cloud.githubusercontent.com/assets/19270364/16356289/8388dc5a-3b0d-11e6-8bc0-e48e1622464e.png)

#862 에서 이어지는 내용입니다.

알겠습니다. 마침 저도 코그 씨가 미래로 돌아가시면 어떻게 연락을 드리나 고민하고 있었습니다. 다행이군요.

라고 문장을 짜르고 조금 다듬어보면 어떨까요?

**Comment by kaleidoscope531** [comment]
다듬는게 좋을 것 같습니다.
