### ISSUE TITLE
네, 노크만 하면 돼요. 자, 어서 가시죠. 전 저녁을 먹으러 원래 시간으로 돌아갈게요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#864]
![screenshot_2016-06-12-22-27-29](https://cloud.githubusercontent.com/assets/19270364/16356330/b3240d26-3b0e-11e6-902b-cd84a9d3070c.png)

#863 에서 이어집니다.

네, 노크만 하시면 됩니다. 자 어서 가시죠. 전 저녁을 먹으러 원래 시간으로 돌아가보겠습니다.

라는 쪽이 좀 더 정중한 코그 씨의 말투에 어울리지 않을까요?

**Comment by kaleidoscope531** [comment]
이전에 언급된 이슈입니다.
#430

**Comment by jungin019** [comment]
현재는 '네, 노크만 하면 됩니다. 자, 어서 가시죠. 전 저녁을 먹으러 원래 
시간으로 돌아가겠습니다.'로 수정되어 있습니다.

**Comment by Y00N** [comment]
왜 제가 검색했을 땐 못 찾았을까요ㅠㅜ
