### ISSUE TITLE
나한텐 그러니까, 어,수수께끼. 그래, 맞아! 나한텐 이제 너가 풀 수수께끼가 

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#865]
![screenshot_2016-06-12-22-31-48](https://cloud.githubusercontent.com/assets/19270364/16356345/158f1e4c-3b0f-11e6-80aa-4ac56c1d09c3.png)

나한텐 그러니까, 어... 수수께끼. 그래, 맞아! 나한텐 네가 풀 수수께끼가 있어!

중간에 쉼표가 많이 사용되니까 하나정도는 다른 걸로 바꾸는 게 어떨까요? 그리고 띄어쓰기도 해주고요.
뒤의 내용은 모르는데 걍 아무거나 적어봤습니다 ㅋㅋ

**Comment by kaleidoscope531** [comment]
훨씬 좋습니다.

**Comment by jungin019** [comment]
현재 '잠깐만! 그렇게 가버리지 마. 그러니까 어, 수수께끼. 그래, 맞아! 나한텐 이제 
네가 풀 수수께끼가 있다고!'로 수정되어 있습니다.

**Comment by kaleidoscope531** [comment]
이건 닫지 않고 얘기를 해 보시는게.....
그리고 여기 검색 시스템이 이상해서 어절 단위로 검색해야 검색결과가 나옵니다. 
예를 들어 수수께끼 40번 이 있는지 검색하고 싶으실 때
40 으로 검색하면 안 나오고 40번 으로 검색해야 나오는 식?
