### ISSUE TITLE
챕터 1 : 허, 이 짠 고기들과 시들한 야채는 아멜리아의 요리에 비하면 아무것도 아니야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#866]
![screenshot_2016-07-09-08-09-41](https://cloud.githubusercontent.com/assets/19295794/16704244/d049a090-45af-11e6-8801-40187626ea83.png)

북미판에서 아멜리아의 이름이 어떻게 나오는지는 모르겠지만,
정발판에서는 '아멜리에' 라고 표현한 바 있습니다.

![_125](https://cloud.githubusercontent.com/assets/19295794/16704246/e523d2c4-45af-11e6-8651-31e9c099e3d3.png)

**Comment by vbn2523** [comment]
그러고보니 챕터 1이 아니라 프롤로그인데 잘못 썼네요 ;_; 죄송합니다

**Comment by STRIKE-F** [comment]
인명을 바꾸는 문제는 조만간 토의해서 결과를 알려드릴게요.
그건 그렇고 번역도 좀 바꾸고 싶은데,
"아멜리아/에라면 이런 짠 고기와 시들한 야채는 상상도 못할 텐데!"로 바꾸는 건 어떻게 생각하나요?

**Comment by STRIKE-F** [comment]
아멜리아->아멜리에로 결정되었습니다.

**Comment by vbn2523** [comment]
번역 수정하신 내용은, 제가 보기에는 수정 전, 후 모두 좋아 보이니
보기 좋으신 대로 수정하시면 좋겠습니다.

**Comment by Porowl** [comment]
다른 의견이 없으면 수정 후로 고치겠습니다.

**Comment by STRIKE-F** [comment]
수정 후로 고쳤습니다.
