### ISSUE TITLE
챕터 1 : 이웃한 테이블의 식탁보가 색이 다른것을 찾았다면...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#868]
![screenshot_2016-07-09-08-12-13](https://cloud.githubusercontent.com/assets/19295794/16704497/9e87ba58-45b2-11e6-8b24-10ceeada2a1d.png)

'다른것을' -> '다른 것을' 로 수정하는 건 어떨까요?

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
