### ISSUE TITLE
챕터 1 : 수 년 동안의 시간여행 분야에서의 연구 끝에, 마침내 노고의 결실을 나눌 수 있게 되어 기쁩니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#869]
![screenshot_2016-07-09-08-14-21](https://cloud.githubusercontent.com/assets/19295794/16704525/fdb6c4e2-45b2-11e6-9f95-7ff55069840f.png)

'나눌 수 있게 되어' 보다는 '맺을 수 있게 되어' 는 어떨까요?

**Comment by STRIKE-F** [comment]
결실을 맺다가 의미 중복이라서(결실 자체의 뜻 때문에) 나눌이 더 적절한 것으로 압니다. 
일단은 열어 둘게요.

**Comment by vbn2523** [comment]
음... 의미 중복인 건 알고 있는데... 결실을 나눈다는 표현도 조금 이상해 보여서요. 
그럼 아예 다른 표현을 찾을 수는 없을까요?

**Comment by Latteria** [comment]
처리된 파트라 종료합니다
