### ISSUE TITLE
챕터 1 : 하지만 우선, 빌 호크스 수상님께서 오늘 이 자리에 와주신 것에 기쁨을 표하지 않을 수 없습니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#870]
![screenshot_2016-07-09-08-14-36](https://cloud.githubusercontent.com/assets/19295794/16704547/4e0667e0-45b3-11e6-9238-7627039fd880.png)

'기쁨을 표하지 않을 수 없습니다'라는 느낌은 번역된 느낌도 들고 문어체 같은 느낌도 든다고 생각해요.

'기쁠 따름입니다.' 는 어떤가요?

**Comment by STRIKE-F** [comment]
괜찮네요.

**Comment by Latteria** [comment]
수용합니다. 수정되면 이슈 닫으세요
