### ISSUE TITLE
챕터 1 : 시침이 어디를 가리키고 있는 지만 안다면 나머지는 쉽게 풀린다

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#871]
![screenshot_2016-07-09-09-39-42](https://cloud.githubusercontent.com/assets/19295794/16705093/3a47b3f0-45bb-11e6-9831-1e123fe7040b.png)

제가 보기에 '있는'과 '지만' 사이가 살짝 띄어져 있는 것 같은데 아닌가요?

그리고 풀린다 뒤에 마침표가 붙는 게 좋을 것 같습니다 :)

**Comment by STRIKE-F** [comment]
있는지만은 붙어 있네요.
마침표는 붙이겠습니다.
