### ISSUE TITLE
챕터 1 : 정말 엄청나구나. 그런데 안타깝게도 작동하지는 않는 것 같구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#872]
![screenshot_2016-07-09-09-38-39](https://cloud.githubusercontent.com/assets/19295794/16705110/812711d0-45bb-11e6-97ef-3622db966cf7.png)

'~구나' 가 두 번 들어가서 어색한 것 같은데 수정하는 것은 어떨까요?

ex) 정말 엄청나구나. 그런데 안타깝게도 작동하지는 않는 것 같은데.

**Comment by STRIKE-F** [comment]
정말 엄청난걸. 그런데 안타깝게도 작동하지는 않는 것 같은데.
이건 어떨까요

**Comment by Y00N** [comment]
정말 엄청나구나. 그런데 안타깝게도 작동하지는 않나 보다.
라고 쓰는 것도 괜찮지 않을까요?

**Comment by STRIKE-F** [comment]
정말 엄청나구나. 그런데 안타깝게도 작동하지는 않나 보다.로 수정하겠습니다
