### ISSUE TITLE
챕터 1 : 선생님, 거기는 시계 가계로 가는 길이 아닌 것 같아요...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#873]
![screenshot_2016-07-09-09-24-23](https://cloud.githubusercontent.com/assets/19295794/16705130/efdb3926-45bb-11e6-8005-5d4340bd0a3f.png)

가계 -> 가게로 수정하는 게 좋지 않을까요? :)

**Comment by STRIKE-F** [comment]
수정했습니다.
