### ISSUE TITLE
챕터 1 : 일을 다 끝내고 나면 오후 3시30분이니 집으로 가는 버스를 탈 수 있는 건 그때부터이다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#874]
![screenshot_2016-07-09-09-21-58](https://cloud.githubusercontent.com/assets/19295794/16705142/4480a48e-45bc-11e6-8243-9a8f4a589ff0.png)

윗부분에서는 12:30분, 1:30분 등의 표현을 사용하고 있는데요,
밑에서는 3시30분이라고 쓰여 있습니다.

둘 중 하나로 통일하면 좋을 것 같은데 개인적으로는 12:30 다음에 '분'을 붙이는 게 약간 이상하기도 하다고 생각해요.
12시 30분, 1시 30분으로 사용하는 것은 어떨까요?
그리고 3시30분은 3시 30분으로 띄워주는 것이 좋을 것 같습니다.

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
