### ISSUE TITLE
챕터 1 : 런던의 하늘과 구름은 말할 필요도 없이 아름답지!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#875]
![screenshot_2016-07-09-08-43-45](https://cloud.githubusercontent.com/assets/19295794/16705385/571ecb00-45c3-11e6-8e36-1fdeeddeebb3.png)

구름은 하늘에 있는 것이니, '런던의 하늘은 말할 필요도 없이 아름답지!' 로 표현해도 좋지 않을까요?

하늘과 구름을 따로 떼서 보는 것이 조금 어색하다고 생각합니다.

**Comment by STRIKE-F** [comment]
괜찮아 보입니다. 다만 원문에도 하늘과 구름이라 해서 함부로 바꿔도 될지 좀 고민되네요

**Comment by vbn2523** [comment]
원문이 그렇다면 수정하기가 좀 그렇긴 하네요...

**Comment by Porowl** [comment]
The London skyline is
simply magnificent!
이거 같은데요?

**Comment by jungin019** [comment]
이거 찬님 말씀대로 원문이 위와 같은데 skyline이라는 단어가 도시의 건물들의 테두리를 뜻하는 것이라 
우리나라 말로 번역하기 애매했습니다. 
초기에 '런던의 하늘과 구름은 말할 필요도 없이 아름답지!'로 번역이 되어 있었는데 
현재는 '런던 시가지의 풍경은 말할 필요도 없이 아름답지!'로 되어 있습니다.

**Comment by STRIKE-F** [comment]
난 뭘 본 거지...
일단 이슈는 닫겠습니다
