### ISSUE TITLE
챕터 1 : 이봐, 거기 궁금이들!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#876]
![screenshot_2016-07-09-08-40-17](https://cloud.githubusercontent.com/assets/19295794/16705393/a74c557a-45c3-11e6-80ad-0b48b44839b2.png)

'궁금이들' 이라는 표현을 어떠한 의도로 사용하신 것인지 궁금합니다.

'젊은이들'이, 노인분께서 레이튼과 루크를 부를 때 사용하기 조금 더 적합한 표현이 아닌가요?

**Comment by STRIKE-F** [comment]
이게 원문이 Bright eyes인데, 우리 기준에선 뜻이 좀 애매하기도 하고 마땅히 좋은 번역이 안 떠올라서 일단은 궁금이라고 했거든요.
괜찮은 게 있을지..

**Comment by Y00N** [comment]
똑순이들?

**Comment by vbn2523** [comment]
이후에 플로렌스에게 말을 다시 걸 때는 똑똑이들이라고 표현합니다.

**Comment by STRIKE-F** [comment]
똘똘이... 는 어감이 좀 묘한데 ㅁㄴㅇㄹ

**Comment by Porowl** [comment]
똑똑이로 통일하는 쪽이 어떨지

**Comment by STRIKE-F** [comment]
근데 이 장면은 할머니가 일행을 처음 만나는 순간인데 대뜸 똑똑이라 하면 어색하지 않나요?

**Comment by Porowl** [comment]
그렇다면 궁금이를 내버려두는게 어떨까요.
이 게임을 하나의 문학작품으로 둘때
궁금이가 무슨 뜻이던 간에 그 의미를 해석하는(읽는)재미가 있지 않을까 싶은데

**Comment by Porowl** [comment]
젊은이 라고 하면 너무 재미가 없어요.
