### ISSUE TITLE
프롤로그 : 우리는 이 편지가 우리를 믿지 못할 상황에 빠지게 할 것 이란걸 알지 못했죠...

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#877]
![screenshot_2016-07-09-08-23-15](https://cloud.githubusercontent.com/assets/19295794/16705412/2d234b0e-45c4-11e6-8ba8-f5c3f6605a1d.png)

것 이란걸 -> 것이란걸 로 수정하는 것이 좋을 것 같습니다.

그리고 제 생각으로는 '믿지 못할 상황' 이라는 표현이 약간 어색하다고 생각하는데

다른 분들은 어떻게 생각하시는지 궁금합니다.

**Comment by Y00N** [comment]
상황에 빠지게 할 것이란걸 이란 말이 이렇게 보니 참 이상하네요
상황에 빠트릴 거라곤
상황에 처하게 하리라곤
정도가 좋지 않을까요?

**Comment by STRIKE-F** [comment]
"상황에 빠트릴 거라곤" 괜찮아 보입니다.
믿지 못할 상황은 믿기 힘든이나 믿기지 않는 정도로 고칠 수 있겠네요

**Comment by STRIKE-F** [comment]
우리는 이 편지가 우리를 믿기 힘든 상황에 
빠트릴 거라곤 전혀 알지 못했죠...

일단 이러면 될 거 같긴 한데, 반영은 좀 늦어질 수도 있겠습니다. 그래픽+더빙이라...
