### ISSUE TITLE
프롤로그 : 과학의 역사에 길이 남을 이 자리에 와주셔서 감사합니다..

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#878]
![screenshot_2016-07-09-08-14-00](https://cloud.githubusercontent.com/assets/19295794/16705424/7f628f06-45c4-11e6-985f-429420f5c68c.png)

뒤의 ..은 말줄임표를 의도한 것인가요?

말줄임표라면 ...으로 세 개를 쓰는 것이 좋을 것이고, 아니라면 하나를 사용하는 것이 좋지 않을까 생각합니다 :)

**Comment by Porowl** [comment]
표기 오류입니다
