### ISSUE TITLE
프롤로그 : 안녕하세요 부인. 그런데 죄송하지만 저희는 시계를 사러 온 것이 아닙니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#879]
![screenshot_2016-07-09-09-36-16](https://cloud.githubusercontent.com/assets/19295794/16705742/3c0fdc2c-45ce-11e6-87dd-1cb3e26640cd.png)

'안녕하세요 부인' 말고 다른 인사말은 없을까요?

제가 멀쩡한 부분을 고치려고 하는 것일 수도 있지만 제가 보기에 레이튼의 성격과 맞는 인사말은 아니라서 생각해서...

다른 분들 의견은 어떤가요?

그리고, '그런데 죄송하지만' 이라는 표현도 이상하다고 생각합니다.

'그런데'와 '죄송하지만' 둘 중 하나만 사용해도 좋지 않을까요?

**Comment by STRIKE-F** [comment]
하하, 안녕하세요라거나?

그 밑에 건 "그런데, 저희는 시계를 사러 온 건 아닙니다." 정도로 고치면 되려나요

**Comment by Porowl** [comment]
앞엣말이 얼마만에 손님이야! 이기 때문에 죄송합니다 쪽이 맞아요.

**Comment by STRIKE-F** [comment]
그럼 "저, 죄송하지만 저희는 시계를 사러 온 건 아닙니다." 는 어떠려나요

**Comment by STRIKE-F** [comment]
이대로 수정하겠습니다.
