### ISSUE TITLE
(Minor) 루크가 벨과 부딛혔을때

### ISSUE THREAD

**Issue by Porowl** [elfinlazz/lt3translation#88]
벨이 루크를 로그(log)라고 부르잖아요,
그것보다 루트 (제곱근)이라고 부르는 것은 어떨까 싶어서요.

**Comment by Latteria** [comment]
전 로그(Rogue)인줄 알았는데.
락커(Locker)는 어떠신지

**Comment by STRIKE-F** [comment]
근데 원래 이름이 루크니까 멋대로 로그라고 부르는 게 이상해 보이지는 않는데요.
로그랑 루크랑 적어도 한국어 발음 상으로는 비슷하니까요
