### ISSUE TITLE
프롤로그 : 다른 사람이랑 착각한 것일 게다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#880]
![screenshot_2016-07-09-09-33-48](https://cloud.githubusercontent.com/assets/19295794/16705750/93ce9840-45ce-11e6-9f0a-4c99372ac16a.png)

'게다'를 풀어서(?) 이야기하면 '것이다' 가 되잖아요.

그럼 '착각한 것일 것이다' 가 되는데 약간 명사화(?)된 이상한 표현이라고 생각합니다.

'다른 사람이랑 착각했을 게다' 정도는 어떨까요?

**Comment by Porowl** [comment]
착각했을 게다
