### ISSUE TITLE
프롤로그 : 내가 다른 고민거리가 있을 때는 이런 게 기억이 잘 나지 않는단 말이지.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#881]
![screenshot_2016-07-09-09-20-38](https://cloud.githubusercontent.com/assets/19295794/16705756/e216842c-45ce-11e6-990c-85828f4d0f3b.png)

'~가' 가 두 번 들어가니 살짝 어색하기도 한 것 같습니다.

'나에게 다른 고민거리가 있을 때는' 은 어떨까요?

**Comment by STRIKE-F** [comment]
내가를 빼거나 난으로 줄이는 건 어떨까요?

**Comment by vbn2523** [comment]
저한테는 내가를 빼는 쪽이 좋아 보입니다.
