### ISSUE TITLE
프롤로그 : 무대에 올라와 저와 함께해주십시오, 수상님.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#882]
![screenshot_2016-07-09-08-14-56](https://cloud.githubusercontent.com/assets/19295794/16705766/75143dc8-45cf-11e6-8111-5b948166613e.png)

물론 쓰인 의미는 살짝 다르지만 '~와' 가 두 번 쓰이니 살짝 어색해 보이기도 한다고 생각합니다.

'무대에 올라오셔서 저와 함께해주십시오, 수상님.' 정도는 어떨까요?

그리고, 뒷부분의 '부끄러워하실' 이라는 표현도 살짝 어색하다고 생각합니다.

북미판에서 'shy'라는 표현을 사용하고 있으니 '부끄러워하실' 이 맞긴 하지만, 

일단 첫 번째로 스탄건의 성격 상 '부끄러워하실' 이라는 표현을 사용할 것 같지 않고,

두 번째로 빌 호크스는 영국의 수상, 즉 언론에서도 자주 나타나는 대상이므로

부끄러움을 탈 인물은 아닌 것 같은데 다른 사람들이 그의 부끄러움을 걱정할 필요가 없다고 해야 하나...

좀 설명이 이상하네요. 어떻게 생각하시나요?

**Comment by Porowl** [comment]
Don't be shy..... 되게 많이 쓰이는 표현이긴 한데

**Comment by STRIKE-F** [comment]
첫 번째 건은 저도 찬성합니다.
두 번째 건은 걱정하시지 않아도 됩니다 정도로 바꾸는 건 어떨까요?

**Comment by vbn2523** [comment]
좋아 보입니다.

**Comment by STRIKE-F** [comment]
텍스트는 수정했습니다.

**Comment by Latteria** [comment]
이미 완료된 파트라 수정불가.
