### ISSUE TITLE
프롤로그 : 경감님, 나쁜 것만 있는 건 아니라고요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#883]
![screenshot_2016-07-09-08-13-27](https://cloud.githubusercontent.com/assets/19295794/16705786/2c2c93c0-45d0-11e6-8d59-9750a0325cea.png)

음, 일단 '건'이라는 표현은 '것은' 이라는 표현을 줄인 것이나 마찬가지인데,

문장으로 보면 '나쁜 것만 있는 것은' 이 됩니다. '~것' 이 두 번 들어가게 되어 이상하다고 생각하는데,

'나쁜 것만은' 으로 바꾸어도 좋지 않을까요?

그리고 바튼이 체르미를 대할 때 '아니라고요'라는 말투로 말할 것 같지는 않습니다.

'아닙니다' 정도는 어떤가요? 

그리고 두 번째 행의 띄어쓰기가 과도하게 크게 된 것 같다는 생각도 듭니다.

**Comment by Y00N** [comment]
경강님, 그렇게까지 나쁘지만은 않다구요.
그래도 여기엔, 쩝쩝, 기다릴 동안 즐길 음식이 있잖아요.
라는 뉘앙스는 어떨까요?

**Comment by vbn2523** [comment]
저는 좋아 보입니다.

**Comment by STRIKE-F** [comment]
저도 괜찮아 보이네요

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
