### ISSUE TITLE
프롤로그 : 저 통조림통 같이 생긴 아파트에 살지 않는다고 해서 여기가 중심가가 아니란 것은 아니란다!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#884]
![screenshot_2016-07-09-09-36-56](https://cloud.githubusercontent.com/assets/19295794/16705808/c29885e4-45d0-11e6-93ed-66ee0416196f.png)

'통조림통' 말고 아파트를 비유할 만한 다른 대상은 없을까요?

그리고 통조림통이라는 표현을 사용한다면 '통조림'과 '통' 사이를 띄워서

'통조림 통' 이 맞지 않을까요?

**Comment by STRIKE-F** [comment]
이중 부정은 보기에 좀 부자연스러우니 그것도 고치자면
"저런 깡통같은 아파트에 살아야만 중심가니!"는 어떨까요

**Comment by Porowl** [comment]
거기에 찬성
