### ISSUE TITLE
프롤로그 : 루크, 이런 혼란스러운 때에도 한결같은 너의 모습은 나를 참 편안하게 해준단다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#885]
![screenshot_2016-07-09-08-07-38](https://cloud.githubusercontent.com/assets/19295794/16705816/298ea1c0-45d1-11e6-998f-92ff20c39699.png)

제 개인적인 의견으로는 번역된 느낌도 많이 들고 문어체 같기도 하다고 생각해요.

다른 표현은 없을까요? 다른 분들은 어떻게 생각하시나요?

**Comment by Latteria** [comment]
Your constancy can be quite a comfort in these uncertain times, my boy.

どうやら, 私は未来でも君に頼られているようだね

예전에 모두 참고해서 제대로 해석하려 노력했는데 적당한 말이 안 보입니다

**Comment by STRIKE-F** [comment]
루크, 미래는 한 치 앞도 알 수 없단다.
그래서 미래에도 한결같은 네 모습이
정말 큰 위안이 되는구나.

이건 어떨지요.
