### ISSUE TITLE
프롤로그 : 근데, 원래 문제로 돌아와서, 어떻게 이 편지가 진짜라는 것을 알 수 있을까요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#886]
![screenshot_2016-07-09-08-07-52](https://cloud.githubusercontent.com/assets/19295794/16705828/73280b1e-45d1-11e6-944a-355b2d43f0cd.png)

저만 그렇게 느낀 것일지도 모르지만, 문장 사이에 쉼표가 두 번 들어가면...

ㅠ 학교에서 배우는 삽입구문 같은 느낌을 주는데...

그리고 문어체 같은 느낌도 주는 것 같아요.

다른 표현은 없을까요?

**Comment by STRIKE-F** [comment]
진짜라는 것을->진짜인지로 고치는 게 좋아 보이네요
근데, 원래 문제로 돌아와서, 이거는 그건 그렇고,로 바꾸는 건 어떨까요?
