### ISSUE TITLE
프롤로그 : 그래도, 만약 사실이라면, 그게 과학계에 불러올 파장이 상상이 가니?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#887]
![screenshot_2016-07-09-08-10-25](https://cloud.githubusercontent.com/assets/19295794/16705850/04ed469a-45d2-11e6-9413-fd9ab3a9e7a8.png)

다른 이슈에서 말씀드린 것과 같은 이유로 쉼표 두 번은 약간 이상하게 보이기도 한다고 생각합니다.

**Comment by Porowl** [comment]
그래도 만약 그게 사실이라면, 그게 과학계에
불러올 파장이 상상이 가니?

**Comment by vbn2523** [comment]
좋습니다. 다만 개행을 조금 수정해서
그래도 만약 그게 사실이라면,
그게 과학계에 불러올 파장이
상상이 가니? 는 어떨까요?
다시 보니 '그게'라는 표현도 반복됩니다.

**Comment by STRIKE-F** [comment]
그래도 타임머신이 진짜라면 그게 과학계에 불러올 파장이 상상이 가니? 는 어떨까요

**Comment by Latteria** [comment]
좀 더 논의해보고 닫겠습니다
