### ISSUE TITLE
프롤로그 : 표정을 보니 뭔가 쓸모있는 이야기를 듣고 싶어하는 것 같구나!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#888]
![screenshot_2016-07-09-08-40-24](https://cloud.githubusercontent.com/assets/19295794/16705858/55f45812-45d2-11e6-9171-1ef5fbed2bb3.png)

'쓸모있는 이야기' 라는 표현이 살짝 이상하지 않나요?

'유용한 정보'는 어떤가요?

**Comment by Y00N** [comment]
아예 이야기를 틀어서
표정을 보아하니 뭔가 유용한 이야기를 해줘야겠구나! 라는 것은 어떨까요?

**Comment by Porowl** [comment]
I can tell from the looks on your
faces that you're hankering to
hear something useful!

너네들 뭔가 유용한 정보를 찾고 있는 듯하구나. 얼굴에 다 써있어

**Comment by STRIKE-F** [comment]
너희들 뭔가 유용한 정보를 찾고 있는 게지? 얼굴에 다 쓰여 있어.
이거로 수정하겠습니다.
