### ISSUE TITLE
프롤로그 : 어떻게 된 건지 모르겠지만 편지 하나가 시간을 여행해 전달되었어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#889]
![screenshot_2016-07-09-08-23-10](https://cloud.githubusercontent.com/assets/19295794/16705864/8c018754-45d2-11e6-8067-8ae3298b81c2.png)

문장이 조금 이상하다고 생각하는데 어떻게 수정해야 할지 모르겠어요.

다른 분들은 어떻게 생각하시나요?

**Comment by Y00N** [comment]
어떻게 된 건지는 모르겠지만 편지 한 통이 시간을 거슬러 배달되었어요.
어떻습니까

**Comment by STRIKE-F** [comment]
좋아 보입니다.

**Comment by Latteria** [comment]
저는 지금도 충분히 듣기에 좋아보입니다만
