### ISSUE TITLE
수수께끼 5 - 힌트 2 : 세계에는 아날로그 시계나 전자 시계만 있는것이 아니다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#890]
![screenshot_2016-07-09-12-45-55](https://cloud.githubusercontent.com/assets/19295794/16706310/75b3fab2-45e2-11e6-9e50-b2791385bcab.png)

있는것이 는 띄워서 있는 것이 라고 적는 것이 좋을 것 같습니다 :)

그리고 하나 덧붙이자면 4행은 3행에 붙이는 것이 좋지 않을까요?

**Comment by Porowl** [comment]
띄어쓰기는 이미 수정되어있습니다.
4행은 3행에 붙였어요
