### ISSUE TITLE
수수께끼 5 - 힌트 3 : 이 시계는 시각대신 얼마나 많은 시간이 지났는지를 알려준다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#891]
![screenshot_2016-07-09-12-46-03](https://cloud.githubusercontent.com/assets/19295794/16706322/ef814584-45e2-11e6-92ae-096bca7fe36b.png)

시각대신 -> 시각 대신 으로 띄워 주면 좋을 것 같습니다 :)

**Comment by Porowl** [comment]
이미 수정됨
