### ISSUE TITLE
수수께끼 6 - 문제 / 힌트 3

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#893]
![screenshot_2016-07-09-12-46-43](https://cloud.githubusercontent.com/assets/19295794/16706340/79af53ae-45e3-11e6-8e01-56b5e0dde0dd.png)

문제 부분에서 '바늘들과 실을 보는것이 너무 어려워' 가 있는데

보는것이 -> 보는 것이 로 띄워주는 것도 좋을 것 같습니다.

그리고 힌트 3에서는 3행을 2행 뒤에 붙이는 것은 어떤가요?

**Comment by Porowl** [comment]
수정완료
