### ISSUE TITLE
수수께끼 8 - 풀이 : 오전인지 오후인지는 알 수 없지만 그거야 창 밖을 보면 되니까..

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#895]
![screenshot_2016-07-09-12-45-22](https://cloud.githubusercontent.com/assets/19295794/16706355/0e6ce61e-45e4-11e6-84a6-612343143f74.png)

다른 이슈에서 한 번 말씀드렸듯 말줄임표라면 . 세 번 사용, 마침표라면 한 번 사용하는 것이 좋을 것 같습니다.

**Comment by Porowl** [comment]
오타
