### ISSUE TITLE
프롤로그 : 저는 한 장소에 이렇게나 다양한 시계들이 있는 걸 본 적이 없어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#896]
![screenshot_2016-07-09-12-44-27](https://cloud.githubusercontent.com/assets/19295794/16706362/47159556-45e4-11e6-827e-7cebdce9e0f5.png)

약간 문장에 사족이 있다 라는 느낌을 받았는데요,

'한 장소에' 라는 표현은 빼도 좋지 않나요? 다른 분들은 어떻게 생각하시나요?

**Comment by Y00N** [comment]
와, 이렇게 많은 시계는 태어나서 처음 봐요!
이런 뉘앙스는 어떨까요?

**Comment by Porowl** [comment]
I've never seen such a wide variety
of clocks in one place.

이렇게나 많은 시계가 모여 있다니! 라는 뉘앙스인것 같아요

**Comment by STRIKE-F** [comment]
이렇게 많은 시계가 모인 모습은 태어나서 처음 봐요.
이 정도가 어떠련지

**Comment by STRIKE-F** [comment]
이렇게 많은 시계가 모인 모습은 태어나서 처음 봐요.
이거로 수정할게요.
