### ISSUE TITLE
이만큼 말했으니, 더이상 화를 내 봤자 의미도 없을 것 같네요.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#897]
![kakaotalk_20160710_162106375](https://cloud.githubusercontent.com/assets/19270364/16712231/ec5a7f86-46bb-11e6-9c28-3ca6c2d6ede6.jpg)

이만큼 말했으니, 더 이상 화를 내봤자 의미도 없겠네요.
라고 다듬어보는 게 어떨까요?

**Comment by Porowl** [comment]
What's done is done, so I guess
there's no point in my stewing
over it.

어차피 지나간 일이니까요. 라는 식인데... 왜 이렇게 됐을까.

아니면 그렇게까지 말씀하시니 식도 좋고... 우선 열어둘게요

**Comment by STRIKE-F** [comment]
저거 왠지 내가 번역한 듯한데 ㅇㅅㅇ;;

어차피 지나간 일이고, 더이상 화를 내봤자 의미도 없겠네요.
합치면 이 정도려나요

**Comment by Porowl** [comment]
다른 의견이 나오지 않으면 닫겠습니다.

**Comment by jungin019** [comment]
어차피(이미) 지나간 일이니 더이상 화를 내봤자 의미도 없겠네요 괜찮을 것 같습니다

**Comment by Porowl** [comment]
다듬어서 

이미 지나간 일이니 더는 화를 내봤자
의미도 없겠네요 
로 고치겠습니다.
