### ISSUE TITLE
이 자료들은 언제 만들어진 건가요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#898]
![kakaotalk_20160710_162121361](https://cloud.githubusercontent.com/assets/19270364/16712263/c8d25240-46bc-11e6-8d17-10e1c173eb28.jpg)
 
이게 다 언제적 자료예요?
정도가 더 자연스럽지 않을까 생각해봤습니다.

**Comment by Porowl** [comment]
이게 다 언제적 자료예요? 찬성

**Comment by STRIKE-F** [comment]
저도 찬성합니다
