### ISSUE TITLE
아, 잘 아시다시피 그 발표회때 사고가 좀 있었잖습니까.

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#899]
![kakaotalk_20160710_164149313](https://cloud.githubusercontent.com/assets/19270364/16712279/4331be5e-46bd-11e6-8bb7-26d3006ce670.jpg)

아, 잘 아시다시피 그 발표회 때 사고가 좀 있었잖습니까?
아, 잘 아시다시피 발표회에서 사고가 좀 있었잖습니까?
라고 하는게 어떨까요?

**Comment by STRIKE-F** [comment]
아, 잘 아시다시피 발표회에서 사고가 좀 있었잖습니까?
이거로 수정할게요.
