### ISSUE TITLE
혹시라도 교수님을 만나게 되면 보여드리려고 생각해 둔 수수께끼가 하나 있는데, 한 번 보실레요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#900]
![kakaotalk_20160710_162141071](https://cloud.githubusercontent.com/assets/19270364/16712284/a0e91e34-46bd-11e6-9761-5523887d8057.jpg)

보실레요? -> 보실래요? 혹은 보시겠어요? 라고 고치길 권합니당...

**Comment by Porowl** [comment]
보시겠어요
