### ISSUE TITLE
또 보는구려, 똑똑이들! 너희들의 힘으로 빛나는 멋진 힌트 코인을 찾는 데에는 성공했니? ~~ 여기 있는 이 분은 선생님께 완전히 반해버린 것 같은데요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#901]
![128351283](https://cloud.githubusercontent.com/assets/19270364/16712792/d6ba41f0-46cc-11e6-8d86-8d6dd803b005.jpg)

플로렌스 : 
또 보는구려, 똑똑이들! 너희들의 힘으로 빛나는 멋진 힌트코인을 찾는 데에는 성공했니?
-> 또 보는구려, 똑똑이들! 너희 스스로 힌트코인을 찾아내 봤니?

레이튼 : 
네, 전문가의 설명 덕분이죠.
-> 네, 전문가께서 도와주신 덕분이죠.

플로렌스 : 
도움이 되었다니 정말 다행이네. 그렇지만 감사 인사는 아직 못 들은 것 같은데...
-> 도움이 되었다니 정말 다행이네. 그렇지만 감사하단 말은 아직 못 들었다만...

레이튼 : 
물론입니다. 감사를 깜박하고 드리지 못한 점 사과드리겠습니다. 도와주셔서 정말 감사합니다.
-> 예, 미처 감사하다고 말씀드리지 않은 점 사과드리겠습니다. 도와주셔서 정말 감사합니다.

루크 : 
맞아요 고마워요.당신처럼 지헤롭고 나이 드신 여자분의 도움이 없었다면 절대 찾아낼 수 없었을 거에요!
-> 맞아요. 고맙습니다. 깊은 연륜에서 우러난  조언이 아니었으면 분명히 모르고 지나쳤을 거예요!

플로렌스 : 
자, 거기서 잠깐... 방금 뭐라고 했니? 누가 나이가 들은 여자라고?
-> 자, 거기서 잠깐... 방금 뭐라고 했니? 깊은 연륜...? 그거 나 말하는 거니?

사람들이 날 허울로만 완벽녀 플로렌스라고 부르는게 아니라우! 나도 여느 십대들처럼 빠릿빠릿허이!
-> 사람들이 괜히 날 "완벽녀 플로렌스"라고 부르는 게 아니라우! 나도 청춘 못지않네!

루크 : 
죄송해요, 플로렌스 씨! 노인이라고 할 생각은 아니었어요!
-> 죄송해요, 플로렌스 씨! 늙은이 취급을 하려던 건 아니었어요!

저도 몇몇 연세 있으신 분들이 나이에 얼마나 민감한지 알아요.
-> 연로하신 분께서는 나이에 민감할 수 있다는 걸 잠깐 잊어버렸어요.

플로렌스 : 
노...노인?! 연세 있으신?! 네가 아직 정신을 못 차렸구나!
-> 느... 늙은이?! 연로하신 분?! 네가 아직 정신을 못 차렸구나!

조금 구닥다리식이긴 하지만 뭔가 가르쳐 주려니 수수께끼밖에 생각이 안 나는군!
-> 조금 옛날 방법이긴 하지만, 수수께끼로 본때를 보여줘야겠구만!

늙은이라고 불러서 죄송스런 생각이 좀 든다면, 내 수수께끼 좀 풀어봐!
-> 늙은이라고 불러서 죄송스런 생각이 든다면, 어디 이걸 풀어보시게!

크흠. 너희둘 정말 수수께끼를 풀 땐 참 똑똑하구나. 내가 그걸 주도록 하마.
-> 너희 둘, 그래도 수수께끼는 똑소리 나게 푸는구나. 내가 그걸 주마.

레이튼 : 
칭찬은 더욱이 아름다운 숙녀에게서 오는 것이랍니다. 플로렌스 양 당신처럼요.
-> 감사합니다. 플로렌스 양의 아름다운 모습만큼 따뜻한 마음씨가 느껴지는 칭찬이로군요.
이 부분은 과하게 틀어버렸습니다만... 까닭은 칭찬은 아룸다운 숙녀가 하는 거라는 말 자체도 좀 불편해서 그랬습니다. 제 개인적인 견해가 다분히 들어가있으므로 안 내키실 수도 있겠네요.

어디선가 또 다시 만났으면 좋겠군요.
-> 나중에 또 다시 뵈었으면 좋겠습니다. 
이건.. 사실 안 바꿀 수도 있는 건데, 개인적으로 제가 연장자에게 사용하는 용어를 사용해봤습니다.

플로렌스 : 
흐흥! 이제 좀 날 낯뜨겁게 만드시는구려!
-> 흐흥! 이제야 좀 마음에 드는 말씀을 하시는구려!
-> 흐흥! 이제야 날 좀 추켜세워 주시는구려!

달달한 말투로 말걸어도 좋아요, 하지만 난 독신이 아니란 걸 알아두라우.
-> 이런 달달한 말은 언제나 환영이에요. 다만 내가 독신이 아니란 건 잊지 마시우.
"난 독신이 아니란 걸 알아두라우."라는 말의 맥락을 잘 모르겠습니다. 유부녀니까 선을 지켜달라? 그런데 그렇다고 하기엔 그 이후로 꽤나 호의적이란 말이죠.

루크 : 
여기 있는 이 분은 선생님에게 완전히 반해버린 것 같은데요...
-> 플로렌스 씨께서 선생님께 완전히 빠지셨나 본데요...
-> 플로렌스 씨께서는 선생님이 대단히 마음에 드시나 봐요
'여기 있는 이 분은'이란 말을 바꾸고 싶었는데 하다보니 뒤에도 손을 좀 대봤네요.

**Comment by STRIKE-F** [comment]
의견이 하나도 없어서... 제 임의로 마저 수정해서 반영하겠습니다.
