### ISSUE TITLE
잠깐 시간 되시나요?

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#902]
![kakaotalk_20160710_162149322](https://cloud.githubusercontent.com/assets/19270364/16713281/5a1e68c2-46dd-11e6-81d6-a4a7d2be95e8.jpg)

시간은 되고 안 되고 할 수가 없죠.... (ex : 좋은 시간 되세요!)

잠깐 시간을 내어주실 수 있으실까요?  정도가 좋다고 생각합니다.

**Comment by Porowl** [comment]
잠깐 괜찮을까요?

**Comment by STRIKE-F** [comment]
잠깐 괜찮을까요? 좋아 보입니다

**Comment by Porowl** [comment]
잠깐 괜찮을까요?
