### ISSUE TITLE
챕터 1 : 이 주변의 공기는 꽤나 침체되었구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#903]
![screenshot_2016-07-12-16-37-06](https://cloud.githubusercontent.com/assets/19295794/16771778/be70bbc6-488c-11e6-8891-904b8ca257f0.png)

어떤 의미로 한 말인지는 잘 알겠지만, 조금 번역체 같다라는 느낌이 들지 않나요?

조금 수정할 수는 없을까요?

**Comment by Porowl** [comment]
이 주변은 공기가 
탁하구나. 

라고 수정되어있습니다.
