### ISSUE TITLE
흠? 어떻게 도와줄까? 흐으으으음?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#906]
![screenshot_2016-07-12-16-38-36](https://cloud.githubusercontent.com/assets/19295794/16772259/85be50b6-488e-11e6-9da1-c6dbd8302a4f.png)

공간은 충분해 보이는데, 1행에 모두 붙여 쓰는 것이 어떤가요?

보기에 안 좋을까요? 다른 분들은 어떻게 생각하시나요?

**Comment by Porowl** [comment]
흠? 무슨 일 있니? <W>흐으으으음?
