### ISSUE TITLE
1번 그림책을 위한 "자두 나무" 스티커를 얻었습니다!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#908]
![screenshot_2016-07-12-16-40-02](https://cloud.githubusercontent.com/assets/19295794/16772517/8ba9abd2-488f-11e6-8c90-073527f2089c.png)

'자두나무'로 붙여 써야 하는 것으로 알고 있습니다.

**Comment by Porowl** [comment]
수정완료
