### ISSUE TITLE
그러니까 우린 가게에서 다른 길로 나간 것일 수도 있어요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#909]
![screenshot_2016-07-12-16-41-34](https://cloud.githubusercontent.com/assets/19295794/16772594/c9afa594-488f-11e6-9edf-1418f82d9f74.png)

'길로' 까지는 1행에 붙여 쓰는 것도 좋지 않을까요?

그리고 '나간 것일 수도 있어요.' 에서는 약간 번역체 같다고 생각해요.

조금 더 자연스럽게 수정할 수는 없을까요? 

ex) 나간 걸지도 몰라요.

**Comment by Porowl** [comment]
So we're probably taking a
different route away from the
shop.

들어오는 길이랑 나가는 길이랑 다르다는 의미인데. 열어놀게요

**Comment by STRIKE-F** [comment]
나갔을지도 몰라요. 는 어떨까요

**Comment by Porowl** [comment]
다른 의견이 없으면 닫겠습니다.

**Comment by jungin019** [comment]
아니면 그냥 '가게에 들어갈 때와는 다른 길로 나왔을지도 몰라요'도 괜찮지 않을까요

**Comment by Porowl** [comment]
조금 다듬어서

가게로 들어갈 때랑 다른 길로 나왔을지도 몰라요. 정도로?

**Comment by STRIKE-F** [comment]
가게로 들어갈 때랑 다른 길로 나왔을지도 몰라요.
이거로 수정하겠습니다.
