### ISSUE TITLE
수수께끼 설명문에 있는 - 관련

### ISSUE THREAD

**Issue by Porowl** [elfinlazz/lt3translation#91]
단서를 줄때 보통 단서들을
- 로 구분하곤 했었는데
(예)
- 단서 1은 이러한 것들을 얘기하고 있다.
- 단서 2는 거짓말을 하고 있다.

누가 replace all 기능을 써버려서 이런 것들도 다 사라졌네요.
언제 날 잡아 확인해야겠습니다.

**Comment by elfinlazz** [comment]
이거 수정되었나요? 확인좀해주세요.

**Comment by itstake** [comment]
수정되어 있습니다.
