### ISSUE TITLE
그런데, 그렇다면 어떻게 여기가 이렇게나 바뀐 걸까요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#910]
![screenshot_2016-07-12-16-41-45](https://cloud.githubusercontent.com/assets/19295794/16772672/23c6e998-4890-11e6-84d8-df8d8383a4c9.png)

'그런데'와 '그렇다면' 둘 중 하나는 빼도 좋다고 생각해요.

그리고 1행에서도

선생님 말씀이 맞는 '것' 같네요 로 수정하는 것도 좋지 않을까요?

**Comment by Porowl** [comment]
선생님 말씀이 맞는 것 같네요. 
그렇지만 그게 아니라면 무슨 수로 
이 상황을 설명할까요?

어색해서 바꿔봤는데...
