### ISSUE TITLE
주변을 둘러보다 보면 몰랐던 걸 알게 될지도 몰라.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#911]
![screenshot_2016-07-12-16-41-54](https://cloud.githubusercontent.com/assets/19295794/16772914/dbed0bb0-4890-11e6-9a33-ef421bf25ede.png)

'둘러보다 보면' 이라는 표현은 '둘러보면' 으로 고쳐도 좋지 않을까 싶은데 어떻게 생각하시나요?

그리고 '걸' 까지는 1행에 붙여 써도 좋다고 생각합니다.

**Comment by jungin019** [comment]
개행 수정

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
