### ISSUE TITLE
사람들이 전부 선생님에게 지나친 반응을 보이는 것 같지 않으세요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#912]
![screenshot_2016-07-12-18-21-51](https://cloud.githubusercontent.com/assets/19295794/16772978/1dd56626-4891-11e6-9a92-5ef0e97346f9.png)

'지나친' 이라는 표현은, 마을 사람들이 레이튼을 괴롭힌다? 라는 느낌을 주는 것 같기도 하거든요.

다른 표현은 없을까요?

그리고 '반응을' 까지는 1행에 붙여 써도 좋다고 생각합니다.

그리고 '선생님에게'는 '선생님께' 로 수정하는 건 어떤가요?

**Comment by jungin019** [comment]
께, 개행 수정

**Comment by STRIKE-F** [comment]
사람들이 전부 선생님께 이상하게 반응하는 것 같지 않으세요? 는 어떨까요
반응을 보이다도 좀 영어식 표현 같아서요

**Comment by Porowl** [comment]
^ 괜찮아 보입니다.

**Comment by STRIKE-F** [comment]
사람들이 전부 선생님께 이상하게 반응하는 것 같지 않으세요? 
이거로 수정하겠습니다.
