### ISSUE TITLE
심지어 떨어져 있는 꽃 주변에는 벌레까지 꼬였어요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#913]
![screenshot_2016-07-12-18-22-57](https://cloud.githubusercontent.com/assets/19295794/16773093/9021d016-4891-11e6-8b37-c99d56bf0a9b.png)

본문에서 '떨어져 있는' 꽃이라고 표현했지만, 실제로 꽃이 어디 떨어졌거나 한 건 보이지 않았는데,

표현을 수정하는 것은 어떤가요?

ex) 축 늘어져 있는 꽃

**Comment by Y00N** [comment]
심지어 이 근처엔 벌레도 꼬여 있어요! 라는 건 어떨까요?

**Comment by jungin019** [comment]
원문이 droopy라서 축 늘어진 꽃이 맞습니다. 오역이네요

**Comment by STRIKE-F** [comment]
여긴 엉망진창인데요! 심지어 축 늘어진 꽃 주변에는 벌레도 잔뜩 있어요!
이 정도면 괜찮으려나요

**Comment by Porowl** [comment]
SF님의 글을 결론으로, 다른 의견 없으면 닫겠습니다.

**Comment by STRIKE-F** [comment]
이대로 수정하겠습니다.
