### ISSUE TITLE
아무래도 수수께끼를 돌보는 일에 슬슬 은퇴를 선언해야 할 거 같구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#915]
![screenshot_2016-07-12-18-24-10](https://cloud.githubusercontent.com/assets/19295794/16785773/d4b968fe-48ca-11e6-9957-179b8b9affef.png)

'할 '것' 같구나로 수정하는 것이 조금 더 보기 좋다고 생각합니다.

그리고 문장 전체적으로 번역체스러운 느낌이 많이 나는데, 조금 더 자연스럽게 수정할 수는 없을까요?

**Comment by Y00N** [comment]
아무래도 수수께끼에서는 이제 손을 털고 은퇴해야겠구나. 라는 건 어떨까요?

**Comment by vbn2523** [comment]
'손을 털다'와 '은퇴'중 하나만 사용하는 건 어떨까요?

**Comment by STRIKE-F** [comment]
슬슬 수수께끼를 돌보는 일도 그만둬야겠어.
이건 어떤가요

**Comment by Porowl** [comment]
손을 털다는 약간 손을 씻다와 비슷한 느낌이 듭니다.

슬슬 은퇴할 때도 됐지 않았니 정도는 어떨까요.

**Comment by STRIKE-F** [comment]
솔직히 나 정도면 은퇴할 때도 되지 않았니?
이거로 수정할게요.
