### ISSUE TITLE
거기 높은 모자 쓴 당신말요 당신이 설마 레이튼 교수는 아니겠죠?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#917]
![screenshot_2016-07-12-18-26-42](https://cloud.githubusercontent.com/assets/19295794/16785940/eb2f093a-48cb-11e6-8ae2-b8e4f780cd4b.png)

일단 '당신말요' 끝에 마침표를 하나 붙여 주는 것이 좋을 것 같구요.

뭔가 쉬플리가 레이튼에게 하는 말인데 조금 거만한 느낌도 드네요.

조금 수정할 수는 없을까요?

**Comment by jungin019** [comment]
마침표 수정.

**Comment by STRIKE-F** [comment]
거기 높은 모자 쓰신 분!
이건 좀 이상한데... 마땅히 떠오르는 게 없네요

**Comment by Porowl** [comment]
거만한 느낌이 드나요?
약간 무례하게 대하는것은 맞지만 아직 정체를 확신할 수 없을 때니 괜찮은 듯 하기도

**Comment by STRIKE-F** [comment]
그냥 수정하지 않을게요. 영 틀린 거 같지는 않고 고칠 것도 마땅히 안 떠올라서...ㅇㅅㅇ;;
