### ISSUE TITLE
조사 메모 - 버려진 버스 정류장

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#920]
![screenshot_2016-07-12-18-29-19](https://cloud.githubusercontent.com/assets/19295794/16786046/ebb0bc54-48cc-11e6-8b90-03875423a93a.png)

첫 번째로, 작중 루크가 '몇 시간 전만 해도' 라는 표현을 사용한 바 있습니다.

그에 따라 조사 메모에서도 '몇 분 전과도' 보다 '몇 시간 전과도' 라는 표현을 사용하는 것은 어떨까요?

그리고 두 번째로 '이곳이 어디든지 간에,' 라는 표현이

번역체스럽다고 생각합니다. 조금 더 자연스럽게 수정할 수는 없을까요?

**Comment by Porowl** [comment]
우선 몇 시간 전만 해도 - 몇 분 전과도 이건 영판에도 이렇게되어 있습니다.
아마 레이튼과 루크의 생각 차이를 드러내는 대목이 아닐까... 싶기도 한데
아마 제작자들이 놓친 부분일 수도 있구요.

이 추측이 맞다면, 루크의 말을 '조금 전만 해도' 로 고치는게 어떨까 싶네요.

이곳이 어디든지 간에는 통삭제하거나

한 가지 확실한 점은 이 곳은 내가 알던 런던이 아니라는 것이다.

등으로 바꿔야 할듯 하네요.

**Comment by STRIKE-F** [comment]
현재는 

지나다니는 몇 사람과 이야기를
나눈 뒤 우리는 버스 정류장으로
갔지만, 그 잠시 사이에 이미
완전히 다른 장소가 되어 있었다.
한 가지 확실한 점은 
이곳은 내가 알던 런던이 아니라는 것이다.
우리가 정말로 시간 여행을 한 걸까?

이렇게 고쳤습니다.
