### ISSUE TITLE
조사 메모 - 두 번째 편지

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#921]
![screenshot_2016-07-12-18-29-24](https://cloud.githubusercontent.com/assets/19295794/16786084/3be7d342-48cd-11e6-9d32-e4a8eb20ce15.png)

'내가 스스로에게 어떻게 이런 일이 가능한지 묻고 있을 때,' 라는 표현은

번역체스러운 느낌을 많이 담고 있다고 생각합니다.

그리고 개행에서 '질문을' 까지는 '내' 뒤에 붙여 써도 좋을 것 같습니다.

또, '정보를' 까지는 '많은' 뒤에 붙여 써도 좋다고 생각합니다.

**Comment by jungin019** [comment]
현재는 문장이 바뀌어 
'믿을 수 없지만 우리가 정말로 
10년 후의 런던으로 온 것 같다. 
어떻게 이런 일이 가능한지 고민하는 
동안, 어디서 보기라도 한 듯이 
미래의 루크가 두 번째 편지를 
보내왔다. 편지를 읽어 보니, 
오클랜드 가에 있는 그린 병원에서 
더 많은 정보를 얻을 수 있을 것 같다.' 이렇게 되어 있습니다.
