### ISSUE TITLE
그림책 - 올바른 곳에 스티커를 붙여 말이 되는 이야기를 만들어 보세요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#922]
![screenshot_2016-07-12-18-29-50](https://cloud.githubusercontent.com/assets/19295794/16786151/a83ca0d6-48cd-11e6-8dd3-8215bae75464.png)

'말이 되는 이야기' 라는 표현이 조금 어색하다고 생각합니다.

조금 더 재미있게 즐기라는 표현을 사용하는 것은 어떨까요?

ex) '재미있는', '재치있는', '자연스러운', ...

**Comment by jungin019** [comment]
원문은 'Place stickers in the correct spaces to create a story that makes sense.' 입니다. 번역상에는 문제가 있진 않지만 어색한 건 맞는 것 같네요

**Comment by STRIKE-F** [comment]
이야기를 자연스럽게 꾸며 보세요. 는 어떨까요

**Comment by STRIKE-F** [comment]
올린 대로 수정하겠습니다.
