### ISSUE TITLE
[건의] 마야의 책리장성

### ISSUE THREAD

**Issue by Y00N** [elfinlazz/lt3translation#925]
![screenshot_2016-07-13-07-42-16](https://cloud.githubusercontent.com/assets/19270364/16786181/e7e40b34-48cd-11e6-8f1a-9a20dda365b6.png)

마야의 책리장성....
"마야의 만리장서"라고 바꾸어보는 건 어떨까요?
장서들이 만리씩 있다는 느낌도 팍팍 들고요!!
책리장성이라는 걸 보자마자 생각나던데요 헤헤;;
만리장성의 오타 느낌나려나...

**Comment by Porowl** [comment]
보는 사람이 장서가 뭔지 모를 것 같아서요...

**Comment by Y00N** [comment]
아... 어려운가요 장서란 말이?
그럼 어쩔 수 없죠 :D
