### ISSUE TITLE
한 가지만 묻겠습니다. 이곳에 버스가 다니지 않는 것이 불편하진 않으신가요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#929]
![screenshot_2016-07-13-08-48-59](https://cloud.githubusercontent.com/assets/19295794/16804611/9c34f9da-4947-11e6-883a-299c1a6610c4.png)

**Comment by STRIKE-F** [comment]
여쭈고 싶은 게 있습니다. 버스가 한 대도 안 보이는데 불편하진 않나요?

**Comment by Porowl** [comment]
여쭈고 싶은 게 있습니다. 버스가
다니지를 않으니 불편하지는 않으신가요?
