### ISSUE TITLE
교수님. 얘가 무슨 이야기를 하는 건지 감이 안 와요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#938]
![screenshot_2016-07-13-09-00-38](https://cloud.githubusercontent.com/assets/19295794/16805241/30e6106c-494a-11e6-830f-e28811841a64.png)

**Comment by Porowl** [comment]
선생님. 얘가 무슨 이야기를 하는지 
전혀 모르겠어요.
