### ISSUE TITLE
좋아, 루크. 우리 친구가 실수한 것이 아니라면, 우리는 동쪽으로 가면 될 것 같구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#940]
![screenshot_2016-07-13-09-53-31](https://cloud.githubusercontent.com/assets/19295794/16805326/9c24b658-494a-11e6-8cdc-2059be386583.png)

**Comment by STRIKE-F** [comment]
"꼬마 신사분이 틀리지 않았다면" 괜찮아 보이네요

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
