### ISSUE TITLE
듀크 호텔은 런던에서 가장 유명하고 최고거든요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#942]
![screenshot_2016-07-13-09-55-28](https://cloud.githubusercontent.com/assets/19295794/16805420/14ef0e6c-494b-11e6-98d2-b145f44b656b.png)

**Comment by Porowl** [comment]
듀크 호텔은 런던에서 가장 유명하고
최고로 알아주는 호텔이거든요!

**Comment by STRIKE-F** [comment]
듀크 호텔은 런던에서 가장 유명하고
최고로 알아주는 호텔이거든요!
이거로 수정하겠습니다.
