### ISSUE TITLE
내가 너 같은 꼬맹이한테 얘기 하는 것처럼 보여? 난 저기 큰 모자 양반이랑 얘기 중이라고!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#945]
![screenshot_2016-07-13-10-00-47](https://cloud.githubusercontent.com/assets/19295794/16821933/36f1f742-4994-11e6-9c30-1dade2c2977e.png)

**Comment by Porowl** [comment]
내가 너 같은 꼬맹이한테 말하는 것 같냐?
난 저기 큰 모자 양반이랑 말하는 중이라고!

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
