### ISSUE TITLE
베키가 말한 대로, 이곳에 있는 동안 중심가에 돌아올 장소를 두는 것은 많은 도움이 될 거야.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#950]
![screenshot_2016-07-13-10-08-30](https://cloud.githubusercontent.com/assets/19295794/16822065/030af914-4995-11e6-92b9-157540be6a88.png)

**Comment by Porowl** [comment]
머무는 것은
숙소를 잡는 것은
숙소를 마련하는 것은

어떤가요

**Comment by Porowl** [comment]
참고로 베키가 말했다시피 로 고쳐두었습니다.

**Comment by vbn2523** [comment]
숙소른 정하는 것은 은 어떤가요?

**Comment by STRIKE-F** [comment]
베키 말대로, 여기 있는 동안 중심가에 숙소를 잡아 두면 도움이 많이 될 거야.
어떤가요

**Comment by STRIKE-F** [comment]
올린 대로 수정하겠습니다.
