### ISSUE TITLE
이렇게 햇볕 잘 비치는 방에 있으니 집에 온 것 같구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#951]
![screenshot_2016-07-13-10-09-32](https://cloud.githubusercontent.com/assets/19295794/16822079/1efae292-4995-11e6-8ea2-a5cc87cb6197.png)

**Comment by STRIKE-F** [comment]
집에 온 것 같구나 -> 집처럼 포근하구나 어떤가요

**Comment by Porowl** [comment]
^ 찬성

**Comment by STRIKE-F** [comment]
이대로 수정하겠습니다.
