### ISSUE TITLE
여기 펜 네 자루가 있는데, 이 중에 잉크가 남아있는 건 한 자루 뿐일 거예요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#952]
![screenshot_2016-07-13-10-19-19](https://cloud.githubusercontent.com/assets/19295794/16822124/5ea1bf06-4995-11e6-84de-d860e9bb8804.png)

**Comment by STRIKE-F** [comment]
여기 펜 네 자루 중에 잉크가 남은 건 하나밖에 없을 텐데...
이러면 어떨까요. 마가렛이 루크에게 반말 쓰는 건 맞습니다.

**Comment by Porowl** [comment]
여기 펜 네 자루가 있는데, 이 중에 
잉크가 남아있는 건 한 자루 뿐일게야.

어디 보자...무슨 펜이었더라?

**Comment by STRIKE-F** [comment]
여기 펜 네 자루가 있는데, 이 중에 
잉크가 남은 건 한 자루 뿐일 게야.

이렇게 수정하겠습니다.
