### ISSUE TITLE
전 베키예요. 필요하신 게 있다면 주저 마시고 불러 주세요

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#957]
![screenshot_2016-07-13-10-46-49](https://cloud.githubusercontent.com/assets/19295794/16822225/e7f5f8ee-4995-11e6-9a3c-c9aec16c715e.png)

**Comment by jungin019** [comment]
마침표 수정

**Comment by STRIKE-F** [comment]
언제든지로 수정하겠습니다.
