### ISSUE TITLE
누나 이름은 이미 알고 있어요, 베키 누나. 아까 알려주셨잖아요? 전 루크예요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#958]
![screenshot_2016-07-13-10-47-46](https://cloud.githubusercontent.com/assets/19295794/16822251/1b5fd4b6-4996-11e6-9c52-ed5cfbecea11.png)

**Comment by STRIKE-F** [comment]
아니면 그냥 "베키 누나"를 빼도 될 듯합니다. 
"누나 이름은 이미 알고 있어요. 아까 알려주셨잖아요? 전 루크예요!" 이렇게

**Comment by Porowl** [comment]
베키 누나 뺐습니다.
