### ISSUE TITLE
쉿! 우리 할머니는 서비스에 엄격하시거든. 말하는 소리가 들릴 때는 공손한 태도로 있어야 해!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#960]
![screenshot_2016-07-13-10-49-53](https://cloud.githubusercontent.com/assets/19295794/16822286/547f8b88-4996-11e6-9604-5942974e760d.png)

**Comment by jungin019** [comment]
엄격하시거든을 1행으로 옮기면 칸이 좀 모자라 아예 2행으로 옮겼습니다.
