### ISSUE TITLE
근데 할머니가 내신 수수께끼를 푼건 정말 대단했어요!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#961]
![screenshot_2016-07-13-10-51-28](https://cloud.githubusercontent.com/assets/19295794/16822303/72de23fa-4996-11e6-8fd4-22c625d43146.png)

**Comment by STRIKE-F** [comment]
저라면 격식을 덜 차리는 편이 더 자연스러울 거 같아요.  
전에 있던 대사에서도 그렇게까지 격식을 차리진 않았고, 솔직히 자기 할머니에게 그렇게까지 존칭을 붙이는 경우는 잘 없지 않나요 ㅇㅅㅇ

**Comment by STRIKE-F** [comment]
푸신 건 이거는 레이튼 일행에게 하는 거니까 이거로 고칠게요.
