### ISSUE TITLE
아, "기운을 북돋아주는 차 한 잔"이구나. 차를 마신 후에 가도록 하자.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#967]
![screenshot_2016-07-13-10-58-12](https://cloud.githubusercontent.com/assets/19295794/16830572/d64f281e-49da-11e6-9111-d920a8651f7b.png)

**Comment by STRIKE-F** [comment]
이게 원문이 Ahh, the ''cup that cheers.'' Let's go once we've had some tea. 입니다.
cup that cheers를 일단 차로 의역했는데, 지금 보니 그냥 컵을 보고 말한 게 아닌가 싶기도 해서.. 애매하네요

**Comment by jungin019** [comment]
찾아보니 cup that cheers 가 a cup of tea 라는 소리라네요. 소설 구절에서 따온 것 같아요.

**Comment by Porowl** [comment]
본 이슈는 번역팀의 토의 후 다음 문장으로 수정되었습니다.

아, '건강과 미용을 위해 
식후에는 홍차 한 잔'이지.
한 잔 하고 가자꾸나.
