### ISSUE TITLE
편지에 적혀있는대로, 둘은 오클랜드 가에 위치한 병원으로 향하기로 했다.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#971]
![screenshot_2016-07-13-11-02-43](https://cloud.githubusercontent.com/assets/19295794/16830729/96dc78de-49db-11e6-95f8-0c737b7eb20b.png)

**Comment by jungin019** [comment]
칸이 모자라 
'편지에 적혀있는 대로, 
둘은 오클랜드 가에 위치한 병원으로 
향하기로 했다.' 로 수정
