### ISSUE TITLE
장난감 자동차의 모든 트랙을 클리어하면, 좋은 일이 일어날 것입니다!

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#975]
![screenshot_2016-07-13-11-06-05](https://cloud.githubusercontent.com/assets/19295794/16830823/36f17be4-49dc-11e6-8ac3-4bee626d13ed.png)

앞서 이슈가 이미 한 번 올라왔는데, 이번에는 개행 부분을 조금 수정하면 어떨까 합니다.

**Comment by jungin019** [comment]
'장난감 자동차 미니게임의 모든 트랙을 
완료하면 멋진 일이 일어납니다!'로 수정
