### ISSUE TITLE
어, 음, 안녕하세요. 혹시 호텔 앞에서 만나지 않았었나요?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#979]
![screenshot_2016-07-13-11-12-27](https://cloud.githubusercontent.com/assets/19295794/16830970/2abffaf2-49dd-11e6-9e1e-22a9849e66eb.png)

**Comment by jungin019** [comment]
어, 음, 중 하나를 굳이 생략해야 할까요? 
개행은 고쳤습니다.

**Comment by vbn2523** [comment]
제 개인적인 의견으로는 그렇게 말을 많이 더듬을 거라고는 생각하지 않았어서요 ㅠ

**Comment by STRIKE-F** [comment]
저는 그래도 부담되는 사람이니까 저 정도는 더듬을 수도 있다 생각했어요.

**Comment by jungin019** [comment]
원문 자체가 'Oh, um, hello, sir. Didn't we just see you out in front of the hotel?' 이라서...

**Comment by Porowl** [comment]
보존에 찬성

**Comment by STRIKE-F** [comment]
얼추 의견이 모인 듯하니 닫겠습니다.
