### ISSUE TITLE
으앗! 음, 다른 사람과 착각했나보네요. 좋은 하루 되세요.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#980]
![screenshot_2016-07-13-11-13-32](https://cloud.githubusercontent.com/assets/19295794/16830999/608d2128-49dd-11e6-83ac-f2cacec9ea1b.png)

**Comment by jungin019** [comment]
이것도 굳이 생략해야 할까요? 두 문장 모두 원문을 따르고 있습니다.

**Comment by STRIKE-F** [comment]
저도 같은 의견입니다

**Comment by Y00N** [comment]
뭐, "음"이야 있든 없든 큰 상관은 없는데 "좋은 하루 되세요."는 "좋은 하루 보내세요"로 고쳐야 합니다.

**Comment by Porowl** [comment]
같은 의견입니다

**Comment by STRIKE-F** [comment]
그런고로...
