### ISSUE TITLE
그렇게는 안 되지, 꼬마야. 말을 건 건 너니까 도망갈 생각은 말라고.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#981]
![screenshot_2016-07-13-11-14-18](https://cloud.githubusercontent.com/assets/19295794/16831030/9cc45774-49dd-11e6-8129-33ec211fd10c.png)

**Comment by STRIKE-F** [comment]
아니면
"그렇게는 안 되지 꼬마야. 네가 말을 걸어 놓고 이제 와서 도망가려고?"
이러면 어떨까요

**Comment by STRIKE-F** [comment]
올린 대로 수정하겠습니다.
