### ISSUE TITLE
새 비밀번호에 대한 힌트를 메모로 남기긴 했는데, 무슨 말을 하려는지 도무지 알 수가 없어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#983]
![screenshot_2016-07-13-11-23-55](https://cloud.githubusercontent.com/assets/19295794/16831153/4bfe8368-49de-11e6-811a-f41bf67fddf4.png)

**Comment by STRIKE-F** [comment]
문장이 정확히 어디가 어색하죠? 저는 솔직히 잘 모르겠네요 ㅡ.ㅡ;;

**Comment by jungin019** [comment]
1 문장이 어색하다기 보단 개행이 어색하시다는 것 같은데 그렇게 고치기엔 좀..

**Comment by Porowl** [comment]
새 비밀번호에 대한 힌트를 메모로 
남겨주긴 했는데, 이게 무슨 말인지
도무지 알 수가 없어.

**Comment by STRIKE-F** [comment]
새 비밀번호에 대한 힌트를 메모로 
남겨 두긴 했는데, 이게 무슨 말인지
도무지 알 수가 없어.

로 수정했습니다.
