### ISSUE TITLE
...어이, 너네 혹시 이 근처에 껄렁거리는 으스스한 놈들을 봤나?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#991]
![screenshot_2016-07-13-11-35-27](https://cloud.githubusercontent.com/assets/19295794/16831365/8b228336-49df-11e6-9ce3-235836ba80e1.png)

**Comment by STRIKE-F** [comment]
전 의미상 틀린 게 아니라면 저 사람 분위기 상 너네가 더 나아 보여요

**Comment by Porowl** [comment]
너네 가 나아 보입니다

**Comment by STRIKE-F** [comment]
그런고로
