### ISSUE TITLE
네, 왜 물으신 거죠?

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#992]
![screenshot_2016-07-13-11-36-10](https://cloud.githubusercontent.com/assets/19295794/16831386/ae9b525c-49df-11e6-86fc-55fa30bbdb9d.png)

**Comment by STRIKE-F** [comment]
아니면 "네, 혹시 문제라도 있나요?"는 어떨까요

**Comment by STRIKE-F** [comment]
네, 혹시 문제라도 있나요?
이거로 수정할게요.
