### ISSUE TITLE
그 편지를 쓴 누군가는 그린 병원에서 우리가 시간여행을 했다는 증거를 찾을 수 있을 거라 했어.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#998]
![screenshot_2016-07-13-11-47-17](https://cloud.githubusercontent.com/assets/19295794/16831586/c4b23528-49e0-11e6-818a-2d6c00914509.png)

**Comment by jungin019** [comment]
'Whoever wrote that last letter assured us that we'd find proof of our time travel at Green Hospital.'
그 편지를 쓴 사람이 누군지는 모르겠지만, 시간 여행의 증거를 그린 병원에서 찾을 수 있을 거라고 했지. 
정도는 어떨까요

**Comment by STRIKE-F** [comment]
괜찮아 보입니다

**Comment by STRIKE-F** [comment]
올리신 대로 수정하겠습니다.
