### ISSUE TITLE
지체하지 말고 빨리 병원에 가보자구나.

### ISSUE THREAD

**Issue by vbn2523** [elfinlazz/lt3translation#999]
![screenshot_2016-07-13-11-48-34](https://cloud.githubusercontent.com/assets/19295794/16831603/e7d8e7d6-49e0-11e6-8357-78e6c885fac1.png)

**Comment by jungin019** [comment]
마침표 수정.

**Comment by STRIKE-F** [comment]
지체하지 말고를 생략하면 좀 허전해 보여서요 ㅇㅅㅇ... 딱히 의미 중복이 있는 것도 아니고요.

**Comment by Porowl** [comment]
굳이 뺄 필요 없어 보입니다
